### ISSUE TITLE
[BUG] Arena Preperation Buff

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#10]
#### 1.1. Description
You keep 'Arena Preperation' buff after gates open.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Check your buffs after the gates open in any arena
  #### 1.3  Source Material
https://clips.twitch.tv/CulturedSpookyArugulaDansGame-LBw3wIYdK47N-uXK
#### 2.1. Description
Arena Prep buff should be removed before gates open
  #### 2.2 Source Material
Not required

**Comment by MuffledBaneMask** [comment]
44833+ If this is still occurring, provide updated examples!
