### ISSUE TITLE
[BUG] Party passive auras not being applied at times (visual)

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#103]
#### 1.1. Description
Sometimes, your party passive auras don't work or don't apply. It has happened with:
- Draenei Heroic Presence
- Elemental oath
  #### 1.2. How to Reproduce
NEED Research
  #### 1.3  Source Material
https://gyazo.com/593401536f4f1f9b963fbfcf205313fb - no elemental oath buff
https://gyazo.com/0ccb275da80f78d45d9fc614cfb73b0c - party member gets it but not draenei
#### 2.1. Description
Those buffs should always be present
  #### 2.2 Source Material
N/A

**Update :** After some testing it seems to be a visual only problem, still needs research on what causes this

**Comment by JamminL** [comment]
Research is needed to figure out how to reproduce it.

**Comment by Aggrend** [comment]
As far as we can tell internally, you still get the benefit of these buffs, but they don't show on the buff bar for some reason. Still a bug, but less serious.

**Comment by JamminL** [comment]
Confirmed to be visual only with Elemental Oath, marking it as minor

**Comment by raethkcj** [comment]
Fixed as of build 45264:

![auras](https://user-images.githubusercontent.com/7716908/186717294-c572abb4-96eb-451f-b644-2d51e8c4edd2.png)
