### ISSUE TITLE
Headless Horseman's Mount not flyable

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#105]
*Issue submitted automatically through Google Forms by: Avizura*<br/> 
 ### 1. Current Behavior <br/> 
 #### 1.1. Description <br/> 
When you mount up on the Headless Horseman's mount you are not able to fly with it even tho you are supposed to in outland/Northrend.<br/> 
 #### 1.2. How to Reproduce <br/> 
   1. Go to Shattrath
2. Use Headless Horseman's mount
3. Notice you can't fly
 <br/>
 #### 1.3  Source Material <br/> 
 https://gyazo.com/670b428c842dd5222636bb3b6af499f3<br/> 
 ### 2. Expected Behavior<br/> 
  #### 2.1. Description <br/> 
You are supposed to be able to fly with this mount, it even says on the tooltip when you mouse over it.<br/> 
 #### 2.2 Source Material <br/> 
https://gyazo.com/fa5ad51d71914e9f5ad4ddb47958a2d3 this is on TBC classic.

**Comment by watchyoursixx** [comment]
fixed as of build 44832, but with new issues #229
