### ISSUE TITLE
[BUG] Time between auto shots is faster than intended

### ISSUE THREAD

**Issue by watchyoursixx** [JamminL/wotlk-classic-bugs#106]
#### 1.1. Description
Auto shot in Wrath of the Lich King had the cast time removed, which does indeed work correctly as it fires near instantly. However, it seems the cast time was quite literally "removed" from the total time between autos😅 

An auto shot with 2.3 base speed (lvl 1 bow for example), has 15% haste built in due to quivers no longer giving haste. So the expected is `2.3 / 1.15 = 2`, or 2 seconds between every auto shot. Currently we are seeing 1.57 seconds instead, which is `2.3 / 1.15` "total time" and `0.5 / 1.15` "cast time", but since there's no cast time it's just using "cooldown" which in classic and TBCC is `2.3 / 1.15 - 0.5 / 1.15`
  #### 1.2. How to Reproduce
        - take a hunter with whatever haste level (easiest with lvl 1)
        - divide base speed of equipped ranged wep by a multiple of all haste buffs (1.15 if no other bonuses), expected time between shots should be this value.
        - actual time between shots is this value minus the hasted cast time of 0.5 divided by haste
  #### 1.3  Source Material
[WoWCombatLog-070322_221338.txt](https://github.com/JamminL/wotlk-classic-bugs/files/9036037/WoWCombatLog-070322_221338.txt)

#### 2.1. Description
An auto shot with 2.3 base speed (lvl 1 bow for example), has 15% haste built in due to quivers no longer giving haste. So the expected is `2.3 / 1.15 = 2`, or 2 seconds between every auto shot. 
  #### 2.2 Source Material
Can find some source material if needed, but doesn't seem right to cast faster than the attack speed simply because the formula removed the cast time 😛

**Comment by Aggrend** [comment]
We deployed a hotfix to beta yesterday that should have resolved this. However, this hotfix *might* need restarts to take effect so you might not be able to test this until we restart beta or ptr next. Not sure when that might happen.

**Comment by TheDunds** [comment]
Fixed build (45327)

**Comment by JamminL** [comment]
Fixed build 3.4.0.45327
