### ISSUE TITLE
[BUG] Holy shock range

### ISSUE THREAD

**Issue by Waynext1** [JamminL/wotlk-classic-bugs#107]
1. Current Behavior
1.1. Description
Holy shock is either defensive spell (to heal) or offensive (to deal dmg)
The range is 20-40 yrds, 20yrds for offensive shock and 40 yrds for heal
When are u tryin to heal friendly target its only 20 yards which is bug.
1.2. How to Reproduce
      {Describe the steps to reproduce the particular bug, in detail:
      
       1. Have hpala with shock
       2. Try heal someone with shock, notice its same range as offensive shock = 20 yards only
       
1.3 Source Material

0:13 (clearly not 20 yards), checkd multiple videos and its same everywhere
https://www.youtube.com/watch?v=dxGEoAsdjzg&ab_channel=WhateversuitsYou)

2. Expected Behavior
2.1. Description
Holy shock should be 40 yrds range for heal, for offensive dmg 20 yards

**Comment by JamminL** [comment]
Happens for penance and priest dispel magic

**Comment by Aggrend** [comment]
Have a fix for this being tested in internally. 8/10 build should have it.

**Comment by JamminL** [comment]
Fixed 3.4.0.45043
