### ISSUE TITLE
[BUG] Paladin Threat not working correctly.

### ISSUE THREAD

**Issue by JayJay-110** [JamminL/wotlk-classic-bugs#108]
### 1. Current Behavior
**_Note in Advance:_**
_**We currently do not know if this is a bug for other classes aswell.**_
_**More Testing is required once a Threat Meter addon becomes available.**_

  #### 1.1. Description
WotLK changes Blessing of Salvation fundamentally to no longer be an active buff on every player. Instead, the base threat of any tank class in their 'tank mode' got increased by 43% (=1/0.7)  to make up for the loss of raidwide Salvation. 
Currently that 43% modifier seems to not exist. 

In our Test we assume that generally 1 Damage = 1 Threat.

**Test Setup:** 
 - Wltr: Righteous Fury active; Expected Threat Mod = 1.43*1.8 = 2.57
 - Jayjay: No Fanaticism, No Righteous Fury active; Expected Threat Mod = 1
 
**Our Test:**
Wltr did a Total Amount of 1061 Holy Damage. Expected Threat: 1061\*1.43\*1.8 = 2731
Jayjay did 2032 Damage, the mob still attacked Wltr. With another swing hitting for 389 the mob switched its target. Jayjay's total Threat now being 2421. This is quite lower than Wltr's expected Threat, pulling Threat should not be possible yet.
If you leave out the baseline multiplier of 1.43 Wltr's Threat would be at 1061*1.8 = 1910. The breakpoint for pulling aggro is at 110%,  resulting in 2101 which would lead to Jayjay pulling aggro with his last hit (going from 2032 to 2421). 

  #### 1.2. How to Reproduce
           1. Hit a Mob with a Protection Paladin with Righteous Fury activated. Add the threat multipliers to the damage done.
           2. Hit the Mob with another Player without any Threat Modifiers. Note the damage number. 
           3. Threat to pull aggro will be lower than what is expected with the baseline 1.43 multiplier.
  #### 1.3  Source Material
[Combat Log of the Test](https://classic.warcraftlogs.com/reports/AydFzvVLt1hfWxg4/#fight=1&type=summary&start=967&end=56000&hostility=1&source=6.2&view=events&pins=2%24Off%24%23244F4B%24damage%24-1%240.0.0.Any%2423652.0.2.NPC%24true%240.0.0.Any%24true%240%24or%24damage%24-1%240.0.0.Any%240.0.0.Any%24true%2423652.0.2.NPC%24true%240)
#### 2.1. Description
There should be a 1.43 Multiplier on every action with Righteous Fury up.
  #### 2.2 Source Material
[Patch Notes mentioning the addition of a Base Threat Modifier](https://wowwiki-archive.fandom.com/wiki/Patch_3.0.2) (Ctrl + F "Tranquil Air")
[Wowpedia mentioning the 1.43 Multiplier for Tanks](https://wowpedia.fandom.com/wiki/Threat?oldid=2222662#Tank_Threat_Bonus)
[Elitist Jerks mentioning the 1.43 Multiplier](https://web.archive.org/web/20100629121045/http://elitistjerks.com/f76/t37172-protection_paladin_field_manual_wow_3_0_wotlk/p58#post1336981) (Slightly outdated, Righteous Fury Threat is 80% in 3.3.5)

**Comment by Cleavis** [comment]
> We currently do not know if this is a bug for other classes aswell.

Death Knight threat did not, on first inspection on v3.4.0.44301, seem to suffer from this issue. Frost Presence appears to be approximately 2.0735x multiplier. Empirical testing with blood presence and frost presence, using DK's ghoul (1.0x threat) melee attacks until aggro rip, put frost presence between 2.19x and 1.96x; and blood presence between 0.905x and 0.755x.

https://docs.google.com/spreadsheets/d/1ntyTACnVtcAG4g2wV1C0n-54SnxbR6_fJcRJB34XTEQ/edit?usp=sharing

If going to conduct further testing to narrow the issue, recommend a non-paladin ripper.

**Comment by JayJay-110** [comment]
After enabling Addons I did some tests on my own. I used both ThreatClassic2 and Details: Tiny Threat for monitoring threat values.

I used exorcism in the examples below but it's the same behavior for every spell I tried with.



### Current Behavior
**Currently Righteous Fury seems to still be based on its TBC version.** 
Its Threat Modifier depends on the amount of points in Improved Righteous Fury and ranges from a 60% to 90% Bonus.

[Exorcism without Righteous Fury:](https://www.youtube.com/watch?v=3G7lZztSv7Q) 350 Damage, 350 Threat. Threat Multiplier = 1
[Exorcism with 0/3 Imp. Righteous Fury:](https://www.youtube.com/watch?v=2XjRCbG7zNA) 342 Damage, 547 Threat. Threat Multiplier = 1.6
[Exorcism with 1/3 Imp. Righteous Fury:](https://www.youtube.com/watch?v=3Kc1Ml84G2I) 356 Damage, 603 Threat. Threat Multiplier = 1.7
[Exorcism with 2/3 Imp. Righteous Fury:](https://www.youtube.com/watch?v=TPCOm0-UYw8) 351 Damage, 631 Threat. Threat Multiplier = 1.8
[Exorcism with 3/3 Imp. Righteous Fury:](https://www.youtube.com/watch?v=oiC0EuSHz3o) 343 Damage, 651 Threat. Threat Multiplier = 1.9


Those results still match up with our previous testing.


### Expected Behavior
Righteous Fury should be a static 1.8 multiplier on Holy Spells. Improved Righteous Fury should not affect the Threat Multiplier anymore.
[3.0.2 Improved Righteous Fury no providing additional Threat.](https://wowwiki-archive.fandom.com/wiki/Patch_3.0.2#Paladins)
[3.2.2 Righteous Fury Nerf from 90% Bonus to 80% Bonus.](https://wowwiki-archive.fandom.com/wiki/Patch_3.2.2#Paladin)

The previously mentioned 1.43 Multiplier is still missing entirely.

**Comment by Undertoe** [comment]
Confirmed still broken with 3.4.0.44729

**Comment by magey** [comment]
I can confirm that warrior Defensive Stance multiplier is 2.0735 (1.45 * 1.43) on build 44729, tested with `UnitDetailedThreatSituation`, so it seems to be working fine for warriors as well.

**Comment by JayJay-110** [comment]
Current state in Build 45189:

The baseline multiplier of 1.43 is there but Righteous Fury still scales with Talents.
Ranging from a 60% to 90% Multiplier depending on the amount of points in Improved Righteous Fury. 
It should always be 80% regarding of invested Talent Points.

**Comment by watchyoursixx** [comment]
I'm assuming this is finally fixed which is why it was closed?

Do you have any test results for confirmation?

**Comment by JayJay-110** [comment]
Fixed with the latest build yes.

Just hit some mob with a few spells and checked `UnitDetailedThreatSituation` like Magey said.
It's an 2.574 (1.43 * 1.8) multiplier now.
