### ISSUE TITLE
[BUG] Volley past 30~ yards only ticks 5 times

### ISSUE THREAD

**Issue by watchyoursixx** [JamminL/wotlk-classic-bugs#111]
#### 1.1. Description
Casting volley on a target more than 30 yds away only ticks 5 times instead of 6. It lasts 6  sec and ticks every 1s. The first tick is skipped past that distance for some reason. Same as BCC actually...
  #### 1.2. How to Reproduce
          stand at least 30 yds away from a target and shoot volley
  #### 1.3  Source Material
https://clips.twitch.tv/PatientPiliablePineappleDatBoi-14S8H1-tucvGoBue
#### 2.1. Description
Should tick consistently at all ranges 6 times.
  #### 2.2 Source Material
At close range it does correctly hit 6 times.

**Comment by watchyoursixx** [comment]
fixed as of build 44644

**Comment by watchyoursixx** [comment]
just kidding...

New findings for some interesting interaction with it...

So casting it in the exact spot I tested, it works and I can hit 6 times every time. However, I moved a few more times and suddenly it stopped working again... I couldn't get more than 5 ticks many times. I tried moving left/right, no luck. Then moved back to the original spot, I got 6 hits again. Then I moved to the left/right and still am getting 6 ticks.

Not sure what's happening here to be honest, but it does work more consistently it seems.

Note this was testing at the max range, right around the edge of it.
5 ticks
![image](https://user-images.githubusercontent.com/47162044/178903877-2f30fb46-1517-422a-9b8a-5a0e5f619832.png)
6 ticks
![image](https://user-images.githubusercontent.com/47162044/178903923-617b646c-5040-44e6-9693-956afa3e470c.png)

notice how the last 2 ticks are after the debuff is gone. The initial ticks are also delayed. Sometimes they just don't do the very last tick.

**Comment by Aggrend** [comment]
Took another swing at a fix. Should be fixed in this week's build (weds eta)

**Comment by TheDunds** [comment]
In 6 casts, 4 were 5 ticks, 2 were 6 ticks. And those 5 ticks occurred at all ranges between absolute max distance (either volley or dummy hit box is way larger than it looks like) and center point. ![image](https://user-images.githubusercontent.com/110584436/182764925-04f25b6b-03fe-4f6f-8ba4-b4087a314283.png)

**Comment by TheDunds** [comment]
![image](https://user-images.githubusercontent.com/110584436/186980215-3a644169-71f2-4c06-8500-a4fd29ec8852.png)
Still in a bugged state
