### ISSUE TITLE
[BUG] Savage Rend (Raptor special ability) Bleed DoT doesn't ignore armor

### ISSUE THREAD

**Issue by watchyoursixx** [JamminL/wotlk-classic-bugs#114]
#### 1.1. Description
Savage Rend has a hit and a bleed effect. The bleed should ignore armor but it doesn't.
  #### 1.2. How to Reproduce
          
- Attack a target with armor and check the damage done by the bleed.
- lvl 69 Raptor
- rank 5 Savage Rend (DoT is 10-12 per tick baseline) scales 7% AP
- AP = 772
- Pet happiness = green, 1.25 modifier
- base line 5% mod for all pets
- orc mod 5%
- damage reduction attacking a lvl 70 warrior dummy (6792 armor) with no debuffs applied: 40.23%
- expected damage: `89-92`
- actual: `53 - 55`
  #### 1.3  Source Material
https://www.warcraftlogs.com/reports/Zz2ac1QLNxphmkFq/#boss=0&difficulty=0&type=damage-done&source=3&view=events&ability=53581
#### 2.1. Description
The dot states it is a bleed and should behave like a bleed according to the tooltip and game data for that aura
  #### 2.2 Source Material
N/A

**Comment by BradBlondebeard** [comment]
Just want to note that the hunter dps sheet from WotLK had savage rend affected by armor (I don't have any direct evidence though) 
![image](https://user-images.githubusercontent.com/81579365/178826755-8182123e-86b5-41a5-afbf-ff6bfacbdd5b.png)

**Comment by Aggrend** [comment]
This was probably something we'd have called a bug in 3.3.5 but it does match reference. Calling it NAB for now. Thanks!
