### ISSUE TITLE
[BUG] equipping a trinket with an internal cooldown induces its internal cooldown

### ISSUE THREAD

**Issue by nodddle** [JamminL/wotlk-classic-bugs#118]
#### 1.1. Description
equipping a trinket with an internal cooldown induces its internal cooldown
  #### 1.2. How to Reproduce
find a trinket with an ICD
start timer
equip trinket
try as hard as you can to proc trinket until the timer reaches a time that is ≥ the ICD of the trinket
  #### 1.3  Source Material
https://youtu.be/PhuKZXiv0jw
#### 2.1. Description
unsure of how this SHOULD work, but in TBC they found this exact same bug, reported it, and it was fixed as of patch 2.5.2.40011:
https://github.com/magey/tbc-warrior/issues/71

**Comment by gyaru** [comment]
You could try reading the issue you've linked: https://github.com/magey/tbc-warrior/issues/71.

> This was a feature that was explicitly added to the game in [**patch 3.2.0 during Wrath of the Lich Kin**g](https://web.archive.org/web/20100507230145/http://www.worldofwarcraft.com/patchnotes/patch3p2.html), and seems to be erroneously present in The Burning Crusade Classic:
