### ISSUE TITLE
[TEST-REQUEST] Resilience

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#12]
### Description
Test resilience, tooltip incorrect, gotta check if just tooltip

**Comment by Turaxy** [comment]
Did some quick test : 

All damage sources are from the same character that move any buff / gear etc 

- 599 resil (6.35% damage reduction pvp) : 

7 smite = 12800 (1829 average) 
Shadow word: pain = 504 damage tick

- 0 resil :

7 smite = 14695 (2099 average)
Shadow word:pain = 577 damage tick


Looks like damage reduction is double from tooltip (~13%), however we don't see the the damage reduction on dots on tooltip or number.
