### ISSUE TITLE
[BUG] Vanish isn't Sappable, or breakable at all, and should be. 

### ISSUE THREAD

**Issue by perpabc** [JamminL/wotlk-classic-bugs#121]
#### 1.1. Description
If an enemy player Vanishes right in front of you while you're spamming sap, you are returned with the error text "Invalid Target". This is true for any spell being used on an enemy player Vanishing.
  #### 1.2. How to Reproduce
          {-
           1. Two Rogues. Rogue A stands in front of Rogue B and both players auto attack each other.
           2. Rogue A uses Shadow Dance, and begins spamming the Sap hotkey. 
           3. Rogue B uses Vanish at any point after Rogue B starts spamming Sap.
  #### 1.3  Source Material
https://gyazo.com/645a62999b279e079fed4f2a3a7f99ff - Watch the '5' hotkey, spamming Sap
https://gyazo.com/622c99d8d67ffcb5b336653bf73f8730 - This is what SHOULD happen, but it's working with Shadowmeld already (ONLY outside of Arena/Instanced PVP does it work with Shadowmeld, which is a bug as it should work inside Instanced PVP too - we didn't find this out 'til Arena was released on beta).
#### 2.1. Description
You should be able to time your abilities to break Vanish, or Sap Vanish. You can sap a player who uses Shadowmeld however, so you may be able to pull some data from it, as they do not get the "Invalid Target" error text. **It's imperative that Vanish retains it's immuning function**, however Sap should not be Vanishable, unless the Rogue using Vanish is already out of combat. If the Vanish used drops combat, enemy rogues should be able to Sap him as seen in the clips below
  #### 2.2 Source Material
{https://www.youtube.com/watch?v=spH5R2pTBFU (**Proof of Vanish immunity, and how it can also be broken**) 
0:16: Vanish Blind (Vanish breaks but Blind effect is immuned, correct behavior), 0:38: Vanish Blind x2, 1:06: Vanish Cheap Shot, 1:30: Blind Vanish reactively (Vanish breaks and Blind isn't immuned, correct behavior if you watch the speed of the spells)
2:04: Mutilate Vanish into Rocket Glove 2nd Vanish
https://youtu.be/FdpGtkThL6w?t=494 rogue pov, can see enemy rogue, can sap vanish by spamming sap (bottom right macro), rogue reappears with similar visual delay 
https://youtu.be/FdpGtkThL6w?t=621 second example sapping vanish 
https://youtu.be/s2WefYizuAY?t=411 blinding vanish, rogue can be seen briefly during the vanish and there's a brief window to blind vanish, and also sapping vanish right after, with same visual window
https://youtu.be/s2WefYizuAY?t=1140 sapping vanish 
https://youtu.be/s2WefYizuAY?t=1312 blinding vanish
https://www.warcraftmovies.com/movieview.php?id=158577 1:42 kidney vanish, 8:40 sap vanish}

**Comment by Aggrend** [comment]
I am super dubious about this one. I suspect if this was a thing in Wrath, it was thing because of massive batch windows and not due to design intent. We aren't going to break an ability to emulate 2008 batch jank. Regardless, we will investigate.

**Comment by perpabc** [comment]
Still bugged as of 4th Aug build

**Comment by perpabc** [comment]
Just tested again, still bugged as of 10th August build
