### ISSUE TITLE
[BUG] Mage - Cold snap should reset GCD * not working as expected

### ISSUE THREAD

**Issue by mattmcdd** [JamminL/wotlk-classic-bugs#127]
#### 1.1. Description
Cold snap should reset the GCD for the caster, eg cone of cold, coldsnap, cone of cold, user should not encounter a GCD between both cone of colds. Another example, nova snap deep, deep should be off GCD when casted as snap would reset the GCD. 
  #### 1.2. How to Reproduce
           0. This should work with any instant cast spell that begins GCD, eg nova, barrier, etc
           1. Press cone of cold
           2. Press cold snap
           3. Press cone of cold
  #### 1.3  Source Material
  Video shows second cone is waiting the global caused by first cone, and gcd in the middle is not resetting gcd
https://gyazo.com/36785fb812af25be59a019d05d735d1d
#### 2.1. Description
 Cold snap should reset the global cool down after being casted, even if a GCD is taking place. Expected behavior is cone snap cone is seamless cone into cone almost instantly. 
  #### 2.2 Source Material
{Video, Posts, etc..}
Looking for evidence - will update ticket within a day have a few places to look.
Thanks Jerry for finding this > https://www.youtube.com/watch?v=7FdeDKeHVjg&t=417s
Jerry suggests this may be visual only, still looking for more evidence, it really does look like it is resetting gcd and not just very high haste however, here is an additional clip https://www.youtube.com/watch?v=MuhBMXySj-s&t=837s from previous tbc ticket regarding this issue

https://youtu.be/6l2iTAU1pxQ?t=363 heres another clip from TBC i found, now this one is a bit more interesting, it looks like a visual bug here more than it does in the wotlk clip as u can actually see the press going down on the nova but its not going on cd untill 0.5sec after

**Comment by JamminL** [comment]
https://youtu.be/bjpi1SPpseY?t=639 adding this evidence, again none of these are very clear. 

No other spell behaves like this so I'm also inclined to call this visual, but there's enough evidence to raise the question so we'll wait for a reference check to say otherwise before closing this

**Comment by Aggrend** [comment]
So this one is a bit odd. When pressing cold snap, it does appear in the UI that cold snap resets the GCD, but it is only visual. You still have to wait the amount of time before you can use another ability. So technically, it was visually bugged in 3.3.5 and now it appears correctly in 3.4.0.

The actual gameplay behavior matches 3.3.5 reference though, so calling this NAB.
