### ISSUE TITLE
[BUG] Dismissing pet and resummoning later causes pet to lose health on resummon

### ISSUE THREAD

**Issue by watchyoursixx** [JamminL/wotlk-classic-bugs#129]
#### 1.1. Description
When you dismiss and resummon your pet, via a mount, using the ability or outranging it your pet when resummoned will lose anywhere from 10-30% of it's health. This is extremely noticeable just spam dismissing/calling pet, but can happen naturally while questing in Outlands flying which constantly desummons your pet.

Note this happened in TBC too, but wasn't as drastic and didn't happen on just normal dismisses from what I recall. Possibly warlock pets are affected as well.
  #### 1.2. How to Reproduce
          1. dismiss a pet
          2. call pet
          3. dismiss a pet
          4. call pet, see how the health goes down each time you resummon it.
  #### 1.3  Source Material
can get a video if really needed but easily tested on beta
#### 2.1. Description
Pet's hp should either recover back to full within a second or two of resummoning or just stay at full/last hp value when resummoning
  #### 2.2 Source Material
N/A

**Comment by watchyoursixx** [comment]
this appears fixed as of 44930

resummoning pet puts it at 65% health, but doesn't go any lower than that each summons. Maybe related to health scaling on "why 65%" but it's similar to how it should be now.

**Comment by watchyoursixx** [comment]
As of 45043, this is happening again when summoning/dismissing pet without allowing to heal to full. Not sure what changed between this build and last. I repeated the same steps both times.

**Comment by watchyoursixx** [comment]
Adding to this. My lvl 80 template character does not have this issue, resummoning does not lower the pet's hp below 55%.
My lvl 70 character does have this issue, resummoning constantly lowers the hp of my pet each time, down to 1% if continuously doing it without healing up.
My level 80 beta char "Sixxiy" has a lvl 80 ravager. BM spec listed here:
https://www.wowhead.com/wotlk/talent-calc/hunter/550002015052002-03-5000032500003
My level 70 beta char "Sixxi" has a lvl 70 ravager. MM spec listed here:
https://www.wowhead.com/wotlk/talent-calc/hunter/-035005131130013233105221251

**Comment by watchyoursixx** [comment]
Some further info 

> I'm managing to consistently replicate the flying mount pet hp scaling issue. The only requirements are A: pet needs to be below full HP and B: pet has any buffs with a fixed duration (aka not Trueshot)
> * Fly up while both conditions are true, despawning the pet
> * Wait until the buff times out while pet is despawned
> * Land and dismount
> Voila, pet is now at 60% of the HP value it was previously at. 
> Rinse and repeat as many times as you want by using Mend Pet>mounting up, it will keep happening as long as both conditions are fulfilled (under max hp, buff expires while pet is despawned).
> 
> 795 stamina, MM+trap leveling spec so no stamina scaling talents or Wild Hunt. People with different talents/stam value might end up with different scaling and consistently lose a different % of their pet's health every time. Only works with buffs and not debuffs for obvious reasons.
> 
> Can't go below 60% hp if pet is manually dismissed.

**Comment by Aggrend** [comment]
At long last, we should have a fix for this on the next 3.4.1 PTR build later this week.
