### ISSUE TITLE
[BUG] Macros casting wrong spell

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#13]
#### 1.1. Description
Certain macros are casting the incorrect spell. EG:

#showtooltip Dispel Magic
/cast [target=Player] Dispel Magic

Casts Divine Spirit
------
/cast [nomod] banish; [mod:shift] drain life

Casts Hellfire

EDIT: It seems like it's a bit more widespread, most of caster macros don't work like /cast ice barrier, however, adding ! infront of the macro makes it work, like /cast !ice barrier

  #### 1.2. How to Reproduce
           1. Make a macro such as /cast [target=Player] Dispel Magic
           2. Click the macro
           3. Notice it casts Divine Spirit
  #### 1.3  Source Material
https://gyazo.com/471ede962b738da6b1fcd8e12ee00383
https://gyazo.com/99e591c7818bd451071a7a8e266755eb
#### 2.1. Description
It should cast the spell described in the macro
  #### 2.2 Source Material
Not required

**Comment by Aggrend** [comment]
Tracking this as well. Thanks!

**Comment by JamminL** [comment]
Fixed
