### ISSUE TITLE
[BUG] Fishing still requires skill to cast in zones, inconsistent with 3.1 (also auto looting seems to be bugged)

### ISSUE THREAD

**Issue by Teebown** [JamminL/wotlk-classic-bugs#131]
#### 1.1. Description
Fishing currently requires a skill level to attempt to fish, instead of only using skill to "roll" for fish and catch/get away.  This should have been changed in patch 3.1 (see screenshot, below)
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Move to an area over your level or over your fishing skill level
           2. Equip fishing pole and attempt to fish
           3. Should receive error message about skill level not being high enough.
Aside - auto looting during fishing seems bugged, unable to auto loot after a successful cast.
  #### 1.3  Source Material
![image](https://user-images.githubusercontent.com/108202746/178174947-2a5ded52-ac1f-4cf3-916f-76e0f2875066.png)

#### 2.1. Description
Should be able to fish and gain skill anywhere, per patch 3.1 notes
  #### 2.2 Source Material
![image](https://user-images.githubusercontent.com/108202746/178174873-30368c5f-06e4-457e-a9ba-11622a74065f.png)

**Comment by watchyoursixx** [comment]
this should be fixed by a recent hotfix. Please report if still not working properly
