### ISSUE TITLE
[BUG] Jo'mah missing from org

### ISSUE THREAD

**Issue by Undertoe** [JamminL/wotlk-classic-bugs#132]
#### 1.1. Jo'mah is missing from org.
https://wotlkdb.com/?npc=30706
https://www.wowhead.com/wotlk/npc=30706/jomah
https://imgur.com/a/rNiOyBR 
  #### 1.2. How to Reproduce
          1) Go to org in the 2nd floor near the lexicon of power.  He isn't there to train inscription.  

#### 2.1. Description
According to wowhead he was added in during the prepatch.
  #### 2.2 Source Material
https://www.wowhead.com/npc=30706/jomah#comments Added patch 3.0.2.  Not present in org currently.

**Comment by watchyoursixx** [comment]
Jo'Mah is in org at least as of 45264, possibly earlier
