### ISSUE TITLE
[BUG] Pets with ranged attacks stutter step to check range while moving into cast range

### ISSUE THREAD

**Issue by BradBlondebeard** [JamminL/wotlk-classic-bugs#133]
#### 1.1. Description
Sometimes when a pet is sent to attack a target with auto cast toggled on with a ranged ability, e.g. a serpent with poison spit, the pet will stop when out of range to cast it's ranged ability, then continue to target.
  #### 1.2. How to Reproduce
1. Get a pet with a ranged attack
2. Make sure the ranged attack is on auto cast
3. Start with the pet out of range of the ranged attack
4. Issue a /petattack command on an enemy out of range of the pet's ranged attack
5. Sometimes the pet will stop, then start to move closer to the target
  #### 1.3  Source Material
I made a clip on the beta but the clip doesn't work anymore :( 
This is a video of this behavior back in original Wrath of the Lich King before the bug was fixed there: https://www.youtube.com/watch?v=abbAm72B0gA&t=204s
#### 2.1. Description
The pet should not stop to cast at all
  #### 2.2 Source Material
This is a clip of a pet working correctly: https://clips.twitch.tv/FrozenDaintyDogHeyGuys-tA6QNWVV1FxiCMeG
I do not know exactly what causes the pet to pause.
Here's another clip from retail Wrath of the Lich King showing no stutter: https://www.youtube.com/watch?v=NDac0ta95KU&t=142s

**Comment by watchyoursixx** [comment]
I didn't test this extensively but if my pet was out of range when commanded, it would run in no problems with no stops, with lightning breath on auto cast. (Wind Serpent)

If I send pet in within range of their ranged attack (pet attack), it will pause, use the ranged ability, then move in to attack.

If I send pet in with the ability from out of range rather than with pet attack, it will run in and stop when it gets in range and cast the spell. Then half a sec later continue on to the target

**Comment by BradBlondebeard** [comment]
Could you try using a serpent with poison spit? That's the pet I first saw the issue when Zeroji was streaming. The vod is gone now because it was more than two weeks ago.

**Comment by watchyoursixx** [comment]
Testing with serpent and poison spit:
- Command to attack: pet runs in, stops to spit and continues running in
- Command to spit from out of range: pet runs in and casts spit while running
- Command to spit from in range: pet stays stationary for half a sec after cast before running in

Not sure what's happening here but it's inconsistent

**Comment by Aggrend** [comment]
Regrettably this behavior (including the inconsistency) matches 3.3.5 reference. We have a bug in for this and we'd like to fix it at some point, but it's unlikely we'll have a great solution for launch.
