### ISSUE TITLE
[BUG] Melee Haste Rating not matching 3.1 patch notes

### ISSUE THREAD

**Issue by Teebown** [JamminL/wotlk-classic-bugs#134]
#### 1.1. Description
Currently, shaman are getting 1% melee haste per ~32.75 haste rating, which was supposed to be changed in 3.1 to ~25.22.
  #### 1.2. How to Reproduce
          Check attack speed on char sheet at different haste ratings, estimate %/rating.
  #### 1.3  Source Material
![image](https://user-images.githubusercontent.com/108202746/178408895-ff753cda-f281-4bcf-ada1-c3eb8a163309.png)
#### 2.1. Description
Expected behavior is that shaman and several other classes should receive 1% haste for a smaller # of haste rating (25.21)
  #### 2.2 Source Material
![image](https://user-images.githubusercontent.com/108202746/178408939-c29e97b3-a902-4e4a-9474-461e1e3a0a0b.png)
https://web.archive.org/web/20100901202350/http://elitistjerks.com/f72/t83319-frost_dps_3_3_3_will_day_long_remembered/ - see stats section,  under haste rating.

**Comment by Wumblesnarf** [comment]
Some additional sources, just to be extra safe: 
https://www.wowhead.com/patchnotes=3.1.0 wowhead's copy of the patch notes https://web.archive.org/web/20090428175302/http://www.worldofwarcraft.com/patchnotes/ web archive of the official patchnotes

**Comment by CharWS** [comment]
![unknown-2](https://user-images.githubusercontent.com/104176019/178424908-4f3dc654-dbbd-4059-8d1c-d7bf32da432f.png)
Here's an additional example of current behavior for DKs, 19 haste rating converting to 0.58 percent or ~32.7586206897 haste rating per 1% melee attack speed increase

**Comment by raethkcj** [comment]
This appears to be fixed for shamans as of build 44729.
