### ISSUE TITLE
Eastern Kingdoms Dungeon Portals Not Working [BUG]

### ISSUE THREAD

**Issue by CharWS** [JamminL/wotlk-classic-bugs#135]
#### 1.2. How to Reproduce
           1. Head to a dungeon portal for an Eastern Kingdoms instance
           2. Attempt to zone in through the portal
#### 2.2 Additional Notes
Tested Scholomance, Blackrock Depths, and Stockades, unable to zone into any through the dungeon portal. Can zone into Blackrock Depths using a Mole Machine from the Brewfest event. The Eastern Kingdom Raid Molten Core's portal seems to work just fine, as do Kalimdor, Outland, and Northrend dungeon portals. 
Beta Build 3.4.0 (44547)

**Comment by Undertoe** [comment]
Confirmed still broken 3.4.0.44832

**Comment by CharWS** [comment]
Fixed as of 44930
