### ISSUE TITLE
[#SomeChanges Suggestion] Soul Shard Use in Arena Specifically

### ISSUE THREAD

**Issue by Jgrenier91** [JamminL/wotlk-classic-bugs#136]
### Description
We've recently learned that there will be no changes to the 32 soul shard cap for Warlocks. Could we instead change the way soul shards are used in arena by returning soul shards used in arena to the warlock after the arena match concludes? This way, arena game-play is unaffected and no other aspect of the game is affected. This would solve the issue of forcing warlocks to farm mobs between every match.

Old Issue Reference: [https://github.com/JamminL/wotlk-classic-bugs/issues/39](https://github.com/JamminL/wotlk-classic-bugs/issues/39)

**Additional Context:**
A lot of warlocks want to try out the revamped Demonology talent tree but are put off by the idea of having to farm soul shards between every match.

**Comment by avizura7** [comment]
This is a great idea!

**Comment by JamminL** [comment]
Live on beta as of 3.4.0.45264
