### ISSUE TITLE
[BUG] Spells still have a 1% chance to resist

### ISSUE THREAD

**Issue by raethkcj** [JamminL/wotlk-classic-bugs#139]
#### 1.1. Description
Enemies have a 1% chance to resist spells that cannot be overcome through level difference, hit rating, nor hit talents. A level 73 Shaman attacking a level 57 mob, with 5.22% hit from gear and 3% spell hit from Elemental Precision still has Lightning Bolt fully resisted.

In addition, the spell is reported by the Combat Log as "fully resisted" rather than "missed".

  #### 1.2. How to Reproduce
           1. Find a mob 10+ levels lower than you, equip hit rating, use hit talents
           2. Repeatedly use any spell against the mob
           3. Observe that eventually, a spell is "fully resisted".
  #### 1.3  Source Material
![Fully Resisted](https://user-images.githubusercontent.com/7716908/178782611-4bb0dbc3-f781-4ad9-b51e-89ed9252129c.jpg)

#### 2.1. Description
  The chance to resist should be completely eliminated by the player's increased chance to hit.
  
  In addition, resists that are not caused by Spell Resistance (in this case, Nature Resistance) should be reported as "missed", not "fully resisted".  
  #### 2.2 Source Material
  A blue post from Kalgan prior to the launch of 3.0.2:
  https://web.archive.org/web/20080913042617/http://forums.worldofwarcraft.com/thread.html?topicId=9679398983&sid=2000&pageNo=3#54
  > If missing a fear (for example) is a gamebreaking event against some targets, then maybe one should consider sacrificing a percentage of damage for that extra percentage or two of hit chance.
  >
  > Also, note that with the wotlk patch you can completely eliminate resist chance through hit chance (you can overcome that final 1% resist chance).

The Patch 3.0.3 Patch Notes:
https://web.archive.org/web/20081204055431/http://www.worldofwarcraft.com:80/patchnotes/
> The combat log now differentiates between a spell failure due to resistance and spell failure due to missing the target. Where once both events reported as a resist; a spell missing the target is now reported as a miss.

**Comment by Aggrend** [comment]
Should be fixed in new build on Wednesday

**Comment by raethkcj** [comment]
This was not fixed in build 44930 on Wednesday. According to a less-than-secret QA discord, it will be in next week instead.

**Comment by Aggrend** [comment]
Apologies, this missed yesterday's build. Should be good in the 8/10 build next week.

**Comment by yurpcraft** [comment]
Fixed in 3.4.0.45043 - 332 hits, no resists
![image](https://user-images.githubusercontent.com/12848366/184021188-ab585e60-4076-4193-822f-f210ce8a0bb8.png)
