### ISSUE TITLE
[BUG] Mass Dispel Outer Circle - Inner Circle

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#14]
#### 1.1. Description
Mass Dispel has two ranges at the moment, it correctly dispels the targets with its full range. But there's a range interval where it will dispel the target but doesn't put anyone in combat

  #### 1.2. How to Reproduce
           1. Duel someone
           2. Have the target enemy stand still
           3. Cast Mass Dispel so it barely hits the target (the target is in the outer ring of your aoe indicator)
           4. Check that it will dispell his buffs but not trigger combat on anyone
           5. Repeat the test but with the target in the center of your indicator
           6. Check that the dispel correctly puts the target in combat as well
  #### 1.3  Source Material
Nothing yet
### 2. Expected Behavior
MD should always dispel and put both players in combat.
{Describe how that mechanic/spell/npc should be working, in detail}
  #### 2.2 Source Material
Nothing yet

**Comment by Aggrend** [comment]
Deja vu : |

**Comment by JamminL** [comment]
Fixed as of build 44930
