### ISSUE TITLE
[BUG] Prayer of Shadow Protection doesn't buff party/raid

### ISSUE THREAD

**Issue by watchyoursixx** [JamminL/wotlk-classic-bugs#141]
#### 1.1. Description
Casting Prayer of shadow protection on a un-pvp flagged group does not buff anyone except the target of the cast.
  #### 1.2. How to Reproduce
          Target someone in your party or raid and cast Prayer of Shadow protection
  #### 1.3  Source Material
![image](https://user-images.githubusercontent.com/47162044/178899784-1f7f9977-45d4-416c-91cc-f595bcee7454.png)
#### 2.1. Description
Should affect all party and raid members on cast
  #### 2.2 Source Material
N/A

**Comment by JamminL** [comment]
Fixed Build 3.4.04543
