### ISSUE TITLE
[BUG] Greater Blessing of Sanctuary cannot be cast on anyone

### ISSUE THREAD

**Issue by watchyoursixx** [JamminL/wotlk-classic-bugs#142]
#### 1.1. Description
Casting the spell Greater Blessing of Sanctuary will just popup a "selection" hand and not self-cast or allow casts on any target friendly party or raid member
  #### 1.2. How to Reproduce
         Try to cast Greater blessing of sanctuary on yourself or a party/raid member (used a horde character if that matters)

  #### 1.3  Source Material
N/A
#### 2.1. Description
You should be able to cast your ability on yourself or a party/raid member
  #### 2.2 Source Material
N/A

**Comment by Undertoe** [comment]
Confirmed still broken as of 3.4.0.44832

**Comment by Undertoe** [comment]
Confirmed still unable to cast on anyone: 3.4.0.44930

**Comment by yurpcraft** [comment]
fixed 3.4.0.45043

**Comment by CharWS** [comment]
Looks like there's still some issue here
https://user-images.githubusercontent.com/104176019/184028367-1af60083-455e-4252-b2d9-b43881ba6165.mp4

**Comment by yurpcraft** [comment]
![image](https://user-images.githubusercontent.com/12848366/185254996-ae92411e-2fe8-48c9-bdb0-ae3997ca4d1f.png)
![image](https://user-images.githubusercontent.com/12848366/185255011-9f92068b-35c5-4daf-856d-99492c183afe.png)

can now be cast on self and party members
