### ISSUE TITLE
[BUG] Some quests in EPL are un-available for deathknights

### ISSUE THREAD

**Issue by Undertoe** [JamminL/wotlk-classic-bugs#144]
#### 1.1. Description
The following quests are unavailable for death knights: 
```
https://www.wowhead.com/wotlk/quest=9125/crypt-fiend-parts
https://www.wowhead.com/wotlk/quest=9136/savage-flora
https://www.wowhead.com/wotlk/quest=9127/bone-fragments
https://www.wowhead.com/wotlk/quest=9132/dark-iron-scraps
https://www.wowhead.com/wotlk/quest=9128/the-elemental-equation
```
  #### 1.2. How to Reproduce
Go to EPL on a death knight, and you cannot grab these quests.
On a toon that hasn't completed them they are still available.
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
Quests should be available.

**Comment by hillerstorm** [comment]
@Undertoe have you gotten your rep up to friendly first? That's a requirement for all of them

**Comment by Undertoe** [comment]
Issue was rep requirements, closed.
