### ISSUE TITLE
[BUG] Deterrence isn't deflecting spells

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#15]
#### 1.1. Description
Deterrence should deflect spells like polymorph, currently not working

EDIT EXTRA: It's also not deflecting/parrying charge/intercept effects

  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Cast Deterrence [19263]
           2. While Deterrence [19263] is still up, cast Polymorph [12826] 
           3. Notice hunter still gets polymorphed
  #### 1.3  Source Material
Nothing yet
#### 2.1. Description
Deterrence should deflect most spells cast while the aura is still up.
  #### 2.2 Source Material
https://www.wowhead.com/wotlk/spell=19263/deterrence

**Comment by Aggrend** [comment]
This didn't make this week but we have a fix on deck internally being tested. Hopefully should be in the 8/10 build.

**Comment by JamminL** [comment]
Fixed 3.4.0.45043
