### ISSUE TITLE
[BUG] Avenging Wrath doesn't prevent Hand of Protection

### ISSUE THREAD

**Issue by JayJay-110** [JamminL/wotlk-classic-bugs#151]
#### 1.1. Description
Currently you can cast Hand of Protection right after Avenging Wrath. Casting Avenging Wrath **after** Hand of Protection however is not possible.
The other Forbearance abilities are working correctly (they are not usable within 30s of Avenging Wrath)
  #### 1.2. How to Reproduce
           1. Use Avenging Wrath
           2. Use Hand of Protection right after
#### 2.1. Description
Hand of Protection should not be usable on targets 'who have used Avenging Wrath within the last 30 sec.' (Ingame Tooltip)
  #### 2.2 Source Material
Ingame Tooltip.

**Comment by JamminL** [comment]
Fixed build 3.4.0.45043
