### ISSUE TITLE
[#SomeChanges Suggestion] Remove "Ignite Munching" from Mages

### ISSUE THREAD

**Issue by yurpcraft** [JamminL/wotlk-classic-bugs#155]
### Description
Right now on beta, "ignite munching" is inconsistently applied.  Ignite munching occurs when 2 critical strikes land within a short amount of time, and the server only registers one of the ignites to be applied.  Because of the difference in travel time of fireball and pyroblast, ignite munching can occur frequently during hot streak procs and cooldown windows.  For now, it looks like ignite will only *sometimes* apply.

Instance of ignite munching not applying:
![image](https://user-images.githubusercontent.com/12848366/179402098-21acaf58-cb69-4447-b1b6-2eb7ac71d2f4.png)

Instance of ignite munching applying:
![image](https://user-images.githubusercontent.com/12848366/179402107-d0c55deb-243a-4673-8ac0-32243d87a6af.png)

~~There *is* a workaround for this - by standing at ranges more than 30 yards, the two spells will land outside of the "munch window", however, this may not be a great solution for most guilds, or on fights where positioning does not allow that.  This also has pvp implications - procs not doing as much damage as they should, if an opponent abuses the ignite munching positioning.~~ (Further research proved that it's not a distance to target thing, except in the case of Frostfire bolt at specific ranges.  See comments for more info)

My #somechanges suggestion is to modify ignite so that munching is no longer present, which would give mages the freedom of movement that other classes enjoy in raid encounters and pvp.

**Comment by yurpcraft** [comment]
Latest raid testing from the beta - thought i might have to dig a little more but it turns out it's pretty widespread, all screenshots here from the same fight https://classic.warcraftlogs.com/reports/CN4xmHJAjdRcKBqn/#fight=last&type=damage-done&source=4&view=events:

![image](https://user-images.githubusercontent.com/12848366/180478389-775814ca-1e25-4231-9e7f-7803dd58d571.png)

![image](https://user-images.githubusercontent.com/12848366/180478404-8dd9a9b2-9c4d-4582-91a2-0560107bd166.png)

![image](https://user-images.githubusercontent.com/12848366/180478431-72dad8ec-d6c9-496a-b4a5-88d9f1084cc8.png)

**Comment by yurpcraft** [comment]
After some more research done on ignite munching, I'm starting to think this is similar to the Arcane Blast bug that existed at the beginning of TBC / TBC Beta.  For that bug, arcane blast would cast, and you'd begin your next arcane blast with the spell queue, however the debuff (which in TBC decreased AB cast time) wouldn't be applied, because you essentially jumped the queue.  By using clear queued spell macros (CQS) mages were able to avoid the bug by re-adding network latency to the cast.  Blizzard decided to step in and fix this anyway because requiring a CQS macro to play the class the way it was meant to be played isn't exactly fun.

Fast forward to Wrath, and we're experiencing a similar issue.  Through some database analysis and a significant amount of data generation, we've found that in the vast majority of cases, queued Fireball / Hot Streak Pyroblasts will munch.  What made this interesting is that because Frostfire Bolt travels faster than Pyroblast, we rarely, if ever, saw any munching on those spells queued together.  Even more interestingly, when trying to find how long of a delay was needed for Fireball and Pyroblast to *not* munch each other, we determined that a simple CQS macro again could be wrapped around a Pyroblast cast, nearly effectively eliminating ignite munching (to an acceptable degree at least).

![image](https://user-images.githubusercontent.com/12848366/184366063-1c61515c-5cf5-45e9-b1ed-de5d6e44a3d7.png)
![image](https://user-images.githubusercontent.com/12848366/184366173-8fba3df9-15d4-45bf-91c8-4e50bc7a92a3.png)

Although in the mage discord, a CQS macro is no big deal, this can affect mage performance significantly in later phases (~2.5% dps loss in T7, closer to 10% dps loss in T10) which may be enough that this should be fixed in a similar fashion to Arcane Blast in TBC.

**Comment by yurpcraft** [comment]
Closing as a "won't fix" per conversations.  Macro workaround to avoid most of the problem

#showtooltip
/cqs
/cast Pyroblast
/cqs

**Comment by Cheesehyvel** [comment]
I would just like it to be known that there is a solution that Blizzard can implement that while it wouldn't remove ignite munching completely, it would prevent players from disabling spell-queue or using a macro that artificially freezes the game.

The solution is to increase the travel speed of Fireball from 24 to 28.
This would avoid fireball and pyroblast to hit the target at the same time, and as such eliminate most of the problems of ignite munching.
We know this works because Frostfire Bolt has a speed of 28 and ignite munching occurs much less frequently with FFB compared to Fireball without a workaround.

We believe this is a simple bandage that would result in a very minor dps gain for top players (less than 50 dps), but a very welcome QoL improvement.
