### ISSUE TITLE
[BUG] Furious Howl different ranks stack with each other

### ISSUE THREAD

**Issue by watchyoursixx** [JamminL/wotlk-classic-bugs#157]
#### 1.1. Description
Currently Furious Howl pet ability stacks with each rank. This means a hunter with call stabled pet can cycle through 5 different leveled wolves and stack up to 5 different abilities to last about 10-20s before a pull. Not a huge boost but 757 AP at lvl 70
  #### 1.2. How to Reproduce
          1. Cast call stabled pet - lasts 2 min or until combat
          2. pull out wolf, cast howl
          3. pull out another higher lvl wolf, cast howl. Repeat 2-3 until no more slots
          4. enjoy huge AP boost to start a fight

  #### 1.3  Source Material
![](https://cdn.discordapp.com/attachments/971994191464894514/996273174872334479/WolfPack.png)
#### 2.1. Description
Furious Howl should not stack with different ranks.
This may actually be blizzlike as I don't see any discussion about it back then so it could've worked or not
  #### 2.2 Source Material
N/A

**Comment by watchyoursixx** [comment]
fixed in build 45043

**Comment by TheDunds** [comment]
Furious howl rank 5 ![image](https://user-images.githubusercontent.com/110584436/193522601-3b37cb0e-abf2-4330-9f24-7b67ad12bae1.jpeg)
Furious howl rank 5 is not sharing CD across wolfs  
You can use howl on wolf 1 
Call out stabled wolf 2
Notice there is no cool down active on howl on wolf 2
This is allowing you too have a furious howl uptime of close to 40 seconds upon a boss pull
