### ISSUE TITLE
[#SomeChanges Suggestion] Glyph-changing should require the Lexicon of Power

### ISSUE THREAD

**Issue by aprimarycolor** [JamminL/wotlk-classic-bugs#161]
## 1. Introduction

In the first phase of the original Wrath of the Lich King expansion, glyphs were only adjustable near a Lexicon of Power, which were only available in major cities near Inscription trainers. This was changed in patch 3.1.0 -  

> Applying a glyph no longer requires a Lexicon of Power. The same rules for switching between dual talent specializations now apply to switching glyphs and cannot be performed while in combat, Battlegrounds (except when Preparation is up), or Arenas (no exceptions).

This was a quality-of-life change, but it had a significant impact on the raiding community at the time, and I think that impact will be magnified in Wrath of the Lich King Classic. Ultimately, I believe that this change is inconsistent with the new Classic WoW design philosophy, and should be reverted.

## 2. The World is the Main Character

The lexicon change erased an important gathering location for players and left behind useless Lexicons nearby every Inscription trainer. I recall being very interested to learn what the purpose of these Lexicons were when I first discovered them in 2009, and I think it would be disappointing to new players to realize that it no longer has a purpose. _Consider removing these lexicons if they are decided to be no longer required in WotLK Classic._

## 3. Approachable and Social Raiding

In The Burning Crusade Classic, travel was an effective barrier to small adjustments to talent changes. I believe that adding a travel barrier to glyph adjustments will make glyph decisions more impactful and make raiding a better social experience. 

If glyph decisions aren't impactful, a lot of un-fun situations arise. For example, glyphs that reduce ability cooldowns, like `Glyph of Fire Elemental Totem`, snapshot after the cast. That is, replacing the `Glyph of Fire Elemental Totem` after casting leaves the cooldown at 5 minutes. This means that a min-maxing shaman would have to swap glyphs every five minutes for ideal Fire Elemental uptime. 

There are other examples of high frequency, min-max swaps like this, and requiring the Lexicon of Power would prevent these situations from arising.

Now, swapping between glyphs is cool and _can be_ very satisfying. An Arms warrior might want to have `Glyph of Cleaving`, `Glyph of Sweeping Strikes`, and `Glyph of Bladestorm` during aoe pulls, but would prefer `Glyph of Heroic Strike`, `Glyph of Mortal Strike`, and `Glyph of Execution` on a single target boss fight. The warrior could do this in two ways:

**A.**
> Use the Dual Talent Specialization System to have an “aoe” spec and a “single target” spec, and swap between those two specializations between boss fights.

**B.**
>They could carry stacks of glyphs with them in their bags, and spend time before and after each boss fight swapping glyphs around. 

Given the option, I think everyone would choose the first approach. The second approach is tedious and requires players to fill their bags with glyphs. That warrior would have to use at least 120 glyphs a week raiding 10-man and 25-man Naxxramas alone. So, option **A** is a great solution for this situation.

## 4. Keep it fun 

What happens if this warrior needs to have a tanking off-spec for their guild? That means that this warrior won't be able to have both an "aoe" and a "single target" spec, so they'd be stuck with option B. Adding the Lexicon of Power requirement would force this warrior to go to a city between bosses, which is effectively just preventing them from enjoying the glyph system to its fullest potential.

The intent of this change is not to prevent players from having fun with glyphs. As such, if this change is considered, also consider some solution for players who still want flexibility, just with additional restrictions. I've provided two ideas.

### Third Dual Specialization Loadout
> Players can purchase an expensive third specialization loadout from their class trainers. Our warrior friend can have a "single target" spec, an "aoe" spec, and an "off-tank" spec.

### Craftable Lexicons of Power
> Similar to [Tome of the Tranquil Mind](https://www.wowhead.com/item=141446/tome-of-the-tranquil-mind), players with inscription can craft and summon their own temporary Lexicons of Power.

**Comment by Restomagus** [comment]
No, this goes directly against how wrath is meant to, and I am someone who has literally always wanted a tri-spec. You are asking for a HEAVY IMPACT NERF to the gold making potential of inscriptionists (scribes).

**Comment by Aggrend** [comment]
Probably a no-go. Thanks for the suggestion, this was removed for a reason and specifically trying to re-implement this isn't likely to be a super popular change.
