### ISSUE TITLE
[BUG] Glyph of Disease Pestilence 

### ISSUE THREAD

**Issue by CharWS** [JamminL/wotlk-classic-bugs#163]
#### 1.2. How to Reproduce
           1. Equip Glyph of Disease
           2. Apply diseases to enemy A
           3. Change targets to enemy B
           4. Cast Pestilence on enemy B which does not have any diseases active on it
           5. Change targets back to target A and note that its diseases are back to maximum duration
#### 2.1. It's expected that Pestilence when cast with Glyph of Disease equipped will only refresh diseases on your primary target, and then spread those diseases to secondary targets as happens without the glyph.

Beta Patch 3.4.0 (44644)

**Comment by Aggrend** [comment]
This matches 3.3.5 reference behavior. NAB for now.
