### ISSUE TITLE
[BUG] Pets and Guardians will turn to target their owner when casting friendly spells

### ISSUE THREAD

**Issue by dombi676** [JamminL/wotlk-classic-bugs#167]
#### 1.1. Description
Shaman's Spirit Wolves and Healing Stream Totem, Priest's Shadowfiend and Death Knight's Bloodworms will turn to target their owner when healing/generating mana.
  #### 1.2. How to Reproduce
           1. Talent into Feral Spirit in the Enhancement talent tree for Shamans
           2. Summon Spirit Wolves and make them attack a target
           4. Watch them turn and target their owner every time they heal through Spirit Hunt
           Same steps for Healing Stream Totem, Shadowfiend and Bloodworms
  #### 1.3  Source Material
Spirit Wolves
https://streamable.com/khufaw

Healing Stream Totem
https://streamable.com/dvav69

Shadowfiend
https://streamable.com/od8o43

Bloodworms (bit hard to see since they are so small and won't aggro target dummies)
https://streamable.com/tgsqbd

#### 2.1. Description
Pets and guardians should not turn around to target their owner when casting spells
  #### 2.2 Source Material
2008 video from original wrath beta shows spirit wolves healing through Spirit Hunt without turning around
https://youtu.be/HhpQneM9enQ

**Comment by yurpcraft** [comment]
@dombi676 can you link a video showing the new behavior and I can mark as closed

**Comment by JamminL** [comment]
Fixed as of 3.4.0.45043
