### ISSUE TITLE
[BUG] Deadly brew doesn't refresh crippling

### ISSUE THREAD

**Issue by peterderpirat** [JamminL/wotlk-classic-bugs#17]
#### 1.1. Description
Whenever Wound poison is applied Crippling poison should be applied or refreshed on the target, currently crippling will not be refreshed if it's already present on the target when Wound Poison is applied.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Spec 2 points into Deadly Brew & apply wound poison on your weapon
           2. Attack the training dummy and observe crippling never being refreshed
  #### 1.3  Source Material
[{Video, Posts, etc..}](https://i.imgur.com/dSaQ0mV.jpeg)
#### 2.1. Description
Crippling should be refreshed when Wound poison is applied
  #### 2.2 Source Material
{Video, Posts, etc..}https://youtu.be/HOGRSWOc7qc?t=268

**Comment by JamminL** [comment]
Confirmed

**Comment by JamminL** [comment]
Fixed
