### ISSUE TITLE
[TEST-REQUEST] Retry timer was not in original Wotlk. 

### ISSUE THREAD

**Issue by fxweber** [JamminL/wotlk-classic-bugs#170]
### Description
I believe that the retry timer which currently exists on beta did not exist in original WotLK. Autoshot always went off instantly after stopping, even for a few ms, if it was off cooldown. 

I would request Blizzard to test this against a reference client, as it would be a huge nerf to Hunters especially in PvP, where having to stop for up to .65s (.15s for game to register that you have stopped+potential retry timer) for your autoshot is a massive deal, due to the pace of WotLK PvP and how reliant the hunter class is on kiting.

Furthermore I would challenge anyone to find a clip of a Hunter from original WotLK whose Autoshot didnt go off after stopping for a short time (while autoshotcd is ready ofcourse).

**Comment by watchyoursixx** [comment]
closing this as "fix not likely" as it appears to be staying. It makes sense that it was part of wrath as well since I don't think it was removed until at least cata when you could shoot while moving.
