### ISSUE TITLE
[BUG] Freedom under stun

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#171]
#### 1.1. Description
You can't freedom while being stunned at the moment (unless you have the Ret talent)
  #### 1.2. How to Reproduce
           1. Get stunned
           2. Try press freedom
           3. You can't
  #### 1.3  Source Material
Nothing yet
#### 2.1. Description
You should be able to press Freedom while being stunned even if you aren't Ret
  #### 2.2 Source Material
https://wowwiki-archive.fandom.com/wiki/Hand_of_Freedom
Hotfix (2015-05-11): "No longer usable while stunned"
This was a hotfix during WoD, so 4-5years after wrath of the lich king

**Comment by JamminL** [comment]
> This is not a bug, untalented freedom works just like other abilities and cannot be used while you are incapacitated.

To be clear, this isnt true. Even without the ret talent you can freedom in saps, gouges, repetances and traps.

- freedom self while sapped <https://www.youtube.com/watch?v=aw1oozbHvVw&t=30s>
- Hpala freedoms warrior while repetanced <https://www.youtube.com/watch?v=0PswF4XCkUE&t=430s>
- hpala freedoms while trapped s8 <https://www.warcraftmovies.com/movieview.php?id=153147> 1:55




there were Aj threads about being possible to use it while stunned as well and cata clips. But no clips have been found for wotlk. I’m reopening but tagging needs research

**Comment by Shintaxgg** [comment]
https://wowwiki-archive.fandom.com/wiki/Hand_of_Freedom
Hotfix (2015-05-11): "No longer usable while stunned"
This was a hotfix during WoD, so 4-5years after wrath of the lich king

**Comment by JamminL** [comment]
https://youtu.be/imrd5EltQao?t=129 cant freedom in stun, closed.
