### ISSUE TITLE
[BUG] Sigil of the Frozen Conscience

### ISSUE THREAD

**Issue by CharWS** [JamminL/wotlk-classic-bugs#176]
#### 1.2. How to Reproduce
           1. Put talent points into the Icy Talons talent
           2. Cast Icy Touch noting your attack speed with the Icy Talons buff
           3. Equip the Sigil
           4. Cast Icy Touch with the Sigil equipped noting your attack speed with the Icy Talons buff
  #### 1.3  Source Material
https://cdn.discordapp.com/attachments/364459574327246851/999859630073196574/unknown.png (no gear no Icy Talons) 1.59 attack speed
https://cdn.discordapp.com/attachments/364459574327246851/999859684309733457/unknown.png (no gear with Icy Talons up) 1.32 attack speed
https://cdn.discordapp.com/attachments/364459574327246851/999859835619250236/unknown.png (Sigil equipped with Icy Talons up) 0.69 attack speed
https://cdn.discordapp.com/attachments/364459574327246851/999859879445549116/unknown.png 
#### 2.2 Source Material

**Comment by JamminL** [comment]
#187 for gargoyle cast speed as an obvious consequence

**Comment by Aggrend** [comment]
We have a fix for this in test and assuming it passes, this should be fixed in the next beta build (~Weds 8/10)

**Comment by JamminL** [comment]
Fixed Build 3.4.04543
