### ISSUE TITLE
[BUG] Right click to attack sometimes doesn't work for hunters auto shot

### ISSUE THREAD

**Issue by watchyoursixx** [JamminL/wotlk-classic-bugs#177]
#### 1.1. Description
With the auto swap between ranged and melee enabled, right clicking a target should start to attack that target with ranged or melee depending on distance from the target.

  #### 1.2. How to Reproduce
          1. Enable auto swap between auto attack and auto shot in Combat settings.
          2. right click a target to attack
  #### 1.3  Source Material
This was a change in TBC and remained like this for the rest of the game
#### 2.1. Description
Should be able to right click and attack from range
  #### 2.2 Source Material
N/A

**Comment by watchyoursixx** [comment]
I switched specs with dual spec and the issue went away. I didn't change any settings.. having difficulty reproducing naturally. Maybe just an issue with templates? I'm not sure.

**Comment by Aggrend** [comment]
QA has had zero luck reproducing this and we are closing it out on our end. Could have been picked up by another fix, potentially.

**Comment by watchyoursixx** [comment]
Just leaving this here as well I haven't had any luck reproducing. I've tried recreating a template and doing the same things but still had no luck. Seems to either be a very rare occurrence where the stars aligned or it's been fixed from another fix or something.
