### ISSUE TITLE
[BUG] Daily quest [Riding the Red Rocket] cannot be completed

### ISSUE THREAD

**Issue by raethkcj** [JamminL/wotlk-classic-bugs#178]
#### 1.1. Description
  Riding the rocket directly into the enemy faction's boat simply ejects your character, without blowing up the boat or providing quest credit. In addition, the rocket is very easy to steer, and turns quickly following the player's camera.
  #### 1.2. How to Reproduce
          1. Accept the quest
          2. Acquire a barrel of Element 115
          3. Enter a Rocket Propelled Warhead
          4. Drive directly into the X on the enemy faction's boat
  #### 1.3  Source Material
  https://youtu.be/d5lyjoJ3Bvw
#### 2.1. Description
  Hitting the X on the enemy faction boat should cause an explosion and grant quest credit. The rocket turns slowly in response to the player turning the camera.
  #### 2.2 Source Material
  https://www.youtube.com/watch?v=hKM38kSJwyo

**Comment by raethkcj** [comment]
As of Build 44833, I am consistently disconnected from the game 5-10 seconds after controlling the rocket.

**Comment by watchyoursixx** [comment]
this should be fixed in 45166 per blizz's notes. Closing unless someone has evidence it is still bugged/crashing people.
