### ISSUE TITLE
[BUG] Vanish isn't dropping combat in instanced PVP/arena/bg (bug since TBC)

### ISSUE THREAD

**Issue by perpabc** [JamminL/wotlk-classic-bugs#182]
#### 1.1. Description
Vanish doesn't drop combat in instanced PVP (it was fine in Classic but upon moving to TBC, something broke this and it persisted through SoM too since it was using the TBC client). Same thing is happening with Shadowmeld so you can't meld drink/meld mount/meld stealth making night elf useless.
  #### 1.2. How to Reproduce
          
           1. Join an Arena game on rogue
           2. Get in combat
           3. Press Vanish and try to mount or eat
  #### 1.3  Source Material
https://gyazo.com/719a41e8e2ad085766618e47a581abde
#### 2.2 Source Material
https://www.youtube.com/watch?v=spH5R2pTBFU (entire video shows vanish dropping combat, specific examples at 49 seconds, 1:27, 1:54)

**Comment by MuffledBaneMask** [comment]
accepted
