### ISSUE TITLE
[BUG] Missing Target Dummy in Dalaran

### ISSUE THREAD

**Issue by Jgrenier91** [JamminL/wotlk-classic-bugs#184]
#### 1.1. Description
There should be a target dummy in the sewers of dalaran.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Navigate to the sewers of Dalaran
  #### 1.3  Source Material
https://i.imgur.com/0wWstKd.jpeg
#### 2.1. Description
{Describe how that mechanic/spell/npc should be working, in detail}
  #### 2.2 Source Material
2008 footage of the dummy: https://www.youtube.com/watch?v=L6kM1EGT6uc

**Comment by yurpcraft** [comment]
I believe this is not a bug - looking at this video you can see there's no training dummy there.  It may be a dummy that existed in the wotlk beta in 2008, but didn't make it to live?

https://youtu.be/RfKnS4uKV2E?t=92
