### ISSUE TITLE
[BUG] Glyph of Sap 30 seconds

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#186]
#### 1.1. Description
Glyph of Sap makes sap 30 seconds in PvP
  #### 1.2. How to Reproduce
           1. Get glyph of sap
           2. Sap a player
           3. Notice the duration
  #### 1.3  Source Material
https://gyazo.com/24cf799e08ef5c250d99687131d041ee
#### 2.1. Description
Sap shouldn't last 30 seconds in pvp with glyph
  #### 2.2 Source Material
Nothing Yet

**Comment by Shintaxgg** [comment]
Still isn't fixed as of new build

**Comment by Shintaxgg** [comment]
fixed, same for seduce & trap timer

**Comment by JamminL** [comment]
Fixed as of 3.4.0.45264
