### ISSUE TITLE
[BUG] Judgement of Justice is causing feared players to maintain control of their character

### ISSUE THREAD

**Issue by Jgrenier91** [JamminL/wotlk-classic-bugs#188]
#### 1.1. Description
Judgement of Justice is causing feared players to maintain control of their character. They are still able to move and use abilities even while under any fear effect.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. fear an enemy target
           2. apply judgement of justice to that target
           3. notice they can control their character
  #### 1.3  Source Material
https://gfycat.com/shimmeringcaninelemur
#### 2.1. Description
Fear should take effect
  #### 2.2 Source Material
https://worldofwarcraft.fandom.com/et/wiki/Patch_3.0.2

**Comment by JamminL** [comment]
Fixed Build 3.4.04543
