### ISSUE TITLE
[BUG] Judgment of Justice vs trinket pvp

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#189]
#### 1.1. Description
Trinket PvP don't remove judgment of justice
  #### 1.2. How to Reproduce
           1. Get judgment of justice
           2. Trinket pvp
           3. Still have judgment of justice
  #### 1.3  Source Material
https://gyazo.com/66b395d7dcf4ab60f04ab0b477317fc1
#### 2.1. Description
Trinket pvp should remove the debuff judgment of justice
  #### 2.2 Source Material
https://www.youtube.com/watch?v=xummB-b9nDE
1m05, shaman trinket it removes HoJ + Judgment of Justice
Patch 2.3.0 (13-Nov-2007): PvP Trinkets: Insignia of the Alliance, Insignia of the Horde, Medallion of the Alliance, and Medallion of the Horde now clear the debuff from Judgement of Justice.
Source: http://wowwiki.wikia.com/wiki/PvP_trinket

**Comment by Shintaxgg** [comment]
fixed

**Comment by JamminL** [comment]
Fixed Build 3.4.04543
