### ISSUE TITLE
[BUG] Shadow Priest Dot Times are not Affected By Haste

### ISSUE THREAD

**Issue by CyberQuackGames** [JamminL/wotlk-classic-bugs#190]
#### 1.1. Description
  The `Shadowform` talent "grants Devouring Plague and Vampiric Touch the ability to benefit from haste", however neither dot is getting haste applied.
  #### 1.2. How to Reproduce
           1. Ensure Shadowform talent is selected in build and some haste gear is equipped.
           2. Cast Devouring Plague or Vampiric Touch on a target
           3. Note the duration is the full 24 seconds for Devouring Plague or 15 seconds for Vampiric Touch

#### 2.1. Description
Per [3.3.0 patch notes](https://wowpedia.fandom.com/wiki/Patch_3.3.0) the total duration and the tick times of Devouring Plague and Vampiric Touch should be reduced.
  #### 2.2 Source Material
Talent description in game and 3.3.0 patch notes.

**Comment by dbyena** [comment]
Might as well add Shadow: Word Pain to the mix while you're at it.

**Comment by watchyoursixx** [comment]
> Might as well add Shadow: Word Pain to the mix while you're at it.

This can be a #somechanges suggestion but it's not how it was in WotLK afaik. Only the 2 mentioned in the talent.

**Comment by dbyena** [comment]
> > Might as well add Shadow: Word Pain to the mix while you're at it.
> 
> This can be a #somechanges suggestion but it's not how it was in WotLK afaik. Only the 2 mentioned in the talent.

I've added it (#somechanges) #85

**Comment by CyberQuackGames** [comment]
This is still a bug as of todays beta release. 

Notes: https://us.forums.blizzard.com/en/wow/t/wrath-classic-beta-development-notes-updated-august-3/1267790

> Spell and melee haste ratings are now providing the full intended benefits.

Is incorrect from the release notes as warlocks and shadow priests still have haste issues with dot(s).

**Comment by acuD1** [comment]
https://www.wowhead.com/wotlk/news/wrath-classic-beta-development-notes-updated-august-10-328279?webhook Fixed

**Comment by JamminL** [comment]
Can anyone confirm?

**Comment by dbyena** [comment]
Yes it's fixed

**Comment by JamminL** [comment]
Fixed Build 3.4.04543
