### ISSUE TITLE
[BUG] Dancing rune weapon

### ISSUE THREAD

**Issue by danniellos94** [JamminL/wotlk-classic-bugs#193]
#### 1.1. Description
1. Really often the first autottack damage from dancing rune weapon is incorrect this only applies for the first autoattack.
2. Autoattack from dancing rune weapon can be resisted.
3. Spells have some weird damage calculation it's definitely not 50% reduced damage even from death coil, frost fever, blood plague  and icy touch which is the easiest to calculate.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Get 100 runic power and use rune weapon
           4. Let it autoattack
           5. Use icy touch
           6.  Use death coil.
           7. Check damage.
  #### 1.3  Source Material
{Video, Posts, etc..} At the end.
### 2. Expected Behavior
DRW snapshots hit,haste,attack power and crit rating and %dmg buffs/debuffs
  #### 2.1. Description
{Describe how that mechanic/spell/npc should be working, in detail}
  #### 2.2 Source Material

https://classic.warcraftlogs.com/reports/BXWxGw8RDAY49ykV/#fight=4&type=damage-done&source=13
https://web.archive.org/web/20100808083352/http://elitistjerks.com/f72/t61176-blood_simple_day_music_died/p6/

00:14.826	Rune Weapon 1 (Rugstox) Melee Instructor Razuvious 551
00:16.909	Rune Weapon 1 (Rugstox) Melee Instructor Razuvious 1502

00:24.301	Rune Weapon 1 (Rugstox) Melee Loatheb 514
00:28.432	Rune Weapon 1 (Rugstox) Melee Loatheb 1354 Glancing 

02:27.380	Rugstox gains Dancing Rune Weapon from Rugstox
02:27.380	Rune Weapon 2 (Rugstox) Melee Kel'Thuzad 384 Glancing
02:29.730	Rugstox Melee Kel'Thuzad 1424 Glancing

01:48.914	Rugstox gains Dancing Rune Weapon from Rugstox
01:48.914	Rugstox Dancing Rune Weapon Sapphiron Resist

00:11.999	Rugstox Death Strike Noth the Plaguebringer 2669
00:12.016	Rune Weapon 1 (Rugstox) Death Strike Noth the Plaguebringer 630  --- according to EJ drw gets improved death strike death strike is 97%- 98% weapon damage if rune weapon hits for 1167 then drw ds should hit for at least 1132
00:12.949	Rune Weapon 1 (Rugstox) Melee Noth the Plaguebringer 1167

00:13.500	Rugstox Heart Strike Noth the Plaguebringer 2578
00:13.517	Rune Weapon 1 (Rugstox) Heart Strike Noth the Plaguebringer 666

00:38.915	Rugstox Frost Fever Noth the Plaguebringer Tick 401
00:38.932	Rune Weapon 1 (Rugstox) Frost Fever Noth the Plaguebringer Tick 186

00:37.266	Rugstox Blood Plague Noth the Plaguebringer Tick 410
00:37.287	Rune Weapon 1 (Rugstox) Blood Plague Noth the Plaguebringer Tick 47 (R: 126)

00:26.744	Rugstox Icy Touch Instructor Razuvious 1081
00:26.777	Rune Weapon 1 (Rugstox) Icy Touch Instructor Razuvious 478

I also want to say that this behaviours was appearing on retail wotlk the same way as a random gargoyle delay that got fixed.
I know that DRW shouldn't get any ARP propably but it's damage should more likely match the 50% without any ARP.
I would like to see any comment from dev saying if it's working correctly and why it's working this way. (with damage calculations)

**Comment by JamminL** [comment]
Please format your bug report properly, and use 1 issue per bug report
