### ISSUE TITLE
[BUG] DRW ability damage probably incorrect

### ISSUE THREAD

**Issue by danniellos94** [JamminL/wotlk-classic-bugs#195]
#### 1.1. Description
Dancing rune weapon ability damage is most likely incorrect. Looking even at icy touch, frost fever, blood plague, death coil it's not doing 50% reduced damage. There is even more difference in strikes.
Spell id 49028
  #### 1.2. How to Reproduce
          
           1. Use rune weapon with x amount of attack power.
           2. Use abilities that should be copied with rune weapon.
           3. See the big difference in hits.
  #### 1.3  Source Material
https://classic.warcraftlogs.com/reports/BXWxGw8RDAY49ykV/#fight=4&type=damage-done&source=13

00:11.999	Rugstox Death Strike Noth the Plaguebringer 2669
00:12.016	Rune Weapon 1 (Rugstox) Death Strike Noth the Plaguebringer 630  --- according to EJ drw gets improved death strike death strike is 97%- 98% weapon damage if rune weapon hits for 1167 then drw ds should hit for at least 1132
00:12.949	Rune Weapon 1 (Rugstox) Melee Noth the Plaguebringer 1167

00:13.500	Rugstox Heart Strike Noth the Plaguebringer 2578
00:13.517	Rune Weapon 1 (Rugstox) Heart Strike Noth the Plaguebringer 666

00:38.915	Rugstox Frost Fever Noth the Plaguebringer Tick 401
00:38.932	Rune Weapon 1 (Rugstox) Frost Fever Noth the Plaguebringer Tick 186

00:37.266	Rugstox Blood Plague Noth the Plaguebringer Tick 410
00:37.287	Rune Weapon 1 (Rugstox) Blood Plague Noth the Plaguebringer Tick 47 (R: 126)

00:26.744	Rugstox Icy Touch Instructor Razuvious 1081
00:26.777	Rune Weapon 1 (Rugstox) Icy Touch Instructor Razuvious 478

### 2. Expected Behavior
Expected behaviour is dancing rune weapon does 50% reduced damage (not considering arp ofc).
  #### 2.1. Description

DRW snapshots hit,haste,attack power and crit rating and %dmg buffs/debuffs

  #### 2.2 Source Material

We know we could observe this on retail wotlk same as random gargoyle delay. Don't close this report if it shouldn't work this way please say (in depth) how the damage should be calculated.

**Comment by watchyoursixx** [comment]
some DK expert can chime in but in this video it clearly shows damage is significantly lower than the DK's damage, significantly lower than 50% too.
https://www.warcraftmovies.com/movieview.php?id=159567&__cf_chl_jschl_tk__=fe74e20672c61afa7427397e122b8546e84c3566-1618075195-0-AXPkg9hx47JPyGWd7Z-yVsBMopaNDOBlXzOUV-x5e8f2vTr_Pk9kCzUn6S_jNXW5QvUwPFQLacpUpX3CbdDRhwd-6RMPssgfjN7bGw_i2-UOMtvL0sS4vTO5iQmZeifYmd7-kz94f7SP7Eq-6XC9e025v0MHbyBJQmy7HYR87MLYyvvEve8sLZRjywFBP7J11_MjyDx3y3G4jLHCcHGM4SWrHA678OwIKzSdUAPNAKe_hKq4MLgtTo0eT86ZC-bZdYL5WvJlk7v9p-GYrpfxZ_PzbyEiUaBeH1r7aukPb7LNKkXPGaoPy_l04NJDlj2dl_eJOoG1uB2UatPA13heZhcO0ai6wKPd4RYV6nanBr4oTEAxwQ2fCZePMZ06TjUU2KHGxPYRtZtVfVYL9Pbb4m8Xcs8a09Xca5A6mh0my-7Q

see below snips:
![image](https://user-images.githubusercontent.com/47162044/180703840-81f619e1-c8b0-40d6-a88f-e633f120ba0f.png)
![image](https://user-images.githubusercontent.com/47162044/180703878-5d4e45ad-e671-426a-9920-f6f940e1ee93.png)
![image](https://user-images.githubusercontent.com/47162044/180703907-e27e3079-c576-4450-ae81-df582c5bfd4f.png)

these are just examples. Possibly in this vid pet doesn't get 30% bonus from the ICC buff, but that still doesn't make up for the nearly 90% difference

**Comment by danniellos94** [comment]
Yea, there are some weird interactions I can link cata video with the guy wearing shadowmourne and icc gear, his drw strikes are way more closer to 50% of dk damage.

https://youtu.be/1e1cL65J87Q?t=290 You can see attack power at left bottom he obv have icc gear and shadowmourne same as the guy in wotlk vid. Mastery gives only shield after death strike for blood in cata and attack power.  I really hope we can get answer how it should work in depth.

**Comment by caccavale** [comment]
Char and I collected data on this-- it seems some skills scale sub 50% and some higher likely due to how / where they pull modifiers from.  Will try and add that to this ticket.

Big issue here though is that tooltips are not expected blizz-like behavior.  Will need some good log / video data from wotlk to pull expected numbers.

**Comment by danniellos94** [comment]
I don't see any reason of not fixing it, looking at any data from later expansions - the linked above video from cata for example.
We've already fixed gargoyle to no delay when it wasn't fixed until mop. https://www.youtube.com/watch?v=jA5I7jCqyfg
https://prnt.sc/NTpN_pfuFr56
https://wowwiki-archive.fandom.com/wiki/Summon_Gargoyle

**Comment by JamminL** [comment]
Then make a SomeChanges Suggestion, closing as NAB for now

**Comment by danniellos94** [comment]
All videos from retail. 

https://youtu.be/221jtKbsWQA?t=46 960 heart strike much more dmg on aa rune weapon 6911 attack power, better weapon wrathful gladiator claymore
https://youtu.be/r11asc2Cd-0?t=109 967 heart strike much (he casted diseases before) less aa on rune weapon 5835 attack power on the guy before procs ,for sure less attack power even with procs Citadel Enforcer's Claymore

https://youtu.be/-_8e-VJfAdk?t=57 death coil 330 seems like not scaling off ap too

https://www.youtube.com/watch?v=221jtKbsWQA&t in this video we can see pet death coil 351 and pet death coil 2694 crit... bug?

Might of mograine seems working.

Seems like just weapon dmg are counted into strikes damage (no ap scaling) this is making rune weapon super weak with 3.5 sec attack speed. I would like to see an answer if this is intended.
