### ISSUE TITLE
[BUG] Arcane Blast (debuff) not applying or increasing stacks after resists

### ISSUE THREAD

**Issue by yurpcraft** [JamminL/wotlk-classic-bugs#196]
#### 1.1. Description

When casting arcane blast and getting a "resist", arcane blast (debuff) is not applying or increasing its stacks.  This is inconsistent with behavior from current (live) TBC classic, and inconsistent with WotLK historically.

  #### 1.2. How to Reproduce
          {1. Remove all gear
           2. Cast Arcane Blast on the boss dummy
           3. When resisted, observe Arcane Blast stacks}
  #### 1.3  Source Material
![image](https://user-images.githubusercontent.com/12848366/180668550-7673b31e-6917-485b-b252-77cbeddfc9be.png)
![image](https://user-images.githubusercontent.com/12848366/180668555-c04c1271-d193-4560-b7b6-2ccf9de84818.png)
![image](https://user-images.githubusercontent.com/12848366/180668559-3592f888-42fa-4a0f-9103-071fb1dee4b6.png)
![image](https://user-images.githubusercontent.com/12848366/180668560-fd3c683a-6374-43bc-a91f-91ecf78a7afa.png)
#### 2.1. Description
As it does in TBC classic, Arcane Blast (debuff) should apply or increase stacks when resisted.
  #### 2.2 Source Material
I checked if any changes were made to the spell to allow this behavior, and I'm not seeing anything according to this fansite's compiled patch notes:  https://wowpedia.fandom.com/wiki/Arcane_Blast#Patch_changes

**Comment by yurpcraft** [comment]
Fixed as of 3.4.0.45043
![image](https://user-images.githubusercontent.com/12848366/184018133-32f366d4-656f-40fe-ab80-3dbaaeb53cea.png)

**Comment by yurpcraft** [comment]
Reversed the logic in my head - still broken

**Comment by Aggrend** [comment]
Calling this NAB. Resists/Misses do not give Arcane Blast stacks in the 3.3.5 reference client.
