### ISSUE TITLE
[BUG] Alliance Death Knight Ghouls

### ISSUE THREAD

**Issue by CharWS** [JamminL/wotlk-classic-bugs#197]
#### 1.2. How to Reproduce
           1. Make an alliance Death Knight (have tested 70 and 80 templates)
           2. Talent into Master of Ghouls
           3. Summon a Ghoul pet
           4. Note the damage of the pet Ghoul and your location
           5. Go to Outland/Northrend/Eastern Kingdoms/Kalimdor and compare the pet damage
  #### 1.3  Source Material
All comparisons done with same talents and glyphs, no buffs present on character or ghoul
Level 80 Horde no gear ghoul in Thunder Bluff: https://cdn.discordapp.com/attachments/364459574327246851/1000194725028053003/unknown.png (1290 ap 235-276 damage)
Level 80 Alliance no gear ghoul in Darnassus: https://cdn.discordapp.com/attachments/364459574327246851/1000195070370254878/unknown.png (1290 ap 224-263 damage)
Level 80 Alliance no gear ghoul in Dalaran: https://cdn.discordapp.com/attachments/364459574327246851/1000198067217240074/unknown.png (1290 ap 235-276 damage)
Level 70 Alliance no gear ghoul in Stormwind: https://cdn.discordapp.com/attachments/364459574327246851/1000265038604533790/unknown.png (652 ap 139-172 damage)
Level 70 Alliance no gear ghoul in Northrend: https://cdn.discordapp.com/attachments/364459574327246851/1000266220454555708/unknown.png (652 ap 146-181 damage)

#### 2.1. Description
Expect Ghoul damage to only change when stats change

Beta Build 3.4.0 (44729)

**Comment by Aggrend** [comment]
Our QA is not able to reproduce this internally at all. Is this still observable on beta as of build 45043?

**Comment by CharWS** [comment]
Yeah still seeing the issue
![image](https://user-images.githubusercontent.com/104176019/184457835-114fe716-34d2-440a-a8a6-af477e514018.png)
![image](https://user-images.githubusercontent.com/104176019/184457853-616a5eee-0dc8-4f78-bc87-4b53dd0cef45.png)
![image](https://user-images.githubusercontent.com/104176019/184457884-31081024-4012-468d-a4a9-7f00f8bfcf53.png)
just took those now that's naked 80 template draenei frost pres Dalaran and then Stormwind and then hearthing back to Dalaran

**Comment by CharWS** [comment]
Whipped up a fresh toon just to be sure (the draenei had existed on the server previously)
    1. create template alliance death knight
    2. unequip gear
    3. purchase and equip glyph of raise dead or corpse dust from vendor
    4. talent into master of ghouls
    5. summon ghoul and check stats in dalaran
    6. take portal to an alliance city and check stats again
Dalaran Stats:
![image](https://user-images.githubusercontent.com/104176019/184458349-b8cabdcd-e825-4af8-86e9-8bf7133175ec.png)
Stormwind Stats:
![image](https://user-images.githubusercontent.com/104176019/184458370-14d6fc56-b479-4dac-9a29-18957bf9e067.png)
