### ISSUE TITLE
[BUG] Armor scaling for Frost Presence and Dire Bear Form on accessories

### ISSUE THREAD

**Issue by wotktestact** [JamminL/wotlk-classic-bugs#198]
#### 1.1. Description
Frost Presence and Dire Bear Form are scaling armor from bonus armor. This includes rings, weapon, trinkets and green armor portion of armor items. 
  #### 1.2. How to Reproduce
           1. Equip a ring/trinket/armor/amulet item with armor on
           2. Cast Frost Presence or Dire Bear Form
           3. Check character sheet
  #### 1.3  Source Material
{Video, Posts, etc..}
![drucast_trink](https://user-images.githubusercontent.com/48561262/180681598-27c43516-5fd9-4a61-9df1-556b8e395041.jpg)
![drubear_trink](https://user-images.githubusercontent.com/48561262/180681602-abcaedcf-6c4b-45b6-b5f4-7b3f03fb06c9.jpg)
![drubear_notrink](https://user-images.githubusercontent.com/48561262/180681608-969308fc-be7f-4d9b-ac85-6fecea38adc8.jpg)
![drucast_notrink](https://user-images.githubusercontent.com/48561262/180681611-2c4e2f92-c86d-4734-ad39-0fed111055d5.jpg)
![dk_armring](https://user-images.githubusercontent.com/48561262/180694721-88ebb259-6a30-4cd2-b6a8-70ecbb5a02f0.jpg)
![dk_noring](https://user-images.githubusercontent.com/48561262/180694725-5de20313-7259-4cec-ab8b-7636190c9f6c.jpg)

#### 2.1. Description
In patch 3.0.8 both Frost Presence and Dire Bear Form was changed to not scale off bonus armor. This includes accessory armor and the green portion of cloth/leather/mail/plate slots.

  #### 2.2 Source Material
Patch notes from 3.0.8:
https://gist.github.com/BradBlondebeard/51de640accc78e63e87a4e6d0ee73783#file-wotlkpatchnotes-txt-L4235

Multiple comments on WoWHead item pages discussing this behaviour e.g.
https://www.wowhead.com/wotlk/item=37257/band-of-torture#comments
https://www.wowhead.com/wotlk/item=46343/fervor-of-the-protectorate#comments
https://www.wowhead.com/wotlk/item=40280/origin-of-nightmares#comments

**Comment by MuffledBaneMask** [comment]
accepted

**Comment by watchyoursixx** [comment]
This appears to be fixed at least as of 45264

Armor w/o dire bear form - 1905
![image](https://user-images.githubusercontent.com/47162044/186323758-c4263aaa-27d9-43d7-8973-d4f84d4da0ed.png)

Armor w/ dire bear form - 7977
![image](https://user-images.githubusercontent.com/47162044/186323789-7dce7a2e-7730-457f-a496-7f46aa6a5ee6.png)

Armor w/ 170 Armor ring - 8147
![image](https://user-images.githubusercontent.com/47162044/186323854-017ba31f-85f9-469c-9130-47eb0def4df5.png)

While investigating this, I also noticed that items with "green" armor text is not currently applying armor at all?
![image](https://user-images.githubusercontent.com/47162044/186323939-c7e3600e-b09b-4309-b417-bb314e5a5630.png)
I should have 8290, but I only have 8147. In the above gear from 1905, I change the ring to anything else without the armor and it doesn't change. Will open another issue for this

**Comment by wotktestact** [comment]
It appears green armor on rings is not contributing any armor at all.
Below is with equipping Violet Signet of the Great Protector. It should increase armor by 392, but it has zero effect.
![image](https://user-images.githubusercontent.com/48561262/187169937-6d91f0df-4b5a-4407-be7d-72ed98b166d5.png)
![image](https://user-images.githubusercontent.com/48561262/187170154-aca9beee-26a2-4a37-93e6-55275f5ebb74.png)
![image](https://user-images.githubusercontent.com/48561262/187170180-78fe9802-bde8-46f9-b760-1dce6332e2e6.png)


White armor on rings are providing the expected non-scald amount however.
![image](https://user-images.githubusercontent.com/48561262/187169887-28e20573-a0dc-4f93-8840-d850aebe2719.png)
![image](https://user-images.githubusercontent.com/48561262/187169732-f840090a-789a-41f9-9720-4a143888498b.png)
![image](https://user-images.githubusercontent.com/48561262/187169712-19eb1a7a-5471-45c5-895b-93305ae24cb6.png)


Other sources of bonus armor appear to be working as intended (i.e. trinkets,cloaks, weapon) although I was unable to test the neck slot as I don't have access to any.
