### ISSUE TITLE
[BUG] Berserker Rage increases rage gain too drastically

### ISSUE THREAD

**Issue by peterderpirat** [JamminL/wotlk-classic-bugs#20]
#### 1.1. Description
When activated, Berserker rage seems to increase rage gain from damage taken by too much 
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Activate Berserker Rage
           2. Let a hunter hit you with a ranged auto attack
           3. Observe how you receive 100 rage from one auto attack.
  #### 1.3  Source Material
{Video, Posts, etc..}
Before: https://i.imgur.com/azKLx9X.jpeg
After: https://i.imgur.com/751mDJK.jpeg
#### 2.1. Description
{Describe how that mechanic/spell/npc should be working, in detail}
No idea what the exact formula should be but the same amount of damage without berserker rage gave 1 rage, with it activated it gave 100 rage. That seems incorrect.
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by JamminL** [comment]
Confirmed

**Comment by Scyllaqt** [comment]
Same issue with Anger Management. Shows gains of roughly 1 per second instead of 1 per 3 sec.
This excess rage seems to be purely visual, doesn't let you use it for spells.

**Comment by marrowwow** [comment]
Tested this versus Large Crag Boars outside of IF. Was hit three times, generating a total of 6 rage. Used Berserker Rage and generated 100 rage, being able to spend it with Bladestorm.

**Comment by JamminL** [comment]
Fixed
