### ISSUE TITLE
[BUG] Summon Gargoyle Target and height

### ISSUE THREAD

**Issue by exythxx** [JamminL/wotlk-classic-bugs#200]
#### 1.1. Description
When you summon your gargoyle, it is too high and doesnt attack correct target.
  #### 1.2. How to Reproduce
           1. Go into arena
           2. Target any player and summon gargoyle 
           3. Watch the height and target
  #### 1.3  Source Material
https://www.twitch.tv/exyth1/clip/DeterminedFreezingNewtSmoocherZ-hPPgyX4Ki2dwTL7d - dont have better evidence of height sadly
https://streamable.com/p2wckp - gargoyle wrong target evidence
#### 2.1. Description
Gargoyle should only attack the target with the buff and should be way lower to the ground.
  #### 2.2 Source Material
World of Warcraft: Wrath of the Lich King Patch 3.2.0 (04-Aug-2009): The gargoyle now flies lower to the ground, making it susceptible to melee attacks. This ability now has a fixed duration of 30 seconds and a fixed cost of 60 runic power.; Corrected the inaccurate tooltip which claimed a Gargoyle could last up to 40 seconds, when in fact 30 seconds has always been the maximum.

https://youtu.be/UqxQXcfyd_c?t=993 - here gargoyle attacks the target under the buff and is lower to the ground, so melees can hit it.

**Comment by exythxx** [comment]
more evidence is here:
https://www.youtube.com/watch?v=F77MvbsLbxg&t=105s
https://www.youtube.com/watch?v=3eV85bRnxMk&t=153s
https://www.youtube.com/watch?v=BYK6OkFwbv8&t=550s

**Comment by CharWS** [comment]
Targeting appears fixed, but still spawning out of melee range (too high to reach) in pvp as of 3.4.0.45264

**Comment by Aggrend** [comment]
We've put in a fix that we believe should allow you to more reliably reach the gargoyle. This fix should be in our next 3.4.1 PTR build (probably going out around 12/1).
