### ISSUE TITLE
[BUG] Snakes from Snake Trap don't apply poisons when the target is shielded

### ISSUE THREAD

**Issue by Homerjayx** [JamminL/wotlk-classic-bugs#204]
#### 1.1. Description
snakes dont apply any poisons at all when the target is shielded.
  #### 1.2. How to Reproduce
1. duel a priest as a hunter
2. let him shield himself
3. lay snake trap
4. see how snakes dont do anything to him while the shield is up
  #### 1.3  Source Material
https://www.twitch.tv/videos/1542196065?t=0h54m35s
#### 2.1. Description
should apply poisons on shielded target
  #### 2.2 Source Material
https://youtu.be/EwLOcI4h_kg?t=1669

**Comment by miley-kingofweebs** [comment]
I just tested this in TBCC, and it functions the same way.  Deadly Poison from snake trap is not being applied on absorb.

**Comment by Homerjayx** [comment]
Ya, probably never noticed cause Snake Trap is so rarely used as it shares CD with Frost and Freezing Trap.

**Comment by Aggrend** [comment]
Mind Numbing and Crippling Poison can still apply if they're shielded, but Deadly Poison will only proc when the target is no longer shielded. This is consistent with 3.3.5 reference behavior.
