### ISSUE TITLE
[BUG] Raise Dead summon bug

### ISSUE THREAD

**Issue by exythxx** [JamminL/wotlk-classic-bugs#207]
#### 1.1. Description
Sometime when ur pet dies and you have minor glyph "Glyph of Raise Dead", then u cant summon him.
  #### 1.2. How to Reproduce
           1. Put "Glyph of Raise Dead"
           2. Find enemy and let ur pet die
           3. See if u can resummon him
  #### 1.3  Source Material
https://clips.twitch.tv/ShakingStupidCougarCoolCat-3XtjmKgZKH7-FwWs - evidence here
#### 2.1. Description
  You should be able to summon him.
  #### 2.2 Source Material
  no evidence needed.

**Comment by kozeen** [comment]
Can confirm, this has happened to me several times when playing arena. Hopefully Exyth can provide some clip from his streams to demonstrate this bug

**Comment by kozeen** [comment]
Here's the clip that demonstrates this bug 
https://www.twitch.tv/exyth1/clip/ShakingStupidCougarCoolCat-3XtjmKgZKH7-FwWs

As you can see at 4 second mark the "Raise Dead" comes off cooldown. Then after using it the pet doesn't get summoned and the ability can't be used now
