### ISSUE TITLE
[BUG] Sweeping strikes arms warrior talent not interracting with Bladestorm

### ISSUE THREAD

**Issue by Fedxlol** [JamminL/wotlk-classic-bugs#209]
#### 1.1. Description
If you use sweeping strikes and then press bladestorm no charges of sweeping strikes is being used while bladestorming.
  #### 1.2. How to Reproduce         
           1. Press sweeping strikes
           2. Press bladestorm (several nearby dummies or just 1 dummy, doesnt matter)
           3. Notice sweeping strikes not proccing.
#### 2.1. Description
In original wotlk you could use sweeping strikes and then press bladestorm and it will proc on anything your bladestorm hits.
  #### 2.2 Source Material
Here is a video from original wotlk prepatch 13 years ago on youtube that shows this:
https://www.youtube.com/watch?v=1Mh_b4dHezQ&ab_channel=Z0haan

**Comment by Wallirik** [comment]
It works slightly differently in later patches, after this hotfix:
World of Warcraft [Hotfix](2009-12-17): "Sweeping Strikes will now only trigger once per whirlwind rotation of Bladestorm."
(https://wowwiki-archive.fandom.com/wiki/Sweeping_Strikes)

Observe the sweeping strikes bladestorm 5 seconds into veev's shadowmourne video:
https://youtu.be/3cGqlcE44m0
He bladestorms with 3 charges of sweeping strikes, and 1 charge is consumed each second of bladestorm.
Does bladestorm and sweeping strikes do absolutely nothing atm?

**Comment by magey** [comment]
It's working fine and has been since I got beta (so about two weeks now)

![image](https://user-images.githubusercontent.com/44882404/181123617-aa831234-4ad1-4d09-8fe5-33887ef1afc3.png)

**Comment by watchyoursixx** [comment]
does it consume the charges though?

**Comment by magey** [comment]
> does it consume the charges though?

Yup

**Comment by JamminL** [comment]
The confusion here is probably because bladestorm range is bigger than sweeping strike range. Closing for now, re-open a new issue if there's some other info we're missing
