### ISSUE TITLE
PRIEST - Inner Focus gets eaten up if casted while in the middle of Penance or Mind Sear channeling

### ISSUE THREAD

**Issue by Jkresist** [JamminL/wotlk-classic-bugs#213]
#### 1.1. Description
Inner Focus spell (Priest -> Discipline Talent) gets eaten up if used during a Penance or Mind Sear channel that isn't finished.
  #### 1.2. How to Reproduce
           1. Get Inner Focus talent
           2. Cast a Penance or Mind Sear (any target should work)
           3. Press Inner Focus while the Penance or Mind Sear channel is still going on
  #### 1.3  Source Material
https://clips.twitch.tv/BoringDeafCarabeefKappaRoss-A6vfTDklDb7oqoQA
#### 2.1. Description
Inner Focus shouldn't be eaten up. Penance or Mind Sear  channel should be interrupted and Inner Focus should apply itself on the buffs and get eaten up by the next spell cast that is elligible for the effect.
  #### 2.2 Source Material
N/A

**Comment by Aggrend** [comment]
Regrettably this matches reference and is not fixable due to a technical limitation that existed in 3.3.5 era and still exists now. Gonna say "Won't Fix" on this, unfortunately.

**Comment by JamminL** [comment]
Depressingly closing this
