### ISSUE TITLE
[BUG] You cannot see enemy player health values

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#216]
#### 1.1. Description
Currently you're not able to see enemy player health values, similar to other classic expansions. On wotlk you should be able to see the actual value instead of just the percentage, granted you have the setting on
  #### 1.2. How to Reproduce
           1. Target an enemy player
           2. Check how you can't see the values even with static text defined as values
  #### 1.3  Source Material
N/a
#### 2.1. Description
You should be able to see raw health values of enemy players in wotlk
  #### 2.2 Source Material
[{Video, Posts, etc..}](https://youtu.be/nWUkwISLPPI?t=62)

**UPDATE: ** Working properly in arenas/bgs

**Comment by Jgrenier91** [comment]
Added screenshot from 2010 as proof:
![image](https://user-images.githubusercontent.com/14340125/181270513-90734bdb-b58b-422b-a119-75d1111cf58c.png)

**Comment by Cleavis** [comment]
This currently also applies to npcs. 

image with 'both' selected under display->status text on build 44729
![image](https://user-images.githubusercontent.com/19498073/181272853-71294a00-a491-454a-87db-d9372cfb2f1a.png)

vs video from sept 2010
https://youtu.be/8w7382enTfM
![image](https://user-images.githubusercontent.com/19498073/181273473-749e6272-8650-42a0-8a65-30ad83c3b681.png)

**Comment by eulergrj** [comment]
Health Values were included on Patch 3.0.2 and therefore should be visible by default on the version currently.

Link to the 3.0.2 Patch Notes:
https://wowpedia.fandom.com/wiki/Patch_3.0.2_(undocumented_changes)

![image](https://user-images.githubusercontent.com/9434985/185815801-ff3f37b5-0aa2-4edd-9be3-601803ff8536.png)

**Comment by JamminL** [comment]
Fixed for arena/bgs only

**Comment by watchyoursixx** [comment]
noticed in raids I can finally see my pet health (before only %) I also could see boss health but I could swear that's always been a thing)

**Comment by watchyoursixx** [comment]
seems completely fixed now, can see hp other other players always
