### ISSUE TITLE
[BUG] Hunter pets use special abilities less frequently than they should

### ISSUE THREAD

**Issue by BradBlondebeard** [JamminL/wotlk-classic-bugs#217]
#### 1.1. Description
{Describe how that mechanic/spell/npc is currently working, in detail}

Currently on the beta, hunter pets use their special abilities slightly slower than 1.5 seconds when the ability is on auto cast and they have enough focus to use the ability. This behavior has existed throughout Burning Crusade Classic.

  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:

           1. Set a hunter pet special ability with no cooldown (such as bite) to auto cast
           2. Issue petattack command            
           3. Observe that pet uses special ability slightly slower than every 1.5 seconds
           
  #### 1.3  Source Material
{Video, Posts, etc..}

You can see this behavior on beta logs: 
![image](https://user-images.githubusercontent.com/81579365/181294207-f224ad34-201d-4d21-9d1c-9241e70ba39c.png)
from https://classic.warcraftlogs.com/reports/YxJbHGg7L1DnQBtc#fight=18&type=summary&source=3&view=events&pins=2%24Off%24%23244F4B%24expression%24ability.name%3D'go%20for%20the%20throat'%20or%20type%3D'cast'
In this log, we would expect the pet to use bite again 1.5 seconds after previously using bite if the pet cast when the gcd was available, but we see that after casting bite at 7.675 the next bite occurs at 8.975, a difference of 1.617 seconds. Focus is not a limiting factor because the pet gained 50 focus at 8.793

#### 2.1. Description
{Describe how that mechanic/spell/npc should be working, in detail}

In Wrath of the Lich King, pets actually used their special abilities faster than the GCD. Pets should use their special abilities roughly every 1.25 seconds. 

  #### 2.2 Source Material
{Video, Posts, etc..}

This behavior was noted on elitist jerks here: https://web.archive.org/web/20111109191023/http://elitistjerks.com/f74/t28573-wotlk_talents_abilities_discussion/p129/#post915345
![image](https://user-images.githubusercontent.com/81579365/181296317-e03c1958-9644-4b7a-a4e1-822f510fbe5f.png)
The poster chul used an in-game command to see that the gcd of claw was 1.5 seconds, but the combat log showed claw being used roughly every 1.25 seconds.

You can also visually see pets using their gcd even when the gcd is active in old videos: 
https://www.warcraftmovies.com/movieview.php?id=141561
You can see that bite is being used even when the gcd swipe is still in place

This behavior was so prevalent that the gcd was set to be 1.25 in contemporary dps sheets and sims. 

![image](https://user-images.githubusercontent.com/81579365/181297297-67ab3a5b-8445-465d-977c-4a7a671a069e.png)

**Comment by MuffledBaneMask** [comment]
This affects anything using AI (and subsequently, random choice) to determine when to cast spells, even in scenarios when they meet all conditions to chain-cast the spell. This is being tracked.

**Comment by BradBlondebeard** [comment]
I think the combat log evidence may be misleading. After reading some more information about combat log entries and how they don't always reflect what happened, eg these elitist jerks post: (https://web.archive.org/web/20090208044338/http://elitistjerks.com/925441-post3426.html and http://web.archive.org/web/20090309075324/http://elitistjerks.com/1126457-post732.html), I think the in-game script that the EJ poster Chul used probably gave the correct information: Pet GCD should be 1.5 seconds and they should not use their on gcd abilities more often than 1.5 seconds. The combat log entries may have been faster than expected because of lag. I do not know how much latency they experienced while playing, but I read anecdotes of people regularly raiding with 2,000ms.

**Comment by NuptupTDOW** [comment]
I still think this should be left open as, while the 1.5 interaction is the intended from back then, this is clearly not "Wrath-like" from a source 3.3.5 standpoint. If they want to ignore it and say it's a bugfix, that's technically correct, but as it is now, it's still technically a classic bug, that is not accurately mirroring how source 3.3.5 acts with it's wrath-true bug for 1.25. 

So, this would be a bug, because it's not 3.3.5-true, even though it is what was originally intended.
