### ISSUE TITLE
[BUG] mp5 bug

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#218]
#### 1.1. Description
Certain items are giving 5 times the actual value of Mp5, tested and confirmed through tooltip and mana regen gained between casts.
  #### 1.2. How to Reproduce
1. Equip at least one of the following items, recording mp5 before and after -
    - [Cannoneer's Morale](https://www.wowhead.com/wotlk/item=44015/cannoneers-morale)
    - [Winged Talisman](https://www.wowhead.com/wotlk/item=37844/winged-talisman)
    - [Loop of the Kirin Tor](https://www.wowhead.com/wotlk/item=44934/loop-of-the-kirin-tor)
    - [Inscribed Loop of the Kirin Tor](https://www.wowhead.com/wotlk/item=45689/inscribed-loop-of-the-kirin-tor)
    - [Lattice Choker of Light](https://www.wowhead.com/wotlk/item=40681/lattice-choker-of-light)
2. Observe Mp5 before and after, notice that after calculating out Spirit/Int gains, you end up with the expected value from gear times 5

  #### 1.3  Source Material

| Test                                                | Intellect | Spirit | Mp5 from gear | Mp5 expected | Mp5 Actual | mp5 listed from gear (regen while casting) | ratio off |
| --------------------------------------------------- | --------- | ------ | ------------- | ------------ | ---------- | ------------------------------------------ | --------- |
| naked                                               | 177       | 179    | 0             | 39           | 39         |                                            |           |
| template neck                                       | 211       | 179    | 18            | 61           | 61         | 18                                         |           |
| template neck + legs                                | 279       | 179    | 63            | 113          | 113        | 63                                         |           |
| template neck + leg + ring                          | 310       | 179    | 84            | 136          | 136        | 84                                         |           |
| template neck + leg + ring + bracer                 | 355       | 179    | 99            | 155          | 155        | 99                                         |           |
| template neck + leg + ring + bracer + wep           | 388       | 179    | 115           | 173          | 173        | 115                                        |           |
| template neck + leg + ring + bracer + wep + offhand | 421       | 179    | 136           | 197          | 197        | 136                                        |           |
| cannoneers morale                                   | 177       | 179    | 28            | 67           | 179        | **140**                                        | 5         |
| cannoneers + winged talisman                        | 177       | 179    | 64            | 103          | 359        | **320**                                        | 5         |
| above + loop of kirin, incribed loop kirin          | 249       | 253    | 97            | 163          | 551        | **485**                                        | 5         |
| above + lattice choker of light                     | 287       | 253    | 113           | 184          | 636        | **565**                                        | 5         |
#### 2.1. Description
1 mp5 should give 1 mp5, not the multiplied amount of x 5 for certain items
  #### 2.2 Source Material
N/A

**Comment by watchyoursixx** [comment]
Not sure which this is related to, but on my lvl 70 hunter I had 14 Mp5 from TBC gear and it gave 15 Mp5. 
I used a Major Mageblood for 20 mp5, and it gave 20 mp5.
I used 3 of the 8 mp5 gems from wrath into a piece of gear, and gained 28 mp5.

Not *way too much* like suggested, but some numbers were off slightly.

What spec were you? what race? template character? how much mp5 *should* you have? Did you have mana related talents like regen while casting or similar?

**Comment by watchyoursixx** [comment]
Updated the OP with research and an explanation of what's actually happening.

In the future, please either submit a bug report request via the google forms or test request here for the bug, or give a little bit more info than just "its broke, looks random"

A quick unequip of each item would have told you which items you had equipped were causing an issue, and you could also notice that the other items weren't all affecting it. It's only certain items.

With that being said, what's weird is if I right click equip something else and I have one of these items equipped, my Mp5 doesn't change until I unequip an item or equip another mp5 item. For example, swapping out either of those trinkets for something else retained that mp5 value.

**Comment by watchyoursixx** [comment]
fixed as of build 44930
