### ISSUE TITLE
[BUG] A Demo Lock in Metamorphosis can be Repentanced 

### ISSUE THREAD

**Issue by Jgrenier91** [JamminL/wotlk-classic-bugs#221]
#### 1.1. Description
When under the effects of Metamorphosis and in demon form, a retribution paladin can repentance the warlock.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Enter demon form
           2. Get repentanced
  #### 1.3  Source Material
https://gfycat.com/LightActiveHogget
#### 2.1. Description
A demon lock in demo form should not be a humanoid and should therefore not be sheepable or repentance-able.
  #### 2.2 Source Material
No proof yet.

**Comment by Tharre** [comment]
> **Repentance**
> [...]
> Usable against Demons, Dragonkin, Giants, Humanoids and Undead.
