### ISSUE TITLE
[BUG] Delay to use Shield Block / Shield Wall / Shield Reflection with a macro

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#223]
#### 1.1. Description
When you use a macro to equip 1-hand and shield and use one of these 3 spells, it takes a delay of like ~0.5sec to be able to use the spell
  #### 1.2. How to Reproduce
           1. Make a macro /equip 1hand /equip shield /cast one of these 3 spells
           2. Spam the macro
           3. Notice it's delayed a lot
  #### 1.3  Source Material
Not yet
#### 2.1. Description
It should take 2 press on the macro for the spell to be used, not around 0.5sec
  #### 2.2 Source Material
Not yet

**Comment by JamminL** [comment]
NAB, another type of batch. Make a somechanges for this

**Comment by Shintaxgg** [comment]
Macro is definitely bugged, if it was a type of batch, i wouldn't be able to press 2 different macros and make it faster
I press equip 1hand/shield with 1 bind, and reflect with another bind, and it's way faster than the macro that equip 1hand/shield & reflect
