### ISSUE TITLE
[BUG] Rogue - Deadly Throw slow not being applied when target is in a Blind

### ISSUE THREAD

**Issue by Jkresist** [JamminL/wotlk-classic-bugs#225]
#### 1.1. Description
Deadly Throw's slow effect isn't being applied on the target when the target is in a blind. Deadly Throw does normal damage and breaks the blind, but the slow effect doesn't get applied on the target.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Blind someone (with combo points on them already on preferably, so you are able to use Deadly Throw)
           2. Use Deadly Throw on them while they are still under Blind (make sure you don't have Crippling Poison or any slow that is potentially more powerful already applied to avoid bias)
           3. Notice that damage is being applied accordingly but slow isn't.
  #### 1.3  Source Material
https://gyazo.com/0cb4967cea4bbf3590717ee7ae88a55f
#### 2.1. Description
Deadly Throw's slow effect should be applied regardless of the target being blinded. The only reason why Deadly Throw's slow effect shouldn't apply is if the target is already slowed by a more powerful effect. Blind isn't a slow effect, therefore shouldn't affect Deadly Throw's slowing ability.
  #### 2.2 Source Material
N/A

**Comment by JamminL** [comment]
NAB, blind is a 60% slow. It'll follow more powerful spell rules unfortunately :(
