### ISSUE TITLE
[BUG] Combat stays forever in arena

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#228]
#### 1.1. Description
If you are in combat in arena, you never leave it even if no one attacks u. One of the causes is shadowfiend.
  #### 1.2. How to Reproduce
1. Press shadowfiend on a player
2.  Wait
3. Keep waiting
4. Combat never ends
  #### 1.3  Source Material
Not yet
#### 2.1. Description
You should leave combat after 6sec~ not stay in it forever
  #### 2.2 Source Material
Not yet

**Comment by JamminL** [comment]
This is a bug yes, but add info to the report before opening one.

This bug only happens sometimes, and  under specific conditions. It usually does drop your combat

**Comment by Shintaxgg** [comment]
I think auras buffs affect it, like the shield disc -3% dmg buff, wrath totem, debuff feral (mangle)

**Comment by JamminL** [comment]
That's not it either since once it happens it doesn't stop even everyone else drops combat and you max range. Its def a combat-stuck type bug but we need to find the trigger

**Comment by Shintaxgg** [comment]
was as disc ele vs feral priest & disc ele too

**Comment by Shintaxgg** [comment]
Still isn't fixed as of new build

**Comment by Evolvee** [comment]
Just got the combat bug as well in a 1v1 scenario. Enemy mage had Water Ele Summoned, it went to attack me (but didnt yet), I buffed myself with Stamina (out of combat) and it put me into infinite combat state. The mage dropped combat just fine.

**Comment by JamminL** [comment]
Shadowfiend fixed atleast, closing this for now until evidence of otherwise

build 3.4.0.45264

**Comment by Evolvee** [comment]
it just happened to me again, skirmish SPM  against 2 disc priests
