### ISSUE TITLE
[BUG] Glyph of Hurricane increases Insect Swarm damage and decreases Hurricane damage 

### ISSUE THREAD

**Issue by zacjen** [JamminL/wotlk-classic-bugs#230]
#### 1.1. Description
Currently if you use Glyph of Hurricane, it causes a 20% increase in damage from Insect Swarm and a 5% damage decrease to Hurricane. Both of these are unintended behaviors. 
  #### 1.2. How to Reproduce
          
           1. Cast Insect Swarm and Hurricane -> look at the damage per tick
           2. Use Glyph of Hurricane 
           3. Cast Insect Swarm and Hurricane -> notice the change in damage per tick 
  #### 1.3  Source Material
Tested on the beta with another boomkin. Able to replicate the issue across different talents. 
#### 2.1. Description
It should just be causing a movement slow, not affecting the damage of either Insect Swarm or Hurricane 
https://www.wowhead.com/wotlk/spell=54873/glyph-of-hurricane

**Comment by JamminL** [comment]
Okay this is probably one of the more weird things I've discovered about wotlk. In spelldata, even in older patches of wotlk, glyph of hurricane should increase Insect Swarm by 30%, that's in the actual spelldata of glyph of hurricane:
https://imgur.com/a/MoQh3Xv

You can also check it on wowhead, as it parses 3.3.5a spelldata:
https://www.wowhead.com/wotlk/spell=54831/glyph-of-hurricane

This is not a "classic" spelldata, this was also present in the original wotlk spelldata.

Now, whether or not this was ignored in code is mystery to me. So marking this as a bug to be checked against reference.

**Comment by watchyoursixx** [comment]
Fixed as of 45166
