### ISSUE TITLE
[BUG] Drain Soul stops channeling when an adjacent mob dies

### ISSUE THREAD

**Issue by rafalss** [JamminL/wotlk-classic-bugs#232]
#### 1.1. Description
Drain Soul will abruptly stop channeling when an adjacent mob dies. As you can see in the source video, it is not caused by pushback. It happens consistently at any level and other Warlocks are seeing the same results. I tested the same scenario with Drain Life and had no issues then.
  #### 1.2. How to Reproduce          
           1. Pull two mobs, dot up one of them heavier to make sure it dies first
           2. Cast Drain Soul on the second mob so that it's channeling while the first mob is about to die
  #### 1.3  Source Material
[Video](https://www.youtube.com/watch?v=XVXr9svUVNg)
#### 2.1. Description
Drain Soul should continue channeling on your target when other mobs die.
  #### 2.2 Source Material
N/A

**Comment by Tharre** [comment]
Still broken as of build 44930.

**Comment by rafalss** [comment]
Appears to be fixed in build 45166.
