### ISSUE TITLE
[BUG] Mana burn should break fears even through absorbs

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#234]
#### 1.1. Description
Currently mana burn isn't breaking fears if the target has a shield up.
  #### 1.2. How to Reproduce
           1. Power word shield yourself
           2. Have an enemy priest fear you
           3. Have that enemy priest cast mana burn
           4. Watch how your fear doesn't break
  #### 1.3  Source Material
No video yet but easy to reproduce
#### 2.1. Description
Manaburn should break fears, even through absorbs
  #### 2.2 Source Material
World of Warcraft: Wrath of the Lich King [Patch 3.2.0](https://wowwiki-archive.fandom.com/wiki/Patch_3.2.0) (04-Aug-2009): Fixed a bug where Mana Burn did not cause fear effects to break when the fear victim had an absorb shield on.

**Comment by simmanheh** [comment]
Might point out that this might be the case with damage reductors too (e.g Barkskin).

**Comment by JamminL** [comment]
Fixed Build 3.4.04543

**Comment by JamminL** [comment]
Not fixed after all

**Comment by JamminL** [comment]
Fixed build 3.4.0.45166
