### ISSUE TITLE
[BUG] Charge / Intercept Resisting

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#236]
#### 1.1. Description
Charge and intercept can currently resist
  #### 1.2. How to Reproduce
Charge or intercept a player, you will eventually resist
  #### 1.3  Source Material
Not yet
#### 2.1. Description
You shouldn't be able to resist your charge or intercept vs players
  #### 2.2 Source Material
Not yet

**Comment by yurpcraft** [comment]
Need logs/video evidence of this appearing in beta and ideally a historical source saying/showing that they don't.  Closing ticket to cut through some noise
