### ISSUE TITLE
[BUG] Shadow fiend first attack does significantly reduced damage

### ISSUE THREAD

**Issue by dbyena** [JamminL/wotlk-classic-bugs#239]
#### 1.1. Description
The first melee attack from shadow fiend does significantly reduced damage.
  #### 1.2. How to Reproduce
           1. Use Shadow fiend on a target
           2. Look at first melee damage relative to following 
  #### 1.3  Source Material 
Two logs (though there are more)
(https://classic.warcraftlogs.com/reports/pXxaBF7hcgD32rZV#fight=13&type=damage-done&source=90&view=events)
https://classic.warcraftlogs.com/reports/twkMVYraF3KR6qnT/#fight=1&source=16&view=events&type=damage-done
#### 2.1. Description
Id expect all of the melee attacks to be relatively equal with no bias towards the first attack

**Comment by JamminL** [comment]
Actually NAB believe it or not.

The reason is there's a delay between summon and its stats being added:
https://youtu.be/HpthT7jE_oo?t=340
https://youtu.be/HpthT7jE_oo?t=42
https://youtu.be/HpthT7jE_oo?t=98

You can see this behavior in all spriest movies from back in the day.
