### ISSUE TITLE
[BUG] Feral talent Predatory Instincts (PI) not reducing imp. Revenge or Sweeping Strikes (SS) damage

### ISSUE THREAD

**Issue by Brolff** [JamminL/wotlk-classic-bugs#241]
#### 1.2. How to Reproduce:
           1. Make two identical specs, one with 3/3 Predatory Instincts, one with 0/3
           2. Go around with an opposing faction warrior and stand next to him hitting mobs passively cleaving you with imp. revenge or SS.
           3. Swap between the specs 3/3 and 0/3 and notice there is no difference to damage taken
### 2. Expected Behavior: Both these abilities are aoe effects so they should be reduced by the talent.

![PI test](https://user-images.githubusercontent.com/110452974/182321836-5f7d870b-1fca-430d-af49-03808cf59e29.png)

EDIT: Looks like no spells with flag SPELL_ATTR5_TREAT_AS_AREA_EFFECT are currently affected by AoE reductions, needs research or confirmation from reference

**Comment by Shintaxgg** [comment]
isn't this intended ? cleave effect =/= aoe

**Comment by Oliaxz** [comment]
> 

Cleaving effect are for sure as AoE. 
The question is if "Aura: Mod AoE Damage Taken" should be applied to anything that hit more than one target.

Whirlwind, bladestorm, cleave, sweeping strike, imp revenge, blade flurry, starfall, chain lightning main hit, etc.

Does sweeping strike "double dip" on spell like whirlind? Like u hit offtarget with WW and it generates a hit on main target, and WW hit on main target generates a hit on offtarget (4 hit totals). If that is the case then maybe the modifier aura is only applied if the hit comes from sweeping strike (double dip).

Either way, blizz should be the one to decide what is right.

**Comment by JamminL** [comment]
This is should be NAB. According to spelldata, not all cleave effects are considered as AoE. 

To understand which ones are, there's an attribute SPELL_ATTR5_TREAT_AS_AREA_EFFECT that you should look out for. Sweeping strikes does not have that attribute.

The spell/ability cleave, for example, does have that attribute.

**Comment by JamminL** [comment]
I stand corrected, sweeping strikes does have that attribute. I was looking at the spell itself and not the spell that it procs, If you look at 26654 (the spell that procs off sweeping strikes) then you'll see it does have that flag and therefore should be considered as AoE

**Comment by Brolff** [comment]
I'll check FoK and Bladestorm when I get home tonight.

**Comment by Oliaxz** [comment]
> I stand corrected, sweeping strikes does have that attribute. I was looking at the spell itself and not the spell that it procs, If you look at 26654 (the spell that procs off sweeping strikes) then you'll see it does have that flag and therefore should be considered as AoE

Nice find! 

So do you think the bug is with predatory instinct or is it this particular attribute that is not working for some spells? Cause if its the talent then it looks easy enough to fix, but if its the spells themself or attribute, its gonna take a list of all the spells that has it to make sure theyre ok. For revenge, its also important to note that it becomes a cleave only when talented. If cleave has that attribute, it would be logical if imp revenge has it too.

On a side note, its be worth testing if cleave take into account armor and resilience. This was a bug on warmane

**Comment by Oliaxz** [comment]
> > I stand corrected, sweeping strikes does have that attribute. I was looking at the spell itself and not the spell that it procs, If you look at 26654 (the spell that procs off sweeping strikes) then you'll see it does have that flag and therefore should be considered as AoE
> 
> Nice find!
> 
> So do you think the bug is with predatory instinct or is it this particular attribute that is not working for some spells? Cause if its the talent then it looks easy enough to fix, but if its the spells themself or attribute, its gonna take a list of all the spells that has it to make sure theyre ok. For revenge, its also important to note that it becomes a cleave only when talented. If cleave has that attribute, it would be logical if imp revenge has it too.
> 
> On a side note, i think itd be worth testing if SS take into account armor and resilience. This was a bug on warmane

Update : imp revenge has a pvp modifier of 60% 
![Screenshot_20220803-083114_Samsung Internet](https://user-images.githubusercontent.com/59798458/182608566-93f527cd-abf8-4c01-a747-526f1b361eaa.jpg)

**Comment by JamminL** [comment]
> I see Bladestorm has ww in it, and ww has the line "treat as area effect" in it. I can't see it on FoK,
> 
> This has me thinking maybe it's the talent itself that is bugged, I'll check with a mage.

The talent is fine, I tested it. It seems that AoE reductions don't affect spells with SPELL_ATTR5_TREAT_AS_AREA_EFFECT. Which could be a bug or it could be intended. Blizzard needs to check the reference on this one. I'll edit your post with this info

**Comment by Brolff** [comment]
I tested bladestorm. 
![image](https://user-images.githubusercontent.com/110452974/182862122-9d341321-24bb-499e-afcd-522555620fb1.png)

**Comment by Aggrend** [comment]
Potentially very silly question, but you were in cat form when you tested this, correct? I would assume so but the steps did not indicate such and I just want to be sure.  I'm being told that our QA is not able to reproduce this internally with sweeping strikes or whirlwind and has not been able to reproduce this since 8/4. Is this still observable in the 45043 build?

As for Improved Revenge, this does not get reduced by this ability, but this matches 3.3.5, so we are considering that part to be Not A Bug.

**Comment by Oliaxz** [comment]
> Potentially very silly question, but you were in cat form when you tested this, correct? I would assume so but the steps did not indicate such and I just want to be sure. I'm being told that our QA is not able to reproduce this internally with sweeping strikes or whirlwind and has not been able to reproduce this since 8/4. Is this still observable in the 45043 build?
> 
> As for Improved Revenge, this does not get reduced by this ability, but this matches 3.3.5, so we are considering that part to be Not A Bug.

hmm it does seem to work on the PTR, i guess the op wasnt in cat form or something got fixed.

On PTR, it worked for me on bladestorm, cleave, shockwave, divine storm, hurricane, immolation aura.

But didnt work on starfall, maybe cause the stars are considered single target projectiles... not sure if its a bug or not
