### ISSUE TITLE
[BUG] Character stats update

### ISSUE THREAD

**Issue by Turaxy** [JamminL/wotlk-classic-bugs#244]
#### 1.1. Description
  
some stats aren't showing properly on character main page before you swap many pieces & close / open
  #### 1.2. How to Reproduce
        
           1. open character page (stats etc)
           2. change trinkets or gear
           3. realise it doesn't update before you close and open it or change other piece of gear
           
  #### 1.3  Source Material
  
https://gyazo.com/a17eadfb6c031ee943958ca9ab1a5bcd
https://gyazo.com/3168641562db1a51b80910303313a257

https://gyazo.com/d644e85f785c5ffd110569e715c6fe66

**Comment by JamminL** [comment]
Please state which item
