### ISSUE TITLE
[BUG] Taste for blood 9sec sometimes instead of 6sec

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#252]
#### 1.1. Description
Taste for blood proc every 9sec sometimes instead of 6sec
  #### 1.2. How to Reproduce
           1. Rend a target with the talent taste for blood
           2. Notice sometimes taste for blood proc every 9 seconds instead of 6sec
  #### 1.3  Source Material
https://www.youtube.com/watch?v=ZEaX6fyO-b0
#### 2.1. Description
Should proc every 6 seconds
  #### 2.2 Source Material
Not yet

**Comment by deanced** [comment]
Per the talent: Whenever your Rend ability causes damage, you have a 33% chance of allowing the use of your Overpower ability for 9sec. This effect will not occur more than once every 6 sec. 

This ability has a 33% chance to proc on every rend tick, and has a 6 sec. internal CD, that does not mean it will proc every 6 sec. it merely means that's when it's available to proc again. This is not a bug.

**Comment by Shintaxgg** [comment]
You realise 3 points in it makes it 100% right, lol

**Comment by deanced** [comment]
No you're right, that's my bad. I can also see what's happening on it looking at my own combat log now, it appears to be resetting the ICD based on when you use the proc, and not when the proc actually happens.

**Comment by caccavale** [comment]
I closed for no expected behavior reference and low quality info.  Can we improve the quality of this ticket?

**Comment by CharWS** [comment]
as per the video here: https://www.youtube.com/watch?v=l7wqOhHNSz4&t=60s
can see that this behavior while strange does appear to match the original behavior in wotlk
0:59 (59.28) - rend applied
1:02 (62.41) - rend damage [1471]
1:05 (65.49) - rend damage [1471] + tfb proc
1:08 (68.25) - rend damage [1471]
1:11 (71.33) - rend damage [1471] - where tfb proc??
1:14 (74.41) - rend damage [1471] + tfb proc

**Comment by caccavale** [comment]
Welp, that was a ride.

**Comment by caccavale** [comment]
Current beta log showing ^ behavior
![image](https://user-images.githubusercontent.com/6198074/182933163-866307bb-a91b-4cb6-9885-37eca59fd95d.png)

**Comment by Shintaxgg** [comment]
So this is a bug that existed back in the day, so it's technically NAB ( there's multiple evidences such as the 3.3.5a video in the post)

That said it's clearly one of those bad and clearly unintended bug that we reckon should be corrected.

**Comment by JamminL** [comment]
> So this is a bug that existed back in the day, so it's technically NAB ( there's multiple evidences such as the 3.3.5a video in the post)
> 
> That said it's clearly one of those bad and clearly unintended bug that we reckon should be corrected.

lol. 

Regardless of the sassyness of that copypaste, its still a fair point. This was probably an unintentional bug so reopening until we hear a final decision.

**Comment by Shintaxgg** [comment]
Still isn't fixed as of new build

**Comment by Aggrend** [comment]
This does in fact match 3.3.5, however I'll  acknowledge that this was likely not intended and as a result we've dug into it pretty deeply and determined that its a pretty risky code change if we wanted to attempt a fix at this point.  We are going to say NAB/WNF for now. We have a bug in our DB and might revisit it in the future, however. Thanks!

**Comment by knasen88** [comment]
Thanks for confirming but could you maybe elaborate for us? it's hard to cope with what seems like such an easy fix of e.g just lowering the CD to 5.9 seconds being a risky change? #59 seems more intricate but got fixed rather quickly.

**Comment by stako** [comment]
Looks like they did just that for Cataclysm - reduced the cooldown to 5 seconds. Doesn't actually allow you to get an overpower proc every 5 seconds as rend still ticks every 3 seconds, just fixes the missed procs.

**Comment by knasen88** [comment]
> This does in fact match 3.3.5, however I'll acknowledge that this was likely not intended and as a result we've dug into it pretty deeply and determined that its a pretty risky code change if we wanted to attempt a fix at this point. We are going to say NAB/WNF for now. We have a bug in our DB and might revisit it in the future, however. Thanks!

`public double tasteForBlood = 5.9 `
where do i send my merge request? @Aggrend
