### ISSUE TITLE
[BUG] AoE Cap is currently limiting to 20 targets, up from expected 10

### ISSUE THREAD

**Issue by yurpcraft** [JamminL/wotlk-classic-bugs#254]
#### 1.1. Description

In patch 3.3, the AoE cap was changed.  The new calculation makes it so an AoE spell would do full damage against up to 10 targets, and after the 10 target limit, the effect would be reduced to reflect the additional targets.  Currently in beta (build 3.4.0.44930) AoE isn't being reduced until 20 targets.

  #### 1.2. How to Reproduce
          {
           1. Cast aoe spell on single target - note value
           2. Find area where you can pull multiple mobs.  In my case I went to the Stockades in Stormwind
           3. Cast the same AoE spell, using logs to determine how many you pulled/damaged
           4. Note the damage done to all targets, and compare value to single target * 10.
           }
  #### 1.3  Source Material

https://classic.warcraftlogs.com/reports/tXmCrPzyvW2xVcwn

On a single target, blizzard would tick for 701 damage.  On 40 targets, blizzard ticked for 350 (expected 175).

https://classic.warcraftlogs.com/reports/rjfVGBy8MZkN9at3/#boss=-3&difficulty=0&type=damage-done&source=1&ability=42198&start=217648&end=220648&view=events
62 hits 154 each = 9548  x 8 ticks = 76,384 damage cap (bug is that its x20 mob aoe cap instead of 10)

https://classic.warcraftlogs.com/reports/rjfVGBy8MZkN9at3/#boss=-3&difficulty=0&type=damage-done&source=1&ability=42198&start=278095&end=285897&view=events
35 hits 260 each = 9,100 x 8 ticks = 72,800 damage cap (bug is that its x20 mob aoe cap instead of 10)

https://classic.warcraftlogs.com/reports/rjfVGBy8MZkN9at3/#boss=-3&difficulty=0&type=damage-done&source=1&ability=42198&view=events&start=285859&end=293730
12 hits 470 each = 5640 x 8 ticks = 45,120 (we have not reached aoe cap with this attack at 12 mobs)

https://classic.warcraftlogs.com/reports/8xPTYZ7KMD3rhzBk/#boss=-3&difficulty=0&type=damage-done&ability=55361&view=events
first pull 17 mobs no aoe cap
second pull 21 mobs aoe cap started
third pull 3 mobs pull same dmg as first pull

![image](https://user-images.githubusercontent.com/12848366/182886638-a7f69402-930c-4ea1-9720-c190807be99b.png)

#### 2.1. Description

AoE damage should be calculated with the area damage cap formula for 3.3.5

  #### 2.2 Source Material

https://wowwiki-archive.fandom.com/wiki/Area_of_Effect#Area_damage_caps
https://wowwiki-archive.fandom.com/wiki/Area_damage_caps#Patch_3.3_mechanics
https://wowwiki-archive.fandom.com/wiki/Patch_3.3.0#Classes:_General

All of this said, there does appear to be *some* confusion as to exactly when this went into effect.  For instance, here's a video showing off Nibelung (ICC weapon, so patch 3.3+) but blizzard is doing pre-aoe nerf damage: https://www.youtube.com/watch?v=9cUI_6YDLLA&t=28s

**Comment by yurpcraft** [comment]
For more screenshot evidence, here's dragon's breath from a video from 3.3:

![image](https://user-images.githubusercontent.com/12848366/182894435-983c000e-10fd-4df5-92ba-a04750c40328.png)

compared to current beta:

![image](https://user-images.githubusercontent.com/12848366/182894464-64c03153-66dc-446a-9a25-f1c18138ffcd.png)

**Comment by yurpcraft** [comment]
Additional data from magey here: https://github.com/magey/wotlk-warrior/issues/13

**Comment by yurpcraft** [comment]
Additional logs of further abilities/items capped at 20 targets:

super sapper 10 targets
https://classic.warcraftlogs.com/reports/LjZBwDvPkbg8qpMX/#boss=-3&difficulty=0&start=25552&end=28587&type=damage-done&ability=30486
super sapper charge 56 targets
https://classic.warcraftlogs.com/reports/6nGgdw8DLH97kJfh/#boss=-3&difficulty=0&start=71663&end=81193&type=damage-done&ability=30486
super sapper charge 122 targets
https://classic.warcraftlogs.com/reports/4YxjWLCGPza3n7Xc/#boss=-3&difficulty=0&start=967724&end=1145499&type=damage-done&ability=30486

goblin sapper charge 57 targets
https://classic.warcraftlogs.com/reports/WaNXgFDzqwb2ARj4/#boss=-3&difficulty=0&start=75502&end=81800&type=damage-done&ability=13241

fel iron bomb 52 targets
https://classic.warcraftlogs.com/reports/a9PF632GKynWkmcr/#boss=-3&difficulty=0&type=damage-done&ability=30216&start=17181&end=107119

adamantite grenade 50 targets
https://classic.warcraftlogs.com/reports/yY2PNt643TX9Mhnx/#boss=-3&difficulty=0&type=damage-done&start=64918&end=90957&ability=30217

dense dynamite 50 targets
https://classic.warcraftlogs.com/reports/yY2PNt643TX9Mhnx/#boss=-3&difficulty=0&type=damage-done&ability=23063&start=125124&end=147511

hunter volley capped at 20 targets
https://classic.warcraftlogs.com/reports/y7C3PQmpgz2hTdGn/#boss=-3&difficulty=0&view=events&type=damage-done&ability=42234

dk howling blast capped at 20 targets
https://classic.warcraftlogs.com/reports/VQdZBTrnPmY4bzxM/#boss=-3&difficulty=0&type=damage-done&ability=51411&view=events

mage living bomb capped at 20 targets
https://classic.warcraftlogs.com/reports/8xPTYZ7KMD3rhzBk/#boss=-3&difficulty=0&type=damage-done&ability=55361&view=events

**Comment by Aggrend** [comment]
Working on a fix for this now. Good bet it'll be resolved in the 8/10 build.

**Comment by JamminL** [comment]
Fixed Build 3.4.04543
