### ISSUE TITLE
[BUG] Feral Rip critical hit ignoring resilience

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#255]
#### 1.1. Description
Rip is ignoring resilience with critical hit
  #### 1.2. How to Reproduce
           1.Rip a target with resilience
           2. Notice the crit dmg isn't reduced

  #### 1.3  Source Material
Not yet
#### 2.1. Description
Resilience should affect rip damage
  #### 2.2 Source Material
Not yet

**Comment by JamminL** [comment]
Adding some more information here. The problem isn't with RIP, it's every dot. Every dot crit is not being reduced by the crit dmg reduction part of resilience.

**Comment by McPero** [comment]
Neither is mana burn.

**Comment by betatestwow** [comment]
After extensive testing Rip is doing ~3200 on crit to target dummies and ~2500 on crit to pvp geared characters of all classes. Rip does seem to be ignoring armor as intended, but not resillience.

**Comment by yurpcraft** [comment]
Can you post logs/evidence of this behavior?

**Comment by McPero** [comment]
![Screenshot_20220803-232547_Twitch](https://user-images.githubusercontent.com/110542148/184289817-ccb1ddce-8bbf-45bd-bf1e-47b06e14cbcc.jpg)
![Screenshot_20220803-232325_Twitch](https://user-images.githubusercontent.com/110542148/184289818-bd983e8a-8a15-47b0-be1a-d8bbed34ca16.jpg)
![Screenshot_20220803-225649_Twitch](https://user-images.githubusercontent.com/110542148/184289820-54f01673-a85e-4fac-b9ac-79f78465dcf6.jpg)

Only screenshots i don't have beta. Shouldn't be hard to replicate.

**Comment by Shintaxgg** [comment]
burn seem fixed (removed 8-9% mana instead of 10), need to test dot crit now

**Comment by Shintaxgg** [comment]
1166 no crit 2565 crit (rip dmg) on a resilience target, still bugged

**Comment by JamminL** [comment]
Fixed in arena/bgs/instanced content. Will be fixed open world next restart

**Comment by imaslakov** [comment]
> Fixed in arena/bgs/instanced content. Will be fixed open world next restart

Is there a proof link or smth?
