### ISSUE TITLE
[BUG] Winged talisman mp5 not working

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#261]
#### 1.1. Description
Winged talisman mp5 not working
  #### 1.2. How to Reproduce
           1. Check your mp5
           2. Equip winged talisman
           3. Check your mp5
  #### 1.3  Source Material
https://gyazo.com/b40f270a2d43bd516ca5455a4fa704eb
#### 2.1. Description
Should give mp5
  #### 2.2 Source Material
Not yet

**Comment by JamminL** [comment]
Fixed Build 3.4.04543
