### ISSUE TITLE
[BUG] Holy shock and getting cc'd

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#263]
#### 1.1. Description
Holy shock does nothing if you get cc in the same time, only spell in the game that act like this for some reason
  #### 1.2. How to Reproduce
           1. Use holy shock and try to get cc in the same time
           2. Notice holy shock did nothing
  #### 1.3  Source Material
https://clips.twitch.tv/SneakyPluckyKathyPeanutButterJellyTime-YRsI03iuBgqheV1p
https://youtu.be/3NtNY-2QkUM?t=555 
#### 2.1. Description
Holy shock is used so it should be doing something
  #### 2.2 Source Material
Not yet

**Comment by JamminL** [comment]
So this is a bug that existed back in the day, so it's technically NAB ( there's multiple evidences such as the 3.3.5a video in the post)

*That said it's clearly one of those bad and clearly unintended bug that we reckon should be corrected.*

**Comment by Shintaxgg** [comment]
Any news regarding this?

**Comment by Azmoddan** [comment]
Still in the game.
