### ISSUE TITLE
[BUG] [Core] [Spell] [Priest] Mind Flay behaves as a non-binary spell

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#265]
#### 1.1. Description

Mind Flay (https://www.wowhead.com/wotlk/spell=15407/mind-flay) currently behaves as a non-binary spells even though it is supposed to be a binary spell, meaning it should either hit or resist, nothing in between.

Currently, if you hit the initial Mind Flay cast, all subsequent 3 ticks of the Mind Flay can be either fully OR even partially resisted. This should not happen. As a Binary spell, if you hit the initial Mind Flay cast, all subsequent 3 ticks should FULLY hit. It should not be possible for the ticks to resists if the initial Mind Flay cast hits, partial resist should not be possible at all.

Currently it looks like each single tick is calculated separately when it comes to hit/resist/miss and on top of that, partial resist of them is allowed.

  #### 1.2. How to Reproduce
       
           1. Make a template priest, learn Mind Flay in shadow tree talents.
           2. Cast Mind Flay on a Target Dummy.
           3. Observe combat log.
  #### 1.3  Source Material

![image](https://user-images.githubusercontent.com/1942409/183244566-3f8f664f-c378-48b0-ac5a-726802218839.png)

**WOTLK spell dbc info:**

![image](https://user-images.githubusercontent.com/1942409/183244865-8cd5fe7a-fc64-4755-b164-b5aa42342dbb.png)
![image](https://user-images.githubusercontent.com/1942409/183244870-aa6d0147-3476-441e-bd41-fbaaaeb8563b.png)

**TBC spell dbc info:**

![image](https://user-images.githubusercontent.com/1942409/183244958-0e17f64f-30e1-4bfa-8555-1c6e49b01b49.png)

^^ in WOLTK the damage component got moved into a different effect of the spell periodically causing channeled damage, maybe that is why it acts incorrectly now? (The main spell is still flagged as Binary but the Triggered spell is not?)

#### 2.1. Description

Mind Flay should be treated as a Binary Spell - if the initial Mind Flay cast hits, all subsequent 3 ticks of it should fully hit, they should not resist or partially resist.

  #### 2.2 Source Material

(https://wowwiki-archive.fandom.com/wiki/Binary_spell)

I am a TBC-only player so I dont have any concrete evidence, there is however some discussion in old wowhead comments about it acting differently each patch so its possible the behavior changed because of underlying core changes (unintended)
![image](https://user-images.githubusercontent.com/1942409/183245517-29cc546a-b1c1-48c7-bb77-17487b97bb6e.png)

**Comment by Cleavis** [comment]
what is source for 3.3.5 behavior here?

here is 3.3.5 sept 2010 video showing partial tick resists on training dummy https://youtu.be/Qorw17xvVXo?t=109

3.2.2a combat w partial resists http://wws.piechart-guild.com/col25/sws-overall-1256080847/actor_0x010000000013f438.html
![image](https://user-images.githubusercontent.com/19498073/183252214-3ebabbe3-b208-49ab-a164-2018032ea664.png)

3.1.3 combat log w partial resists http://wws.piechart-guild.com/uld25/sws-overall-1249008033/actor_0x010000000013f438.html
![image](https://user-images.githubusercontent.com/19498073/183252138-53b2906f-cc4e-4479-9e00-a8f495df19c7.png)
