### ISSUE TITLE
[#SomeChanges Suggestion] Remove Hyper-Vision Goggles from Arena

### ISSUE THREAD

**Issue by perpabc** [JamminL/wotlk-classic-bugs#273]
EDIT: Ollipopped's find below this post is incredibly significant - the devs definitely intended to have this item removed in original Wrath.

**Preface**

Balance changes are always incredibly hot topics when it comes to older versions of WoW, which are usually fleshed out with rock solid metas and the people playing them will always advocate for whatever's the most "Blizzlike" product. 

However, in a few very specific and ultra-rare cases, players will speak up about certain things that may alter the game in a way that the majority find un-fun. 

It's a difficult topic because once you start going down the slope, you're unlikely to stop; so removing or altering things tends to trend further away from the original game that people want, over time. 

On private servers, certain things are however restricted in ultra-rare cases, with little to no backlash whatsoever. 

**Hyper-Vision Goggles**

One of these things are the Hyper-Vision Goggles. They provide you with very little stat-boost, offer almost nothing in terms of skill oriented or knowledge based mechanics/decisions, and were used all the way through to Mists of Pandaria on the live game even though they were a level 70 item. 

Why? They give you an abnormal boost to seeing people in Stealth. This is fine with Perception as we've spoken about above - the community hates it when racials, spells, trinkets or even weapons are touched as that's how the game was, and therefore how it should be, but in this case, the on-use effect is so great that it completely negates the need for acquiring a level 80, 85, or even 90 (in the case of MoP) head item, on ANY race. To the point where, if you're not using this specific item, you're behind and likely to be found in Stealth - not fun.

Please consider restricting this item in Arena.

**Comment by avizura7** [comment]
Well explained, thank you Perp. This item definitely does not belong in WOTLK and should for sure get disabled/removed in PVP.

**Comment by ollipopped** [comment]
additional pertinent information would be that the original dev team for wotlk seemed to intend to remove these goggles: 

![image](https://user-images.githubusercontent.com/110876820/183555177-80fc0631-0c8b-4988-9ac0-9ec71b05c155.png)

the goggles in question which they removed were the 'Ultra-Spectropic Detection Goggles' which certainly sound like they do some detecting but its of gas clouds and actually feature no stealth detection whatsoever, passively or on use. 

It's likely they intended to remove the 'Hyper-Vision Goggles' which do provide a very powerful on-use stealth detection effect, which was used by players far beyond the wotlk expansion despite being of a low level (exactly in line with their logic of restricting such items: 'these items provided a necessary advantage in competitive PVP and forced players to use lower level equipment even when more powerful items were available to them')
