### ISSUE TITLE
[BUG] Faerie Fire cannot be _reapplied_ to targets with Misery

### ISSUE THREAD

**Issue by CharWS** [JamminL/wotlk-classic-bugs#274]
#### 1.2. How to Reproduce
           1. Apply Faerie Fire or Faerie Fire (Feral) to the target 
           2. Get a Shadow Priest who has talented into Misery and have them apply the debuff to the target
           3. Attempt to reapply Faerie Fire or Faerie Fire (Feral) to the target while it has Misery active
#### 2.2 Source Material
There were similar issues with the Improved Faerie Fire and Misery talents and regular Faerie Fire and Faerie Fire (Feral) in retail WotlK as well as can be noted from this thread from 2008: https://www.mmo-champion.com/threads/624913-Improved-Faerie-Fire (posters note that "it dosent overwrite FFF but it does block us from reapplying giveing us the too powerfull message unless misery is applied first. there are just some weird bugs with the way misery and faerie fire interact all around.")

Another example where the interaction is mentioned can be found in this blog: http://wowthinktank.blogspot.com/2009/05/druidthe-net-threat-value-of-faerie.html?m=1 (where a user posts "Monkeytree - I believe that this has finally, successfully been fixed in 3.1. Mostly because faerie fire is now a different spell in feral and non-feral forms. I guess the only way I could see is if a cat put it up beforehand or something, but even then it should be able to be overwritten unless that cat has improved FF. Which would be...bizarre.")

Here's a video from July 2009 where a Druid casts Faerie Fire (Feral) multiple times on Algalon despite the boss having Misery active: https://www.youtube.com/watch?v=fRfVDgTLMGA this would be after patch 3.1 (April 2009) and the adjustment to the Faerie Fire spell noted from the wowthinktank.blogspot posters

There's also logs here from Freya in August 2009 where a Feral Druid does multiple casts of Faerie Fire (Feral) onto the boss despite Misery being active http://wws.piechart-guild.com/col25/sws-freya-1250047391/actor_0x010000000229f76e.html http://wws.piechart-guild.com/col25/sws-freya-1250047391/actor_0x010000000013f438.html#auras

In these logs from September 2009 can find a Feral Druid casting Faerie Fire (Feral) against Jaraxxus and the Northrend Beast bosses multiple times despite Improved Faerie Fire being active from a Moonkin http://wws.piechart-guild.com/col25/sws-lordjaraxxus-1252454751/index.html#raid__amp__mobs http://wws.piechart-guild.com/col25/sws-northrendbeasts-1252461472/index.html#raid__amp__mobs

**Comment by caccavale** [comment]
Seems related to #283

**Comment by CharWS** [comment]
Fixed as of 3.4.0.45166
