### ISSUE TITLE
[BUG] Spirit Healers won't ressurect players under level 10

### ISSUE THREAD

**Issue by eulergrj** [JamminL/wotlk-classic-bugs#275]
#### 1.1. Description
The spirit healers won't ressurect players under level 10. After selecting the "Return me back to life" option on the dialog box, the NPC performs the ressurection animation but player stays dead. Working as intended as soon as you hit lvl 10. I believe the issue has something to do with the fact that before level 10 you don't get the sickness debuf.

  #### 1.2. How to Reproduce
           1. Let your under lvl 10 character die;
           2. Try talking to the spirit healer;
           3. Do this again on a character above level 10;
           
  #### 1.3  Source Material
Under level 10 attempt:
https://vimeo.com/737488169 

Over level 10 attempt:
https://vimeo.com/737488569

#### 2.1. Description
Characters under level 10 should be ressurected without the res sickness debuff.
  #### 2.2 Source Material

**Comment by eulergrj** [comment]
Not working again. Tested on lvl 9 and 10

**Comment by leiske** [comment]
Fixed on 45327 (tested lvl 7)
