### ISSUE TITLE
[BUG] Cant override snapshotted RIP "a more powerful spell is already active"

### ISSUE THREAD

**Issue by Oliaxz** [JamminL/wotlk-classic-bugs#276]
#### 1.1. Description
You cant override snapshotted RIP (with temporary AP trinket buff) by a another RIP (with lower AP value).
  #### 1.2. How to Reproduce
1. Build 5 combo points
2. Use an attack power trinket.
3. Cast RIP
4. Remove attack power trinket buff
5. Build 5 combo points
6. Cast RIP 
Step 6 fails because snapshotted RIP is stronger, you'll get "a more powerful spell is already active" error.
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
In wotlk, i believe that there should no longer be any situation where the game doesn't let you override spells that scale with AP/Spell power and have been enchanced by temporaty buff, when you no longer have those buffs up.  I found out that RIP can still get that message, unlike Rake/Insect Swarm, which indicate an inconsistent behavior with that mechanic, one behavior or the other should be blizzlike. 
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by JamminL** [comment]
This mechanic was changed in cata. Unfortunately we're bound to have it in wotlk pending /#somechanges
