### ISSUE TITLE
[BUG] Sacred shield +50% crit fol proc not working

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#277]
#### 1.1. Description
Sacred shield +50% crit fol proc not working
  #### 1.2. How to Reproduce
           1. Sacred shield, spam flash of light on sacred shield proc
           2. notice u crit only 20-30%~ of ur flash of light instead of 70-80%~ (+50%)
  #### 1.3  Source Material
Not yet
#### 2.1. Description
Flash of light should benefits from the 50% crit buff of the sacred shield proc
  #### 2.2 Source Material
Not yet

**Comment by raethkcj** [comment]
Here's a log corroborating this bug, filtered to only show Flash of Light casts with the 6-second Sacred Shield proc on the target:

https://classic.warcraftlogs.com/reports/4VXAcGtBhyCDLMz7/#fight=2&type=healing&source=2&pins=2%24Off%24%23244F4B%24auras-gained%24-1%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24true%2458597%24true%24false&ability=48785

With a character sheet crit of 18.04%, Flash of Light with Sacred Shield active only crit 19.6% of the time, when it should crit 68.04% of the time.

**Comment by Shintaxgg** [comment]
fixed

**Comment by JamminL** [comment]
Fixed build 3.4.0.45327
