### ISSUE TITLE
[BUG] Enemy Target-of-Target doesn't drop fast enough when you cast Stealth/Prowl/Shadowmeld

### ISSUE THREAD

**Issue by Oliaxz** [JamminL/wotlk-classic-bugs#278]
#### 1.1. Description
Prowl/Stealth/Shadowmeld does not make your enemy drop target instantly. This can result in a lot of strange break on stealth, such as prowling into feral charge - cat from max range, and having prowl break as you cross your enemy because of his auto attacks.
  #### 1.2. How to Reproduce
           1. Have somebody target you
           2. Cast prowl/stealth
           3. Notice that his ToT doesnt drop until 0.5-1s later, even when u are really far away (so when stealth detection is not a factor).
This behavior can enable a lot of random stealth/prowl/shadowmeld break, such as when u prowl into feral charge-cat from 25 yard, a target with fast auto attacks will sometime break your prowl as you cross him, before you can pounce, because his ToT does not drop instantly as you prowl.
  #### 1.3  Source Material
Notice in this screenshot how I'm fairly far from my target, around 15 yard, that i got prowl buff up, and that his ToT/auto attacks are still enabled. Those are default unitframes even though they look different, so they have the fastest update/blizzlike.
![ToT_dont_drop](https://user-images.githubusercontent.com/59798458/183448991-a0644baa-2bb0-4fdf-b434-2f766b62aec9.png)
#### 2.1. Description
Prowl/Stealth/Shadowmeld should make your enemy drop target instantly, granted that stealth detection is not severely increased which can sometime allow ToT to not drop.
  #### 2.2 Source Material

**Comment by JamminL** [comment]
This was the case back in the day as well. There's always been an invisibility delay, it's on a batch as well.

The argument could be that you should lower it as well, such as it was made here #124.

If you have proof of otherwise please comment here and I'll consider reopening

**Comment by Oliaxz** [comment]
> This was the case back in the day as well. There's always been an invisibility delay, it's on a batch as well.
> 
> The argument could be that you should lower it as well, such as it was made here #124.
> 
> If you have proof of otherwise please comment here and I'll consider reopening

thx for the reference, since this visibility update is also why u can sap vanish and such, then we need to keep it, but i agree that 500ms is way too long of a window by todays standard.
