### ISSUE TITLE
[BUG] Living Bomb Rank 3 Cannot be Refreshed on Targets

### ISSUE THREAD

**Issue by yurpcraft** [JamminL/wotlk-classic-bugs#281]
#### 1.1. Description
Living bomb ranks 1 and 2 are able to be refreshed on targets, however, living bomb rank 3 is unable to be refreshed, giving a "A more powerful spell is already active" warning
  #### 1.2. How to Reproduce
          {1. Cast living bomb rank 1 on a target dummy
           2. With time remaining on the original cast, re-cast living bomb rank 1
           3. Cast living bomb rank 2 on a target dummy
           4. With time remaining on the original cast, re-cast living bomb rank 2
           5. Cast living bomb rank 3 on a target dummy
           6. With time remaining on the original cast, re-cast living bomb rank 3
           7. Observe error}
  #### 1.3  Source Material

![image](https://user-images.githubusercontent.com/12848366/183539566-40525381-0ad3-48b1-b21d-02ace4cbb661.png)

https://youtu.be/6RStm6eZMfk

#### 2.1. Description

I'm honestly not sure which living bomb behavior is correct.  I can't find any video evidence (so far) of mages being unable to refresh living bomb, and I'm also unable to find any video evidence of mages refreshing living bomb.  The challenge is it's a relatively low priority in the rotation, and the whole reason why you cast it is for the explosion anyway which requires the dot to expire.  It is odd that we're seeing different behavior with different ranks of the spell, though.  Research may be needed to determine which behavior is correct.

  #### 2.2 Source Material

Living Bomb Rank 3 uunable to be refreshed in pvp: https://youtu.be/AnolYQQGbjM?t=414

Obviously finding living bomb rank 2 or rank 1 video evidence might be more difficult.

**Comment by JamminL** [comment]
Unfortunately, https://youtu.be/AnolYQQGbjM?t=414

**Comment by yurpcraft** [comment]
Removed the bug label and marked as research needed in case a source reference would be quick/easy to determine if Rank 1/2 should work the same way.

**Comment by yurpcraft** [comment]
Can now refresh all ranks of Living Bomb (3.4.0.45264)
