### ISSUE TITLE
[TEST-REQUEST] Wound Poison damage/proc rate/resist rate etc

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#282]
### Description
Can someone check if wound poison is actually normal in beta, thanks

**Comment by yurpcraft** [comment]
Closing for lack of any evidence / test methodology

**Comment by caccavale** [comment]
Expected damage of wound poison in 3.0.8 is `.5*(231+.04*AP)=115.5+.02*AP`.  There are no changelog notes for Wound Poison after this patch.
Please collect data from beta about the actual damage if you want to move this ticket along.

**Comment by Shintaxgg** [comment]
https://gyazo.com/1f0dd24feaa15621754210387b555099
115.5 + (2953 * 0.02) = 174.56
i'm getting 354 dmg with wound poison atm (double than expected)

on wowhead it says  (231 + 0.04 * Attack power) which match the dmg of the beta 
https://www.wowhead.com/wotlk/spell=57978/wound-poison-vii
is it intended ? or they forget to add the 0.5* like you linked

**Comment by caccavale** [comment]
Are you DWing and do you have any poison talents?

**Comment by Shintaxgg** [comment]
no poison talents, with poison talent (+20%) it does 425 per wound, and yes i DW

**Comment by Shintaxgg** [comment]
https://www.youtube.com/watch?v=OK_VbTcex3A ye u right
