### ISSUE TITLE
[BUG] "A more powerful spell is already active" on CC casts when a party member dot is present on target.

### ISSUE THREAD

**Issue by chanbetatestwow** [JamminL/wotlk-classic-bugs#283]
#### 1.1. Description
Currently you're not able to recast fear or entangling roots on targets that also have a dot up (this might affect other CC but these are the two we found). 

When attempting to recast, say a fear, on a target already feared then it'll give out "A more powerful spell is already active" until the fear is completely over. This behavior is only present if the target also has a dot on at the time fear is pressed - even if the dot expires mid-fear.

**Update** it's not dot related, it's any damage taken

  #### 1.2. How to Reproduce
           1. Cast Fear on a player or a mob
           2. Cast fear again after 50% of the fear duration has gone past
           3. Watch how you're able to reapply fear
           4. Wait for DR
           5. Cast fear on a player or a mob
           6. Use corruption dot on the mob
           7. Cast fear again after 50% of the fear duration has gone past
           8. Watch how you can't reapply fear until the fear is completely over
    
  #### 1.3  Source Material
https://streamable.com/es5nwy -> Fear with a dot. You can see you simply can't re-apply fear throughout the entire duration. 
https://streamable.com/es5nwy -> Same as example above, but this time the dot expires mid-fear but you're still not able to reapply throughout the entire duration
https://streamable.com/hydwud ->  Example on a dummy with ROOT as the CC and moonfire as the dot

https://streamable.com/5e1lf5 -> How it should always work, with or without a dot

#### 2.1. Description
You should be able to reapply CC after 50% of the duration has gone through, regardless of whether the target has an extra dot or not.
  #### 2.2 Source Material
https://www.youtube.com/watch?v=TWTogJMtt1o -> you can see that the shadowpriest in their party "Talbadar" gets feared with corruption up, into a re-fear before the first fear is over.

**JAMMIN UPDATE: Re-wrote the entire thing and added evidence**

**JAMMIN UPDATE 2: it's not dot related, it's any damage taken**

**Comment by yurpcraft** [comment]
This is accurate as of behavior from 2010: https://www.mmo-champion.com/threads/690864-Affliction-Learning-to-corrupt

If you find sources that say otherwise we can reopen this ticket.

**Comment by chanbetatestwow** [comment]
I may have been mistaken on the Corruption part -- but there is no way this is correct for CC effects is it?

**Comment by yurpcraft** [comment]
For anything with a dot effect, seeing "A more powerful spell is already active" makes sense.  A quick google search didn't come up with anything on entangling roots, but it would be in line with other dot effects seeing "a more powerful spell is already active" on cast.  Fear is a little different since there's no dot effect.  Out of curiosity was fear glyphed in your test?  This may be worth modifying / opening a new ticket exclusively around fear with a little more research fleshed out.

**Comment by yurpcraft** [comment]
Oh maybe I misread.  If there aren't any other modifiers on corruption then I'm not sure why it would prevent the druid from being able to cast other spells.  Could you modify the original post to be more specific around that interaction, and I'll reopen?

**Comment by JamminL** [comment]
This is a bit bigger than what we thought. Keep it open for now I'll add new data soonTM

**Comment by JamminL** [comment]
Re-wrore the entire bug report with evidence to support. I'm cleaning up all the comments now

**Comment by JamminL** [comment]
Re-wrote the issue and deleted the discussion.

**Comment by caccavale** [comment]
Seems related to #274

**Comment by JamminL** [comment]
Apparently it's any damage taken, it's not related with auras. If a breakable-by-damage CC takes damage, the game is considering it more powerful than a fresh one.

**Comment by JamminL** [comment]
Fixed as of 3.4.0.45166
