### ISSUE TITLE
[BUG] Pet abilities are not working if the target is out of Line of Sight

### ISSUE THREAD

**Issue by chanbetatestwow** [JamminL/wotlk-classic-bugs#284]
#### 1.1. Description
All pet abilities are not working if the target is out of its Line of Sight. The pet will stay where it is when the ability is pushed and do nothing. Tested with Felhunter & Succubus (seduction) -- should apply to any pet ability though.
  #### 1.2. How to Reproduce
           1. Press Spell Lock on an out of line of sight target
           2. Try to Devour yourself or a teammate (when out of LoS of your pet)
           3. Press Seduction on an out of line of sight target
  #### 1.3  Source Material
https://clips.twitch.tv/NurturingBraveLemurYouDontSay-nUhqpAesl6AKP3_C
#### 2.1. Description
Your pet should run into line of sight of its target and cast the ability when it is in line of sight.
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by danniellos94** [comment]
Proof for that https://youtu.be/vVvBpuY9BDM

**Comment by JamminL** [comment]
> Proof for that https://youtu.be/vVvBpuY9BDM?t=444

Technically this is evidence that this is NAB. Not clear though

**Comment by danniellos94** [comment]
I see everything he is spamming the silence from pet "not in line sight" and his pet comes out and silence him, but yea videos is really poor quality.

**Comment by JamminL** [comment]
#62
