### ISSUE TITLE
[BUG] Tauren hitbox bigger than normal

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#286]
#### 1.1. Description
Tauren hitbox is longer than other races
  #### 1.2. How to Reproduce
           1. Make tauren
           2. Try hitbox vs a player
           3. Make another race and try hitbox vs a player
  #### 1.3  Source Material
https://gyazo.com/2504118fd29c5991468009bbcafa67d4 = hitbox tauren
https://gyazo.com/5394d9520c9081200c4695c645e2aca4 = normal hitbox
#### 2.1. Description
Tauren should have same hitbox like other races
  #### 2.2 Source Material
Not yet

**Comment by yurpcraft** [comment]
https://www.mmo-champion.com/threads/615003-Tauren-warrior-hit-box-changed-confirmed

Anecdotally fixed around 2008.  @Shintaxgg please include any expected behavior source material when making claims.

**Comment by knasen88** [comment]
Anecdotal evidence to support the claim?
Either way what is true why remove one of the truly unique racials for the curse that is streamlined everything in an rpg. #somechanges

**Comment by knasen88** [comment]
somehow phone deleted comment, anyways.
Why confirm it when the "source" is anecdotal to begin with, and if it became proven otherwise I believe this is a #somechanges kind of feature because it is one of the truly unique racials in an ever-increasing streamlining rpg.

**Comment by JamminL** [comment]
Fixed Build 3.4.0.45327
