### ISSUE TITLE
[BUG] Crusader Strike does less than 75% weapon damage

### ISSUE THREAD

**Issue by limek8** [JamminL/wotlk-classic-bugs#287]
#### 1.1. Description
(3.4.0.44930 PTR build)
Crusader strike does around 71% weapon damage instead of 75%.
  #### 1.2. How to Reproduce
 Attack target with meaningful number of Crusader Strike casts and melee attacks, and compare their average dmg.
  #### 1.3  Source Material
Tooltip: 
[Crusader Strike](https://www.wowhead.com/wotlk/spell=35395/crusader-strike)
Talent
5% of base mana
Melee Range
Instant  4 sec cooldown
Requires Paladin (Retribution)
Requires Melee Weapon
An instant strike that causes 75% weapon damage.

#### 2.1. Description
Crusader strike should cause 75% weapon damage, as in the tooltip.
  #### 2.2 Source Material
PTR Logs: (https://classic.warcraftlogs.com/reports/a:TAp7wKvCkY9hgVrB#fight=last&type=damage-done&source=6)
A template Blood Elf paladin (nick: Player (6), 1204 attack power, weapon 276-414 dmg, speed 3.7) attacked 60 lvl training dummy in front of Orgrimmar (0 armor) for around 13 minutes. No buffs except Devotion Aura. No dmg increasing debuffs on the dummy.
**Talent build:**
No damage-increasing buffs for melee attacks, Crusader Strike or Divine Storm were chosen in the talent tree.
(https://www.wowhead.com/wotlk/talent-calc/paladin/-05005-55232251220000020133231331)

There were 221 melee attacks and 156 Crusader Strike casts. 
Average melee damage was calculated based on the data from logs (159 hits, excluding crits) and it is equal to **663** - it is expected value
( (276+414)/2+1204/14*3.7). 
Average **Crusader Strike** damage (104 hits, excluding crits) was also calculated - it was **471.4 = 71.1%** of average weapon damage (less than expected 75%). 
In the same log **Divine Storm** was tested (199 hits, excluding crits) and its damage averaged to **729.3 = 110%** average weapon damage - as expected).

**Comment by caccavale** [comment]
Missing the weapon speed normalization formula, no?

**Comment by Wumblesnarf** [comment]
looks like your math doesnt account for normalization, when accounting for that the numbers look correct

**Comment by caccavale** [comment]
Good to have confirm Wumble.  Closing since the numbers are as expected if the math is done correctly.
