### ISSUE TITLE
[BUG] Night elf racial bugged

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#289]
#### 1.1. Description
Night elf racial gives way more than 2% miss to melee attack
  #### 1.2. How to Reproduce
           1. Make a melee with just hit cap (5%)
           2. Attack a night elf player
           3. Notice that you miss often
  #### 1.3  Source Material
https://gyazo.com/6846812d49dad6e04d0e3582212c677b
1 miss overpower, 2 miss mortal strike, 1 miss autoattack, 1 miss bladestorm in a 10sec window
#### 2.1. Description
Should be 2% not 20%
  #### 2.2 Source Material
Not yet

**Comment by JamminL** [comment]
@CharWS was faster than me. But yea, test this but test it after today's patch drop

**Comment by Shintaxgg** [comment]
77 rend, 1 miss, 60 autoattack 1 miss, seem fixed

**Comment by JamminL** [comment]
Fixed Build 3.4.04543
