### ISSUE TITLE
[BUG] Unrelenting Assault getting ignored by Absorbs

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#290]
#### 1.1. Description
Absorbs ignoring Unrelenting Assault effect
  #### 1.2. How to Reproduce
           1. Get Unrelenting Assault on yourself
           2. Use Ice barrier / stoneclaw totem glyph / sacred shield / shield priest / Lock pet sacrifice
           3. Notice shield isn't reduced by half
  #### 1.3  Source Material
Not yet
#### 2.1. Description
Unrelenting Assault should reduce the amount of absorb if it's casted after getting Unrelenting Assault
#### 2.2 Source Material
https://www.mmo-champion.com/threads/696428-Absorption-and-Healing-Reduction

**Comment by yurpcraft** [comment]
absorbs aren't healing, no source material provided that says otherwise.

**Comment by Shintaxgg** [comment]
https://www.mmo-champion.com/threads/696428-Absorption-and-Healing-Reduction
"MS does not reduce PWS absorb, but Unrelenting Assault does."

Stop closing issue and writing "not a bug" when it's actually is, this is getting annoying

**Comment by caccavale** [comment]
Stop opening issues without sources, this is getting annoying

**Comment by Shintaxgg** [comment]
> Stop opening issues without sources, this is getting annoying

ye my bad for doing free work and finding bugs so the game is enjoyable to play, my bad my bad

**Comment by Shintaxgg** [comment]
Still isn't fixed as of new build

**Comment by Aggrend** [comment]
Calling this NAB for now. Despite whatever MMO champ comments say, this worked this way until 2012.

**Comment by Shintaxgg** [comment]
https://youtu.be/EwLOcI4h_kg?t=1751
Priest is getting unrelenting assault debuff, no rend, mortal strike already used
Priest cast shield
Warrior auto attack once into execute proc most likely (can't be overpower -no rend- or mortal strike -mortal strike already used before shield-)
The auto attack and execute is enough to break the shield (shield should be around 7k~ absorb in season 8 gear
Only 1 of the 2 attacks from warrior crits
There is no way this is any close to 7k dmg if unrelenting assault doesn't affect shield

**Comment by JamminL** [comment]
https://www.warcraftmovies.com/movieview.php?id=165347 5:41 (3.3.5a with combat log on)

DEEP WOUNDS 478 (ABSORBED)
DEEP WOUNDS 478 (ABSORBED)
REND 833 (ABSORBED)
WHIRLWIND 3097 (ABSORBED)
FROST FEVER 728 (ABSORBED)
DEEP WOUNDS 478 (ABSORBED)
BLOOD PLAGUE 559 (ABSORBED)
||DEEP WOUNDS 449 (ABSORBED)
||DEEP WOUNDS 38 (landed)

7,100 total absorbed

NAB.
