### ISSUE TITLE
[BUG] Frozen Orbs aren't meant to be BoP

### ISSUE THREAD

**Issue by AmNegative** [JamminL/wotlk-classic-bugs#291]
#### 1.1. Description
Frozen Orbs are currently Bind on Pickup for some reason
  #### 1.2. How to Reproduce
  
           1. Arrive at badge vendor
           2. Buy Frozen Orb
           3. Attempt to trade it
  #### 1.3  Source Material

#### 2.1. Description
Frozen orbs are meant to be fully tradable between players at launch. I've gone through dozens of youtube videos uploaded in an era of it just not being possible to have a private server fully functional and have yet to see a single video where the person had the pop up warning you that an item would become soulbound or a tooltip saying "Bind on Pickup".

  #### 2.2 Source Material
WoTLK Beta Heroic Utgarde Keep  
Sep 26 08 
Timestamp: 0:44 
No warning for looting BoP item like other items
https://www.youtube.com/watch?v=m04l7EzHKzY&ab_channel=typhoonspam

WoTLK Heroic Utgarde Keep 
Dec 2 08 
Timestamp: 2:26
Hovers over Frozen orb to show no BoP
https://www.youtube.com/watch?v=haSGb5WBVJU&ab_channel=Dalmthehallowed

WoTLK Heroic Utgarde Keep 
Dec 4 08 
Timestamp: 6:03
Upload hovers over Frozen orb to show not BoP
https://www.youtube.com/watch?v=JKeX29IhDAQ&ab_channel=TboneSynergy

WoTLK Heroic Utgarde Pinnacle 
Dec 6 08 
Timestamp: 2:23
Quickly hovers over Frozen orb to show not BoP
https://www.youtube.com/watch?v=tW0V6AcbMLE&ab_channel=Tuvalee

WoTLK Heroic Utgarde Keep 
Jan 19 09
Timestamp: 4:00
Quickly hovers over Frozen orb to show not BoP
https://www.youtube.com/watch?v=Fn6hujaKq2Y&ab_channel=Tyriama

**Comment by vjtd3** [comment]
I'd like to add additional evidence to this. The Internet Archive snapshotted the Thottbot page for Frozen Orb on December 3rd, 2008, which would be patch 3.0.3 (the first expansion patch of WotLK). The item is not listed as BoP on there, further supporting the OP's claim that frozen orbs were never BoP in WotLK.

[https://web.archive.org/web/20081203075653/http://thottbot.com/i43102](url)

There is also additional discussion of this on the Wrath Classic Beta and Pre-patch PTR subforum referencing old Wowhead comments that state that they were not BoP. The linked comment is during patch 3.0.1.

[https://us.forums.blizzard.com/en/wow/t/frozen-orbs-being-bop/1279571/4](url)
[https://www.wowhead.com/item=43102/frozen-orb#comments:id=383081](url)

**Comment by yurpcraft** [comment]
![image](https://user-images.githubusercontent.com/12848366/185669879-2263e78b-e6af-4be8-935e-a03036898500.png)
Frozen orbs are no longer BoP
