### ISSUE TITLE
[BUG] Mana regen in combat with 0 mp5 talents, and 0 mp5 shown on character sheet.

### ISSUE THREAD

**Issue by yurpcraft** [JamminL/wotlk-classic-bugs#292]
#### 1.1. Description

When casting and in combat, and a character sheet that shows 0 MP5, mana regen is still happening.

  #### 1.2. How to Reproduce
          {
           1. Create any mana using class with 0 talent points
           2. Unequip gear
           3. Ensure no mp5 buffs have been inadvertently applied
           4. cast any spell on a target dummy
           5. observe mp5 ticks}
  #### 1.3  Source Material

https://youtu.be/FLp12Y5Capw

When geared vs. ungeared, the mana ticks will be slightly different values, indicating that this mp5 may be coming somewhere from gear.

#### 2.1. Description

When character sheet shows 0 casting mp5 and no buffs, you should have 0 casting mp5

  #### 2.2 Source Material

None required

**Comment by CharWS** [comment]
https://user-images.githubusercontent.com/104176019/184047009-f4e67404-b845-4ea1-88b3-622849687aff.mp4

Tested with a Priest without Meditation talented. The Priest has 159 out of 5 second rule (oo5sr) mp5 and 0 casting mp5. You can see the mana jumps - from 84 to 144 to 209. The first mp2 tick is a dynamic adjustment (like TBC mp2 ticks), the second tick is for 65 mana, roughly matching up to the oo5sr mp5 for the Priest.

ALL mana users are receiving oo5sr mana in mp2 ticks, within the 5 second window. Additionally, if talented into Meditation or an equivalent talent, the caster regenerates their in-combat mp5 while ALSO receiving the oo5sr mp2 ticks, effectively causing classes with Meditation talents to have 150% mana regen

**Comment by yurpcraft** [comment]
MP5 when 0 MP5 is shown on character sheet is now correct.  Initial testing shows MP5 inside of the 5sr is now correct.  This can be reopened if new evidence shows further MP5 issues.
