### ISSUE TITLE
[BUG] Improved Icy Talons provides unintended additional 20% melee haste

### ISSUE THREAD

**Issue by Jack879** [JamminL/wotlk-classic-bugs#298]
#### 1.1. Behavior
 Frost Fever is currently providing 20% haste to the party/raid, as well as the Death Knight who already gains 25% haste from the Icy Talons and Improved Icy Talons talents.
  #### 1.2. How to Reproduce
           1. Spend points into the Death Knight's Frost tree and reach 5/5 Icy Talons.
           2. Go further into the tree and attain 1/1 Improved Icy Talons.
           3. The Death Knight should have received 25% melee haste passively.
           4. Cast Icy Touch to proc Icy Talons.
           5. Swing speed should rise by an additional 20% for the duration of Icy Talons.
  #### 1.3  Source Material
http://puu.sh/JfL12/212927b649.mp4
#### 2.1. Description
The Death Knight should gain 5% haste from speccing into Improved Icy Talons. Upon proccing Frost Fever / Icy Talons, the Death Knight gains an additional 20% haste. The party/raid members also gain 20% melee haste while within 100 yards, but this should not affect the Death Knight, and does not stack with Windfury Totem or other Icy Talons buffs from other players. 
The Death Knight's Icy Talons also does not stack with Windfury Totem or other Icy Talons buffs.
  #### 2.2 Source Material
https://www.wowhead.com/patchnotes=3.3.3
[(Spell #50887)](https://www.wowhead.com/wotlk/spell=50887/icy-talons): The personal haste benefit provided by this talent is no longer exclusive with other sources of melee haste. This will allow death knights to always swing 4/6/12/16/20% faster when Frost Fever is applied. Windfury Totem and the party/raid component of Improved Icy Talons still do not stack.
[(Spell #55610)](https://www.wowhead.com/wotlk/spell=55610/improved-icy-talons): This effect is now passive instead of being a proc. The self haste buff remains unchanged.

**Comment by caccavale** [comment]
Patch notes specify a clause about the personal portion, and separately that Windfury and **the party/raid** portion of Imp Icy Talons do not stack.  The personal portion should stack.

**Comment by caccavale** [comment]
![image](https://user-images.githubusercontent.com/6198074/184267116-0a04c6f0-33c9-42c5-8bf0-60a0962b0964.png)
