### ISSUE TITLE
[BUG] Mind Flay vs Hand of Freedom

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#303]
#### 1.1. Description
Hand of Freedom doesn't cancel the cast of Mind Flay
  #### 1.2. How to Reproduce
           1. Press Mind flay on a player
           2. Give freedom to that player being mind flay'd
           3. Mind Flay doesn't get cancelled
  #### 1.3  Source Material
Not yet
#### 2.1. Description
If you apply hand of freedom on a target it should cancel mind flay, priest can still mind flay after the freedom to damage his target
  #### 2.2 Source Material
https://wowwiki-archive.fandom.com/wiki/Mind_Flay
"When attacking a druid with Mind Flay, shapeshifting cancels it."
"Similarly, if the target uses a PvP trinket, it removes Mind Flay, due to the snare."
^ Hand of freedom removes "snares" effects

**Comment by Evolvee** [comment]
https://www.warcraftmovies.com/movieview.php?id=163587
doesnt seem to cancel mind flay channeling here

^^Whats happening, I guess, is that Mind Flay has 3 effects - 0) dummy aura (the debuff you see applied), 1) hidden snare effect and 2) hidden triggered spell that does the damage component. In WoW, **aura stacking system** works the way that every effect stands as an entity on its own and isnt fully bound to other effects of the spell, so its possible for 1 of the effects (slow in this case) to be disabled for the duration of Freedom while the other 2 effects arent. 
For example, this is why Mind Numbing Poison and Curse of Tongues can be applied side by side without one overwriting the other even though they do the exact same thing (60% reduction of cast speed) so one could think that the longer aura should overwrite the shorter one but... Curse of Tongues has more than 1 effect - the demonic language effect which makes it stay applied even though its cast-speed-slow effect is temporarily disabled (until numbing poison ends).

The footage above is not entirely conclusive though, you have to literally count frames there... couldnt rly find anything else yet.
And yes, it is retail footage. The fact that you can see (*) symbol in nameplates combined with the year of release should be enough --> no private server had crossrealm arenas back then in 2010, let alone server realms named "Ravencrest" 
![image](https://user-images.githubusercontent.com/1942409/184507331-9b39cac7-cc8f-4392-929f-e8fc35ff406a.png)

**Comment by Shintaxgg** [comment]
nice find, #NAB

**Comment by JamminL** [comment]
https://youtu.be/_uRiKBLD-C8?t=12 adding a better clip as evidence of NAB
