### ISSUE TITLE
[BUG] Silvermoon Hunter Trainer "Oninath" is missing on PTR

### ISSUE THREAD

**Issue by leiske** [JamminL/wotlk-classic-bugs#304]
#### 1.1. Description

Currently, there is no hunter trainer in Silvermoon City. I've tested on a fresh troll I leveled, a boosted 70 blood elf hunter, and my copied 70 troll hunter. All showing Oninath is not present. This occurs on both PTR servers, I can't test on beta.

  #### 1.2. How to Reproduce
           1. Create any character
           2. Go to Silvermoon city
           3. Navigate to 81, 26.5 (hunter trainer location)
           4. You will see the pet trainer and a Silvermoon ranger, but no hunter trainer
  #### 1.3  Source Material

![image](https://user-images.githubusercontent.com/4615743/184503566-dbfd48a6-0628-41de-8e6c-f4fd233dcb00.png)

#### 2.1. Description

The hunter trainer should be present in Silvermoon City. Other trainers such as the org trainer are working as expected.

  #### 2.2 Source Material

Video of Oninath location in Classic TBC (not original wotlk im sorry QQ)
https://youtu.be/kOU2hG0CUlE?t=32 (32 seconds in)

Wotlk db has Oninath listed here: https://wotlkdb.com/?npc=16673

**Comment by JamminL** [comment]
Present on beta
