### ISSUE TITLE
[BUG] Dalaran arena, wall jumping

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#305]
#### 1.1. Description
You can wall jump in dalaran arena
  #### 1.2. How to Reproduce
Get in dalaran arena, go north east side and try to wall jump, you need a mount to do it, draenei race don't need a mount to do that wall jump
  #### 1.3  Source Material
https://gyazo.com/de3b777431f4d73d82139258b684957d
https://cdn.discordapp.com/attachments/708734099208011777/1001836832293654598/99d37e7e89ad037fa84cdc00331e2a4f.mp4
https://streamable.com/3yghgz
#### 2.1. Description
You shouldn't be able to wall jump in dalaran arena, the south west side for example you can't wall jump, only north east side
If it's possible somehow to copy the walls from south side to north side one
It would be kinda game breaking in lot of scenarios if this goes live
  #### 2.2 Source Material
Not yet

**Comment by JamminL** [comment]
https://www.youtube.com/watch?v=hVyUmGm1Cvo NAB

**Comment by Evolvee** [comment]
When you are at the arena jumping topic, the ruins of lordaeron jump should not be possible either yet everyone "abuses" it ever since TBC beta.

![image](https://user-images.githubusercontent.com/1942409/184517756-a0e4d7df-5321-45af-8628-78d34047e74c.png)

**Comment by JamminL** [comment]
Dalaran sewers jump no longer works, but ruins jump (Evolve's comment) is still active

**Comment by Xhyzi** [comment]
> Dalaran sewers jump no longer works, but ruins jump (Evolve's comment) is still active
Actually, this bug it's still up and running, I have seen multiple people doing it on arena recently.
You see Laynzerz and his tema "pulling it off" at the wotlk eu arena finals 3:46:06 https://www.youtube.com/watch?v=BdES4MHiuzU
Also I've seen one guy jumping from a different spot at the center of the ledge (between boxes and stairs), altough I don't have any recording of it.
