### ISSUE TITLE
[#SomeChanges Suggestion] Add S4 pvp gear for death knights in prepatch

### ISSUE THREAD

**Issue by yurpcraft** [JamminL/wotlk-classic-bugs#315]
### Description
Brutal Gladiator's Dreadplate set was added on the cusp of Cataclysm to backfill (mostly for transmog purposes) prior season gear for Death Knights.  Since many players will try and acquire gear on their death knights as quickly as possible during pre-patch, having a PVP set that's grindable would allow these players willing to put in the time/effort to be rewarded appropriately.  This should be a relatively easy addition to vendors that already exist unless there's something funky going on with how the Dreadplate looks on pre-cataclysm character models.

https://www.wowhead.com/wotlk/item-set=-416/brutal-gladiators-dreadplate

**Comment by dariuzsdk** [comment]
This is an awesome suggestion :)

**Comment by yurpcraft** [comment]
Gear on all applicable vendors in the latest build 3.4.0.45327
