### ISSUE TITLE
[BUG] Haunt healing on application

### ISSUE THREAD

**Issue by rafalss** [JamminL/wotlk-classic-bugs#317]
#### 1.1. Description
Haunt is currently healing on application and behaves as if the debuff already is on the target, even if it's the first time you are applying it. When you are replacing the old Haunt debuff, you only receive one instance of healing, which I assume also happens on application, given that the ghost comes back to you before the Haunt projectile reaches the target. On single target, when the debuff expires, it does heal you on return, as expected and with the correct timing. However, when your Haunt is up on one target and you apply a new Haunt on a secondary target, the first Haunt will come back to you and heal (as expected), but you also receive a second heal from applying the new Haunt. When that new Haunt on a secondary target expires, there is no ghost returning and you do not get healed.
  #### 1.2. How to Reproduce       
           1. Drop life with Life Tap
           2. Cast Haunt on a target without Haunt on it and notice the immediate heal on application
           3. Recast Haunt when it comes off cooldown and notice how the ghost comes back before the Haunt projectile reaches the target
           4. Let Haunt expire naturally and notice the normal behavior of the ghost returning and healing
           5. Cast Haunt again on one target again
           6. Cast Haunt on a secondary target once it's off cooldown, notice the double heal
           7. Let the secondary target's Haunt expire and notice no ghost return or heal
  #### 1.3  Source Material
[Video](https://www.youtube.com/watch?v=ky-6J1ixb8U)
#### 2.1. Description
As the talent and spell description indicates, the healing should happen when the ghost returns to you after the debuff is refreshed/applied to another target, or when it expires.
  #### 2.2 Source Material
n/a

**Comment by rafalss** [comment]
Still having a ghost sent at me on Haunt cast, although something changed - now when you refresh Haunt on the same target, you will get two ghost heals - one from the cast, and the other 'proper' one from the ghost returning after refresh.

**Comment by NoCement** [comment]
Btw, if Haunt kills the target it heals twice. I do not belive that is desired behaviour but looking for evidence of the opposite would be quite hard. Any point in doing new report without strong evidence?
