### ISSUE TITLE
[BUG] Everlasting Affliction and Corruption - unable to manually reapply Corruption under certain circumstances

### ISSUE THREAD

**Issue by rafalss** [JamminL/wotlk-classic-bugs#318]
#### 1.1. Description
I will preface this by saying that there is an [old WowHead comment](https://www.wowhead.com/wotlk/spell=47205/everlasting-affliction#comments:id=587635) which suggests there has been an issue in the past as well and initially it led some people to shrug it off as intended behavior, however there are glaring inconsistencies in this behavior that suggest there is indeed a bug.

I've tested a lot of different combinations of spell power buffs to test this, and it appears to me that Fel Armor is a common culprit each time this issue appears.

With Fel Armor on and without any other buffs, it will be impossible to manually recast Corruption, if it has previously been refreshed through Everlasting Affliction, no matter if it was done without any spell power buffs, or if it was boosted by a spell power buff (for example a trinket or Glyph of Life Tap buff). Even if you refresh the Corruption with Shadow Bolt (through Everlasting Affliction) after that spell power buff expires, which should update it to new unbuffed values, it will still be impossible to manually recast Corruption. Neither can you manually recast it when the target is under 35% hp, which should boost your damage through the Death's Embrace talent. You will **only** be able to manually recast it if you get the spell power buff back on, or if you reach/exceed that amount through other buffs.
Edit - more inconsistencies: also tested with Fel Armor on and with a spell power food buff, in this case it will let me manually recast after refreshing duration with Shadow Bolt. However you still can't do it if you use Fel Armor with a flask and no food buff. 

Without Fel Armor, you are able to manually recast Corruption whenever you want, even after the spell power buff expires and a weaker Corruption is refreshed through Everlasting Affliction.

  #### 1.2. How to Reproduce
           1. Make sure to spec Everlasting Affliction and get Glyph of Life Tap. Test the following steps twice, with Fel Armor and without it.
           2. Cast Corruption on the target
           3. Life Tap for a spell power buff (Glyph of Life Tap)
           4. Cast Shadow Bolt to refresh Corruption and to apply the new spell power buff to it
           5. (Optional: you can currently manually recast Corruption, with or without Fel Armor you will be able to do it)
           6. Click off the Life Tap spell power buff
           7.  Cast Shadow Bolt again to refresh Corruption, this time without the spell power buff
           8. Now that Corruption is back to its original unbuffed state, try manually recasting it on the target
           9. Notice how you can recast Corruption manually without Fel Armor, but you are unable to do it with Fel Armor
           10. You can test the same steps with trinkets instead of the Life Tap buff, but the results will be the same.
           
  #### 1.3  Source Material
1. [Fel Armor + Life Tap - after briefly boosting it with the Life Tap bonus, I'm unable to recast it even after Corruption is refreshed back to an unbuffed state. Moreover, the mob is under 35% hp within Death's Embrace's threshold for 12% extra damage, which adds an extra layer of damage increase which is completely ignored by this mechanic](https://www.youtube.com/watch?v=vAFuvTUlNIc)
2. [No Fel Armor + Life Tap - I'm able to recast it at any time, no matter what buffs are up or whether the Corruption is buffed or not](https://www.youtube.com/watch?v=cXhGcGQ5e00)
3. [Showcasing how you can't recast it if you refresh with Everlasting Affliction even before applying any spell power buffs](https://www.youtube.com/watch?v=FF04V_vvGOU)
4. Edit: [you can recast with Fel Armor on if you're using a spell power food buff](https://www.youtube.com/watch?v=ZZCQkXh3O-U)

2 more bonus videos where I use Hex Shrunken Head's active spell power buff instead of Life Tap, just to show that Fel Armor is a consistent issue here and it's not some link between Fel Armor and Glyph of Life Tap. The behavior is exactly the same, so you can skip it if you take my word for it:

5. [Fel Armor + trinket](https://www.youtube.com/watch?v=RPr-HbYIN2w) 
6. [No Fel Armor + trinket](https://www.youtube.com/watch?v=k_f_AdhfSMQ)
#### 2.1. Description
As mentioned before, it is apparent there has been a similar issue in original WotLK that appeared around patch 3.0.8. Considering the behavior of clipping any other dot in Wrath, as well as the inconsistencies in the current beta behavior for Corruption alone, I would still try to apply common sense to what it should work like.

Logically, you should be able to clip/manually recast it like any other DoT, no matter the circumstances, especially that during this testing I was prevented from recasting Corruption even after it got refreshed back to its original, unbuffed state. This issue is only observed with Corruption and not any other DoT ability - you can clip any other dot, even if it was snapshotted with a spell power buff. This behavior potentially prevents you from rolling a new Corruption with % damage modifiers from Death's Embrace or Tricks of the Trade, should you not meet the peculiar conditions that allow you to recast it with Fel Armor on.

  #### 2.2 Source Material
n/a

Welcoming any more data if anyone finds anything extra. Decided to report my findings here, since even though it was a known issue, I haven't heard anyone mentioning Fel Armor as a common culprit, and it looked to me like a solid lead.

**Comment by Aggrend** [comment]
Hotfixed to beta yesterday, should be resolved now!

**Comment by rafalss** [comment]
Works fine in most scenarios now, only still impossible to recast right after a buff expires and you don't refresh it with a new Shadow Bolt yet, so in a scenario like this (can recast any other dot, just not Corruption):

1. Life Tap for the spell power buff
2. Cast Corruption
3. Click off the Life Tap buff
4. **Can't manually recast Corruption now**
5. Cast Shadow Bolt to update Corruption to new spell power values
6. Can manually recast after Shadow Bolt lands
