### ISSUE TITLE
Fingers of Frost dispel case

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#32]
#### 1.1. Description <br/> 
Fingers of Frost has two components: the hidden aura (44544) and the visible aura with stacks (74396). Currently the hidden aura (44544) is dispellable while the visible aura (74396) is not which leads to cases where if a Mage with the FoF proc gets dispelled they have the visible aura (74396) stacks indicating to them that their targets will be treated as frozen but the hidden aura (44544) responsible for ignoring target aurastate is dispelled and doesn't allow the mage to cast for example Deep Freeze.<br/> 
 #### 1.2. How to Reproduce <br/> 
  1. Dispel a Mage with Fingers of Frost buff active
2. Try to cast Deep Freeze as the dispelled Mage <br/>
 #### 1.3  Source Material <br/> 
 n/a<br/> 
 ### 2. Expected Behavior<br/> 
  #### 2.1. Description <br/> 
Those buffs could probably be flipped in which one is dispellable and which one isn't to not confuse the player.<br/> 
 #### 2.2 Source Material <br/> 
n/a

**Comment by JamminL** [comment]
Updated How to reproduce

**Comment by Aggrend** [comment]
I believe this is fixed as of the latest build 44547.
