### ISSUE TITLE
[BUG] Corpse Explosion crit rate lower than expected

### ISSUE THREAD

**Issue by caccavale** [JamminL/wotlk-classic-bugs#320]
#### 1.1. Description
Repeated casts of corpse explosion on many mobs gives around a 5-8% crit rate with 14% spell crit.  I'm wondering whether this is similar to Earth Shield initially using the targets crit.
  #### 1.3  Source Material
![image](https://user-images.githubusercontent.com/6198074/185439208-3aef8222-3f5d-4a2e-a28a-8621ba5be238.png)
![image](https://user-images.githubusercontent.com/6198074/185445595-05ff331b-28fa-4cc2-a533-4f5124253b53.png)

#### 2.1. Description
We would expect the crit of CE to be within a magnitude of spellbook crit.
  #### 2.2 Source Material
TBD, source

**Comment by Shintaxgg** [comment]
Corpse Explosion is based on the ghoul crit chance (5% crit), means it cannot crit in arena with enough resilience

**Comment by caccavale** [comment]
![image](https://user-images.githubusercontent.com/6198074/185765318-b13adc2d-d662-4766-a54d-eb2867d062f9.png)
