### ISSUE TITLE
[BUG] Pets should be auto-targeted by a Player whenever they directly cast a spell onto such player if the player doesnt have a target selected already

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#333]
#### 1.1. Description

Whenever player does not have any Target selected, any UNIT that is casting a harmful spell towards such Player should force the Player to automatically select such Unit into its TargetFrame at the moment such spell cast is initiliazed (ON_CAST).

Currently no such thing happens with **ENEMY PETS**, it works only with enemy players and enemy non-player-controlled npcs _(I guess this is because of aggro reasons)._

**It should work with pets as well.**

The fact that the object delay _(a batched delay between stealthed units are visible from the moment they cancel their invis/stealth)_ is still in place makes certain pets extremely cancerous - especially warlock´s sucubbus.  You are not able to see the pet before you are already charmed from invisibility despite the charm having a cast time. The object delay has pretty much the same duration as the cast time.

  #### 1.2. How to Reproduce
          1. Enter arena against enemy warlock.
          2. Let the warlock summon succubus.
          3. Let the succubus enter into invisibility.
          4. Clear your target.
          5. Let the sucubus cast Charm on you.
          6. Observe that you got charmed out of nowhere, you have no target, you dont know whats going on, you had no chance to react.
          
  #### 1.3  Source Material

sample 1: https://www.youtube.com/watch?v=iY_gB-T3sGo
sample 2: https://www.youtube.com/watch?v=9o4LsBD6rG8

in both samples you can see the above behavior, Player(me) didnt get any Target and the charm was pretty much instant from stealth - no chance to react to it despite it having a cast time that cancels the invisibility.

beta build 45189

#### 2.1. Description

Whenever a harmful spell cast starts to be cast against a player, such player should immediately select a unit that started such spell cast against him into his TargetFrame IF he doesnt have any target selected already. Even player pets.

  #### 2.2 Source Material

<didnt find anything exact yet, still searching...>

**Comment by JamminL** [comment]
NAB, in wotlk succubus invisibility is only removed at the end of the cast, resulting in that behavior

**Comment by Evolvee** [comment]
This report is mainly about the targeting. Which is an issue regardless of invisibility.

**Comment by JamminL** [comment]
> This report is mainly about the targeting. Which is an issue regardless of invisibility.

Which is explained by the targeting event happening while the pet is still invisible, as the targeting happens when cast starts, not when cast ends.
