### ISSUE TITLE
[BUG] [Core] [Arena] Arena Draw Delay is missing

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#334]
#### 1.1. Description

Currently (since day 1 of classic TBC) its not possible to get a DRAW result of arena match due to both teams dying at _almost_ the same time.

On retail, it was possible to get a draw if both teams killed each other within short amount of time (approx. 400-800ms) after the last guy from either team dies.

This is not possible since classic TBC because there is no delay after the last person still alive on a team dies - the arena scoreboard pops up instantly.

There should be a slight delay between the moment the last person on a team dies and the moment arena scoreboard pops up, allowing the remaining team to die within this slight time interval (due to dots ticks for example or flying projectile spells) and invoking a draw between both teams - neither team loses any rating.

  #### 1.2. How to Reproduce

1. enter 2v2 arena
2. kill 1 person of each team
3. reduce HP of both remaining players to 1%
4. let players cast frostbolt (or whatever projectile that does more than 1% hp) on each other
5. observe that there is no draw

#### 2.1. Description
Described above already.
  #### 2.2 Source Material

I had atleast 2 or 3 retail videos when I was researching TBC mechanics back in 2016 but I cant access these links anymore, I will try to look for it more but I think this mechanic is well known and doesnt rly need any extensive proof...

E: https://youtu.be/Yg4kyAbtPDA?t=123 ; https://youtu.be/fk5pwzaGZLs?t=101

**Comment by solarblazin** [comment]
https://www.youtube.com/watch?v=Rf-sPIgfVtg
https://www.youtube.com/watch?v=oykR2saNcDc
^TBC
https://www.youtube.com/watch?v=xO5X8wO4c2o (not full arena match though)
^Wrath

**Comment by Evolvee** [comment]
https://clips.twitch.tv/LovelyThirstyOkapiResidentSleeper-qkooEZWbCZvQRmU-

things like this should never happen, ever, since the very beggining of arena introduction back in TBC
cl_ass_ic 🤷🏿‍♂️

**Comment by Evolvee** [comment]
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/1942409/c888ad56-d2e0-47b8-bad6-6f8bcba9f23a)
