### ISSUE TITLE
[BUG] Rogue Overkill with

### ISSUE THREAD

**Issue by caccavale** [JamminL/wotlk-classic-bugs#338]
#### 1.1. Description
A second bug I have noticed as rogue is that "Overkill" is being registered in the combat log event unfiltered even when not having the talent from the assassination talent tree. CLEU will register applying / removing the aura upon entering or leaving stealth. However the buff is never applied in the first place.

  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Do this
           2. Do that
           3. Do this again and voilá}
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
{Describe how that mechanic/spell/npc should be working, in detail}
  #### 2.2 Source Material
{Video, Posts, etc..}

ex-#336

**Comment by XyzKangUI** [comment]
Dear Caccavale,

It is pretty hard for me to find any original source (3.3.5) on this issue. But it cannot be denied that this must be a bug. 

![image](https://user-images.githubusercontent.com/94811434/185817044-e1e757fc-d559-4007-925e-92ac0ab36d7a.png)

**Comment by caccavale** [comment]
Ohhhh-- I misunderstood.  Thanks!

**Comment by JamminL** [comment]
You're right, marking this as minor bug, I tested it myself, all visual
