### ISSUE TITLE
[BUG] Taste for blood - Warrior Arms Talent

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#34]
#### 1.1. Description
Cannot Overpower with Taste for Blood buff
  #### 1.2. How to Reproduce
           1. GET TASTE FOR BLOOD 
           2. TRY TO OVERPOWER
           3. NOTICE U CANT
  #### 1.3  Source Material
Nothing yet
#### 2.1. Description
Should be able to overpower
  #### 2.2 Source Material
Nothing yet

**Comment by Aggrend** [comment]
We should have a fix for this in our next beta build (Eta Weds 8/3). Sorry for the delay on this, we are starting to make better progress through the bug backlog finally :P

![image](https://user-images.githubusercontent.com/81382721/182261209-c863b827-2c3a-4b2c-a064-f3429b29ebf2.png)

**Comment by CharWS** [comment]
Fixed as of build 44930
