### ISSUE TITLE
[BUG] Omen + Hurricane inconsistent behavior

### ISSUE THREAD

**Issue by caccavale** [JamminL/wotlk-classic-bugs#343]
#### 1.1. Description
Hurricane seems to proc Omen of Clarity _very_ often.  Casting Hurricane while you have Clear Casting does not cost mana and also does not consume the Clear Casting buff.

Rejuv / Wild Growth / GotW seem unaffected though a very small sample size was tested.
  #### 1.3  Source Material
[Video](https://streamable.com/9xound)
### 2. Expected Behavior
Leaving this section to Blizzard here.

**Comment by caccavale** [comment]
Logged 9m of hitting 5 target dummies with hurricane.  In 2550 hits, CC was refreshed 179 times for an estimated 7.01% chance.
Not the largest sample size for sure.

**Comment by Aggrend** [comment]
We've got a hotfix in place for this that should go to beta/ptr servers sometime today.  This issue was a by-product of the Gylph of Hurricane bug fix.
