### ISSUE TITLE
[BUG] Flag Holders not shown on Map in Warsong Gulch

### ISSUE THREAD

**Issue by powerlol** [JamminL/wotlk-classic-bugs#347]
#### 1.1. Description
When holding a flag, as of patch 2.4 (TBC), you should be able to track the enemy flag holder position through the map, in Warsong gulch, after 45 seconds that the flag has been picked up. This isn't the case in TBCC neither it's in PTR/Beta of WotlkC. 
  #### 1.2. How to Reproduce
          
           1. Enter Battlegrounds
           2. Let the opposite faction get flag
           3. Wait 45 seconds
           4. Open map and see that you don't see enemy flag position. 
  #### 1.3  Source Material

https://www.twitch.tv/videos/1568003648?t=1949s

Watch until 34:21 - 2 min has passed and yet when he opens map Enemy flag holder isn't shown on map. 
#### 2.1. Description
When the A team holds the flag for more than 45 secondes, A team flag holder should be shown on map for the B team. 
  #### 2.2 Source Material

https://www.wowhead.com/warsong-gulch#comments:id=261759 ![image](https://user-images.githubusercontent.com/46472285/186470647-01c6135c-097c-49c4-a961-86fd0d502c25.jpeg)

https://wowwiki-archive.fandom.com/wiki/Patch_2.4.0 ![image](https://user-images.githubusercontent.com/46472285/186470530-732a75b7-2362-4af9-baa4-a47f8bfc8bde.jpeg)

And old video from back in time https://youtu.be/j4tDfYcjZ_w?t=352 you see that the opposite team takes the flag and isn't shown directly on map - later on you'll see a flag icône on the mini map in the corner because the enemy team has hold the flag for more than 45 seconds

**Comment by Evolvee** [comment]
This could be a complete bullshit and I have no source for this but... Shouldnt the enemy flag carrier be also map-visible for the rest of the team when someone from your team has a direct vision of the person?

**Comment by powerlol** [comment]
> This could be a complete bullshit and I have no source for this but... Shouldnt the enemy flag carrier be also map-visible for the rest of the team when someone from your team has a direct vision of the person?

I remember something like this aswell - But I think it's a feature added in Cataclysm. I remember being able to track people in RBG once seen. But definitely not in wotlk

**Comment by powerlol** [comment]
Fixed as of today's hotfix

![image](https://user-images.githubusercontent.com/46472285/193964298-48db01d7-7ad4-460a-bc2d-8065199d7849.jpeg)
