### ISSUE TITLE
[BUG] Shaman's Nature's Swiftness cooldown should be 2 minutes, not 3 minutes

### ISSUE THREAD

**Issue by raethkcj** [JamminL/wotlk-classic-bugs#348]
#### 1.1. Description
  Resto Shaman's Nature's Swiftness talent has a 3 minute cooldown.
  #### 1.3  Source Material
  ![image](https://user-images.githubusercontent.com/7716908/186535379-aae2ba5d-0cf8-484b-ad4f-82a639b5eef3.png)
#### 2.1. Description
  It should have a 2 minute cooldown.
  #### 2.2 Source Material
  > Nature's Swiftness: Cooldown is now 2 minutes, down from 3 minutes.
  
  [Patch 3.2.0 Patch Notes](https://web.archive.org/web/20090807205046/http://www.worldofwarcraft.com/patchnotes/)

**Comment by Teebown** [comment]
Confirmed fixed today, September 2
