### ISSUE TITLE
[BUG]Rifle the Bodies quest

### ISSUE THREAD

**Issue by Undertoe** [JamminL/wotlk-classic-bugs#351]
#### 1.1. Description
Trying to loot the bodies for the quest [Rifle the Bodies](https://www.wowhead.com/wotlk/quest=11999/rifle-the-bodies) 
  #### 1.2. How to Reproduce
https://youtu.be/6cljG5Vp5KY Youtube of issue.  WHen looting an error "nothing to dispell" pops up and nothing is looted.
#### 2.1. Description
You should be able to loot the bodies.

**Comment by Undertoe** [comment]
Quest still broken as of build 45327.  Pretty much nukes the ability to progress at all in dragonblight for horde.

**Comment by watchyoursixx** [comment]
fixed at some point completed this today
