### ISSUE TITLE
[BUG] Improved Unholy Presence Talent Not Reducing Rune Cooldown

### ISSUE THREAD

**Issue by CharWS** [JamminL/wotlk-classic-bugs#355]
#### 1.2. How to Reproduce
           1. Talent into Improved Unholy Presence
           2. Ensure you're in Unholy Presence
           3. Spend runes paying attention to their refresh timers
  #### 1.3  Source Material
![UHP](https://user-images.githubusercontent.com/104176019/186806248-bbe2aff9-df00-40b0-980b-f597ddf49bbd.png)
Can see 10s rune CDs from combat log timestamps with Improved Unholy Presence talented while in Unholy Presence
#### 2.2 Source Material
https://wowpedia.fandom.com/wiki/Improved_Unholy_Presence?oldid=2709921
https://www.wowhead.com/wotlk/spell=50392/improved-unholy-presence#comments
https://cdn.discordapp.com/attachments/364459574327246851/1012556206268747797/unknown.png

**Comment by dariuzsdk** [comment]
As of the most recent patch this is still bugged, could we get some eyes on this? Fairly gamebreaking bug

**Comment by dummyaccounter** [comment]
Yes, this is one of the most important aspects of an unholy death knight's identity. This would be like if wrath rogue ambush talents weren't working. Please fix this! Cheers...

**Comment by dariuzsdk** [comment]
Been over a month now, this remains an unusable critical talent and arenas will come out soon, can we please get some eyes on this?

**Comment by NuptupTDOW** [comment]
While I also hope it gets fixed, I want to say that for you guys playing unholy, you can still get the increased movement speed from the talent and go with blood/frost presence. Blood presence with +15% move speed is pretty fun currently, and unholy tanking with 115% move speed is making dungeons go faster. Obviously it's not the ideal solution, but until we get someone to put some time into fixing it, using the talent and a different presence still grants the talent's intended buff for those presences and is still pretty fun.
