### ISSUE TITLE
[BUG] Hunter Pet Avoidance 

### ISSUE THREAD

**Issue by TheDunds** [JamminL/wotlk-classic-bugs#364]
#### 1.2. How to Reproduce
           1. Have pet stand in aoe ability that is not from a player 
           2. Notice how Pet takes more damage than expected
  #### 1.3  Source Material
Using a ptr swp log from the 22nd of august which i believe is one build behind current build: 
https://classic.warcraftlogs.com/reports/hQtDZVPdm34HnXf1
Kalecgos spectral blast and arcane buffet are being mitigated by 32% to 77% 
![image](https://user-images.githubusercontent.com/110584436/187062527-9eafa5d8-bb96-4336-a262-10cc653a2199.png)
Eredar twins Burn (blaze) is getting as low as 1.5% mitigated
![image](https://user-images.githubusercontent.com/110584436/187062911-c9e88bf0-6560-4bff-85eb-65f76924fc42.png)
And up to 17% in this log 
![image](https://user-images.githubusercontent.com/110584436/187063040-f795a60d-6134-4af6-8da0-3853da9333c7.png)

#### 2.1. Description
Hunter pets take 90% less damage from area-of-effect abilities like all other class pets.
  #### 2.2 Source Material
Patch changes
World of Warcraft: Wrath of the Lich King [Patch 3.3.0] This talent has been replaced by Culling the Herd. Hunter pets now innately take 90% less damage from area-of-effect abilities like all other class pets. This does not apply to area-of-effect damage caused by other players.

Please note:
I have checked multiple naxx/maly/sarth logs and have not yet found a log with a aoe ability not being mitigated by avoidance correctly

**Comment by CharWS** [comment]
The reason those abilities are not reduced would be that they're non NPC sourced damage, spectral blast is environmental, and burn is sourced to blaze, non npc sourced damage are not reduced by pet 90% aoe reductions. This is normal behavior and was present in 2009 as can be noted by such threads as https://www.mmo-champion.com/threads/640913-Pet-during-Sarth-D regarding Sartharion Flame Walls which are also environmentally sourced damage and not effected by aoe reductions.

**Comment by CharWS** [comment]
Here's some additional examples for wotlk as per abilities reduced or not reduced by pet avoidance.

http://wws.piechart-guild.com/uld25/sws-thorim-1248914128/actor_0.html blizzard and defeaning thunder not reduced on thorim 
http://wws.piechart-guild.com/uld25/sws-ironcouncil-1248907282/actor_0xf130008059005dfd.html chain lightning on iron council reduced, but not lightning whirl
http://wws.piechart-guild.com/uld25/sws-ironcouncil-1248907282/actor_0xf130008063005dfc.html static disruption not reduced, high voltage is reduced 
http://wws.piechart-guild.com/uld25/sws-hodir-1248915753/actor_0xf13000804d021066.html freeze on hodir looks to be reudced
http://wws.piechart-guild.com/uld25/sws-mimiron-1248909049/actor_0xf1500082980093e5.html mimiron shock blast not reduced
http://wws.piechart-guild.com/uld25/sws-mimiron-1248909049/actor_0xf15000837300a616.html heat wave reduced, hand pulse reduced, rapid burst reduced, lazer barrage not reduced
http://wws.piechart-guild.com/uld25/sws-mimiron-1248909049/actor_0.html flames reduced
http://wws.piechart-guild.com/uld25/sws-mimiron-1248909049/group_0xf13000863a00a0ea.html proximity mines reduced 
http://wws.piechart-guild.com/uld25/sws-yoggsaron-1248919531/group_0xf13000817002a49c.html yogg shadow nova reduced, dark volley reduced, crush potentially not reduced? (need more hits to tell)
