### ISSUE TITLE
[BUG] Impale - Warriors Arms Talent

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#37]
#### 1.1. Description
Impale %dmg not working properly, something like 0-5% instead of +20% crit dmg
  #### 1.2. How to Reproduce
- Test crit damage without talent
- Re-test crit damage with talent
  #### 1.3  Source Material
Nothing yet
#### 2.1. Description
It should increase crit dmg by 20% and not way less
  #### 2.2 Source Material
Nothing yet

**Comment by JamminL** [comment]
Fixed
