### ISSUE TITLE
[BUG] Songflower Buff Unobtainable on Characters Level 60 and Below

### ISSUE THREAD

**Issue by tacocat777** [JamminL/wotlk-classic-bugs#379]
#### 1.2. How to Reproduce
           1. Play a character lvl 60-50 (?)
           2. Cleanse a Songflower in Felwood
           3. Click the newly cleansed Songflower
           4. Cry as you wasted plant salve and received no buff !

**Comment by rodrigo-barraza** [comment]
Have you tried playing a better game?

**Comment by tacocat777** [comment]
Someone mentioned this issue has been fixed after this week's reset (9/20/2022).

Confirmed today (9/22/2022) that it has indeed been fixed!

![](https://cdn.discordapp.com/attachments/762734438375096380/1022707512136450108/buufs.png)
