### ISSUE TITLE
[BUG] Armored to the Teeth - Arms Warrior Talent

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#38]
#### 1.1. Description
Armored to the Teeth does nothing
  #### 1.2. How to Reproduce
           1. Check your attack power
           2. Pick talent
           3. Check your attack power again
  #### 1.3  Source Material
Nothing yet
#### 2.1. Description
Should increase attack power
  #### 2.2 Source Material
Nothing yet

**Comment by CharWS** [comment]
Bladed armor on Death Knights is similarly not functioning as per: https://github.com/boukx/wotlk-death-knight/issues/21
