### ISSUE TITLE
[BUG] [Spell] Dispersion animation ends abruptly without fully finishing

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#381]
#### 1.1. Description

**Current behavior:** https://youtu.be/x4LPEhDDL_4

As you can see, the dispersion animation cuts off at the end.

Its worth to mention that even the initial seconds of the animation arent exactly "smooth"... The character model goes from "humanoid" into "dispersed void" instantly.

**Expected behavior:**

https://www.warcraftmovies.com/movieview.php?id=134749 0:00, 1:40
https://youtu.be/pibwCLprfp4?t=494
https://youtu.be/pibwCLprfp4?t=825
https://youtu.be/DMXM4D8vHgg?t=27
https://youtu.be/DMXM4D8vHgg?t=111
https://youtu.be/DMXM4D8vHgg?t=206

Smooth animation both in and out without cutting off.

  #### 1.2. How to Reproduce

           1. Use dispersion.
           2. Observe its animation.
           3. Compare with the videos above.
  #### 1.3  Source Material
live prepatch build 45327

**Comment by Evolvee** [comment]
its not fixed, atleast not on live server

**Comment by watchyoursixx** [comment]
Hmm, watching myself disperse it looks like a complete animation. Is there something I'm missing here? The animation is finishing as far as I can tell

**Comment by Evolvee** [comment]
It still looks the same as on the video https://youtu.be/x4LPEhDDL_4 on Firemaw-EU right now.

**Comment by watchyoursixx** [comment]
So.. how is that any different from the old videos? Maybe I'm blind or something but they look the same as live (with the exception of the initial animation delay, but technically this report only refers to the end)

**Comment by Evolvee** [comment]
The retail animation is smooth both at the beggining and end. Classic animation has no smooth transition at neither beggining or end. I will try to make a video comparison soon or idk.

**Comment by Evolvee** [comment]
@watchyoursixx i made a comparison video with both clips being in sync when disperion starts and when it ends, you can clearly see that the beggining transition is scuffed and the end "fade-out" transition is scuffed even more to the point where there is no transition whatsoever, it just cuts to normal form in mid-animation:

https://www.youtube.com/watch?v=iuVtlB70Pug

reopen pls

**Comment by watchyoursixx** [comment]
Good eye, I'm definitely blind. It's subtle but it's there and obvious side by side. Clearly not fixed yet 😟

**Comment by Evolvee** [comment]
There has been an update to the animation today, it seems waaay better when it comes to the end of the animation, the start still looks scuffy so i will have to compare it again and make another comparison video.

**Comment by Evolvee** [comment]
https://user-images.githubusercontent.com/1942409/199547741-05f692d4-73e7-4e43-8cca-deb2f88fd5d6.mp4


^^ This is how the animation currently looks.
Obviously its way better than before but there are still 1 differences:

**When you enter dispersion, your "humanoid" character is still visible for some time. That was not the case on retail.**

**Comment by Evolvee** [comment]
when you try your best but dont succeed 🍼
