### ISSUE TITLE
[BUG] Hunter Pet Talents Reset 

### ISSUE THREAD

**Issue by TheDunds** [JamminL/wotlk-classic-bugs#382]
#### 1.1. Description
On the live Prepatch servers build 3.4.0(45327) hunter pet talents are resetting themselves under a variety of different circumstances. 
Logging in and out.
Flying up and despawning your pet and landing will make your pet lose all its talents.
Going into and out of a battle ground.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Be BM Have a exotic pet (devilsaur)
           2. Spend your pets talent points 
           3. log out and in 
           4. Notice how the talent points you just spent are reset 
  #### 1.3  Source Material
  https://streamable.com/855xfx
### 2. Expected Behavior
Spent talent points to be permanent 
  #### 2.1. Description
The talents points you spent on your pet should be permanent unless you reset them from a trainer
  #### 2.2 Source Material
https://wowwiki-archive.fandom.com/wiki/Pet_talents 
"Pet talents can be reset at a pet trainer for free."

**Comment by watchyoursixx** [comment]
this should be fixed from a hotfix. Please note if it's still not working. Personally haven't seen this happening anymore.
