### ISSUE TITLE
[BUG] Wild Growth Smart Targeting Pets over Players

### ISSUE THREAD

**Issue by Frankensteak** [JamminL/wotlk-classic-bugs#385]
#### 1.1. Description
Wild Growth frequently chooses pets as targets with its smart cast. Out of 109 WG casts in my last raid, 105 of them targeted at least 1 pet. From reviewing targets mid-raid, i saw ~3 pets getting targeted with WG pretty frequently.

This has frustrating results with trying to blanket raid members with the WG hot for incoming damage, and decreases the impact of Revitalize.

It appears when there is no healing to be done, WGs smart cast chooses targets in range with lowest health totals first. This frequently picks pets as targets over raid members

  #### 1.2. How to Reproduce
           1. Be an awesome Druid
           2. Get into a raid
           3. Hit Wild Growth while everyone is at 100% hp
           4. Notice how many pets are targets of said WG cast

  #### 1.3  Source Material
Log of WG casts (109 casts)
https://classic.warcraftlogs.com/reports/ynJgVQCLTxAPdrWw#boss=-3&difficulty=0&type=healing&source=26

Filter of WG casts to pets (105 casts hit pets)
https://classic.warcraftlogs.com/reports/ynJgVQCLTxAPdrWw#boss=-3&difficulty=0&type=healing&pins=2%24Off%24%23244F4B%24expression%24target.type%20%3D%20%22Pet%22&source=26

#### 2.1. Description
Expected behavior is WG targets other raiders more often when there is no healing to be done, raiders more frequently have the WG hot active for future incoming damage and benefit more from Revitalize coming from WG casts.

  #### 2.2 Source Material
Shaman CH smart cast behavior mostly targeting players. Priest CoH smart cast behavior mostly targeting players.

**Comment by Cleavis** [comment]
Needs source material from 3.3.5 if smart healing is not behaving correctly. Or better demonstration how Wild Growth is behaving differently from other smart heals (still 3.3.5 reference would be better).

Comparing to Priest CoH in your same log, most pets are at 100% overheal. If CoH is not prioritizing pets, that seems unlikely.
https://classic.warcraftlogs.com/reports/ynJgVQCLTxAPdrWw#boss=-3&difficulty=0&type=healing&ability=34866&by=target

**Comment by Frankensteak** [comment]
If you use the target.type = "Pet" filter pin, you can see in the events that only 10 of the CoH casts hit pets
https://classic.warcraftlogs.com/reports/ynJgVQCLTxAPdrWw#boss=-3&difficulty=0&type=healing&ability=34866&by=target&pins=2%24Off%24%23244F4B%24expression%24target.type%20%3D%20%22Pet%22&source=42&view=events

Total number of casts is 49, so ~20% of CoH casts hit a pet, as opposed to 96.3% of WG casts hitting pets

**Comment by Frankensteak** [comment]
Similarly for our resto shaman: 

https://classic.warcraftlogs.com/reports/ynJgVQCLTxAPdrWw#boss=-3&difficulty=0&type=healing&ability=25423&by=target&pins=2%24Off%24%23244F4B%24expression%24target.type%20%3D%20%22Pet%22&source=1

22 chain heals hit pets out of 420 casts, only 5.2% of casts targeted pets

**Comment by Teebown** [comment]
http://wws.piechart-guild.com/col25/sws-overall-1256080847/actor_0x010000000301c822.html

You could reference these old logs, they don't give quite as much information as wcl but you can find % from them.  There was a mention in this thread from 2013 suggesting that WG uses lowest max HP to choose targets when everyone's at 100% (obviously post wotlk), but that would fit with the behavior you're seeing, since you'd expect pets to be the lowest max HP. https://www.mmo-champion.com/threads/1274596-Wild-growth-range-issues. I haven't dug back to 2009/2010 to see if this was a finding back then also.

**Comment by NOHITJEROME** [comment]
I can confirm that Wild Growth is prioritizing pets. I was in a raid today with 4 pets. WG only seemed to go on players when they had less than 100% HP. 

If I pre-hot the tank currently, even the tank does not receive the WG. This makes WG an extremely unreliable spell for pre-hotting. I will attach a VOD with timestamps of the intraction at 1AM EST, currently not at PC.

From WoW wiki:
"Heals 5 targets total, the target counts as one.
If there are not 5 targets in range below 100% health, the HoT will land randomly on players with full health."

No mention anywhere on Google of Wild Growth issues targeting party/raid members at 100% HP.

**Comment by baelbael** [comment]
Divine Hymn seems to be bugged the same way
https://cdn.discordapp.com/attachments/1001547917158531153/1015292888277598269/unknown-205.png

**Comment by ClassicShane** [comment]
This is garbage and should be changed immediately. They are open to changes only if they come up with them; but aren't willing to even the playing field and would rather allow Pally to literally be the only healer needed besides a priest for the second time in 3 versions of classic. Absolutely trash balancing once again.

**Comment by Frankensteak** [comment]
If this ends up not being a bug and the intended implementation, I'd like this to be updated to a #somechanges request.

Druids are in a slightly special situation with Wild Growth and the full use-case in practice might not have been considered when developing the smart targeting order.

The strength of resto druid comes from "proactive healing", having hots rolling on players for future incoming damage so that the players are healed automatically. This relieves other healers of some of the mental load of worrying about the raid, and gives them the space to impact healing in the way their classes shine.

Common advice for raid healing as a resto druid in wotlk is to blanket the raid with rejuv and wild growth on CD to buffer against any AoE they might suffer. This fits the flavor/lore of a druid as protecting life, "planting seeds to flourish", other hippy malarky, etc. This healing profile is a big part of the unique benefits a resto druid brings to raid.

With current smart targeting behavior however, Wild Growth does not fit this playstyle. WG has to be used reactively when players are low enough to ensure they are the recipients over pets. It's not possible to add WG to the proactive "hot blanket" while waiting for an AoE strike as pets will eat all the charges, and then the spell will go on cooldown for when the AoE actually happens. This makes WG not fun to cast, and forces people to reconsider whether single-target healing in an AoE situation would be more effective in case too many pets get targeted.

Suggested smart targeting order to make WG more impactful and fun:
1. Largest player hp deficit (Could be percentage or raw deficit)
2. Lowest % HP Pets/NPCs (Could be percentage or raw deficit)
3. Lowest total HP Players
4. Lowest total HP Pets/NPCs

1 is obvious, heal the lowest players first.
2 if no player is damaged, damaged pets can be valid targets to heal.
3 if no one is damaged, players or pets, it should prioritize low hp total players for the proactive healing "hot blanket".
4 if there is no valid player targets, then full hp pets can be targeted as to not lose the cast to the void.

**Comment by Frankensteak** [comment]
@Cleavis @Teebown @CharWS any updates regarding this ticket?

**Comment by Aggrend** [comment]
We've looked at this several times and this is indeed how this spell is set up in 3.3.5. It's fine to update this to a #somechanges suggestion, but we have no plans at this time to re-write this spell.

**Comment by NatsumeLily** [comment]
> We've looked at this several times and this is indeed how this spell is set up in 3.3.5. It's fine to update this to a #somechanges suggestion, but we have no plans at this time to re-write this spell.

Fuck you..This is a fucking bug you fucking idiot. Amateur dev indeed.
We'll just need reporting this ingame until you fucking learn how to code shit...
