### ISSUE TITLE
[#SomeChanges Suggestion] Soulshard Cap

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#39]
### Description

In WOTLK Soulshards got capped at 32. We assume this was done because of the new talent "Improved Drainsoul" which made players want to Drain Soul for mana, but wouldn't want to deal with the large amount of soulshards.

Back then 32 soulshards seemed like a large enough number, we now know that's not the case, and players often do want more soulshards stored. Any chance we can remove this cap?

#SomeChanges?

**Comment by Aggrend** [comment]
We've looked at this and our designers decided not to make adjustments here. This has implications in PvP as this cap limits a warlocks throughput and allowing you to stack shards to the moon could impact the flow of a fight. Thanks for the suggestion, but no changes here for now.
