### ISSUE TITLE
[BUG] DRW abilities incorrect scaling

### ISSUE THREAD

**Issue by danniellos94** [JamminL/wotlk-classic-bugs#394]
### 1. Current Behavior
DRW abilities are doing base damage instead scaling with attack power. I believe this was a bug back in the wrath and got hotfixed with stealth hotfix in cata. This might be somehow connected with issue #194.
  #### 1.1. Description
This only applies to abilities, autoattacks are mostly working fine. 
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Try with on use trinket or without.
           2. Use rune weapon
           3.  Do death coil or any other spell.
           4. Observe same ' base'  damage.
  #### 1.3  Source Material
https://www.youtube.com/watch?v=1e1cL65J87Q&t=290s

https://www.youtube.com/watch?v=221jtKbsWQA&t=44s  - observe the bug 315 normal pet death coil and 2594 crit pet damage death coil seems like sometimes death coil was getting benefits off attack power most likely

https://web.archive.org/web/20100808151937/http://elitistjerks.com/f72/t61176-blood_simple_day_music_died

### 2. Expected Behavior
"Your DRW checklist looks something like this, in order of importance 
Bloodlust/Heroism
Hysteria
On use trinkets / Trinket Procs
Empowered Rune Weapon
Potion of Speed"
  #### 2.1. Description
Dancing rune weapon should snapshots stats like gargoyle.
  #### 2.2 Source Material
https://www.youtube.com/watch?v=cmNWKblENnI with attack power trinket
https://www.youtube.com/watch?v=vrbi8dKx5oY without attack power trinket

**Comment by ambiwar** [comment]
DRW is scaling with AP.
![image](https://user-images.githubusercontent.com/111925369/189456895-c9d75245-e155-4787-a681-602c56ed8340.png)

**Comment by danniellos94** [comment]
https://youtu.be/1e1cL65J87Q?t=292 15128 attack power 11228 drw death strike
https://youtu.be/xRxPAzxC04g?t=1580 57788 attack power 54887 drw death strike

**Comment by bibothe** [comment]
From my testing the ap scaling seems to work fine for strikes but any %damage buffs or talents/glyphs do not apply to said strikes.

Using Plague Strike of Obliterate in unholy or frost presence do deal around 50% damage but do not increase when in blood presence or using unholy frenzy. The Auto attacks of DRW however seem to take everything into account.

**Comment by danniellos94** [comment]
Bibothe might of mograine works for sure atm.

in unholy presence:

2548 ap 466 drw death strike

3560 ap 540 drw death strike

74 damage difference for over 1k ap seems pretty low if you ask me.

**Comment by bibothe** [comment]
Death strikes base scaling is 75%
14 Attack power gives 1 dps and the weapon speed on instant attacks for scaling is normalized to 3.3 speed
DRW is supposed to deal 50% of damage

so 1000/14*3.3*0.75*0.5=88.3928571 Now the only thing missing to get to your 74 damage is the armor of said target.

As for might of mograine your right it does seem to work but all %damage ones from what i can tell do not.

As a baseline test here some numbers :
Plague strike with only a weapon equipped in Uh presence and the only damage buff being 3 stacks of bloody vengeance, Blood gorged and two handed spec:
Plague strike : 366 average (non crit)
DRW plague strike : 163 average (non crit)

if you add the %increases to DRW you get 163*1.09*1.04*1.1=203 which would be more than expected so one of the 3 damage amps potentially works. Armor pen also makes this more difficult to test then it already is.

Doing the same but putting on all my gear, popping trinket and using horn of winter i get
PLague strike : 601 average (non crit)
DRW plague strike : 258 average (non crit)

This gave me a 1936 ap diff which should give me 1936/14*3.3*0.5*0.5=114 extra damage. Take armor into account and ap scaling seems to work just fine

And the same seems to apply to Death Strike. With all gear and talents/glyphs unholy frenzy active and in blood presence
Death strike : 1940 average (non crit)
DRW Death strike : 464 average (non crit)

Same thing but unholy presence and no frenzy
Death strike : 1484 average (non crit)
DRW Death strike : 454 average (non crit)

**Comment by danniellos94** [comment]
Well maybe but it's hard to check it exactly, however it change nothing with drw death coil damage not scaling at all that I showed in video.

This is also weird that DRW autoattacks get benefit of hysteria, all %talent buffs and the weapon you wield while the abilties don't. DRW inherits most of talents (epidemic for sure as example, EJ threads talking about imp death strike and bloody strikes working also).

If DRW does 50% reduced damage of base abilities and it's not even counted on your weapon damage than it's ultra omega usless.

**Comment by danniellos94** [comment]
https://web.archive.org/web/20100808083358/http://elitistjerks.com/f72/t61176-blood_simple_day_music_died/p54/

"Autoattacks seem to work fine, but its main damage source, Heart Strike, doesn't scale at all. Look closely at your logs, or go to the dummy and test in Frost Presence, Blood Presence and Blood Presence with Hysteria up."

"In the WOL you linked autoattack is close to 70% of the DRW's total damage. Furthermore, the average crit is showing at almost 9k - the max crit would be even higher. Another thing to consider is that in most cases the first DRW you cast will be with the most procs up at the same time - things like the Ashen Verdict ring, and DBW throw proc alignment out of whack because of their strange ICD's (i.e. not 45 seconds like most trinkets).

It's pretty clear that DRW is gaining some benefit during the BQL encounter - there is no other explanation for 12k DRW crits when the norm for top of the line ICC gear is 7 to 8k max."

"@Decaying:
Autoattacks are the main source of DRW-damage because the Strikes do not scale correctly.
If these scaled correctly, i would expect at least a 50% increase in DRW-DPS."

"Additionally, I don't think it's terribly surprising that DRW's strikes don't seem to scale with the ICC buff since they don't scale with many of our talents either (DRW's Oblits will eat it's own diseases even if you have Annihilation, for example). Something about the ability is coded weird, but this isn't new and doesn't stop it from being a valuable talent."

**Comment by danniellos94** [comment]
Dear Blizzard,
I'm writing again to you to make you consider fixing the dancing rune weapon.
Dancing rune weapon was kinda bugged in wotlk like gargoyle (that got fixed btw).
To prove this I'm sending this two videos. 
Please don't ignore this, I'm myself a casual player like many others and we as community shouldn't only make fixes for meta specs.
This is me getting big damage buff while doing battle for undercity quest, as you can see only autoattacks are increased.
https://www.youtube.com/watch?v=vgMIv5nYcF8 (600% damage buff + my own buffs)
This is a video from cata from retail when pet stat system got rewritten and drw was fixed :
https://www.youtube.com/watch?v=_WYB0uK2ims
As you can see the guy is hitting xt heart and his strikes are doing about 50% reduced damage.
As last ticket I got an answer that my last report will be checked and considered, however I didn't get any answer or possible timeline for decision.

**Comment by MghTG** [comment]
I mean, things working the way they don't on retail is what should be considered as a bug, no?
Gargoyle is actually so damn broken without 1s gcd cap, it is ridiculous, and that should be fixed.
DRW never did the damage you want it to do. Btw, when "fixing" things, they should consider pvp aswell.
"Do you guys remember original behind the scenes video saying that one of our goal is to death knight not having a tanking tree in wrath?"
Well, you have solid tanking talents on all trees, just like he said. You can easily tank as a frost for example. And I'm pretty sure you can make blood dps viable, though you shouldn't be speccing it if you have no unholy on your raid lmao.
Finally, to think that they should balance classes to get an even dps all around is just silly.

**Comment by MHMabrito** [comment]
You don't see DPS warriors deep into Prot, or DPS Paladins deep into Prot - Why would Blood be any different? You're linking videos from Cata, this is WOTLK.

**Comment by danniellos94** [comment]
So the reasoning of fixing this is actually the thing how it should work, the same as gargoyle. If gargoyle got fixed drw should got the same treatment if we don't want fixing anything revert gargoyle changes, be fair to other specs. I'm not talking about balances changes I'm talking about a thing that should be considered as a bug.

**Comment by MghTG** [comment]
"So the reasoning of fixing this is actually the thing how it should work, the same as gargoyle. If gargoyle got fixed drw should got the same treatment if we don't want fixing anything revert gargoyle changes, be fair to other specs."
And why would you think it got "fixed". Don't be naive... Gargoyle is just bugged since launch lmao.

**Comment by Bakurersu** [comment]
> Gargoyle is actually so damn broken without 1s gcd cap, it is ridiculous, and that should be fixed. 

> And why would you think it got "fixed". Don't be naive... Gargoyle is just bugged since launch lmao.


Gargoyle never had a 1 second GCD cap in retail, which was proven multiple times in blight club using logs posted in old EJ forum threads during the wrath classic beta, the 1 second GCD cap for gargoyle was only ever present on private servers. The only current bug with gargoyle is it's spawning positioning (which was correct during beta and changed when pre-patch hit for some reason). The "fix" that gargoyle got was a fix to the wind serpent pet AI as it did not work the way it was supposed to in retail wrath (having random pauses between casts sometimes), which is in line with other "fixes" applied to other classes. If you think gargoyle is actually bugged (other than the already reported positioning bug) I'd suggest making a issue for it with actual evidence to back up your claims.

**Comment by danniellos94** [comment]
Gargoyle is fixed (I'm actually playing unholy) overall he is doing 1 autoatack that don't break first cast and then casts only gargoyle strike plus it does not have any delay.  Waiting for any answer for rune weapon.
