### ISSUE TITLE
[BUG] Backdraft not lowering the GCD

### ISSUE THREAD

**Issue by Zephancode** [JamminL/wotlk-classic-bugs#396]
#### 1.2. How to Reproduce
           1. Talent into Backdraft
           2. Use Conflagrate to proc Backdraft
           3. Shaman uses Heroism
           4. Cast Immolate (1.5/1.3/1.3= 0.888... seconds cast and GCD)
  #### 1.3  Source Material
[Destruction log from prepatch](https://classic.warcraftlogs.com/reports/WtJ4GxpKTkFADyjn#fight=14&type=casts&source=38&view=timeline)
- 5s
- 15s
- 35s

Backdraft is active at these times along with Bloodlust and partially Haste potion (along with the player's gear) this puts them below 1 second cast times for incinerate.
#### 2.1. Description
Backdraft is triggered when you cast Conflagrate. It should lower the cast time AND the global cooldown by 30% for the next 15 seconds or three destruction casts. This includes going below the 1-second Global Cooldown minimum as we can see from the VOD provided (why else lower the GCD in the tooltip mention).

  #### 2.2 Source Material

In the following video you can clearly see cast time (thanks quartz) and the GCD bar right below (as well as on the button bars).
- [Jun 22, 2010](https://www.youtube.com/watch?v=3MX2mDaIrik)
- 0:47 - 0.9s cast/GCD
- 0:48 - 0.8s cast/GCD
- 4:18 - 0.9s cast/GCD
- 4:24 - 0.9s cast/GCD

**Comment by Cleavis** [comment]
just to clarify, there is a 1.0s minimum cap on GCD in wrath. casted spells can have a shorter cast time but should still trigger the minimum gcd if their cast time is below the minimum.

this is intended https://web.archive.org/web/20101108010644/http://elitistjerks.com/f47/t15393-global_cooldown/

this video's quartz display has quite a lot of latency on the front end of each cast unfortunately.

can watch the gcd more precisely going frame by frame and watching the swipes on his bartender bars:
http://www.watchframebyframe.com/watch/yt/3MX2mDaIrik
at 0.47.33 player starts 0.8s immolate. at 0.48.31, there is still swipe left on the bartender icons. swipe finishes at 0.48.33.
at 4.17.77 player starts 0.9s immolate. at 4.18.63 there is still swipe left on the frame. swipe finishes at 4.18.77
at 4.23.80 player starts 0.9s immolate. at 4.24.87 there is still swipe left on the frame. swipe finishes at 4.24.89 and their next (chain-)cast starts at 4.25.12

can add more references if I'm missing something, but fairly confident this is NAB.

**Comment by Zephancode** [comment]
Whilst there indeed is a 1 second GCD minimum the tooltip states lowering the GCD specifically. 

Other articles such as https://www.mmo-champion.com/threads/749321-Warlock-Haste-question/page2 also hint at that with the following:

`In other words, it used to just give you 30% reduction, applied in the same way as bloodlust (ie, multiply by 1/1.30) . If your GCD without backdraft was 1.2 sec, it used to just multiply that, giving you a 0.92 sec cast on immolate, but leaving the GCD at the 1 sec hard cap.

Now, it actually reduced the GCD too, meaning your GCD can go below the usual hard cap. That is to say, a new minimum GCD of 1/1.30 = 0.77 seconds with backdraft.
Now, for backdraft you simply multiply your normal hasted GCD (still with the 1 sec "hard" cap) by ~0.77.
So, if you have excactly 50% haste = 1 sec base GCD, your backdraft GCD will be 0.77 sec. If you have over 50% haste, your base GCD will still remain 1 second (though your immolate cast time will be shorter), and your backdrafted GCD still 0.77 second (and your backdrafted immolate cast time even shorter).

Kinda hard to explain, but hope you get the gist of it.


If you've played a destro lock with a decent amount of haste (20% or so) pre-3.0.8, you would have noticed this when under bloodlust. This would give you a base cast of 1.19 seconds on Immo, giving you a backdrafted cast of 0.92 seconds, meaning for 0.08 seconds after an immolate, you are under the GCD. When chaining spells (by this i mean, if you try to cast a new spell in the last ~10% of the cast of the previous spell, it will auto-cast the new spell after the previous finishes), you would get a "this spell is not ready yet" error, kinda messing up your flow, and underutilizing your haste. And due to the new glyph of conflag, you will rarely cast immolate backdrafted, diminishing the problem with bloodlust+20% haste (a base cast that's lower than base GCD).

The consequence of this new way backdraft affects the GCD, is obviously that deep destro locks will enjoy haste a lot more. Not only has it always scaled better than crit when fully raidbuffed (ie, ~20% base+5% devastation+5% boomkin+3% wrath+10% imp scorch+8% 2-piece t7 setbonus average+7% Empowered Imp average ~= 58% crit average), but it no longer has that annoying "clipping" when using backdrafted immolate.

_Zexion `

Trying to find that specific EJ topic, but sadly it wasn't linked. I can search for a more clear VOD as well tomorrow. There are also ppl saying they recall this from wayback, but memory is always hazzy and not a real credible source. 

I have some more time tomorrow to dedicate to this.

**Comment by Zephancode** [comment]
http://www.watchframebyframe.com/watch/yt/FCbKGdPCbyE

Here is another example at 3:05 a Chaos Bolt is casted for 0.8s and a incinerate following it at 0.9s without a cast gap in between. You can see the incinerate cast animation already starting before the chaos bolt leaves the hand.

http://www.watchframebyframe.com/watch/yt/PJYX20MjuZE at 1:02
Also here we see a chaosbolt being casted at 0.859 (in the tooltip) and incinerate being started casting at the moment the chaosbolt animation stops (the bar is 1/4 of the way for incinerate by the time the chaos bolt cast bar fades from completion.

**Comment by Cleavis** [comment]
First video (http://www.watchframebyframe.com/watch/yt/FCbKGdPCbyE) I see the following:
3:05.43 start conflag 3:06.43 finish gcd swipe
3:06.47 start chaos bolt 3:07.47 finish gcd swipe
3:07.55 start incinerate 3:08.55 finish gcd swipe

looks exactly 1.0s

Second video (http://www.watchframebyframe.com/watch/yt/PJYX20MjuZE) is hard to tell what the speed of the recording is at but there are missing frames. I put it somewhere more than 2x speed. For example at 0:31.89 he casts a "1.2s" feuerbrand (immolate) that finishes roughly 0:32.46 = 0.57 seconds. 1.2 / 0.57 = 2.1x time? But then at 1:21.55 he starts a "1.6s" chaosbliz that finishes 1:22.22 = 0.67 seconds. 1.6 / 0.67 = 2.4x time? Have to guess the compression.

1:02.57 start chaosblitz (chaos bolt) 1:03.00 finish gcd swipe (0.43s)
1:03.19 start verbrennen (incinerate) 1:03.63 finish gcd swipe (0.44s)

His minimum GCDs look to be roughly 0.43 seconds or 0.44 seconds in video-time. That could be 1.0s with a 2.3x speed.


Further reference-
EJ thread with some backdraft conversation
https://web.archive.org/web/20090211051047/http://elitistjerks.com/f80/t36783-warlock_simple_questions_simple_answers/p30/

![image](https://user-images.githubusercontent.com/19498073/188889625-5d30e6cf-f753-4161-8a3d-3e755f991d48.png)

**Comment by Zephancode** [comment]
I stand correct, I could swear the first vid was under 1 second but I must have been miss looking, and the second vid indeed is sped up. 

Thanks for carefully going through this and the watchframebyframe tool is quite cool.
