### ISSUE TITLE
[BUG] "You're Infected" Debuff From WOLK Scourge Invasion Removes Chronobooned World Buffs

### ISSUE THREAD

**Issue by tacocat777** [JamminL/wotlk-classic-bugs#398]
#### 1.2. How to Reproduce
           1. Get the "You're Infected" debuff from a box in Booty Bay
           2. Hearth to a major city (Orgimmar) and find somebody with Chronobooned buffs
           3. Wait for 10 minutes on top of them
           4. Press the Zombie abilities to infect nearby players
           5. Wait 10 minutes for the AFK and newly infected Zombies to die
           6. They we're afk healing ZA and lost all their world buffs
  #### 1.3  Source Material
![1](https://cdn.discordapp.com/attachments/610924538477150239/1017286189306363994/buffs.png)
![2](https://cdn.discordapp.com/attachments/610924538477150239/1017289155530735646/cleg.png)

**Comment by samsullivent** [comment]
Moving the displacer item from bank to inventory or vice versa does not re-apply the bottled buffs.  It should be impossible to remove the bottled buffs from your character (e.g.right clicking it from the buff pane, zoning into raid/arena, death, server transfer etc).  Also, on a side note, the haunted memento buff gets removed when turning into zombie, but you can re-apply the memento buff by moving the item from bank to bags.

The supercharged chronoboon displacer should re-apply the bottled buffs to character buff panel.

**Comment by watchyoursixx** [comment]
closing as the scourge event is over for a few months now and unable to verify if fixed
