### ISSUE TITLE
[BUG] Track Humanoids

### ISSUE THREAD

**Issue by Selybe** [JamminL/wotlk-classic-bugs#399]
#### 1.1. Description
Currently Track Humanoids is overwriting any and all tracking currently active at the time of entering Cat Form even if that is not your previously selected form of tracking. In the event that you were previously tracking Herbs/Minerals/Fish, your original tracking is not even reinstated upon leaving form; regular tracking such as mailboxes are, however. Supposedly, Druids who haven't even trained Track Humanoids are also subject to this issue, but I cannot corroborate personally.
  #### 1.2. How to Reproduce
  1. Manually select a non-humanoid form of tracking in Cat Form.
  2. Leave and re-enter Cat Form.
  3.  Be forcibly set back to Track Humanoids. 
  #### 1.3  Source Material
N/A.
### 2. Expected Behavior
  Track Humanoids should only be automatically active on entering Cat Form if you have previously selected it to be. If you manually select another form of tracking, it should not forcibly overwrite it. 
  #### 2.2 Source Material
You can see in this video that at 6 minutes and 12 seconds, they enter Cat Form from caster and their Track Herbs is not forcibly overwritten. (https://youtu.be/JYTqvFarc5o?t=370)

**Comment by watchyoursixx** [comment]
This is reportedly fixed with a recent hotfix. Can you test and confirm?

**Comment by Selybe** [comment]
Apologies for the belated response. Yes, it does now appear to be fixed!
