### ISSUE TITLE
[BUG] Overpower Glyph - Warrior

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#40]
#### 1.1. Description
Overpower Glyph doesn't work
  #### 1.2. How to Reproduce
           1. Get Overpower Glyph
           2. Attack someone and wait for a parry
           3. Try to press Overpower
  #### 1.3  Source Material
Nothing yet
#### 2.1. Description
Should be able to overpower after a parry with the glyph
  #### 2.2 Source Material
Nothing yet

**Comment by JamminL** [comment]
Fixed

**Comment by JamminL** [comment]
Apparently not :(

**Comment by CharWS** [comment]
Fixed as of build 44930
