### ISSUE TITLE
[BUG] [Core] [Spell] [Priest] Dispersion does not always provide snare immunity

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#400]
### 1. Current Behavior

https://www.wowhead.com/wotlk/spell=47585/dispersion

Dispersion currently doesnt always provide full snare (movement slows) immunity. If you get 2 slows and you apply Dispersion, then Dispersion will not take effect when any positive buff ends. 

https://www.youtube.com/watch?v=oI840BY_R_o

https://clips.twitch.tv/SmellyGlutenFreeShingleSpicyBoy-7IF5Xw4GFLKu3nXw

  #### 1.2. How to Reproduce
  
           1.  Get slowed by 2 slows (cone of cold and frostfirebolt for example)
           2. Cast Dispersion
           3. Dispel any helpful buff (renew for example)
           4. Notice how you get slowed

  Example:
 https://www.youtube.com/watch?v=oI840BY_R_o

### 2. Expected Behavior

Dispersion should always provide full snare immunity during its duration.

**Comment by Evolvee** [comment]
Confirmed, just happened again 12. 11. 2022 on live server against a  frost mage.

**Comment by Evolvee** [comment]
https://clips.twitch.tv/SmellyGlutenFreeShingleSpicyBoy-7IF5Xw4GFLKu3nXw

finally managed to record it - this is like 4th time it happened to me, always against frost mages

**Comment by Miyur1** [comment]
So, I have never seen such strange interactions. If you get 2 slows and you apply Dispersion, then Dispersion will not take effect when any positive buff ends. On your clip, for example, at this moment the Shadow Weaving buff ended
https://www.youtube.com/watch?v=oI840BY_R_o

**Comment by Evolvee** [comment]
> So, I have never seen such strange interactions. If you get 2 slows and you apply Dispersion, then Dispersion will not take effect when any positive buff ends. On your clip, for example, at this moment the Shadow Weaving buff ended
> https://www.youtube.com/watch?v=oI840BY_R_o
> 

Ok, now this is even worse than I though before.

**Comment by Evolvee** [comment]
@JamminL

this is still bugged, i have like 5 clips of this bug still happening in the past 2 days, if necessary

**Comment by JamminL** [comment]
> @JamminL
> 
> this is still bugged, i have like 5 clips of this bug still happening in the past 2 days, if necessary

Think it was only fixed on PTR

**Comment by Evolvee** [comment]
> > @JamminL
> > this is still bugged, i have like 5 clips of this bug still happening in the past 2 days, if necessary
> 
> Think it was only fixed on PTR

Its still bugged on live patch 3.4.1.
Reopen.

**Comment by Evolvee** [comment]
I am still getting slowed in dispersion as of 28/4/2023 (yes, 7 months after the release and more than half-way throught the entire expansion)

**Comment by Evolvee** [comment]
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/1942409/92ed368d-35c3-472d-9b94-a053a907bfef)

**Comment by Evolvee** [comment]
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/1942409/38e83fda-1c11-4195-98fa-f3a2cdd15b7d)

**Comment by Evolvee** [comment]
https://clips.twitch.tv/JoyousUglyCourgetteTooSpicy-f35FxyKmIAiVyD-2

hello?

**Comment by Evolvee** [comment]
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/1942409/deaaf7cf-3899-4af0-bb90-7b33620629b2)
