### ISSUE TITLE
[BUG] Destruction Talent 'Backdraft' being consumed by instant destruction spells

### ISSUE THREAD

**Issue by dreschnuutest** [JamminL/wotlk-classic-bugs#408]
#### 1.1. Description
After using Conflagrate you get 3 stacks of Backdraft. When using a instant destruction spell a stack gets consumed.
 

 #### 1.2. How to Reproduce
           1. Cast Conflagrate
           2. cast other instant destruction spells such as Shadowflame, Shadowfury, Shadowburn
  

 #### 1.3  Source Material
https://streamable.com/gpihd9 

#### 2.1. Description
After getting the 'Backdraft' buff and then cast instant destro spells such as Shadowflame, Shadowfury, Shadowburn the 'Backdraft' stacks should NOT be consumed. 
  #### 2.2 Source Material
- https://youtu.be/8WoL3rsvgFg?t=325   - way to prove this is live is he is mouseovering the boomkin and it reads 'name-Echsenkessel' which is a german retail server, also he has https://www.wowhead.com/item=50357/maghias-misguided-quill in his bars which got added in Patch 3.3.0.10805 + he is wearing S8 gear.
- https://youtu.be/8WoL3rsvgFg?t=172     - different timestamp
- https://youtu.be/yq3N1fP3a24?t=173
- https://gfycat.com/daringvaluablegroundhog

**Comment by JamminL** [comment]
**PATCH 4.0.1**
https://youtu.be/WWk5EMn4J3g?t=183 4.0.1 sfury
https://youtu.be/WWk5EMn4J3g?t=382 4.0.1 shadowburn

**PATCH 3.3.5a**
https://youtu.be/IQYrH72-oXI?t=676 - Shadowfury
https://youtu.be/IQYrH72-oXI?t=565 - Shadowburn
https://www.youtube.com/watch?v=8WoL3rsvgFg&t=172s - Shadowfury (miss)
https://youtu.be/8WoL3rsvgFg?t=327 - Shadowfury
https://youtu.be/8WoL3rsvgFg?t=331 - Shadowflame

~ **PATCH 3.3.5 but 100% < 3.3.5a** 
https://youtu.be/IQYrH72-oXI?t=513  - Shadowflame
https://youtu.be/IQYrH72-oXI?t=519  - Shadowfury

~ **PATCH 3.2**
https://youtu.be/yq3N1fP3a24?t=174 - Shadowflame

~ **Patch 3.1.0**
https://youtu.be/JVJqsqK7o-w?t=491 - Shadowfury
https://youtu.be/JVJqsqK7o-w?t=525 - Shadowfury

~ **WOTLK prepatch**
https://www.youtube.com/watch?v=KZdkbeujPPM&t=36s Shadowfury

**Comment by Aggrend** [comment]
We've reverted part of a previous bug fix we put in that made instants consume backdraft bug also benefit from the GCD reduction. On next PTR build (ETA 12/1-ish) you should see that these spells no longer consume backdraft but are also no longer seeing a GCD reduction after being used.
