### ISSUE TITLE
[BUG] Protection warrior Warbringer talent does not break you out of roots as intended

### ISSUE THREAD

**Issue by fixmyclasspls1** [JamminL/wotlk-classic-bugs#410]
#### 1.1. Description
 Prot warrior talent warbringer does not break roots
  #### 1.2. How to Reproduce
           1. Be prot warrior
           2. Get rooted by anything 
           3. Try to intervene a friendly party member in group
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
Protection warriors with the talent warbringer is supposed to be able to use intervene to break out of roots, currently you only get error saying "unable to move"
  #### 2.2 Source Material
{Video, Posts, etc..}
Here is video evidence of Warbringer talent being broken and not breaking roots

https://www.youtube.com/watch?v=6b8afPDxJtc

as you can see in the clip the hunter is rooting me and im attempting to intervene a friendly target but only get "unable to move" error on my screen.

**Comment by Tharre** [comment]
> Fixed an issue with Warrior’s Warbringer talent which prevented Intervene from breaking root effects.
Should be fixed per the official patch notes.
