### ISSUE TITLE
[BUG] Engineering Grenade(s) - Adamantite Grenade & Likely the rest (Iron, Thorium, Saronite etc)

### ISSUE THREAD

**Issue by wayno1337** [JamminL/wotlk-classic-bugs#415]
1. Current Behavior
1.1. Description
Adamantite Grenade does not do the incapacitate effect even though the tooltip still states it should. Against players or mobs.

1.2. How to Reproduce
       1. Use/throw a grenade at a player or mob/NPC
       2. Wonder why the incap wont happen
       3. Also wonder why you dumped gold/time into levelling Engineering again to discover nades may be bugged/silent nerfed? xD
       4. Observe the tooltip to confirm you are not crazy
       
1.3 Source Material
https://preview.redd.it/7q5q7j8j81o91.png?width=375&format=png&auto=webp&s=420a4bdd45c326a738375a7e65ecdf0f7ac365ff
https://www.wowhead.com/wotlk/item=23737/adamantite-grenade
![Capture](https://user-images.githubusercontent.com/113652757/190542581-a368744e-d267-417e-bd42-4b38d4d92045.JPG)

2. Expected Behavior
An incapacitate effect

**Comment by watchyoursixx** [comment]
hotfixed recently
