### ISSUE TITLE
[BUG] VANISH can be dispelled

### ISSUE THREAD

**Issue by simmanheh** [JamminL/wotlk-classic-bugs#417]
### 1. VANISH bugged
   1.1. The Vanish "buff" is showing on target for about 0.5s/500 ms before target disappears

  #### 1.2. How to Reproduce
           1. Purge class (e.g. priest/shaman) can have a Weak Aura showing the"Vanish buff" 
           2. Target the rogue who vanishes (needs to have a dispellable buff)
           3. When Weak Aura Glows - the purger/dispeller presses his button and vanish will break
  #### 1.3  Me and my friend tested it with a simple weak aura: 
(https://www.youtube.com/watch?v=zvYB_mstLRs)
#### 2.2 Source Material
https://www.youtube.com/watch?v=zvYB_mstLRs

**Comment by simmanheh** [comment]
Is this intended?

**Comment by JamminL** [comment]
Unfortunately NAB, I can't speak much to whether it was intended back then or not.

And to clarify, it has nothing to do with vanish being dispellable or the dispel itself. There's a delay between vanish and invisibility which we tend to call visibility delay, back in 3.3.5a this delay is still considerably big and if any spell hits the rogue during this delay then the vanish will break (or it did back then)

The current beta vanish version we have is a bit sturdier when it comes to that (which is not true to reference) but the actual behavior described with dispel, as an example is the same as back then.

If you have video clips from 3.3.5a that disprove this I'll reopen it though

**Comment by JamminL** [comment]
To give a more obvious example, this is how on wotlk you could "blind a vanish" or "sap a vanish"

**Comment by simmanheh** [comment]
I see, thanks for the reply. 

I feel like this has to do with how batching works now compared to then. For example, you said sap blind/vanish - that is not working in the same manner anymore as 3.3.5a did. This has been tested by rogues ever since batching changed back in TBC pre-patch. 

I don't have any proof of how this worked back in original 3.3.5a, _but I can research in it._ 

Thanks again for input, I just have the feeling Vanish isn't working as intended.

**Comment by JamminL** [comment]
When we're talking about "blinding a vanish" (not vanishing a blind) then it's less about batching and more about that visibility delay. You're right it's not working exactly like it was back then, but what you described is one of the things that is in fact working like it did back then.

Not making judgments on whether it's good or bad, personally I have a feeling that amount of visibility delay is not good for today's standards (I mentioned it here #124)

**Comment by simmanheh** [comment]
I did some more research from Warmane and the major difference is that in Warmane client you will lose the target almost instantly. On Wrath Classic you will keep the vanished target as a target until he is gone. On Warmane you can still see the character but you lose target. 

Reference video: https://www.youtube.com/watch?v=D4KfKjoUjfk

**Comment by simmanheh** [comment]
But I kinda agree with you in the post you did about Visibility Update Delay - but I think you should lose target on a vanished character faster than it is right now. I guess this have turned to a opinion more than a bug then - but I had to report this incase it wasn't researched. But it seems you have done some research on it and I appreciate that. Thanks Jammin!

> When we're talking about "blinding a vanish" (not vanishing a blind) then it's less about batching and more about that visibility delay. You're right it's not working exactly like it was back then, but what you described is one of the things that is in fact working like it did back then.
> 
> Not making judgments on whether it's good or bad, personally I have a feeling that amount of visibility delay is not good for today's standards (I mentioned it here #124)

**Comment by JamminL** [comment]
> I did some more research from Warmane and the major difference is that in Warmane client you will lose the target almost instantly. On Wrath Classic you will keep the vanished target as a target until he is gone. On Warmane you can still see the character but you lose target.
> 
> Reference video: https://www.youtube.com/watch?v=D4KfKjoUjfk

Linking private server videos have no merit, you can look at any original 3.3.5a videos to see the huge visibility delay

**Comment by simmanheh** [comment]
> > I did some more research from Warmane and the major difference is that in Warmane client you will lose the target almost instantly. On Wrath Classic you will keep the vanished target as a target until he is gone. On Warmane you can still see the character but you lose target.
> > Reference video: https://www.youtube.com/watch?v=D4KfKjoUjfk
> 
> Linking private server videos have no merit, you can look at any original 3.3.5a videos to see the huge visibility delay

Okay! Thanks.

One more question: Why does only certain spells break Vanish then? Like you can purge the target, auto attack, but you cannot SW:P it? Is there a specific explanation for this behaviour?

**Comment by Evolvee** [comment]
I find this particular "bug" very funny. On one hand, they made the vanish to be break-able, on the other hand, they hackfixed regular stealth not to be breakable by putting an artifical "INVALID TARGET" error message whenever you try to cast/hit someone who is in process of stealthing... You can literally see the target player but you cannot cast anything (invalid target).

So at the end of the day, if you are INTENTIONALLY trying to break someones stealth, you cant. If you are just hanging around, spaming useless globals, you get to dispel someones vanish.

Good design much?

**Comment by perpabc** [comment]
"So at the end of the day, if you are INTENTIONALLY trying to break someones stealth, you cant. If you are just hanging around, spaming useless globals, you get to dispel someones vanish."

This is the most frustrating part of this bug, and the whole Invalid Target bug that's existed now for a few years. Other bugs are getting fixed, yet this one remains, would be fantastic if we could get an update on why this is, because it's such a vital part of the classes kit, and the counterplay of it.

**Comment by simmanheh** [comment]
> would be fantastic if we could get an update on why this is, because it's such a vital part of the classes kit, and the counterplay of it.

Yes indeed - this was my point of it all. Thx Perp.

**Comment by Evolvee** [comment]
The "fun" part is that it was hackfixed in. It didnt behave like this at the beggining of tbc classic. They had to change something in order to introduce this, its not like it was a bug from the very beggining.

_If I had to guess they just tried to eliminate getting auto-attacked inside the fade-out-delay (because they couldnt fully eliminate the object delay due to it having consequences not only in PVP but also in the outside world), but the implementation turned out to be botched._

**Comment by simmanheh** [comment]
@JamminL @perpabc @Evolvee here is a comparison from Neilyo vs Akrios from original Pre-Patch. Just a frame by frame comparison to see how it behaved.

https://www.youtube.com/watch?v=48KEiMgU_rQ

**Comment by simmanheh** [comment]
> @JamminL @perpabc @Evolvee here is a comparison from Neilyo vs Akrios from original Pre-Patch. Just a frame by frame comparison to see how it behaved.
> 
> https://www.youtube.com/watch?v=48KEiMgU_rQ

So in this comparison the stealth/vanish delay timer is almost 2/3 longer in Classic than it was in the original game.

**Comment by Evolvee** [comment]
It depends on when its casted. 

The object delay (a delay between the moment an object is created in the world and the moment it becomes visible to the player) ticks every 400ms. This could be verified from plethora of other mechanics or even from sniffs - in Black Morass, the black crystals that are floating around Medivh are appearing exactly in intervals of around 400ms...coincidence? I think not.

So when the vanish gets executed at the end of the object delay batch, it obviously looks way faster compared to when its executed right at the start of the batch. The issue with classic is that they reduced the duration of certain spell delay batches from 400ms to 10ms but left other types of batches unchanged _(there are multiple types, for example spell proc batch or a batch that delays the buff/debuff visibility on player - e.g. if you get cone of colded, you should take dmg instantly, cone debuff in delay and winters chill in double delay)_. The object delay/visibility delay seems to not be impacted by that change. So what happens is that you will encounter way more random vanish/restealth behaviors than you could on retail since currently there is nothing that stops you from casting spells in random parts of the object delay.

**Comment by simmanheh** [comment]
> It depends on when its casted.
> 
> The object delay (a delay between the moment an object is created in the world and the moment it becomes visible to the player) ticks every 400ms. This could be verified from plethora of other mechanics or even from sniffs - in Black Morass, the black crystals that are floating around Medivh are appearing exactly in intervals of around 400ms...coincidence? I think not.
> 
> So when the vanish gets executed at the end of the object delay batch, it obviously looks way faster compared to when its executed right at the start of the batch. The issue with classic is that they reduced the duration of certain spell delay batches from 400ms to 10ms but left other types of batches unchanged _(there are multiple types, for example spell proc batch or a batch that delays the buff/debuff visibility on player - e.g. if you get cone of colded, you should take dmg instantly, cone debuff in delay and winters chill in double delay)_. The object delay/visibility delay seems to not be impacted by that change. So what happens is that you will encounter way more random vanish/restealth behaviors than you could on retail since currently there is nothing that stops you from casting spells in random parts of the object delay.
> 
> _Btw, the spell delay implementation on classic has close to nothing in common with the actual retail spell delay, its rly hard and pointless to even compare those 2 systems. Just like the spell queue system that became a completely client-sided thing compared to the old retail version that allowed to bypass the GCD server-side as well as client-side... Classic is more like "Reforged" when it comes to emulation of retail behavior._

Thanks for the reply. Even if all of this isn't confirmed it makes a lot of sense. So if you wanna be practical about the immune bug you gotta wait at least 400 ms before you Cone of Cold a Vanished rogue to get both damage and the slow debuff on him.

**Comment by JamminL** [comment]
> It depends on when its casted.
> 
> The object delay (a delay between the moment an object is created in the world and the moment it becomes visible to the player) ticks every 400ms. This could be verified from plethora of other mechanics or even from sniffs - in Black Morass, the black crystals that are floating around Medivh are appearing exactly in intervals of around 400ms...coincidence? I think not.
> 
> So when the vanish gets executed at the end of the object delay batch, it obviously looks way faster compared to when its executed right at the start of the batch. The issue with classic is that they reduced the duration of certain spell delay batches from 400ms to 10ms but left other types of batches unchanged _(there are multiple types, for example spell proc batch or a batch that delays the buff/debuff visibility on player - e.g. if you get cone of colded, you should take dmg instantly, cone debuff in delay and winters chill in double delay)_. The object delay/visibility delay seems to not be impacted by that change. So what happens is that you will encounter way more random vanish/restealth behaviors than you could on retail since currently there is nothing that stops you from casting spells in random parts of the object delay.
> 
> _Btw, the spell delay implementation on classic has close to nothing in common with the actual retail spell delay, its rly hard and pointless to even compare those 2 systems. Just like the spell queue system that became a completely client-sided thing compared to the old retail version that allowed to bypass the GCD server-side as well as client-side... Classic is more like "Reforged" when it comes to emulation of retail behavior._

So this is not necessarily true, evidence suggests it can be a lot longer than 400ms, but it is batched yes, so you'll get different timings in different vanishes/restealths.




> Thanks for the reply. Even if all of this isn't confirmed it makes a lot of sense. So if you wanna be practical about the immune bug you gotta wait at least 400 ms before you Cone of Cold a Vanished rogue to get both damage and the slow debuff on him.


Vanish provides a 1 second immunity window to snare/root effects. So you'd have to wait a second after vanish to actually slow the rogue.
