### ISSUE TITLE
[BUG] Overkill refreshes when exiting stealth even when you don't have the talent

### ISSUE THREAD

**Issue by simonizeshow** [JamminL/wotlk-classic-bugs#418]
#### 1.1. Description
If a rogue takes a talent spec where they have Overkill talent, stealths, then uses dual talent specialization to swap to a spec without Overkill talent, they preserve the buff from Overkill and even in the new spec, exiting stealth will refresh the duration of Overkill buff if it is done before the initial buff from before the spec swap fades. Overkill buff still provides energy generation post-spec swap.
  #### 1.2. How to Reproduce
           1. Get rogue with dual talent spec, one spec with Overkill, one without Overkill talent.
           2. Take the overkill talent. Stealth. Activate dual spec. Enter stealth, then exit stealth before Overkill buff has faded.
           3. Observe that the overkill buff duration is refreshed upon exiting stealth.
  #### 1.3  Source Material
https://imgur.com/a/Fa1yndW
this image shows that i can refresh overkill without actually having overkill talent. first "stealth fades" in the combat log is when i exit stealth with overkill talent to activate dual spec. overkill is refreshed many times and you can see it finally fading over 1 minute later because i just entered and exited stealth a bunch of times.

#### 2.1. Description
Overkill should not refresh when leaving stealth when you don't have the talent.
  #### 2.2 Source Material
I don't have source material for this - it just seems obvious that overkill should not refresh upon exiting stealth if you don't have the overkill talent.

FIX:
Dual spec swap should probably remove any existing Overkill buff. There are two spell IDs for Overkill, maybe the problem is related to that.

**Comment by watchyoursixx** [comment]
hotfixed 10/20/22
