### ISSUE TITLE
[BUG] SpellGetVisibilityInfo data wrong/incomplete

### ISSUE THREAD

**Issue by XyzKangUI** [JamminL/wotlk-classic-bugs#419]
#### 1.1. Description
 Normally most buffs on the compact unit raid frames should hide in combat if hasCustom returns true from this API: SpellGetVisibilityInfo. 
  
For example; Power Word Fortitude returns false on Rank 7 and 8, while it returns true on the ranks 1-6. Also the latest ranks 7 and 8 have an incomplete table, not containing any information about 'alwaysShowMine' and  'showForMySpec'.

I only used power word fortitude as an example here, but the issue most likely exists with all the friendly buffs like prayer of spirit, blessing of kings and so forth.
  #### 1.2. How to Reproduce
 What can I say..? See 1.3.
  #### 1.3  Source Material
/dump SpellGetVisibilityInfo(spellId, "RAID_INCOMBAT" or "RAID_OUTOFCOMBAT")
#### 2.1. Description
- New spells (read: including added ranks) have to be added to the SpellAuraVisibility db
- Every spell with a buff or debuff should return 3 boolean values.

  #### 2.2 Source Material
Obviously there is no proper source for this that references to 3.3.5, because Compact Raid UnitFrames got introduced in Cataclysm. Blizzard decided to let this stay in the game with the relaunch of Classic in 2019. 

The SpellAuraVisibility db seems identical on 3.4.x to 2.4.x, meaning it hasnt been updated for all new added spells. 

Sources: 
- https://wowdev.wiki/DB/SpellAuraVisibility
- https://github.com/Ketho/wow-ui-source-wrath/blob/3eaa29bfc00a05362e4cf30921a5c0792fc47519/Interface_Wrath/FrameXML/CompactUnitFrame.lua#L1018
- https://wow.tools/dbc/?dbc=spellauravisibility&build=2.5.4.44833#page=1
- https://wow.tools/dbc/?dbc=spellauravisibility&build=3.4.0.45613#page=1

**Comment by Loregon** [comment]
Couple of days ago, they fixed some of the most basic class buffs, but not all.

**Comment by XyzKangUI** [comment]
> Couple of days ago, they fixed some of the most basic class buffs, but not all.

I dont know what they fixed. When I tried it out it never showed for all pre wotlk spells like rank 1-6 stamina. Also the database has nothing new added to it. Maybe some flags got changed of existing spells at best.

**Comment by XyzKangUI** [comment]
https://wow.tools/dbc/?dbc=spellauravisibility&build=3.4.0.46269#page=1

**Comment by Loregon** [comment]
The thorns of the last level were never repaired. Although the level below is fine. ID 53307
