### ISSUE TITLE
[BUG] Hunter pet level after taming

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#42]
*Issue submitted automatically through Google Forms by: Homerjay*<br/> 
 ### 1. Current Behavior <br/> 
 #### 1.1. Description <br/> 
The pet stays the level it was at when tamed.<br/> 
 #### 1.2. How to Reproduce <br/> 
  Tame a pet that is more than 5 levels below u and u will see :3 <br/>
 #### 1.3  Source Material <br/> 
 https://imgur.com/a/EDgy2lR<br/> 
 ### 2. Expected Behavior<br/> 
  #### 2.1. Description <br/> 
It should be 5 levels below the hunter's level.<br/> 
 #### 2.2 Source Material <br/> 
https://wowpedia.fandom.com/wiki/Patch_3.0.2

**Comment by watchyoursixx** [comment]
this also happens with pets pulled out of the stable. They should auto level to your level - 5. Currently on the beta they do not.

**Comment by TheDunds** [comment]
Fixed build (45327)
