### ISSUE TITLE
[BUG] Coren Respawn

### ISSUE THREAD

**Issue by ToN1c** [JamminL/wotlk-classic-bugs#421]
#### 1.1. Description
Coren Direbrew doesnt respawn when killed.
  #### 1.2. How to Reproduce
          During Brewfest go to BRD and activate Coren Direbrew. 
          Kill him.
#### 2.1. Description
Coren Direbrew should respawn almost instantly so everybody in the group can use their daily to activate him.
  #### 2.2 Source Material
https://www.youtube.com/watch?v=1S8I74ehGzk

**Comment by Cleavis** [comment]
video is from 2009 level 80 version. believe we are supposed to expect 2008 level 70 version this year.

**Comment by CharWS** [comment]
https://www.youtube.com/watch?v=Pt0dxeMMbsM here's one for 2008 brewfest at lvl 70 as well, can see similar behavior of a quick respawn of the boss

**Comment by ToN1c** [comment]
> video is from 2009 level 80 version. believe we are supposed to expect 2008 level 70 version this year.

Some factors which makes me think that its a weird 2009 version at 70.
We got the 2008 Brewfest Stein last year.
The Pink Elephant pet is optainable and was introduced in the first wrath brewfest
(https://wowpedia.fandom.com/wiki/Pint-Sized_Pink_Pachyderm)

But yes the Coren respawn behaves the same until the first brewfest with dungeonfinder.

I think this is a really urgent issue because people want to farm their mounts like its supposed to work so they focus on leveling in a few days and not have launch runied by yet another bugged event

**Comment by lavjamanxd** [comment]
looks like this was fixed already, i was able to kill the boss 5 time today without resetting the dungeon

**Comment by ToN1c** [comment]
> looks like this was fixed already, i was able to kill the boss 5 time today without resetting the dungeon

Yes looks like they fixed it ~10 hours after the event launched
