### ISSUE TITLE
[BUG] [UI] "IsStealable" flag does not function properly vs buffs that have 100% immunity to be dispelled/spellstolen

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#427]
#### 1.1. Description

In the default Blizz UI, the "IsStealable" flag is responsible for showing up UI-TargetingFrame-Stealable.blp texture around enemy target/focus spellstealable/dispellable buffs.

However, there are certain buffs such as Barkskin, which can be further improved with talent Improved Barskin (https://www.wowhead.com/wotlk/spell=63411/improved-barkskin) and Subtlety (https://www.wowhead.com/wotlk/spell=17120/subtlety), which in combination gives Barskin 100% chance not to be dispelled - an error message "Nothing to dispel" is displayed properly, however the buff is still highlighted.
![image](https://user-images.githubusercontent.com/1942409/192136213-3c48a084-5df6-4a0c-83e6-a4b8e682292c.png)

  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Create druid
           2. Get resto talents Subtlety and Improved Barskin to full
           3. Cast Barkskin
           4. Observe from enemy character that the flag "isStealable" returns "true" instead of "false" and highlights the undispellable Barkskin

#### 2.1. Description

A "highlight" texture for dispelable buffs should not be applied when the buff is ... well ... undispellable 🤷🏿‍♂️

**Comment by XyzKangUI** [comment]
Pending approval 😆

**Comment by JamminL** [comment]
marking this as NAB unless you have info of otherwise

**Comment by JamminL** [comment]
Per request, marking this as #SomeChanges instead
