### ISSUE TITLE
[BUG] [UI] [Misc] UIWidgetTopCenterContainerFrame is not centered properly in arena instances

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#429]
#### 1.1. Description

This is the current behavior of that frame in: WSG / Arena / Terokkar Forest. As you can see, in arena the frame is heavily off-center. And no, its not because of my UI, its the same with default UI.

![image](https://user-images.githubusercontent.com/1942409/192138807-9fee0279-8573-46ef-9893-8219c640be4b.png)

#### 2.1. Description
The "players remaining" frame should be properly centered in the top middle screen.
  #### 2.2 Source Material

https://youtu.be/EwLOcI4h_kg?t=89

**Comment by XyzKangUI** [comment]
The alignment of the text is set from right to left as well, which is not original wotlk alike:

3.4.x: 
![image](https://user-images.githubusercontent.com/94811434/192150839-17fd9708-d2cd-4bf2-8c99-3fd38b9378a9.png)

Original wotlk: 
![image](https://user-images.githubusercontent.com/94811434/192151061-36264780-dbe1-4025-a548-22dff259aa01.png)

Also apparently it was "Green" team and not "Purple"

**Comment by Evolvee** [comment]
> Also apparently it was "Green" team and not "Purple"

They changed this on purpose for colorblind ppl or something 🤷🏿‍♂️

**Comment by Evolvee** [comment]
Wintergrasp has the same issue with time remaining but not with vehicle count:
![image](https://user-images.githubusercontent.com/1942409/196029594-aff6af13-ebf5-4d61-810b-66f6cfd7a1f9.png)

**Comment by Evolvee** [comment]
This is not fixed.

**Comment by Evolvee** [comment]
Exactly the same issue is present even in Trial of Crusader raid on PTR:

![image](https://user-images.githubusercontent.com/1942409/236614870-7d0255f6-5ef9-4401-a34f-bae08b9158ed.png)

Like how is this still in the game, is there nobody else with OCD?

**Comment by Evolvee** [comment]
After a thorough 1 year investigation it was decided this issue is not possible to be resolved without a major core engine framework refactoring. The community also agreeably concluded that the risk of subsequent implications were not worth the Blizzard™ time.

However, a new custom pet was added to the game instead in order to alleviate the consequences this has caused.🍼
