### ISSUE TITLE
[BUG] Thunderstorm not knocking pets - Shaman Elemental

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#43]
#### 1.1. Description
Thunderstorm isn't knocking pets
  #### 1.2. How to Reproduce
           1. Get a warlock or a hunter
           2. Thunderstorm next to one of the pets
           3. Pets stand still
  #### 1.3  Source Material
https://gyazo.com/d746b683b91f2a83b1ab25d2f5849f62
#### 2.1. Description
Thunderstorm should knock pets
  #### 2.2 Source Material
https://www.youtube.com/watch?v=pB4YAc2RQsA&t=1581s 
Fel hunter gets knocked in this video

**Comment by JamminL** [comment]
Updated with a clip

**Comment by Shintaxgg** [comment]
https://gyazo.com/9056016cebec10ca67a467477bf4c084
seem fixed

**Comment by yurpcraft** [comment]
Fixed and working as of 3.4.0.44930
