### ISSUE TITLE
FERAL CHARGE CAT[BUG]

### ISSUE THREAD

**Issue by Raiudd** [JamminL/wotlk-classic-bugs#430]
#### 1.2. Reproduce: can be confirmed easily in game, try to use this ability on a flying target. 

#### 2.2 Source Material
https://youtu.be/8Kr6ywPi2NQ
You can even find a lot of comments from the time on wowhead, talking about how much fun it is to use on air targets.

**Comment by Aggrend** [comment]
The video you linked is fine and good, but we have not once been able to reproduce this working like this on any 3.x version of reference. Talking with the designer who worked on druids in Wrath, it is not his expectation that this would behave differently that it does now (which is to say, it should fail against mobs you cant path to). In the video itself, the mob evades, those mobs also have a large hitbox, and this is happening on uneven terrain, so I don't think we can take that video as ironclad proof this should work this way every time. Regardless, I'm calling this NAB for now. Thanks!
