### ISSUE TITLE
[TEST-REQUEST] Shadowmeld being ignored sometimes

### ISSUE THREAD

**Issue by NatsumeLily** [JamminL/wotlk-classic-bugs#432]
### Description
Can anyone test and figure out why enemies sometimes ignore shadowmeld and keep attacking?

**Comment by NuptupTDOW** [comment]
Seconded. It is really, really annoying to do a pull, realize "whoa, got a bit too ballsy, need to drop it and reset", only for you to run around a corner, LoS the ranged mobs, and pop Shadow Meld, only for the entire enemy group to very clearly run directly to you, and smack you in the face while you're supposed to be invisible.

**Comment by fxweber** [comment]
#175

**Comment by ManneN1** [comment]
@JamminL, close this as it's essentially just a copy of #175 and #476?
