### ISSUE TITLE
[BUG] The 2% maximum health regen component of Fel Armor is not working 

### ISSUE THREAD

**Issue by Jgrenier91** [JamminL/wotlk-classic-bugs#44]
#### 1.1. Description
No Health Regen is occurring from the Fel Armor effect.
  #### 1.2. How to Reproduce
           1. Apply Fel Armor
           2. Watch for health regen
  #### 1.3  Source Material
(https://gfycat.com/ElaboratePlasticGenet)
#### 2.1. Description
2% health regen should occur in accordance with the Fel Armor tool-tip shown in source material
  #### 2.2 Source Material
(https://gfycat.com/EuphoricRadiantBighorn)

**Comment by JamminL** [comment]
Fixed
