### ISSUE TITLE
[BUG] Bonus stats on Heirloom gear doesn't work

### ISSUE THREAD

**Issue by ToN1c** [JamminL/wotlk-classic-bugs#440]
#### 1.1. Description
Hit Rating is on the Item but doesn't change melee or spell hit in character sheet
  #### 1.2. How to Reproduce
          Equip and unequip Heirloom Staff
  #### 1.3  Source Material
https://youtu.be/ziiyo53EgRg
#### 2.1. Description
Item should give the stats that are listed on it.

**Comment by TheDunds** [comment]
Each trinket should give 7 haste rating on lvl 22. 
[image](https://user-images.githubusercontent.com/110584436/195300758-4e49f327-92ad-4c10-a1ff-58a99f194faf.jpeg)![image](https://user-images.githubusercontent.com/110584436/195300857-4b7874b0-f2b4-4f16-9d42-be6bbb162eb6.jpeg)

**Comment by sunbatherr** [comment]
Resilience is also not being applied from Wintergrasp Heirlooms. Nor the hit.

Spell Power and base stats work normally.
