### ISSUE TITLE
[BUG] Tauren Racial Endurance

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#441]
#### 1.1. Description
Tauren Racial Endurance is not giving any health increase. (The aura doesn't work at all)
  #### 1.2. How to Reproduce
           1. Log on a tauren with template
           2. Log on an orc with template
           3. Notice they have the same HP
  #### 1.3  Source Material
![image](https://user-images.githubusercontent.com/107503518/193488357-ca9d9753-5ff4-4195-926f-f74995188e2a.png)
![image](https://user-images.githubusercontent.com/107503518/193488359-9ff92842-2eb3-4a30-8dd1-55115376d861.png)

#### 2.1. Description
Tauren racial "Endurance" should increase HP
  #### 2.2 Source Material
https://www.wowhead.com/wotlk/spell=20550/endurance

**Comment by Dayliex** [comment]
Will need to make sure that extra hp can be increased by Toughness shaman talent. (Increasing stamina by 10%).

**Comment by JamminL** [comment]
Fixed

**Comment by Loregon** [comment]
**Funny fact** 
After the correction, my druid's health increased by 340 and became 8607, which corresponds to the old comments. BUT the attached calculation in the same comment indicates an increase of 370 units, and then the question arose earlier, did all players have an extra three stamina? Or is it a [comment error ](https://www.wowhead.com/wotlk/spell=20550/endurance#comments:id=416275:reply=108630)
Or did I get something wrong...
