### ISSUE TITLE
[BUG] Unholy Blight debuff keeping player in combat

### ISSUE THREAD

**Issue by XyzKangUI** [JamminL/wotlk-classic-bugs#442]
### 1. Current Behavior
The target affected by a DK's Unholy Blight cannot drop combat until Unholy Blight wears off + the usual dynamic out of combat timer passes after that, totalling 16s of combat time. This is a game changing bug that will prevent anyone from drinking in arena, getting a restealth or a chance at resetting in a 1v1 scenario vs a Death Knight. There are abusers profiting from this bug, while the season already started.

  #### 1.2. How to Reproduce
 Have a death knight apply unholy blight to you and see that the combat timer starts running after unholy blight drops off.
  #### 1.3  Source Material
  
![UnholyBlight](https://user-images.githubusercontent.com/94811434/193492214-245bed6e-9ff3-4e69-b240-543d1050510c.gif)

### 2. Expected Behavior
You should be able to normally drop combat even with unholy blight up. It should not be any different from a regular DoT.
#### 2.2 Source Material
https://youtu.be/_2PaC2aIom0?list=PLO06CtzFP8tpws6ZUE074nlExxkadXpFf&t=1345
https://youtu.be/a3i4UOIwE9M?t=353

**Comment by XyzKangUI** [comment]
What does one have to do to get a bug approved @JamminL

![image](https://user-images.githubusercontent.com/94811434/193889522-657f4fe4-e8d0-4df3-b046-63887123e652.png)

**Comment by XyzKangUI** [comment]
https://youtu.be/a3i4UOIwE9M?t=353

![image](https://user-images.githubusercontent.com/94811434/195746336-bda7aedb-ac69-4432-8b1d-2bc4811a64f7.png)

Fix asap please. High prio: prevents drinking, restealthing and 1v1 vs a death knight cause resetting is impossible.

**Comment by NuptupTDOW** [comment]
Somewhat unrelated, but wanted to ask. How is this affecting the Death Knight? Do they also stay locked in combat and unable to reset? Is it acting differently than expected? I'm trying to find out if this could be related to my comments in a Shadowmeld Bug report, where I am seemingly never able to Shadowmeld during a fight, but I am more successful when Shadowmeld'ing if I am not playing my unholy spec it seems. Just wondering if the two might be related. It could also be because of pet interactions, so I'm just trying to narrow it down is all.

**Comment by XyzKangUI** [comment]
> Somewhat unrelated, but wanted to ask. How is this affecting the Death Knight? Do they also stay locked in combat and unable to reset? Is it acting differently than expected? I'm trying to find out if this could be related to my comments in a Shadowmeld Bug report, where I am seemingly never able to Shadowmeld during a fight, but I am more successful when Shadowmeld'ing if I am not playing my unholy spec it seems. Just wondering if the two might be related. It could also be because of pet interactions, so I'm just trying to narrow it down is all.

The DK who applied unholy blight drops combat just fine.

**Comment by NuptupTDOW** [comment]
> The DK who applied unholy blight drops combat just fine.

Thank you for the reply, that narrows down my issue a bit!

**Comment by XyzKangUI** [comment]
https://www.bluetracker.gg/wow/topic/eu-en/379954-wrath-of-the-lich-king-classic-hotfixes-updated-24-october/

🎉
