### ISSUE TITLE
[#SomeChanges] AMS reduced by Imp coc aura

### ISSUE THREAD

**Issue by dariuzsdk** [JamminL/wotlk-classic-bugs#448]
### 1. Current Behavior
Anti Magic Shell  https://www.wowhead.com/wotlk/spell=48707/anti-magic-shell is being reduced by Improved Concentration Aura https://www.wowhead.com/wotlk/spell=20256/
{Describe how that mechanic/spell/npc is currently working, in detail}
  #### 1.2. How to Reproduce
Step 1. Group up with a paladin with 3/3 Improved Conc aura https://www.wowhead.com/wotlk/spell=20256/
Step 2. Use AMS
Step 3. Notice AMS is only 5s or 3s duration depending on whether or not you have the glyph  
  #### 1.3  Source Material
(https://clips.twitch.tv/DarkTolerantThymeTTours-m3udrOsASD-x3Q8X) 2 AMS in this clip, 1 without 1 with and the different durations.
### 2. Expected Behavior
AMS should not be affected by IMP conc aura as it is not an interrupt.

This was a bug back in the day: https://youtu.be/BYK6OkFwbv8?t=357

**Comment by exythxx** [comment]
not only 5s, any bracket, just had ams multiple times for 5 seconds instead of 7 with the glyph.

**Comment by dariuzsdk** [comment]
Can confirm the glyph is just randomly not functioning in a variety of scenarios/brackets 
https://imgur.com/a/vrIk2Sq

**Comment by JamminL** [comment]
- Edited main post after figuring out what was happening
- Marked as SomeChanges
