### ISSUE TITLE
[BUG] [Core] [Priest] [Spell] Shadow Word: Death backfire damage does not break CC (Blind, Repentance etc.)

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#449]
#### 1.1. Description

Footage from 5.10.2022 - https://www.twitch.tv/videos/1610126915

SWD damage has a history of not breaking CC, namely Blind, through all of Classic.
This is a footage from classic tbc: https://www.twitch.tv/bogdan_rtm/clip/VictoriousSeductiveDeerPermaSmug-f0kTUjQhpxCw6zSJ?filter=clips&range=all&sort=time where you can observe the exact same bug happening, and even worse (the dmg literally came through instead of being absorbed in my clip)

~~This is an edge-case that happens only rarely.~~ Its one of these "sometimes" bugs. It probably has to be timed perfectly for it to happen - maybe something to do with the reduced 10ms batch. It could also be the reason why you can get slowed in Dispersion: https://github.com/JamminL/wotlk-classic-bugs/issues/400

  #### 1.2. How to Reproduce

Currently unknown how to reproduce.

#### 2.1. Description

SW: Death backfire damage should always break CC auras that break on dmg taken.

**Comment by dummyaccounter** [comment]
In this most recent version of TBC at least, Blind, Gouge, Sap did not break to damage in the first ~0.5 seconds after application. I played TBC rogue and discovered this via testing in duels -- burst dmg, bleeds, white hits, etc would not break the effect as long as the damage hit in the "grace period". Is this accurate to original tbc/original wotlk? I'm not sure. All I know is that this behavior is not specific to SW:Death.

**Comment by Evolvee** [comment]
Yes this is also why every rogue abused the "rupture-wait for last tick-sap into the tick" without the sap breaking while having sap guaranteed. If the enemy tried to restealth, the stealth would break, there was no outplay potential. It was one of many cancerous playstyles this bug created.

**Comment by Evolvee** [comment]
and again https://clips.twitch.tv/InquisitiveHomelyRhinocerosRalpherZ-Otf7zoZ4fKelWEpa

**Comment by Evolvee** [comment]
And another one https://streamable.com/81z8lm

**Comment by Evolvee** [comment]
and another one https://www.twitch.tv/videos/1917227865

**Comment by Evolvee** [comment]
exactly the same case with SWD vs Repentance: https://clips.twitch.tv/KindSlipperyTurnipPartyTime-kNFJPRnBxBItHIDd
the bug affects all spells that break by damage taken

1 season left to end of the game, is this ever going to be fixed?

**Comment by Evolvee** [comment]
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/1942409/2aafc867-eef3-4a87-b420-52826691514e)
