### ISSUE TITLE
[BUG] Devour Magic is attempting to dispel even when no magic debuff exists to be dispelled

### ISSUE THREAD

**Issue by Jgrenier91** [JamminL/wotlk-classic-bugs#45]
#### 1.1. Description
Using devouring magic on a hostile target will cause the spell to go off and start the cooldown.
  #### 1.2. How to Reproduce
       Target any hostile entity without magic buffs and attempt to use your fel hunter's Devour Magic ability
  #### 1.3  Source Material
https://gfycat.com/UnawareLongAfricanjacana
#### 2.1. Description
An error should occur which states that there is "Nothing to dispel" and the cooldown should not be used.
  #### 2.2 Source Material
No dispel in WOTLK works by allowing the dispel to go off when there is no magic buff to be dispelled.

**Comment by chanbetatestwow** [comment]
This also occurs when dispelling friendly targets. "Nothing to dispel" red text should show up and the ability should not go on cooldown.

**Comment by JamminL** [comment]
FIXED as of 3.4.0.45264
