### ISSUE TITLE
[BUG] Savage Gladiator's Totem of the Third Wind not working at all

### ISSUE THREAD

**Issue by Dayliex** [JamminL/wotlk-classic-bugs#450]
#### 1.2. How to Reproduce 
           1. Equip this relic and cast Lesser Healing Wave
           2. Don't use it and cast Lesser Healing Wave
           3. You will see that there is no difference
  #### 1.3  Source Material

Screenshots attached.
![image](https://user-images.githubusercontent.com/65792292/194596829-3f77d025-37a8-4256-8981-44e5810e08cf.png)
![With](https://user-images.githubusercontent.com/65792292/194597080-46505a6a-7382-4502-8007-7667dfbc4a78.png)
![Without](https://user-images.githubusercontent.com/65792292/194597084-f4bb71c2-5afb-496b-89c0-c9ee9bc8e2db.png)

**Comment by watchyoursixx** [comment]
hotfixed 10/7
https://us.forums.blizzard.com/en/wow/t/wrath-of-the-lich-king-classic-hotfixes-updated-october-7/1323891/220
