### ISSUE TITLE
[BUG] Max rank of Master Marksman is not applying the mana reduction to Aimed Shot

### ISSUE THREAD

**Issue by Slykz** [JamminL/wotlk-classic-bugs#457]
#### 1.1. Description
The Hunter Marksman talent "Master Marksman" is not applying the stated "25% reduced cost" effect to Aimed Shot when speccing 5 points into it.

It works fine for for rank 1-4 but not when the talent is max rank.
  #### 1.2. How to Reproduce
  Spec into 5/5 Master Marksman
  #### 1.3  Source Material
https://i.imgur.com/hTrk3kp.png
#### 2.1. Description
The actual mana cost of Aimed Shot should be (basemana * 0.08) * 0.75 which would be 302 mana at level 80.
  #### 2.2 Source Material
N/A

**Comment by watchyoursixx** [comment]
This was working at lvl 70. Can you confirm if it's just max rank or all ranks?

**Comment by Slykz** [comment]
Can confirm that Rank 1-4 works fine.
0/5 - 403 Mana
1/5 - 383 Mana
2/5 - 363 Mana
3/5 - 343 Mana
4/5 - 322 Mana
5/5 - 403 Mana

**Comment by NuptupTDOW** [comment]
> Can confirm that Rank 1-4 works fine.

I think they meant to check if the lower ranks of Aimed Shot work with the 5/5 talent, and only the Aimed Shot ranks that you get from 71-80 don't work.

**Comment by skinnay-dev** [comment]
Hotfixed 10/21

https://us.forums.blizzard.com/en/wow/t/wrath-of-the-lich-king-classic-hotfixes-updated-october-20/1323891/323
