### ISSUE TITLE
[BUG] Shackle Undead vs Lichborne

### ISSUE THREAD

**Issue by exythxx** [JamminL/wotlk-classic-bugs#458]
#### 1.1. Description
If you get shackled into lichborne then you cannot remove it with Will to Survive(59752) or any medalion.
  #### 1.2. How to Reproduce
           1. Duel any priest with talented Lichborne.
           2. Let priest use Shackle Undead on you
           3. Try to use medalion or will to survive
  #### 1.3  Source Material
https://clips.twitch.tv/TenderSmilingAsparagusBudStar-4dA_Wt2g7KmRl90I
#### 2.1. Description
You should be able to trinket shackle undead.
  #### 2.2 Source Material
Not yet

**Comment by JamminL** [comment]
Marking this as a bug. 

If this was a thing back then there would be forum posts, and the absence of those is indicative, it'd be super hard to concrete evidence of this very specific case
