### ISSUE TITLE
[BUG] DeleteCursorItem() function not working

### ISSUE THREAD

**Issue by Jgrenier91** [JamminL/wotlk-classic-bugs#46]
#### 1.1. Description

/run DeleteCursorItem() 
This function is not functioning on WOTLK Beta.

  #### 1.2. How to Reproduce

           1. Create Macro with the following:
           /run DeleteCursorItem()
           2. Assign macro to a keybind similar to what you would do with any ability
           3. Drag an item from your bags and while holding the item, press the keybind to run the macro
  #### 1.3  Source Material
https://gfycat.com/RigidRemarkableDuckling
#### 2.1. Description
When written in a macro, this function will delete the item held in the cursor of the user when the macro is used:

/run DeleteCursorItem()

  #### 2.2 Source Material
https://gfycat.com/WastefulBestErin - TBC Classic use of this macro works fine
https://wowpedia.fandom.com/wiki/API_DeleteCursorItem

**Comment by yurpcraft** [comment]
Fixed and working as of 3.4.0.44930
