### ISSUE TITLE
[BUG][UI]Minor buffs on the classic raid frame

### ISSUE THREAD

**Issue by Loregon** [JamminL/wotlk-classic-bugs#462]
#### 1.1. Description
The minor class buffs that player's buff on their allies before the combat don't hide when entering the combat on the raid frame. For example, "Thorns", the old ID (ex. ID 26992) is hiding, but to new levels (ID 53307) from WotLK it's visible. I am sure that this is not the only such spell.
#### 1.2. How to Reproduce
           1. Turn on raid frame
           2. Buff your self WotLK Thorns (8 rank)
           3. Join on combat
           4. Check raid frame
#### 2.1. Description
  The minor class buffs that player's buff on their allies before the combat should hide when entering the combat on classic raid frame.
  #### 2.2 Source Material
[https://imgur.com/zbk7XLj](https://imgur.com/zbk7XLj)

**Comment by XyzKangUI** [comment]
Duplicate: https://github.com/JamminL/wotlk-classic-bugs/issues/419
