### ISSUE TITLE
[#SomeChanges Suggestion] Fish Feast Ranged AP

### ISSUE THREAD

**Issue by TheDunds** [JamminL/wotlk-classic-bugs#463]
### Description
Fish Feast does not give ranged attack power. 
Is this meant to be intended? The ingame tooltip doesn't mention melee ap or ranged ap just ap 
It has been tested in game and shown in the paper doll to not increase ranged ap
If this is the intended interaction to only give melee ap, I'd like to put forward a some changes request to also give it ranged attack power. 
![image](https://user-images.githubusercontent.com/110584436/195379205-238b23b7-3f9b-4461-b195-a343d882df25.png)

**Comment by watchyoursixx** [comment]
I believe this is actually a bug, spell power doesn't give healing power either, despite being one and the same in wrath from buffs and gear

**Comment by TheDunds** [comment]
Healing v spell damage was got fixed today as per the blue post https://www.bluetracker.gg/wow/topic/us-en/1323891-wrath-of-the-lich-king-classic-hotfixes-updated-october-11/

**Comment by TheDunds** [comment]
![image](https://user-images.githubusercontent.com/110584436/196841880-35b019ff-3bab-42e6-9ad5-0fc734c238c1.png)

https://www.wowhead.com/blue-tracker/topic/us/wrath-of-the-lich-king-classic-hotfixes-updated-october-19-1323891

Fixed 
Can be closed now
