### ISSUE TITLE
[BUG] Currently all bosses in T7 are Parry Hasting, including Patchwerk.

### ISSUE THREAD

**Issue by MHMabrito** [JamminL/wotlk-classic-bugs#464]
#### 1.2. How to Reproduce
           1. Equip 2x One-Handers
           2. Tank each boss while dual wielding
           3. Review logs of Parries reducing the time of the remaining part of the swing.

  #### 1.3  Source Material
Patchwerk:
![PW Parry Haste](https://user-images.githubusercontent.com/115662284/195427684-b9614a18-70aa-49ad-8bc1-52bd5b59c90c.png)
Heigan:
![Heigan Parry Haste](https://user-images.githubusercontent.com/115662284/195427740-a991dc98-a4ef-441c-a540-098652658be7.png)
Thaddius:
![Thaddius Parry Haste](https://user-images.githubusercontent.com/115662284/195427766-2f5caf09-1725-4505-8732-1a6c32160073.png)
Loatheb:
![Loatheb Parry Haste](https://user-images.githubusercontent.com/115662284/195427801-5be0f114-8b5c-4fe7-88d0-364f2778ef6e.png)
Noth:
![Noth Parry Haste](https://user-images.githubusercontent.com/115662284/195427862-a6a5f941-526e-4cb5-8f14-524428a7dd87.png)

#### 2.2. [Source Material](https://www.bluetracker.gg/wow/topic/us-en/13129903275-parry-hasting-was-it-removed/)

**Comment by watchyoursixx** [comment]
https://cdn.discordapp.com/attachments/989916728605679688/1029865187215417354/unknown.png
Swing timings from a log, made by Magey, for reference as how it is currently on live.
