### ISSUE TITLE
[BUG] Queued spells and other talent triggers

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#468]
#### 1.1. Description
  Queued spells that replace auto-attack trigger some talents. I think this is a big issue and also applies to other procs that should only proc from auto-attacks. An example of such talents:
https://www.wowhead.com/wotlk/spell=13002/unbridled-wrath
https://www.wowhead.com/wotlk/spell=16864/omen-of-clarity
  #### 1.2. How to Reproduce
           1. Learn talents
           2. Press "Heroic strike" and "Maul"
  #### 1.3  Source Material
https://imgur.com/a/8wlN7cB
#### 2.1. Description
Queued abilities that replace auto-attacks should not trigger these talents
  #### 2.2 Source Material
Unbridled wrath:
https://www.mmo-champion.com/threads/705779-Losing-5-5-Unbridled-Wrath-in-exchange-for-more-Utility?
-I'm also not sure if the spreadhshet reflects that it doesn't even proc on Heroic Strikes and Cleaves anymore. It's really quite terrible.

https://web.archive.org/web/20100809093737/http://elitistjerks.com/f81/t37462-warrior_dps_calculation_spreadsheet/p109/
-It wasn't counting off specials. It was counting on next swing abilities. It was counting Heroic Strikes. Since Cleave and Heroic Strike was stealth fixed 2 months ago to not proc Unbridled Wrath off Cleaves and Heroic Strikes it does need to be updated.

In this video, you will never see a triple proc from a talent. Periodically, you can see through the addon 2 procs, this is its implementation, because. sometimes the addon delays the display of the proc with the previous and current auto-attack, after which they are summed up. "Cleave" with the glyph hits 3 targets, so the addon should display 3-4 procs at a time, because. the talent, according to the old working capacity, procs for each target hit with a cleave, which is not visible in the video from 3.3.5
https://www.youtube.com/watch?v=ikSZ7S_dVBg

Omen of clarity:
In this video, you can see that from now on, the bear only spams Maul, because only yellow attacks are visible, no white ones. As you can see from the video, there are no procs.
https://youtu.be/MTPb4C2gLZk?t=130

**Comment by caccavale** [comment]
Need better evidence for Omen.  Not taking Omen in talents was fairly popular for feral tanks back in the day.

**Comment by Miyur1** [comment]
> Нужны лучшие доказательства для Omen. Не брать Omen в таланты было довольно популярно для ферал-танков в свое время.

You can see the omen trigger at the beginning of the video when feral auto-attacks

**Comment by Miyur1** [comment]
> Anecdotal as well: https://youtu.be/HciHmfncLc0?t=32 "Omen of clarity gives you a chance on all of your white swings and mauls to enter a clearcasting state."

This video is the start of wotlk. After that, the talent has undergone many changes.

**Comment by caccavale** [comment]
> > Need better evidence for Omen. Not taking Omen in talents was fairly popular for feral tanks back in the day.
> 
> You can see the omen trigger at the beginning of the video when feral auto-attacks

Good catch.  Yeah this seems bugged on classic.

**Comment by NatsumeLily** [comment]
Maul triggering omen is correct. https://github.com/SunwellTracker/issues/issues/2500 has a really detailed report about it. 

![image](https://user-images.githubusercontent.com/15247730/196011152-395361d4-e15e-4036-bab0-f9cca3f9fc4f.png)

**Comment by JamminL** [comment]
@NatsumeLily, refrain from posting links to those githubs for obvious reasons. You're more than welcome transposing that information here.

**Comment by NatsumeLily** [comment]
Ummm ok..?

> How it should work:
> Omen of clarity used to proc on retail from for example from; nature's grasp, gift of the wild, faerie fire feral (cat and bear) and even from barkskin so its should proc atleast from those abilities not sure if theres more. It was a thing to use those abilities like gotw before a pull to get free ooc before the boss fight, i am ofc not able to test if its procs from gotw since im not high enough level on angra. Omen of clarity worked fine on other private servers like on dragonblight so i dont know whats different on here?
> 
> Earlier there was a problem with maul not proccing it so was something wierd done to it?
> 
> Virtually any spell cast can trigger the Clearcasting, including ones with no mana cost, though not all spells will benefit from it.
> Some abilities may cause Clearcasting to trigger, but will not benefit from it or consume the buff when cast. This includes spells such as Mark of the Wild and Nature's Grasp. Thorns is considered a damage spell for this purpose, and as such will benefit from (and consume) the Clearcasting state when cast.
> 
> Essentially almost everything can cause Clearcasting with this ability, regardless of whether it's a druid ability or not. The herbalist ability Lifeblood can trigger it.
> Curiously, characters with Dual Talent Specialization will sometimes trigger Clearcasting by activating their other talent tree.
> 
>     https://wowwiki.fandom.com/wiki/Omen_of_Clarity
> 
> How To reproduce?
> Spec In To Omen of clarity use faerie fire feral, barksin, gotw, motw, nature's grasp atleast those abilities should proc clearcasting but its not happening proc chance is about 6%
> 
> Source (you should point out proofs of your report, please give us some source): *
> theres very little i could find online but i could try to search some videos if i can find any since not many people used those tricks back in wotlk.
> https://vanilla-wow.fandom.com/wiki/Omen_of_Clarity
> https://ptr.wowhead.com/spell=16864/omen-of-clarity?classicRedirect&fromClassic&name=omen-of-clarity#comments some people commenting about it proccing from some wierd stuff and stuff not too wierd from patch 3.0.2 to 3.3.5 etc
> https://www.youtube.com/watch?v=4gyy3GSokm0 this guy uses gotw before the pull to get ooc proc then again im not sure if gotw works on your server because i cant test it atm
> https://www.youtube.com/watch?v=KFMPEECCAP0 i believe this is from retail wow here he uses gotw before the pull too to get ooc proc
> https://wowwiki.fandom.com/wiki/Feral_DPS_guide here one post about natures grasp usage if you search the page with ctrl+f and type in nature's grasp u should find the part "you have less than 35 Energy, use [Tiger's Fury] (or [Nature's Grasp] - which can proc [Omen of Clarity])."
> 
> https://youtu.be/WuWOFtk6JS4?t=122 video showing barkskin proccing omen of clarity while hes stunned there.
> 
> https://youtu.be/y0NI3hDZyjs?t=38 ooc proccing from cyclone just a example that the ability that makes it proc doesnt have to be a 'damagin ability"
> 
> https://youtu.be/iCBb4fSuako?t=308 heres a clip of faerie fire feral proccing omen of clarity.
> 
> Tested on max level on Frosthold still not proccing from faerie fire feral, natures grasp or gotw, motw nor barkskin its pretty big deal for pvp and even for pve To get Those extra damages or heals. Why those abilities proc ooc If u check https://wotlk-twinhead.twinstar.cz/?spell=16810 it says physical there and same thing on faerie fire https://wotlk-twinhead.twinstar.cz/?spell=16857 no idea why barkskin procced it.
> 
> Updating with some wol reports about gotw atleast
> [http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/xe/x=spell+%3D+"Gift+of+the+Wild"%0D%0AAND+type+%3D+TYPE_CAST%0D%0AAND+sourceName+%3D+"Hoofarted"%0D%0Aor+spell+%3D+"Clearcasting"+AND+sourceName+%3D+"Hoofarted](http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/xe/x=spell+%3D+%22Gift+of+the+Wild%22%0D%0AAND+type+%3D+TYPE_CAST%0D%0AAND+sourceName+%3D+%22Hoofarted%22%0D%0Aor+spell+%3D+%22Clearcasting%22+AND+sourceName+%3D+%22Hoofarted)"
> 
> Faerie fire feral
> [http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/xe/?x=spell+%3D+"Clearcasting"%0D%0AAND+sourceName+%3D+"Oranoss"%0D%0AOR+spell+%3D+"Faerie+Fire+(Feral)"%0D%0AAND+sourceName+%3D+"Oranoss"+&page=1](http://www.worldoflogs.com/reports/s9nu6f6x43oed1ws/xe/?x=spell+%3D+%22Clearcasting%22%0D%0AAND+sourceName+%3D+%22Oranoss%22%0D%0AOR+spell+%3D+%22Faerie+Fire+(Feral)%22%0D%0AAND+sourceName+%3D+%22Oranoss%22+&page=1)
> 
> [18:05:42.211] Oranoss's Faerie Fire (Feral) fades from Volatile Ooze
> [18:05:44.934] Professor Putricide's Faerie Fire (Feral) is refreshed by Oranoss
> [18:05:45.067] Oranoss gains Clearcasting from Oranoss
> [18:05:47.980] Oranoss casts Faerie Fire (Feral) on Volatile Ooze
> [18:05:48.263] Volatile Ooze afflicted by Faerie Fire (Feral) from Oranoss
> 
> 18:36:01.079] Oranoss casts Faerie Fire (Feral) on Blazing Skeleton
> [18:36:01.153] Blazing Skeleton afflicted by Faerie Fire (Feral) from Oranoss
> [18:36:01.494] Oranoss gains Clearcasting from Oranoss
> [18:36:02.103] Oranoss's Clearcasting fades from Oranoss
> 
> Spell ids
> https://wotlk-twinhead.twinstar.cz/?spell=16810 Nature's Grasp buffing Yourself with it should be able to proc ooc
> https://wotlk-twinhead.twinstar.cz/?spell=16857 faerie fire feral cat and bear
> https://wotlk-twinhead.twinstar.cz/?spell=65860 barkskin
> https://wotlk-twinhead.twinstar.cz/?spell=26991 gotw almost 100% chance since it goes to many People not sure how it works does it multiply the chance of the proc like x25 etc?
> Mark of the wild should Do it too.
> 
> So In short how it should work
> 
> -No ICD works correctly here
> -Proc rate ~6% 3.5ppm haste affect this
> 
> -It shouldn't proc off HoT-/DoT-ticks unless u have tier 8 set bonus, but off spellcasts. It should also trigger from things like crafting, changing specialization, etc. - since these are considered spell casts not that important imo If its hard to code.
> -It shouldn't proc off feral abilities (excluding "Maul", since Maul is an auto attack with added damage), but off auto attacks and other spells.
> -It should proc from MoTW/GoTW, Fearie Fire all forms so faerie fire cat, bear and human form, Nature's Grasp, innervate and barkskin, dash (thorns dmg ticks? Someone commented about this i didnt ever know about this was a thing or i didnt notice it and i have no proof about this).
> 
> So pretty much anything can proc it except for feral abilities (shred, mangle etc.
> 
> Seems that most of the spells that should proc it are from nature school maybe thats a solution To something?

**Comment by caccavale** [comment]
This is rehashing some Omen behavior that has already been proven not to reference for classic.  Crafts should be suppressed as well as there is suppression for multi-target and instant spells which are not taken into account in your evidence.  

Speaking of the issue at hand-- the forum reports of UW being made to not proc from queued abilities are consistent and plentiful.  We should look to more first hand sources such as 3.3.5 feral videos for Maul but the evidence we have shows it not procing Omen for a statistically significant amount of hits.  Posting a pserver bug report that is essentially "all of omen scripting is not correct isn't particularly helpful to this exact issue.

**Comment by caccavale** [comment]
Can you isolate any evidence of Omen procs from maul?  Those would be helpful.

**Comment by JamminL** [comment]
> Ummm ok..? Dumb reason to ignore pserver's research, since at the moment they have better scripting.

I never said that, quite the contrary. Just asking not to link back to these websites!

**Comment by caccavale** [comment]
Towards evidence that Maul was made to not proc Omen, this video takes place after the supposed stealth nerf and the only 3 Clearcasting procs are from Barkskin and two non-maul white hits. 

https://www.youtube.com/watch?v=LjpBsZ9kf9Q

**Comment by Aggrend** [comment]
We have a potential fix in place for this. Should be on PTR this week (ETA ~12/1)

**Comment by styxel** [comment]
Source (you should point out proofs of your report, please give us some source): https://youtu.be/HciHmfncLc0?t=31s a retail guide, hear him say "and Mauls"

https://youtu.be/RjU5w5Wnp-w?t=1m49s also retail video. You can see many times throughout the video as a big Clearcasting! sign pops up on the middle top of the screen. The time I referred to is one example. See on the right hand side of the screen as Maul hits show up and only a split second later clearcasting.

https://youtu.be/VNORpfUxvxQ?t=1m57s another retail video if one is not enoguh proof. Harder to see, but also it has Darude Sandstorm b4 it was cool.

Some comments on it:
"Maul can proc it since the game views maul as an auto attack that just has a bonus damage modifier attached to it."
"Omen can proc on Maul."
"it can proc off all spells, auto attacks, and off mauls"

**Comment by Miyur1** [comment]
> Source (you should point out proofs of your report, please give us some source): https://youtu.be/HciHmfncLc0?t=31s a retail guide, hear him say "and Mauls"
> 
> https://youtu.be/RjU5w5Wnp-w?t=1m49s also retail video. You can see many times throughout the video as a big Clearcasting! sign pops up on the middle top of the screen. The time I referred to is one example. See on the right hand side of the screen as Maul hits show up and only a split second later clearcasting.
> 
> https://youtu.be/VNORpfUxvxQ?t=1m57s another retail video if one is not enoguh proof. Harder to see, but also it has Darude Sandstorm b4 it was cool.
> 
> Some comments on it: http://www.wowhead.com/forums&topic=129225.1#p1545184 "Maul can proc it since the game views maul as an auto attack that just has a bonus damage modifier attached to it." "Omen can proc on Maul." "it can proc off all spells, auto attacks, and off mauls"
This is all outdated information

**Comment by Miyur1** [comment]
Fixed as of build 3.4.1.46917 PTR
