### ISSUE TITLE
[BUG] Snare Immunity and slow

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#469]
#### 1.1. Description
There is a massive issue with spells that remove slows
Spells that remove slows:
https://www.wowhead.com/wotlk/spell=1044/hand-of-freedom
https://www.wowhead.com/wotlk/spell=53271/masters-call
https://www.wowhead.com/wotlk/spell=47585/dispersion

Examples of slows that can be applied under the hand of freedom:
https://www.wowhead.com/wotlk/spell=42842/frostbolt
https://www.wowhead.com/wotlk/spell=31589/slow
https://www.wowhead.com/wotlk/spell=48485/infected-wounds
https://www.wowhead.com/wotlk/spell=47610/frostfire-bolt
 
If during "hand of freedom" cast "frostbolt", then after the disappearance of "hand of freedom", the slow will take effect.
  #### 1.2. How to Reproduce
           1. Press hand of freedom
           2. Get frostbolt/slow/frostfire bolt/infected wounds
  #### 1.3  Source Material
https://www.youtube.com/watch?v=56YKk_4ECXo
#### 2.1. Description
Slows applied under "hand of freedom" should not work after "hand of freedom" disappears. This also applies to Dispersion and Master call.
  #### 2.2 Source Material
https://www.warcraftmovies.com/movieview.php?id=165755 @8:15
https://www.warcraftmovies.com/movieview.php?id=149717 @5:47
Patch 3.2.2 (2009-09-22)
Master Call: This ability now correctly removes the snaring component of Infected Wounds, Frostfire Bolt, and Slow.

**Comment by Miyur1** [comment]
Fixed as of build 3.4.1.47014 PTR

**Comment by Evolvee** [comment]
This is still bugged for dispersion - Live 3.4.0.47168

**Comment by Evolvee** [comment]
Things should be marked as fixed when they actually hit the live server. For all we know this can go live in 1 or 2 months, meaning its not gonna be fixed until end of the season and marking this fixed is misleading as its still bugged ingame and will be until Ulduar, which isnt even announced yet.

**Comment by Evolvee** [comment]
this is still bugged for dispersion @JamminL 
reopen

**Comment by JamminL** [comment]
There's already a seperate issue for dispersion

**Comment by Evolvee** [comment]
@JamminL This is a different issue than the one written in the topic for Dispersion.

Dispersion has 2 issues: 1) it doesnt grant immunity during its duration 2) it doesnt grant immunity to snares applied during its duration after the dispersion duration ends

This topic is about 2).

### reopen, not fixed...

**Comment by Cryogenics** [comment]
still not fixed for https://www.wowhead.com/wotlk/spell=47585/dispersion

**Comment by JamminL** [comment]
While I agree it's probably an old bug, it matches reference behavior @Cryogenics 
https://youtu.be/Yd-mvo-E7tU?t=49

**Comment by JamminL** [comment]
The clip @Evolvee linked happens because the mage he played against didn't have MS talented into it.
