### ISSUE TITLE
[BUG] Interrupt charge while сс

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#470]
#### 1.1. Description
Some types of control may interrupt the charge (stun, cyclone, polymorph, hex, blind, Scatter Shot, etc)
  #### 1.2. How to Reproduce
           Give a charge at the moment of casting the spell
  #### 1.3  Source Material
https://www.youtube.com/watch?v=8yrRxVlDRuc
https://clips.twitch.tv/BrainyFriendlyDoveLeeroyJenkins-MzEoaccs-BctcgYo
Here you can see how the intercept was interrupted by the stun
#### 2.1. Description
In the original WoW, when gaining control (Apply Aura: Stun and Apply Aura: Root) in a charge, a warrior teleported to the enemy. With other types of control (polymorph, death coil, hex, fear, blind, Scatter Shot) the warrior simply continued to charge while in control. Of course, I doubt that the developers will leave teleporters in wotlk classic, but at least I hope that the charge will not be interrupted if this is corrected.
  #### 2.2 Source Material
https://www.warcraftmovies.com/movieview.php?id=163797 @10:07
https://www.youtube.com/watch?v=OP63cb5cHf0&t=291s
https://www.youtube.com/watch?v=qSGJRoVGFeU&t=5s
https://www.warcraftmovies.com/movieview.php?id=161647 @8:29
https://www.warcraftmovies.com/movieview.php?id=158761 @26:39, 28:41
https://www.warcraftmovies.com/movieview.php?id=166559 @2:08
https://youtu.be/qSGJRoVGFeU?t=37
https://www.warcraftmovies.com/movieview.php?id=163797 @1:27
https://www.warcraftmovies.com/movieview.php?id=134603 @17:32, 17:51, 19:38, 27:36, 36:52
https://youtu.be/YGqixUSmWhI?t=13
https://youtu.be/VzOYpeN2dUM?t=5m32s
The warrior is under the polymorph debuff, but the charge continues

https://www.warcraftmovies.com/movieview.php?id=153967 @37:14
https://www.warcraftmovies.com/movieview.php?id=143325 @5:32

**Comment by Azmoddan** [comment]
Personally I feel like this is one of those things that should stay like they are right now #SomeChanges. Being able to cc warriors/ferals mid-charge gives an outplay potential which is inherently good thing for a competitive environment.

**Comment by Miyur1** [comment]
Fix not likely
