### ISSUE TITLE
[BUG] Cyclones removes Aimed Shot mortal strike effect

### ISSUE THREAD

**Issue by Homerjayx** [JamminL/wotlk-classic-bugs#472]
#### 1.1. Description
When using Aimed Shot on a target and the mortal strike effect gets applied and the target then gets cycloned it removes the 50% reduced healing effect.
  #### 1.2. How to Reproduce
1. Aimed Shot an enemy player
2. Have a friendly druid use cyclone after the mortal strike effect has been applied
3. Watch how the 50% reduced healing effect fades
  #### 1.3  Source Material
https://clips.twitch.tv/LitigiousCrepuscularGoblinKreygasm-bjc54DJCruAIFrMQ
#### 2.1. Description
There is no reason for the Cyclone to remove the mortal strike effect.
  #### 2.2 Source Material

**Comment by XyzKangUI** [comment]
Seems to be original wotlk behaviour. The ns clone removed aimed shot: https://youtu.be/QWCbsjJ08lM&t=29
