### ISSUE TITLE
[BUG] Tiger's fury and Berserk

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#473]
#### 1.1. Description
Berserk does not remove Tiger's Fury
  #### 1.2. How to Reproduce
           1. Press Tiger's Fury
           2. Press Berserk    
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
After fixing Blizzard, Berserk no longer removes Tiger Fury. This is the wrong fix. Berserk should remove Tiger's Fury
  #### 2.2 Source Material
https://youtu.be/WK57aabors4?t=42
https://youtu.be/3HZbmez8NOk?t=72
https://youtu.be/BZdhmPG-qGQ?t=40

**Comment by Aggrend** [comment]
Doing a bit of housekeeping and realized that this was still open. This matches reference and is NAB. You can't USE Tiger's Fury while under Berserk, but you won't lose it if you already have it up.
