### ISSUE TITLE
[BUG] Explosive Trap - crit damage

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#474]
#### 1.1. Description
Explosive Trap with Glyph Explosive Trap deals 200% Critical Damage
  #### 1.2. How to Reproduce
           1. Put glyph
           2. Press explosive trap   
  #### 1.3  Source Material
https://imgur.com/a/Ad3vVvZ
#### 2.1. Description
Explosive trap with glyph Explosive trap should deal 150% Critical Damage
  #### 2.2 Source Material
Log from 2010:
http://www.worldoflogs.com/reports/p3exnfqr43ual5ww/xe/?s=8418&e=9169&x=spell+%3D+%22Explosive+Trap%22

[21:30:04.779] Bullseyes Explosive Trap Val'kyr Shadowguard 559
[21:30:05.029] Bullseyes Explosive Trap Val'kyr Shadowguard 863

559 * 1,5 = 838 (base spell crit damage is 150%)
838 * 1,03 = 863 (meta gem gives 3% bonus crit damage)

Dr.damage 2010:
 - Glyph of Explosive Trap
if self:HasGlyph(63068) then
        calculation.E_canCrit = true
        **calculation.critM = 0.5**

https://www.wowace.com/projects/dr-damage/files/417657
Dr.damage changelog Feb 28, 2010
- Corrected Glyph of Explosive Trap crits to receive meta gem bonus like a spell does (it's a spell that has a inherent +50% increase)

**Comment by watchyoursixx** [comment]
do you have a link to the logs that actually works?

**Comment by Miyur1** [comment]
> do you have a link to the logs that actually works?

It was the only site that kept logs from 2010, but closed a year ago.

**Comment by Miyur1** [comment]
https://youtu.be/k9dOrjKqDyQ?t=85
While the explosive trap is in effect you can see the numbers that are most often seen:
non crit 1019-1020
crit 1529-1530

non crit 1070
crit 1605-1606

non crit: 496-501
crit: 744-750

non crit: 927
crit 1390

Why is this not a private server:
- NPCs that were hit on the bridge trigger all other NPCs while running towards the player
- NPCs after approaching the enemy move differently than on private servers
- NPCs have dialogue
- on a 2010 private server, npc's walk through textures, ignoring them
- when collecting rare (blue) loot from the boss, the player is warned that it will become personal
- when collecting loot, you can observe a slight delay

**Comment by Miyur1** [comment]
> The focus regeneration of the pet is going up in chunks, all resources for wotlk were moved to a smooth system. I 1st though it might of just been a ui error but you can easily see the hunters mana regeneration is smooth and not in chunks.
> 
> ![image](https://user-images.githubusercontent.com/110584436/196221853-437d253e-8ac3-47ce-bbe9-c2cffbe38262.jpeg)
> 
> https://www.youtube.com/watch?v=N4zoD2scJ_s
> 
> This video is from the same creator it is 4 months later but there flying in the air on a raptor and no mount at all. This doesn't inspire much confidence in there videos.

However, this video is not from a private server. I suspect this is a visual bug from flightpath. it lands at their point
https://www.youtube.com/watch?v=E9Twxt4TCO0
https://www.youtube.com/watch?v=uh96FD-YcX0
https://www.youtube.com/watch?v=-28UEJNtyag

Smooth resource regeneration is the official behavior, see succubus mana regen
https://www.warcraftmovies.com/movieview.php?id=138555
https://www.warcraftmovies.com/movieview.php?id=141545

https://youtu.be/cFetB75DCyk?t=92
Here you can see that the hunter received critical damage from Mortal Strike, but in the debuffs, the warrior talent "Deep Wounds" appears with a delay, this is spell batching, which in 2022 is not implemented on the best WoW private servers
https://imgur.com/a/ebosTVC

1:31, 1:35, warrior launches charge, hunt stun appears after 0.2 seconds, this is spell batching.

Another moment at 1:39. The warrior emerges from the slow trap, but he still has a second and a half of the slow debuff on him. This is "AoE Aura Batch".

More videos from this channel:
https://youtu.be/P7TRv3BxPz4?t=30
The enemy player takes the flag from the Alliance base, the flag icon does not appear on the map. The developers of Blizzard on Wotlk Classic fixed this only recently (I reported about it)
October 4: Flag carriers in the Warsong Gulch battleground now appear on the map after 45 seconds of carrying the enemy flag.
On private servers, this was noticed and fixed only starting in 2018.

Also on the channel there are videos from the pre-patch of the cataclysm)

**Comment by Aggrend** [comment]
Discussed as a team but decided not to fix this. We would have considered the 50% crit damage a bug in 2008, so we'll let this ride.

Unrelated, but we've also decided not to fix https://github.com/JamminL/wotlk-classic-bugs/issues/478 for similar reasons. This is not intended and wasn't in 2008 either.

One is a buff, one is a nerf. so we are calling it a wash. Won't Fix/NAB.
