### ISSUE TITLE
[BUG] Improved Tracking and Piercing Shots

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#478]
Yo
I'm wondering if the developers of wotlk classic will fix some of the spells that scaled twice from talents.

#### 1.1. Description
Improved Tracking does not increase the damage of Piercing Shots
  #### 1.2. How to Reproduce
       1. Learn Improved Tracking
       2. Enable Improved Tracking   
       3. Deal a critical hit with Aimed/Steady/Chimera shots
  #### 1.3  Source Material
https://imgur.com/a/BgGQknq
1765 * 0,3 / 8 = 66
#### 2.1. Description
Improved tracking should increase the damage of Piercing Shots
  #### 2.2 Source Material
  
https://youtu.be/rUDlqg96aGc?t=14
13474 * 0,3 / 8 * 1,05 = 530,53 ~ 531

https://www.youtube.com/watch?v=WAQCrKDz9Mg&t=111s
15752 * 0,3 / 8 * 1,05 = 620

https://www.youtube.com/watch?v=-1Zf3otQw4Q&t=26s
8499 * 0,3 / 8 * 1,05 = 334,6 ~ 335

No raid buffs:
https://youtu.be/_BWeGKTnUUg?t=76
6058 * 0,3 / 8 * 1,05 = 238,53 ~ 239 (tick on 238 and 239)

To determine that improved tracking gives 5% damage to Piercing Shots, and not talents such as Marked for Death or Ranged Weapon Specialization, which also add 5% damage, you need to find a video with a test on the mechanism. We don't need to know if the hunter has tracking enabled, because the dummy is a mechanism, and accordingly the talent will not work in any case.

https://youtu.be/Xy279G86zLU?t=56
8418 * 0.3 / 8 = 315.6 ~ 316
Accordingly, the damage of Piercing Shots is increased by Improved Tracking

**Comment by Aggrend** [comment]
Won't fix/NAB. See comments on https://github.com/JamminL/wotlk-classic-bugs/issues/474
