### ISSUE TITLE
[BUG] Heartbeat CC for PVP

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#48]
### 1. Current Behavior
Heartbeat is still in the game for PVP, it shouldn't.
  #### 1.2. How to Reproduce
           1. Cast CC on a player, like blind
           2. Keep casting until it breaks early from heartbeat mechanic rng
           3. Be upset because your cc broke before its duration
  #### 1.3  Source Material
Not yet
#### 2.1. Description
Heartbeat was not in the game for pvp in 3.3.5a, 100%.
  #### 2.2 Source Material
N/A

**Comment by Aggrend** [comment]
Heartbeat was in the game in 3.3.5, 100%. :)

**However**, the "rules" around it changed in the code after 2.X and there was a significant delay placed on when the heartbeat resist system would kick in and start to try and check for resists. This meant that this effectively had no chance to resist on the first few sever ticks and a small chance to resist on what was (typically) the final tick of a full-duration CC in PvP settings. As a result, this wasn't something that players would often encounter with CC in PvP, but would much more often encounter with full-duration CC in PvE.  This matches all 3.X versions of our reference clients.

All that being said, after a significant amount of discussion about this we've decided to completely remove heartbeat resists in PvP, and restore the 3.3.5 behavior in the outdoor world and in PvE situations. We didn't want this to impact PvE scenarios and this feels like a good compromise to remove this, uh... _much debated_ mechanic from PvP scenarios. 

This fix/change should be present in our next beta build, eta 8/10. Thanks!
