### ISSUE TITLE
[BUG] Devouring Plague - reflect

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#480]
#### 1.1. Description
If the plague is reflected, then in order to remove the Devouring Plague, it is enough to cast the plague on any target
  #### 1.2. How to Reproduce
           1. Press reflect
           2. Press Devouring Plague into reflection
           3. Сast a Devouring Plague on any target
  #### 1.3  Source Material
https://www.youtube.com/watch?v=o7JClT2qv8c
#### 2.1. Description
Devouring Plague should not be removed from the Priest by casting on the target if it is reflected
  #### 2.2 Source Material
https://youtu.be/VnPQBFe7-nU?t=62
https://youtu.be/jJyxCbvK_Dk?t=268
https://youtu.be/-LFhOdJb9nw?t=150
https://www.warcraftmovies.com/movieview.php?id=159305 
6:03

**Comment by JamminL** [comment]
#372 related
