### ISSUE TITLE
[BUG] Dragon's breath interaction with Earthen power

### ISSUE THREAD

**Issue by Naoshytm** [JamminL/wotlk-classic-bugs#481]
#### 1.1. Description
Dragon's breath is currently getting dispelled by Enhacement Shaman's talent Earthen power, which is only supposed to dispel slows

  #### 1.2. How to Reproduce
           1. Use dragon's breath while earthen totem is up and the shaman is talented into earthen power
           2. Wait for earthen totem to tick
           3. Voilà

#### 2.1. Description
Dragon's breath applies 3 effects:
Effect #1: School Damage (Fire)
Effect #2: Apply Aura: Confuse 
Effect #3: Apply Aura: Decrease Run Speed 

Earthbind totem should optimally only dispel the Effect #3, even though it never did neither on WotLK retail, old AT or warmane.

**Comment by Aggrend** [comment]
This matches 3.3.5 and is not a bug. Because of how Dragon Breath is built, it's both a snare AND a disorient, hence it being removed. We will be updating the tooltip of dragon breath in our next full patch to note the snare effect aspect of it and hopefully alleviate some confusion.

**Comment by Naoshytm** [comment]
As I said, there's a snare AND a disorrient effect but that definetly doesn't mean that the DISORIENT effect should be dispelled. Only the snare effect.

**Comment by Naoshytm** [comment]
@Aggrend, If what you said was indeed a bug, Earthen power should dispel ALL disorients effects, since in wotLK, all of them have a snare effect to. Such as Blind:

Effect #1 | Apply Aura: Decrease Run Speed 
Effect #2 | Apply Aura: Confuse

I'd like you to revisit this post. If it is indeed intended, i'll report Blind or any other double disorient/snare effect not getting dispelled.
