### ISSUE TITLE
[BUG] One or more Four Horseman sometimes don't move off the platform on pull in Naxx

### ISSUE THREAD

**Issue by carlpoole** [JamminL/wotlk-classic-bugs#482]
#### 1.1. Description
In Naxx Four Horseman - the 4 boss NPCs are expected to run to their respective corners on pull. Last night in our Naxx 25, Zeliek did not run to his corner, and stood on the center platform for the entire duration of the fight.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Begin the 4hm encounter.
           2. Not sure if this is every encounter, can only do 1-2 lockouts per week to test.
  #### 1.3  Source Material
Logs https://classic.warcraftlogs.com/reports/Gvx3mgkM7VDW1XCy#fight=18
VOD timestamp https://www.twitch.tv/videos/1628055054?t=00h39m47s
#### 2.1. Description
4hm boss NPCs should run to their respective corners.
  #### 2.2 Source Material
  log from last week https://classic.warcraftlogs.com/reports/nNF4r7zjKpabhAqd#fight=17
VOD from fight last week with expected behavior https://www.twitch.tv/videos/1621730099?t=00h48m41s

**Comment by caccavale** [comment]
Thanks for this.  Blizz is aware and its to be fixed.
