### ISSUE TITLE
[BUG] Penance redirected on feign death

### ISSUE THREAD

**Issue by Oddwaffletbc** [JamminL/wotlk-classic-bugs#483]
#### 1.1. Description
When you penance a friendly hunter and he uses feign death mid penance, your penance is automatically redirected to yourself for the remaining duration.
E.g. If he feign deaths after the first tick the remaining two ticks Will heal myself instead of him.

  #### 1.2. How to Reproduce
           1. Use penance on a hunter
           2. Hunter uses feign death mid cast
           3. Cast is redirected 

  #### 1.3  Source Material
Not yet

#### 2.1. Description
Hunter should receive all 3 ticks of the penance.
  #### 2.2 Source Material
Not yet

**Comment by Aggrend** [comment]
This is a NAB/WF. In reference the cast is simply cancelled and does not continue to heal the hunter. This behavior does not currently match reference perfectly, but we aren't going to be fixing that part of this right now.
