### ISSUE TITLE
[BUG] meta gems are able to be swapped in combat to double dip on meta bonuses

### ISSUE THREAD

**Issue by Teebown** [JamminL/wotlk-classic-bugs#484]
#### 1.1. Description
Haste meta gems are currently not sharing an internal cooldown, and the internal cooldown isn't triggered on swapping gems.  Players are able to macro swap gems in combat to gain benefits from multiple meta gems and/or to receive full uptime of meta gem haste procs.
  #### 1.2. How to Reproduce
     
           1. Use a haste meta gem until a proc is observed
           2. Use a macro or the gem interface to swap your meta to either a crit damage or a new haste meta gem.
           3. Continue to attack and observe another proc within the icd, or increased damage due to the crit damage meta.
  #### 1.3  Source Material

### 2. Expected Behavior
Either gems shouldn't be swappable in combat or there should be a common ICD to eliminate gains possible from doing this.
  #### 2.1. Description
No historical reference could be found, but this seems like a thing that should not be possible - swapping gear in combat isn't possible, and swapping items in combat should mostly share ICD (another issue is in pertaining to weapon swaps not triggering icd).
  #### 2.2 Source Material
No original wrath data pertaining to this issue could be found.

**Comment by Bakurersu** [comment]
This is also currently allowing players to stack the haste buff from both Thundering Skyflare Diamond (wrath haste meta gem) and Thundering Skyfire Diamond (TBC haste meta gem)
![image](https://user-images.githubusercontent.com/109535615/198495392-6b1caded-8ae0-4d61-a650-83e46a04dfb0.png)

**Comment by TheDunds** [comment]
Adding onto this 
You can "meta gem drink walk" 
Swapping helms with the beaming earthsiege diamond or even just activating the gem by re-socketing it or setting your gemming up in a certain way that you can deactivate and re active your meta with a wand/weapon during combat 
This even can be used in pvp to gain 2% mana per wand/weapon swap during combat 

https://youtu.be/ZfXfUvNoQrM

**Comment by Teebown** [comment]
https://wago.io/d1h5gxmb-
https://wago.io/X0_lwu2kX
Several WeakAuras now exist to automate or semi automate swapping gems in combat.  First link posted requires a macro keypress, second one automatically swaps after a proc of the meta.

**Comment by JamminL** [comment]
Fixed on PTR 3.4.2.49442
