### ISSUE TITLE
[BUG] Glyph of Trueshot Aura does not provide additional crit% to aimed shot

### ISSUE THREAD

**Issue by ggrochow** [JamminL/wotlk-classic-bugs#485]
#### 1.1. Description
  The increased critical strike chance on aimed shot is not improved by the glyph of trueshot aura.
  
  #### 1.2. How to Reproduce
Shoot a target dummy with the trueshot aura glyph with aimed shot 200 times review crit % of aimed.
Do a set of aimed shots without glyph for a set of results to compare to
Do a set of aimed shots with the glyph socketed in and trueshot aura active
Do a set of aimed shots with the glyph socketed in and trueshot aura inactive 

  #### 1.3  Source Material
Personal testing, details results of shooting the heroic training dummy in the above 3 cases.

[Case 1](https://i.imgur.com/Xx4qX4J.png) - TSA glyph not socketed in
[Case 2](https://i.imgur.com/PfcocGU.png) - TSA glyph socketed in and trueshot aura inactive
[Case 3](https://i.imgur.com/AZdNXBJ.png) - TSA glyph socketed, trueshot aura active
In these tests I am wearing the same gearset, with no crit% chance altering trinkets, I have 36.89% char sheet ranged crit%, and in all tests my autoshot crit rate in details is 33%

although my sample size is not large enough to draw definite conclusions, I would expect what I believe to be a 10% increase to have a much greater impact here

#### 2.1. Description
We should observe some measurable increase in critical strike chance of aimed shot when compared to the two cases where the glyph is not active. 

  #### 2.2 Source Material
[Glyph Description](https://www.wowhead.com/wotlk/spell=56842/glyph-of-trueshot-aura) implies it should alter the critical strike chance of aimed shot

**Comment by skinnay-dev** [comment]
did some testing myself, seems to be working fine?

without glyph: https://cdn.discordapp.com/attachments/1006662477167206552/1034709947549757500/notsaglyph.png 
with glyph: https://cdn.discordapp.com/attachments/1006662477167206552/1034709966520582164/tsaglyph.png
