### ISSUE TITLE
[PVE] [BUG] [Core] [Priest] Shadowfiend spawn causes gamebreaking issues

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#489]
#### 1.1. Description

First of all, this is aparently already known behind the scenes but since this is going on for a **LONG** time now with no fix on sight, I feel like it deserves its own thread.

There are **multiple** issues regarding shadowfiend, however this topic is just about **two** of them - the issues it causes when the shadowfiend unit is created.

-------------

**1. If you spawn shadowfiend next to someone who is not in combat, the spawn will put such person in combat.**

https://streamable.com/j9kpqg Here you can see a priest who sits full blind and is not in combat, then he is put into combat the moment shadowfiend spawns - there is no other source of combat there and it happens in the exact same frame as shadowfiend is created, no doubt that this is the cause.

The shadowfiend also immediately removes stealth and/or vanish from rogues/druids that are nearby the shadowfiend spawn location. https://streamable.com/ywrh3p

**2. If you spawn shadowfiend next to a CC-ed Player, such CC will immediately break , even though the shadowfiend is casted at a completely different Player**

https://clips.twitch.tv/ProtectiveThankfulMagpieTheRinger-eGjnyRodeIgwcHED Here you can see a Feral druid who sits full blind and the moment shadowfiend spawns on his priest (while the shadowfiend was put on Passive mode + I was spamming /petattack macro onto his priest) the Blind breaks instantly as soon as shadowfiend unit is created in the map.

----------

Aparently, these 2 issues are caused by the shadowfiend 1) triggering AOE combat to anyone nearby its spawn location 2) randomly attacking nearby enemy units no matter what mode the fiend is set on and no matter what unit the fiend is casted on.

These issues were not present since day of 1 beta, but it looks like they were present since around the launch, so they were caused by some botched hackfix/attempt to fix something else (maybe the infinite combat stuck bug https://github.com/JamminL/wotlk-classic-bugs/issues/228#issuecomment-1229183429).

  #### 1.2. How to Reproduce

           1. Get 2 enemy players next to each other.
           2. Cast shadowfiend on 1 of them.
           3. Observe ®Classic™ behavior.

#### 2.1. Description

Shadowfiend should not trigger aoe combat / CC removal on its spawn.

**Comment by JamminL** [comment]
Edited the post to remove the associated PS bug, had nothing to do with this. Marking it as a bug.

**Comment by Evolvee** [comment]
bump, gamebreaking

**Comment by Evolvee** [comment]
Shadowfiend spawn also reveals stealthed NPCs nearby! HUUUUuuuuge **PVE** ISSUE !!

**Comment by JamminL** [comment]
Fixed PTR 3.4.2.49563

**Comment by Evolvee** [comment]
https://clips.twitch.tv/ThirstySwissSandwichAllenHuhu-S6F_bpgzJz6PrzXM

Fixed on PTR, Bugged on Live... round 6?

**Comment by JamminL** [comment]
> https://clips.twitch.tv/ThirstySwissSandwichAllenHuhu-S6F_bpgzJz6PrzXM
> 
> Fixed on PTR, Bugged on Live... round 6?

Tested it, seems fixed on live. If you have more information on how to reproduce it I'll reopen.
