### ISSUE TITLE
[BUG] Glyphed Water Elemental "snapshots" even after switching specs

### ISSUE THREAD

**Issue by yurpcraft** [JamminL/wotlk-classic-bugs#49]
#### 1.1. Description

When glyphed, water elemental will remain out permanently even when switching to a spec without water elemental or its associated glyph.

  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Glyph Water Elemental
           2. Summon Water Elemental
           3. Switch to spec without water elemental talented or glyphed}
  #### 1.3  Source Material
More details available here: https://github.com/yurpcraft/wotlkbeta-mage/issues/26
![image](https://user-images.githubusercontent.com/12848366/175720146-4dded586-5327-4f31-a3d7-b0c502bc8870.png)
![image](https://user-images.githubusercontent.com/12848366/175720159-08c05f2d-de9b-4e28-bb61-8d003f5b61b4.png)
In addition, this elemental remains summoned even when switching zones
![image](https://user-images.githubusercontent.com/12848366/175720165-2efe7e07-37d0-4351-8494-e260243cf603.png)
#### 2.1. Description
When not glyphed or talented, water elemental should not be summoned.
  #### 2.2 Source Material

**Comment by JamminL** [comment]
Fixed
