### ISSUE TITLE
[BUG] "The Undying" of Naxxramas

### ISSUE THREAD

**Issue by Loregon** [JamminL/wotlk-classic-bugs#495]
#### 1.1. Description
If someone dies on boss, make a full wipe, refresh naxx, continue to complete achievement.
  #### 1.2. How to Reproduce
           1. Make full wipe on any boss except the first one (don't die before that).
           2. Refresh naxx.
           3. Don't die anymore, if someone died, repeat step 1 and 2.
           4. Get an achievement.
#### 2.1. Description
Updating the raid after killing the first boss should not update the trigger of deaths. Most likely also works at 25.

**Comment by Vishiswaz** [comment]
How did you do step 2? "Refresh naxx"?

**Comment by Loregon** [comment]
> How did you do step 2? "Refresh naxx"?

Exit raid or game and RL refresh naxx.

**Comment by NuptupTDOW** [comment]
> > How did you do step 2? "Refresh naxx"?
> 
> Exit raid or game and RL refresh naxx.

I believe they are meaning they leave Naxx, and raid leader does a "Reset Instances" and that is the "refresh" they're talking about. Though.., that shouldn't really _do_ anything for a raid, so it might just be as simple as everyone walking out and back in.

**Comment by Loregon** [comment]
> > > How did you do step 2? "Refresh naxx"?
> > 
> > 
> > Exit raid or game and RL refresh naxx.
> 
> I believe they are meaning they leave Naxx, and raid leader does a "Reset Instances" and that is the "refresh" they're talking about. Though.., that shouldn't really _do_ anything for a raid, so it might just be as simple as everyone walking out and back in.

Oh my mistake if on the english client it is "Reset"

**Comment by Vishiswaz** [comment]
My group tried this and it didn't do anything.

**Comment by JamminL** [comment]
Its fixed.
