### ISSUE TITLE
Buffs instead of debuffs shown adjacent to the pet frame[BUG]

### ISSUE THREAD

**Issue by Homerjayx** [JamminL/wotlk-classic-bugs#498]
#### 1.1. Description
Below the pet frame of pet classes buffs are shown and not debuffs.
  #### 1.2. How to Reproduce
1. Play a pet class
2. Buff it to see buffs below the pet frame
3. See that buffs are shown
  #### 1.3  Source Material
![image](https://user-images.githubusercontent.com/39262303/197651067-752533b2-fbd8-4d87-9f19-a10104e70bca.png)

#### 2.1. Description
Debuffs should be shown, not buffs.
  #### 2.2 Source Material
![image](https://user-images.githubusercontent.com/39262303/197651176-72faca50-d87e-42aa-8036-23ee648c9e17.png)

Screenshot taken from the video below from 3.3.5a

https://youtu.be/Sb-PFTqYHPw?t=641

**Comment by Evolvee** [comment]
https://github.com/JamminL/wotlk-classic-bugs/issues/362
