### ISSUE TITLE
[BUG] Arcane Missiles Face

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#50]
#### 1.1. Description
If you turn away from your target during Arcane Missiles cast, it'll keep casting but no missiles will be launched.
  #### 1.2. How to Reproduce
           1. Cast Arcane Missiles at a target facing you
           2. Turn away from your target
           3. See how the cast continues but missiles won't be thrown out
  #### 1.3  Source Material
https://clips.twitch.tv/SuaveCovertVanillaPermaSmug-B3_aYNTdVx289B7t
#### 2.1. Description
It should keep casting and keep throwing missiles even though you're not facing your target
  #### 2.2 Source Material
Nothing yet

**Comment by Aggrend** [comment]
Calling this NAB for now. Verified in reference for 3.3.5 and this behavior is the same.

**Comment by JamminL** [comment]
Closed as NAB
