### ISSUE TITLE
[BUG] [Arena] [NPC] [Misc] The instanced Dalaran Arena Croc has a faulty waypoint path

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#510]
#### 1.1. Description

https://clips.twitch.tv/GloriousUglyAlligatorRiPepperonis-FJQqHlJHv_6us51k
https://clips.twitch.tv/SnappyOilyCurlewUWot-TfRNDp9DWNF_LvwT

In both of these clips you can see the exact same scuffed crocodile movement pattern where the croc just flies in the air and ignores any pathfinding between 2 separate waypoints. _(probably caused by a scuffed last waypoint of the whole path, or the croc is about to despawn but before it does it starts the waypoint path all over again causing this telepor-tish behavior due to the huge Z difference between first and last waypoint)_

  #### 1.2. How to Reproduce

           1. join into dalaran arena
           2. observe the croc
         
#### 2.1. Description

I guess crocodiles shouldnt fly?

**Comment by Evolvee** [comment]
https://us.forums.blizzard.com/en/wow/t/wrath-classic-patch-notes-version-341/1490168

rip Croc

**Comment by Miyur1** [comment]
Still not fixed
https://youtu.be/speoFipa4dA

**Comment by Evolvee** [comment]
The 1 year long investigation into the arena Croc flying across the entire area since day 1 is still ongoing, however it is not expected for the issue to be resolved.
