### ISSUE TITLE
[BUG] Arena point cap is 5k should be 10k

### ISSUE THREAD

**Issue by Dverikk** [JamminL/wotlk-classic-bugs#513]
#### 1.1. Description 
  The maximum points you can have on one char is set to 5000, on original wotlk it was 10 000.
  This is a problem because some weapons cost 4500 arena points and if you have just below 4500 arena points, get 1500 arena points from the weekly flush, you lose a lot of arena points.

  #### 1.2. How to Reproduce      
           1. Do this
           Log at lvl 80 char and mouseover the arena point cap in the ''Currency'' tab.
        
  #### 1.3  Source Material
 https://www.wowhead.com/forums/topic/max-arena-points-able-to-keep-154306
#### 2.1. Description
10 000 cap instead of 5000
{Describe how that mechanic/spell/npc should be working, in detail}
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by watchyoursixx** [comment]
hotfixed the other day
