### ISSUE TITLE
[BUG] Weapon swapping OUT-OF-COMBAT in arena triggers GCD

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#518]
#### 1.1. Description
In arena, weapon swapping will trigger a GCD even if out of combat.
  #### 1.2. How to Reproduce
1. Join arena
2. Wait for arena to start (after prep)
3. Try swapping weapons while still out of combat
  #### 1.3  Source Material
-
#### 2.1. Description
GCD should only be triggered by weapon swapping if player is in combat, in arena or not.
  #### 2.2 Source Material
-

**Comment by Miyur1** [comment]
Looks like it's NAB
https://www.warcraftmovies.com/movieview.php?id=143993
5:45, rogue swap dagger out of combat, GCD starts

**Comment by JamminL** [comment]
> Looks like it's NAB https://www.warcraftmovies.com/movieview.php?id=143993 5:45, rogue swap dagger out of combat, GCD starts

Add my discord Jammin#8283
