### ISSUE TITLE
[BUG] Hammer of Wrath is using Ranged Attack Power

### ISSUE THREAD

**Issue by Foknetics** [JamminL/wotlk-classic-bugs#519]
#### 1.1. Description
Currently Hammer of Wrath is using Ranged Attack Power in it's damage calculation
  #### 1.2. How to Reproduce
           1. On a paladin with different Ranged AP then Melee AP
           2. Cast Hammer of Wrath
           3. See that the damage does not fall within the tooltip range (which is calculated off of melee AP)
  #### 1.3  Source Material
[Forum Bug Post](https://us.forums.blizzard.com/en/wow/t/hammer-of-wrath-using-ranged-attack-power-instead-of-melee-attack-power/1395779)

[Gear set](https://eightyupgrades.com/set/jGR8tfjkemobf2a1QBeePy)
Melee Attack Power - 3549
Spell Power - 1064
Ranged Attack Power - 1568 (note eighty upgrades currently does not report this correctly)

Following the tooltip and using Melee Attack Power to calculate the expected damage range:
```
1139 -> 1257 + .15*1064 + .15*3549 | 1139 -> 1257 + 159.6 + 532.35
1139 -> 1257 + 159.6 + 532.35      | 1830.95 -> 1948.95
1830.95 -> 1948.95 * 1.03          | 1885.8785 -> 2007.4185 (3pt crusade) (3%)
1885.8785 -> 2007.4185 * 1.03      | 1942.4848 -> 2067.6411 (3pt crusade) (3% humanoid)
1942.4848 -> 2067.6411 * 1.03      | 2000.7593 -> 2129.6703 (sanctified ret) (3%)
2000.7593 -> 2129.6703 * 2.0       | 4001.5186 -> 4259.3406 (crit) (200%)
4001.5186 -> 4259.3406 * 1.03      | 4121.5642 -> 4387.1208 (meta gem) (3% on crit)
```
When tested in game however I see crits such as: 3484, 3462, 3538, 3662, 3710 3668, 3462, 3570, 3711
If we recalculate the formula using Ranged Attack Power instead:
```
1139 -> 1257 + .15*1064 + .15*1568 | 1139 -> 1257 + 159.6 + 235.2  
1139 -> 1257 + 159.6 + 235.2       | 1533.8 -> 1651.8
1533.8 -> 1651.8 * 1.03            | 1579.814 -> 1701.354 (3pt crusade) (3%)
1579.814 -> 1701.354 * 1.03        | 1627.2084 -> 1752.3946 (3pt crusade) (3% humanoid)
1627.2084 -> 1752.3946 * 1.03      | 1676.0247 -> 1804.9665 (sanctified ret) (3%)
1676.0247 -> 1804.9665 * 2.0       | 3352.0493 -> 3609.933 (crit) (200%)
3352.0493 -> 3609.933 * 1.03       | 3452.6108 -> 3718.23099 (meta gem) (3% on crit)
```
Which matches our actual values see in game which all fall within the 3452 to 3718 range. Cross posted from

#### 2.1. Description
Hammer of Wrath uses Melee Attack Power
  #### 2.2 Source Material
AP/SP in game:
![image](https://user-images.githubusercontent.com/21084811/200338964-a5e2deae-9249-4597-bcf1-3c3dd2e9e673.png)

Tooltip in game:
![image](https://user-images.githubusercontent.com/21084811/200339070-a82da1b3-0777-4fe6-a879-4d2524ebdd8d.png)

Math for tooltip:
```
(1139 + 0.15 * Spell power + 0.15 * Attack power) to (1257 + 0.15 * Spell power + 0.15 * Attack power)
(1139 + 0.15 * 1064 + 0.15 * 3549) to (1257 + 0.15 * 1064 + 0.15 * 3549)
(1139 + 159.6 + 532.35) to (1257 + 159.6 + 532.35)
(1139 + 159.6 + 532.35) to (1257 + 159.6 + 532.35)
1830 to 1948
```

**Comment by watchyoursixx** [comment]
hotfixed 11/18
