### ISSUE TITLE
[BUG] Shield Bash + Gag Order

### ISSUE THREAD

**Issue by Kostickaz** [JamminL/wotlk-classic-bugs#524]
#### 1.1. Description
Whenever target is affected by slow immunity ability (like Hand of Freedom), it also can't be affected by Gag Order from Shield Bash. Please note that Gag Order can still be applied from Heroic Throw. It seems like Gag Order effect for Shield Bash is coupled by daze effect, which Shield Bash provides, meaning that if the target can't be affected by daze effect from Shield Bash, then it doesn't apply the silence effect from Gag Order.

  #### 1.2. How to Reproduce
           1. Duel any Paladin
           2. Let Paladin use Hand of Freedom on himself
           3. Use Shield Bash
           4. Review that Gag Order effect was not applied}
  #### 1.3  Source Material
(https://clips.twitch.tv/JazzyEnergeticPanSeemsGood-_NlktuRi0cJ_61Ja)
#### 2.1. Description
As long as the Shield Bash is successful (it's not blocked/dodged/parried), it should apply silence effect from Gag Order.
  #### 2.2 Source Material
I wasn't able to really find any reasonable material, but I hope this isn't really rocket science to tell, that silence effect shouldn't be tied to daze effect from Shield Bash.

**Comment by Miyur1** [comment]
Yes, this is a bug
https://youtu.be/EvvBBLHrSTY?t=362

**Comment by Miyur1** [comment]
NAB
https://youtu.be/hPkf1JvEX68?t=192
https://youtu.be/O7QzJQx3XMs?t=142
