### ISSUE TITLE
[BUG] Hamstring on target affected by Frost Trap

### ISSUE THREAD

**Issue by Kostickaz** [JamminL/wotlk-classic-bugs#525]
#### 1.1. Description
While target is affected by Frost Trap effect, it is immune to Hamstring effect. If target, who is affected by Hamstring effect gets then affected by Frost Trap effect, the Hamstring effect gets removed (it seems to get overwritten).
  #### 1.2. How to Reproduce
          {1. Get in group with Hunter
           2. Use Hamstring on enemy target
           3. Let the target get affected by Frost Trap effect from Hunter (here the Hamstring effect will get removed)
           4. Try to apply Hamstring effect on the enemy target, who is still affected by the Frost Trap effect (here the target will be immune to Hamstring effect)}
  #### 1.3  Source Material
https://clips.twitch.tv/DreamyDarlingOryxResidentSleeper-g_s4pC2lbMIigQ7c
#### 2.1. Description
Even if the target is affected by Frost Trap effect, there should be possibility to also apply Hamstring effect at the same time (even though in that moment it will not have any additional effect in terms of slow efficiency) and also the Hamstring effect should remain on the target, even if it then gets then affected by Frost Trap. 
  #### 2.2 Source Material
I didn't find any reasonable material from original Wrath, but Hamstring should follow same rules like other slows, where you can apply multiple types of slow effects on the same target without them overwriting each other (even though you won't get any extra effect from multiple types of slows of same efficiency at the same time.

**Comment by Evolvee** [comment]
> I didn't find any reasonable material from original Wrath, but Hamstring should follow same rules like other slows, **where you can apply multiple types of slow effects on the same target without them overwriting each other** (even though you won't get any extra effect from multiple types of slows of same efficiency at the same time.
> 

This is not true at all. Sounds like a pre-2015 private server behavior.

It would be true only for auras with multiple effects. If both spell only have 1 effect, then the one which is bigger overwrites the smaller. If both effects have the same value, the one with longer duration overwrites the shorter.

Unless hamstring got added some additional effects, I dont see how it would not be overwritten by frost trap.

**Comment by Kostickaz** [comment]
> > I didn't find any reasonable material from original Wrath, but Hamstring should follow same rules like other slows, **where you can apply multiple types of slow effects on the same target without them overwriting each other** (even though you won't get any extra effect from multiple types of slows of same efficiency at the same time.
> 
> This is not true at all. Sounds like a pre-2015 private server behavior.
> 
> It would be true only for auras with multiple effects. If both spells only have 1 effect, then the one which is bigger overwrites the smaller. If both effects have the same value, the one with longer duration overwrites the shorter.
> 
> Unless hamstring got added some additional effects in wotlk, I dont see how it would not be overwritten by frost trap.

I actually did additional research on my side and you are right. Even though it partially looks strange that Frost Trap would overwrite it since people can just walk in and out on demand, but it doesn't matter since there is certain duration on it (30s or something). So yeah, I guess this one can be locked.
