### ISSUE TITLE
[BUG] Judgements of the Just proc'ing seals.

### ISSUE THREAD

**Issue by hvownij** [JamminL/wotlk-classic-bugs#527]
#### 1.1. Description
With 2/2 in Judgements of the Just in the Prot. talent tree, Judgements can now proc seals.
  #### 1.2. How to Reproduce
Build a talent tree with 2/2 Judgements of the Just
Go to Org. or any city with target dummies.
Cast a Judgement
View the proc'ing of seal of command on multiple targets
Build a talent tree with 0/2 Judgements of the Just
Go to Org. or any city with target dummies.
View NO proc'ing of seal of command on multiple targets.
  #### 1.3  Source Material
(https://cdn.discordapp.com/attachments/1007472331431620608/1040819908038107187/image.png)
#### 2.1. Description
When you cast a Judgement, seals should not proc. With or without 2/2 Judgements of the Just 
  #### 2.2 Source Material

**Comment by JayJay-110** [comment]
This is not a bug, see #93

**Comment by Miyur1** [comment]
NAB, Judgments of the Just should proc seals
https://www.warcraftmovies.com/movieview.php?id=159747 
6:32, paladin presses judgment on 2 stacks of Seal of Vengeance
1. Deals 253 damage, this is periodic damage from seal of vengeance
2. Judgment deals 1079 damage
3. Judgments of the Just triggers and the damage goes into absorption

https://www.warcraftmovies.com/movieview.php?id=155093
6:47, presses Judgment at 3 stacks of seal, 
1. Judgment deals 965 damage
2. Proc addition seal damage from Judgments of the Just, deal 191 damage 
3. Deals 314 damage, this is periodic damage

https://wowwiki-archive.fandom.com/wiki/Seal_of_Command_(old)
Under normal conditions Seal of Command will apply extra holy damage to the initial target, but this damage will not "spread" onto two nearby targets. However, if the paladin has spent at least 1 point in [Judgements of the Just], the spread will be applied, causing Judgements to damage three different targets when Seal of Command is active.
