### ISSUE TITLE
[BUG] World Buffs usable in raid

### ISSUE THREAD

**Issue by caccavale** [JamminL/wotlk-classic-bugs#529]
Currently, the following buffs of over 30s duration can be collected through Mind Control or Spell Steal and brought into raid encounters:
- Arcane Destruction (32689, 38647)
- Arcane Focus (51777)
- Aura of Arcane Haste (50182)
- Blessing of Blackfathom (8733)
- Blood of Sseratus (54482)
- Blind Faith (56410)
- Fel Armor (44520, 44977)
- Fiery Intellect (35917)
- Fire Destruction (38648)
- Flame of the Seer (52281)
- Frost Destruction (38649)
- Holy Fury (34809)
- Metanoia (57524)
- Might of Malygos (51800)
- Steal Magic (30037)
- Vir'aani Concentration (33839)
- Whirling Winds (54589)
- Zeal (51605)

Expected behavior is cleansing the buffs on instance zone in or encounter start. 

Buffs from consumables:
- Crystal Yield (15235)
- Scourgebane Draught (28486)
- Scourgebane Infusion (28488)
- Tracker's Ferocity (30848)

Unsure of expected behavior for consumables.

**Comment by caccavale** [comment]
Added Crystal Yield.  Couple people have mentioned this seemed to work into Cata.

**Comment by Aggrend** [comment]
These should be reported in advanced combat logging (as of about a week ago) allowing Khira to ban logs using them for now. We'll put in a full fix for Ulduar.
