### ISSUE TITLE
[BUG] Pet focus regen

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#530]
#### 1.1. Description
Pet focus regeneration is 10 per sec
  #### 1.2. How to Reproduce
  #### 1.3  Source Material
https://clips.twitch.tv/AstuteInventiveYogurtHassaanChop--0XzNuN3yH7c1BF9
#### 2.1. Description
Pet focus regeneration should be 5 per sec
  #### 2.2 Source Material
https://wowwiki-archive.fandom.com/wiki/Focus?oldid=2326992
When used, it regenerates fairly slowly (5 focus every second). 

https://bigredrhino.wordpress.com/pet-stats/
Your pet has 100 focus when summoned, and regenerates 5 focus per second. Bestial Discipline doubles this to 10 focus per second. Your pet’s focus regeneration is unaffected by the pet’s combat status.

https://youtu.be/_BWeGKTnUUg?t=85
regenerated 50 focus in 10 seconds
https://youtu.be/0SKhaCm42OQ?t=17
https://www.warcraftmovies.com/movieview.php?id=145315
2:32

**Comment by TheDunds** [comment]
Fixed as of current ptr 

https://www.wowhead.com/wotlk/news/wotlk-classic-ptr-ulduar-raid-development-notes-330870?webhook
