### ISSUE TITLE
[BUG] [Core] [Spell] Charge/Intercept path should be range-limited

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#533]
#### 1.1. Description

Currently charge/intercept doesnt seem to be range limited and you can force the server to do some crazy long charges as long as you have LoS.

https://user-images.githubusercontent.com/1942409/202585890-ca6d3eeb-8fd0-450a-b5f7-ead7b5e02c7a.mp4

This should not be possible, charges should have internal limit on how far their pathfinding can be calculated, if a charge path would exceed such limit, the server should throw out "invalid path" error and the spell should not go off.

I assume this is an issue with the pathfinding mechanism rather than the charge itself.

  #### 1.2. How to Reproduce

Too "random" to be easily reproducable.

  #### 1.3  Source Material
∅

**Comment by Evolvee** [comment]
also wtf is this https://clips.twitch.tv/PerfectRenownedLaptopLeeroyJenkins-2JMyehfXp7WKGs-k

**Comment by JamminL** [comment]
I'll mark this as Needs Research, I know what's happening and I'm confident it's the same behavior as og wotlk

**Comment by Aggrend** [comment]
This is going to be NAB/WF for now. This is some pretty deep engine code and it's not likely safe to fix at the moment. We can't verify with total confidence, but we also believe this is likely authentic behavior.
