### ISSUE TITLE
[BUG] Only one deep wound will be applied when multiple critical strikes happens at the same time

### ISSUE THREAD

**Issue by RobFalfa** [JamminL/wotlk-classic-bugs#536]
#### 1.1. Description
If multiple critical strikes happens at the same time only one will be applied to deep wounds. This often occur when running dual wield and both weapons sync or when both weapons critical strike from a whirlwind or when running sword specialization and the attack and extra hit both critical strike.

  #### 1.2. How to Reproduce
           1. Equip two weapons with the same speed
           2. Sync weapons, easy with shattering throw or swap weapons
           3. Wait for both main hand and offhand to critical strike and notice how only one deep wound will be applied, the last one in combat log.
  #### 1.3  Source Material
Main hand and offhand critical strike and only offhand apply deep wound.
![bild](https://user-images.githubusercontent.com/103991844/202877905-2fddf13a-395e-4ccd-a42d-a87012aa2f30.png)

Attacking with a whirlwind and both weapons critical strike and the melee attack at the same. Causing only the offhand of whirlwind to apply deep wounds.
![bild](https://user-images.githubusercontent.com/103991844/202877944-a6c6ab9c-02d2-48e2-9066-14583a57ba0d.png)

#### 2.1. Description
Every critical strike should apply deep wound, it is unintuitive for players loosing out on major damage because weapons happens to sync.

**Comment by JamminL** [comment]
NAB, please make a #somechanges post regarding this. This behavior was the exact same back in the day
