### ISSUE TITLE
[BUG] Hammer of Wrath now procs Seals

### ISSUE THREAD

**Issue by TheHate123** [JamminL/wotlk-classic-bugs#538]
#### 1.1. Description
Since the last hotfix where Hammer of Wrath was changed to scale with Melee Attack Power, it now procs Seals, something which it never did before and should not do.
  #### 1.2. How to Reproduce
         1. Find any mob.
         2. Get it below 20% health.
         3. Have any seal up (ex: vengeance / command)
         4. Observe how Hammer of Wrath produces a Seal proc.
  #### 1.3  Source Material
https://streamable.com/8ghpp0
At around 6 seconds in, I use the first Hammer of Wrath, which produces a Seal of Vengeance proc of 159 damage. You can tell it's not the dot because the dot ticks immediately after for 140 (16 resisted). Then I switch to Seal of Command and Hammer of Wrath the mob again from a distance at the 12 second mark. The Hammer immediately procs Seal of Command for 766 damage and finishes off the mob before the Hammer lands. You can clearly tell I was not in Melee range in both cases so there was nothing else to proc either of the Seals.
#### 2.1. Description
Hammer of Wrath is not a Melee ability, therefore it should not proc your Seals.
  #### 2.2 Source Material
 https://web.archive.org/web/20100505023450/http://elitistjerks.com/f76/t68951-retribution_updated_3_3_a
No mention of Hammer of Wrath ever doing this, and there is a specific line that states that only your melee swings, Crusader Strike and Divine Storm proc seals and nothing else.
 Quote from the thread: "In addition to seals scaling from both AP and SP, ALL seals can now be triggered from our instant melee attacks, DS and CS".

**Comment by Aggrend** [comment]
This is NAB. Thanks!
