### ISSUE TITLE
Memory Leak with CHAT_MSG_ADDON API

### ISSUE THREAD

**Issue by ZeChrales** [JamminL/wotlk-classic-bugs#541]
(original post auto closed on wow support forums, without any answer : https://eu.forums.blizzard.com/en/wow/t/memory-leak-with-chatmsgaddon-api/395585 )

#### 1.1. Description
Hello, in WOTLK Classic, when addons are trying to communicate between players, they send a lot of CHAT_MSG_ADDON messages. When there are a lot of messages (pvp like wintergrasp, big addons trying to sync data like TSM, raids …), the game start to freeze and become unplayable.
After some analysis and with the help of addons developers (like dbm), it seems that memory is increasing very very fast (more than 1MB/s during this kind of peak). It always happen when an addon receive lot of CHAT_MSG_ADDON messages.

  #### 1.2. How to Reproduce
An easy example to reproduce this issue, is to have DBM installed, and another addon like details, tsm, or whatever is going to receive messages. When some messages start to be received, memory is increasing slowly for DBM-core (something like 200KB every “big” message), until a garbage collector is used. DBM is not doing anything with these mesages, and does not store anything, because others prefixes are never subscribed by DBM (also, we see DBM here because it contains the deflate lib, and is the first addon loaded). This is where the memory leak happens.

Since the first post, we talked with a lot of players in multiple guilds, and we can't define when is triggered the memory leak. People with exact same list of addons, exact same weakauras, will have big freezes during a raid, but not at the same time. It seems to happen since Sunwell patch.
Activating the /etrace logs during a freeze show that a lot of chat_msg_addon are received. Also, using an addon for memory analysis or mouseovering the system icon, we can see that global memory increase more and more, and fps are reduced to <5 fps.

**Comment by Feper24** [comment]
Great find, hope it gets worked out. Does cpu cache help with that increased memory usage?

**Comment by volostyle** [comment]
Been dealing with this since WOTLK pre-patch in SWP. Would LOVE to see some traction from Blizzard's end on this.

**Comment by ZeChrales** [comment]
From a quick check of Questie code, they are also using the same api through Ace to exchange quests progress, and from comments they already had a really similar issue with Reputable ( https://github.com/Questie/Questie/issues/3540 ).
