### ISSUE TITLE
[BUG] Blood-caked blade proc have no internal cooldown

### ISSUE THREAD

**Issue by danniellos94** [JamminL/wotlk-classic-bugs#543]
#### 1.1. Description
Blood-caked blade proc have no internal cooldown.
  #### 1.2. How to Reproduce
          
           1.  Attack a dummy with two one handers.
           2. Be specced into blood-caked blade.
           3.  Observe no internal cooldown.
  #### 1.3  Source Material
https://classic.warcraftlogs.com/reports/VzJmaCDkLYNfwxZP#fight=10&type=damage-done&source=16&view=events

00:03.852 | Legian Blood-Caked Strike Patchwerk 323 |  
00:03.852 | Legian Necrosis Patchwerk 109 |  
00:04.004 | Legian Death and Decay Patchwerk *1662* |  
00:04.057 | Legian Frost Fever Patchwerk Tick 759 |  
00:04.057 | Bonemaw (Legian) Melee Patchwerk 620 |  
00:04.246 | Legian Melee Patchwerk *1558* |  
00:04.269 | Legian Blood-Caked Strike Patchwerk 456

#### 2.1. Description
There should be 3 seconds internal cooldown on this talent.
  #### 2.2 Source Material
{Video, Posts, etc..}

https://wowpedia.fandom.com/wiki/Blood-Caked_Blade
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-general/216666-ptr-3-1-0-patch-notes-alot-of-extra-info.html

**Comment by CharWS** [comment]
believe that was a ptr only change that never made it to live with the launch of 3.1.0, can see in the launch patch notes that there's no mention of it anymore https://web.archive.org/web/20090417033401/http://forums.worldofwarcraft.com/thread.html?topicId=16403300172&sid=1
https://web.archive.org/web/20090508164613/http://elitistjerks.com/f72/t53624-3_1_dk_relevent_patch_notes/

**Comment by danniellos94** [comment]
True,  I found it was only on ptr for someone that interested.

https://www.mmo-champion.com/threads/650579-Blood-caked-blade/page2

"There was an Internal CD on the PTR's before 3.1, but they took it off cause it was a huge Nerf to DPS."
