### ISSUE TITLE
[BUG] No sacred shield absorb after spellstealing it

### ISSUE THREAD

**Issue by laynerzy** [JamminL/wotlk-classic-bugs#549]
### 1. Current Behavior
After spellstealing sacred shield, the shield doesn't proc from damage.

  #### 1.1. How to Reproduce
           1. Have a mage spellsteal sacred shield
           2. Damage the mage
           3. Notice how sacred shield proc never procs

  #### 1.2  Source Material
N/A

### 2. Expected Behavior
Sacred shield should still work after the mage spellsteals it.
#### 1.2  Source Material
https://youtu.be/g0_2PuUmFDQ?t=102

**Comment by Dolamor** [comment]
https://youtu.be/eEDxMZemZsE?t=49

To add to this - there is another bug in classic **(closely linked to this one)** that makes rebuffing sacred shield remove the spellstolen one (which it doesn't in the video I posted).

00:51 (mage spellsteals the sacred shield)
00:57 (enemy hpal rebuffs warrior with sacred shield, the spellstolen one on mage doesn't disappear)

The way it works now in classic decently nerfs any double dps mage comps in 2v2.

Both my video and Laynerz's video is from 2010 May/July meaning latest patches (Season 8), that did not change anything with sacred shield/spellsteal mechanics.

**Comment by JamminL** [comment]
That one has been fixed

**Comment by Jgrenier91** [comment]
Part of this is still bugged.

**Comment by Jgrenier91** [comment]
Still bugged

**Comment by JamminL** [comment]
Fixed on PTR 3.4.2.49442
