### ISSUE TITLE
[BUG] Life Tap Tooltip

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#55]
#### 1.1. Description
Lifetap tooltip is outputting the formula instead of the value
  #### 1.2. How to Reproduce
           1. Hover over the tooltip
  #### 1.3  Source Material
https://imgur.com/a/Uxyizft
#### 2.1. Description
The value should be shown, not the formula
  #### 2.2 Source Material
N/A

**Comment by yurpcraft** [comment]
Still broken as of 3.4.0.44930
![image](https://user-images.githubusercontent.com/12848366/183665762-b42d473e-f20d-453b-9461-8c275bf9ceb8.png)

**Comment by yurpcraft** [comment]
![image](https://user-images.githubusercontent.com/12848366/184023104-5cdafe39-9867-4471-af55-308067bd0c83.png)
fixed in 3.4.0.45043
