### ISSUE TITLE
[BUG] Obliterate may consume one rune only

### ISSUE THREAD

**Issue by ennvina** [JamminL/wotlk-classic-bugs#553]
#### 1.1. Description
Frost Death Knight's Obliterate may either consume 2 runes (most of the time), or 0 runes (rarely) or 1 rune (almost never). The latter should never happen.
  #### 1.2. How to Reproduce
1. Cast Obliterate
2. Observe which runes were consumed
   - if 2 runes were consumed -> OK
   - if 0 runes were consumed -> OK
   - if 1 rune was consumed -> bug

Note: the exact conditions to trigger the bug is unknown. Sometimes I can cast a hundred Obliterates or more before seeing it again. But for sure I've witnessed it multiple times, and probably experienced it even more without noticing it.
  #### 1.3  Source Material
The following pictures were taken one after the other.
The first screenshot was taken right before Obliterate was cast:
![1](https://user-images.githubusercontent.com/75951742/205511192-60675b57-cce6-4f0c-8bd2-80f0a5c1b29d.png)
Obliterate is expected consume 2nd Blood rune (as Death rune) and 1st Frost rune.
The second screenshot was taken when Obliterate was just cast.
![2](https://user-images.githubusercontent.com/75951742/205511194-f0952c91-22e1-49cb-80f3-2768d762d2a1.png)
Only 1st Frost rune was consumed. The 2nd Death rune was not consumed, neither the almost-ready 1st UH rune (but looks ready on 2nd screenshot). Maybe the "almost-ready UH rune" is causing the bug?
#### 2.1. Description
Frost Death Knight's Obliterate is supposed to use either 2 runes or none:
- if attack hits: 1 Frost + 1 Unholy
- if attack misses (dodge/etc): no runes

When Dual Wielding, it doesn't matter whether the main hand or offhand attack misses. As long as there's a miss, both runes are refunded.
There is no plausible explanation about how Obliterate could consume 1 rune only.
  #### 2.2 Source Material
None other than common sense, and no known record of the unexpected behavior.

**Comment by CharWS** [comment]
looking at the default frames in the second screenshot the first frost and unholy runes are on cd from being used on the obliterate, so it seems the issue is with your weakaura

**Comment by ennvina** [comment]
@CharWS indeed you're right. Although I'm using the WA which is by far the most famous for runes in Wrath Classic (https://wago.io/RunesDK), maybe they've got a bug.
