### ISSUE TITLE
[BUG] Expertise rating is still truncated

### ISSUE THREAD

**Issue by vigo2** [JamminL/wotlk-classic-bugs#556]
#### 1.1. Description
With 213 expertise rating from gear and no other sources of expertise, you'd arrive at ~25.9835 expertise (via GetCombatRatingBonus(CR_EXPERTISE)) without truncating, or about 1 expected dodge in 24k melee attacks. In TBC, expertise rating was always truncated, leaving you with an effective 25 expertise in this case, or 1 expected dodge in 400 melee attacks. In WotLK, this shouldn't be the case anymore, as per testing done in the infamous "Retesting Hit Table Assumptions" thread from the Elitist Jerks forum.

  #### 1.2. How to Reproduce
Equip 213 expertise, and swing away. You'll get dogdes in line with the displayed 0.25% dodge chance effective (e.g. 1 expected dodge in 400 melee attacks).
          
  #### 1.3  Source Material
E.g. https://classic.warcraftlogs.com/reports/w6LP9HWdmJZgvcF3#fight=last&type=damage-done&source=3. This is a warrior with a 41/30/0 spec, foregoing both Weapon Mastery and Strength of Arms, and having 213 expertise rating equipped. I've tested various patch releases on a level 70 warrior with similar setup before, all with the same result.
![Screenshot 2022-12-07 at 09 24 00](https://user-images.githubusercontent.com/9415187/206127535-388a8509-b285-4f77-aafd-9708eb5bd1c1.png)
![Screenshot 2022-12-07 at 09 26 36](https://user-images.githubusercontent.com/9415187/206127601-cbd16130-ec90-43de-b007-550ff2fc5f71.png)

#### 2.1. Description
With expertise rating no longer truncating, I'd expect 1 dodge in ~24k swings.
 
  #### 2.2 Source Material
EJ's [Retesting hit table assumptions](https://web.archive.org/web/20100810064048/http://elitistjerks.com/f78/t38095-retesting_hit_table_assumptions/p3/#post1092985) thread. Testing was most likely done on Patch 3.1.0, but there's no reason to believe this was changed later on.

The thread has screenshots of 25k attacks vs. training dummy at 209 and 213 expertise rating:
![209ratinguv9](https://user-images.githubusercontent.com/9415187/206743870-54a92bfa-8581-4957-bacd-b95a9b154ab0.jpg)

![213ratingeb1](https://user-images.githubusercontent.com/9415187/206743906-0936612e-b5b2-4513-8827-e645fe8c9741.jpg)

With the following commentary:
> So, using the same Fischer's Exact Test we applied before, we find that the probability that the data can be observed by random chance is .00000000021 - aka, tremendously improbably. Thus, we can conclusively say that there is a difference in the dodge rate between the two data sets, and, as such, that expertise does not truncate.

I've had this bug reported on Magey's repository since August 23, but it's never been confirmed or denied as a bug, so I'm trying here as well.

It would make guides, sims, and the game more simple if expertise rating behaved like any other rating.

**Comment by CharWS** [comment]
should be fixed as of patch this week as per https://www.bluetracker.gg/wow/topic/us-en/1616136-wrath-classic-patch-notes-version-342/

**Comment by CharWS** [comment]
did a test with 213 expertise ~9000 melee swings, ~2000 special attacks, and saw only 1 dodge so does indeed look to be working properly now
