### ISSUE TITLE
[BUG] Incubus has pet talent tree

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#56]
#### 1.1. Description
The warlock new pet incubus has a pet talent tree displayed.
  #### 1.2. How to Reproduce
           1. Summon Incubus
           2. Check talents
           3. Find your pet talent tree
  #### 1.3  Source Material
https://imgur.com/a/4KBjVu0
#### 2.1. Description
There should not be talent trees for warlock pets
  #### 2.2 Source Material
N/A

**Comment by Aggrend** [comment]
Um, lol.

**Comment by yurpcraft** [comment]
Fixed as of 3.4.0.44930
![image](https://user-images.githubusercontent.com/12848366/183666228-8bda0440-e0db-48cd-ac1d-15ba6a90dcd6.png)
