### ISSUE TITLE
[#SomeChanges Suggestion] Wintergrasp PVP gear should also get an item-level increase

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#561]
All S6 PVP items got an item-level increase alongside pretty much all the PVE items dropped in the next phase (Ulduar). However, this does not seem to be the case with Wintergrasp gear.

If you compare the original item level with the new item level of S6 items, you can see that the bump is from 226 to 232 on offset and 232 to 238 on mainset. So the PVP items bump is _(only)_ +6 item levels while keeping the same set bonuses.

![image](https://user-images.githubusercontent.com/1942409/207286406-385d6e4b-7ffd-42d4-af20-d763b353e1ee.png)
![image](https://user-images.githubusercontent.com/1942409/207286647-2e03b788-2473-44d4-8274-734053182718.png)

If you compare Wintergrasp items though, you can observe that the item-level remains the same --> 213, which is an item level equivalent to Season 5 gear. 

![image](https://user-images.githubusercontent.com/1942409/207294836-43b001d1-57c0-45b9-b343-243db8843335.png)

---------------------

Without any item level increase, these items will become completely obsolete and in comparison with the newly bumped Season 6 items or PVE items, they will be completely useless. The difference between Wintergrasp offset is 19 item levels while the difference between Wintergrasp mainset is a staggering 25 item levels... Noone sane would pick WG gear.

![image](https://user-images.githubusercontent.com/1942409/207288966-1b6ac32d-fe1b-43df-af1c-8707217f3c75.png)

The proposition is to bump the WG gear to get the equivalent item-level _(or slightly lower)_ as all the other Phase 2 (Season 6) PVP items. In a perfect world, most of the PVP items should get an additional item-level increase in order to be able to even try to compete with the heroic PVE items but yeah..

------------------------------

**PROS:**

- common sense
- bigger gearing diversity, players get more choices for their equipment builds
- wintergrasp wont be rendered useless
- more WG activity

**CONS:**

- nada

**Comment by Evolvee** [comment]
Bump.

Lets not fuck this up (pls?), there is still 1 week to invest 5 minutes of one of your intern's time to change a couple of values in an item table of world DB and push the SQL on production repo.

**Comment by CaithUI** [comment]
great change, has to be done

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/213165809-df8b3dbb-240d-4483-a5cd-f2fdb1275d76.png)


Nevermind then, I guess the 5 min of work was too much to ask for.

Perhaps next expansion.

🤡🤡
