### ISSUE TITLE
[BUG]Thunderstorm can't be spell reflected

### ISSUE THREAD

**Issue by Dverikk** [JamminL/wotlk-classic-bugs#562]
#### 1.1. Description
If Thunderstorm is used on a warrior with Spell Reflection up the warrior gets knocked away.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Do this
           Duel ele shaman vs. warrior
           2. Do that
           Cast Thunderstorm while warrior has spell reflection up
          
  #### 1.3  Source Material
#### 2.1. Description
Shaman should take damage and be knocked back if cast close to a warrior with spell reflection up
  #### 2.2 Source Material
https://www.mmo-champion.com/threads/624196-Thunderstorm-amp-Spell-Reflection
https://www.wowhead.com/spell=23920/spell-reflection#comments Comment from [2008/10/23] (Patch 3.0.2)
https://www.mmo-champion.com/threads/658630-Spell-reflect-and-elemental

Some people are saying this was changed in Cata, I can't find anything about it being changed earlier in the patch notes or thte undocumented changes.

**Comment by Miyur1** [comment]
It only worked on old patches
https://youtu.be/UhX40s-lH3g?t=509
https://youtu.be/7ZJ-3SgDC70?t=197
You can see the author's comment under the video after a year:
-Its been changed now, but for a long time thunderstorm and aoe roots were both spellreflectable.
I think they just messed up a bit but its fixed now hurrah!
I still see warriors stand near cliffs and spellreflect.
And to this, i just laugh, and send them flying to their deaths

3.3.3:
https://www.warcraftmovies.com/movieview.php?id=158313 @ 1:49

3.3.5:
https://www.warcraftmovies.com/movieview.php?id=158897 @ 15:14
