### ISSUE TITLE
[BUG] Commanding Shout and Blood Pact stacks

### ISSUE THREAD

**Issue by RobFalfa** [JamminL/wotlk-classic-bugs#567]
#### 1.1. Description
Warriors Commanding Shout and Warlocks Blood Pact stack which they didn't in 3.3.5
  #### 1.2. How to Reproduce
1. Get Commanding Shout
2. Get Blood Pact
  #### 1.3  Source Material
![pact](https://user-images.githubusercontent.com/103991844/209404536-d6f28669-8aff-4aaa-9a4d-7c780610920b.png)
#### 2.1. Description
They should not stack.
  #### 2.2 Source Material
https://www.youtube.com/watch?v=CGB4WcIK2jM
45s into the video the player gains Blood Pact and his HP stays at 39.8k. This happens a couple of times during the fight.

**Comment by itsZvn** [comment]
The blood pact icon that you see in the video is coming from the warrior T10 2P set - https://www.wowhead.com/wotlk/spell=70854/item-warrior-t10-melee-2p-bonus
note that in the video there's a duration for that blood pact icon, indicates it's a buff from something.

Also there's a single lock there that's using felhunter and not imp (around 1:00 you can see all the pets behind the boss)

**Comment by Miyur1** [comment]
https://www.mmo-champion.com/threads/612981-Patch-3-0-2-On-Debuffs-Buffs-and-Raid-Stacking
- Health Buff: [Commanding Shout](http://wotlk.wowhead.com/?spell=47440), [Blood Pact](http://wotlk.wowhead.com/?spell=47982)

**Comment by Tharre** [comment]
No longer stacking on the PTR.
