### ISSUE TITLE
[BUG] Item Level Adjustment for Comet's Trail Active Not Increased

### ISSUE THREAD

**Issue by where-fore** [JamminL/wotlk-classic-bugs#568]
#### 1.1. Description
Comet's Trail active originally granted 726 haste rating. In the first round of ilvl bumps to 245, Comet's Trail active was bumped to 768 haste rating. In the second round of ilvl bumps to 252, Comet's Trail active was unchanged, still resting at 768 as it was at 245 ilvl, despite now being 252 ilvl.

  #### 1.2. How to Reproduce
          The In-Game Tooltip reads 768 haste rating, and the Wowhead Spell Data reads 768 haste rating as well.
![image](https://user-images.githubusercontent.com/108002636/209416564-ddc16f4b-07f4-4207-a1a7-17627930fb74.png)

  #### 1.3  Source Material
The original proc was 726 haste rating, confirmed from multiple sources such as old screenshots, mostly notably [a Wowhead comment:](https://www.wowhead.com/wotlk/item=45609/comets-trail#comments)
> By zapiks44 (15,415 – 5·37·115) on 2009/08/21 (Patch 3.2.0)		
> The proc from this trinket gives roughly 22% melee/ranged haste.

22% haste of course being 32.78 * 22 ~= 721.16.

There are old tooltips of a Comet's Trail with 612 haste rating, which seems to be an old tooltip bug that got corrected at some point, as per [this Wowhead comment.](https://www.wowhead.com/wotlk/spell=64772/comets-trail#comments)
> By thaer (616 – 3·7) on 2009/06/13 (Patch 3.1.3)		
> This is the proc you get from the trinket Comet's Trail, which drops off of Algalon 25 man.
> 
> Note: At this time, the equip of the trinket shows 612 haste as the buff when it is actually 726, as shown on this page.

#### 2.1. Description
726 at 239 ilvl, * 1.06 to reach 245 ilvl should be ~769.56. *1.07 to reach 252 ilvl should be ~823.4292.
  #### 2.2 Source Material
Wowhead Tooltip above.

Happy Holidays!

**Comment by where-fore** [comment]
As of 1/18, the haste proc is still 768 per Wowhead datamining - seems this item was passed over during the last item level adjustment.

**Comment by where-fore** [comment]
In game testing shows the tooltip still displaying 768 haste rating, and the in-game benefit to the character is also 768 haste rating.

[One of the World First Algalon kills with a Comet's Trail tooltip:](https://www.twitch.tv/videos/1712409110?t=02h12m34s)
![image](https://user-images.githubusercontent.com/108002636/217306274-b910f7a9-8f64-4e04-b3c4-a1059aca6e21.png)

In-game testing of the proc giving exactly 768 haste rating:
![image](https://i.imgur.com/1SS3jvW.png)
![image](https://i.imgur.com/fX1Dtkf.png)

**Comment by vigo2** [comment]
Comet's Trail has been updated to grant 819 haste rating, adequate for the bumped ilevel.
