### ISSUE TITLE
[BUG] DK Death rune is not being consumed when you macro UA + BT + Obliterate

### ISSUE THREAD

**Issue by lime-green** [JamminL/wotlk-classic-bugs#573]
#### 1.1. Description
If you macro and cast UA + BT + Obliterate together it should use 3 runes total: 1 frost for UA + 1 death for oblit + 1 unholy for oblit. However, if you macro them all together you are able to get it to only consume 2 runes

  #### 1.2. How to Reproduce
Create the following macro:
 ```
/cast Unbreakable Armor
/cast Blood Tap
/cast Obliterate
```
1. Start attacking a target with all runes available
2. Cast Icy Touch
3. Cast Plague Strike
4. Wait for GCD to become ready
5. Use the above macro
  #### 1.3  Source Material
  https://www.youtube.com/watch?v=h8lu-WaJMfM
#### 2.1. Description
  The macro should consume 3 runes
  #### 2.2 Source Material
n/a

**Comment by CharWS** [comment]
https://us.forums.blizzard.com/en/wow/t/wrath-classic-patch-notes-version-342/1616136/1 should be fixed as of patch
