### ISSUE TITLE
[BUG] Drain Soul 5th tick missing sometimes (cant reproduce)

### ISSUE THREAD

**Issue by nistra123** [JamminL/wotlk-classic-bugs#577]
#### 1.1. Description
When you Channel a full Drain Soul sometimes the last tick does not happen, there is a mechanic(bug?) when another warlock finishes his complete drainsoul that all other drainsoul casting warlocks will get there next tick instantly and pushing back the next one further - however sometimes you dont get the fifth tick when youre the only warlock casting drain soul. Pushback is not an issue, it happens on Dummys aswell. 

https://classic.warcraftlogs.com/reports/RYnPVjaBzNbTqyHc/#fight=11&type=damage-done&source=7&ability=47855&view=events  if anyone wants to see the log to the clip.

  #### 1.2. How to Reproduce
How to Reproduce is the problem, tested many different things because i thought it must be related to haste but i cannot reproduce it on every cast it just sometimes happens          

  #### 1.3  Source Material
https://clips.twitch.tv/SweetSpikySwanMingLee-D_1BUMWu1g697axV
Last casted Drain Soul (3% boss hp) the last tick does not happen

### 2. Expected Behavior
The last Tick of Drain Soul should obviously occur all the time.

**Comment by TheDunds** [comment]
May be related to https://github.com/JamminL/wotlk-classic-bugs/issues/232
Even though that issue was fixed 
Could of became broken again

**Comment by nistra123** [comment]
But how does it happen on dummies then? a critter dying nearby?
