### ISSUE TITLE
The Phase 6 sigils are not available on any vendor. [BUG]

### ISSUE THREAD

**Issue by enthozzz** [JamminL/wotlk-classic-bugs#578]
#### 1.1. Description
As of now, Sigil of the Vengeful Heart should be available in Dalaran for 19 emblems of conquest. It also drops from Hardmode XT-002, but was historically sold by vendors in patch 3.1.3. This is the absolute BIS sigil for death knights in PVP and for the unholy/blood dps specs by a wide margin.

**Comment by Speaker1264** [comment]
They weren't added to the vendor until the ToGC patch.  The wowhead comment you may be referring to says patch 3.1.3, but it dated 2009/08/05.  The ToGC patch was 2009/08/04.

**Comment by ToN1c** [comment]
The Sigils that drop in Naxx werent added until Ulduar back in the day but they were on the vendor in classic from day 1. 
This is a nice quality of life feature because getting Sigils from raids can be quite annoying.
They should put them on the vendors so it stays consistent for classic.

**Comment by ToN1c** [comment]
Maybe this should be moved to #somechanges as it is technically not a bug, but should be changed to stay consistent wihtin classic.
Sigils from naxx shouldnt have been added to the vendor from the start, now that they missed this you have to put the Ulduar sigils on the vendor too.
There is still time for this change as people are spending their emblems mostly on tier tokens.
Having them on the vendor is just expected, even back then in ICC they removed sigils from raid loot and only made them available from the vendor.
