### ISSUE TITLE
[BUG] Target of Target not updating resource

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#579]
#### 1.1. Description
Currently target of target will always show unit at full mana, it won't update it.
  #### 1.2. How to Reproduce
           1. Enable target of target
           2. Target someone
           3. Have that person target you
           4. Cast AoE spells to reduce your mana
           5. Notice how the mana of the target-of-target frame doesn't update ever
  #### 1.3  Source Material
https://streamable.com/n29qrl
#### 2.1. Description
Target of target should update unit resource bar as well.
  #### 2.2 Source Material
N/N

**Comment by Evolvee** [comment]
It shows the amount of HP/Mana correctly but only for the exact moment when you first targeted the unit. The follow-up HP/Mana progress isnt displayed.

**Comment by Evolvee** [comment]
Bump debuffs still bugged

**Comment by XyzKangUI** [comment]
https://github.com/Gethe/wow-ui-source/commit/5ed038e6241b62b9b884f069c406b61bd5a18a93#diff-1bf4a6d17c9b628563cd60587ba9d93a8fdf72f385e4315ecc29e3f6ddedd63eL453

https://github.com/Ketho/wow-ui-source-wrath/blob/25887c2f15ce549ceffc28f5b30b4c989b8a1b1c/Interface_Wrath/FrameXML/TargetFrame.lua#L959

Blizz take notes:

If you decide to not use the onUpdate, then atleast call the function in an UNIT_AURA event.

**Comment by JamminL** [comment]
Fixed in PTR 3.4.2.4944

**Comment by Evolvee** [comment]
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/1942409/8d905616-d359-4a44-91b7-d6c55b49b3ed)

doesnt look fixed to me

**Comment by JamminL** [comment]
So in this case there's still a problem with HP only values yea?

**Comment by JamminL** [comment]
/run SetCVar("predictedHealth", 1) this fixes it still or not?

**Comment by Evolvee** [comment]
idk, im just watching a stream rn, even if it worked with the CVar, I dont think it makes sense to leave the game bugged in its default state and only make it "fixed" if a player decides to research how to fix it - its not even visible anywhere, the cvar is completely hidden, you have to go out of your way to specifically search on it on obscure sites
