### ISSUE TITLE
[BUG] Pets and Owner Sap Interaction

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#58]
#### 1.1. Description
Bare with me:

During original 3.3.5a a bug was introduced that caused the owners of pets that have /petattack command active (pet is running towards the enemy target) to be unsappable, they won't be in combat during this time but from the rogue's perspective, it'll say "target is in combat" when trying to sap.

This was a bug introduced in that patch and we do not want to re-introduce it in classic.

That said, right now in wotlk classic beta, there's another one of that kind of bug. If you send your pet to attack another **player**, you can still be sapped (which is correct because you'll still be out of combat). But, if someone attacks your pet while your pet is attacking something, even though the owner never gets combat, he'll be unsappable and the rogue will receive "target is in combat" error.

Which would be great if it was fixed as well so that you can always sap someone who is not in combat.

  #### 1.2. How to Reproduce
           1. Be a hunter and out of combat (player 1)
           2. Send your pet to attack another **player** (player 2)
           3. Notice how you're still out of combat (this is correct behavior) (player1)
           4. Have the other player attack your pet (player 2 attacks player 1 pet)
           5. Notice how you're still out of combat (player 1)
           6. Have a rogue try sap you while your pet keeps attacking player 2 (player 3 saps player 1)
           7. Notice how the rogue gets a "target is in combat" error message when trying to sap, even though the hunter (player 1) is out of combat. 

  #### 1.3  Source Material
Can post later if needed
#### 2.1. Description
If a player is out of combat, he should be sappable. In this example, the player will be out of combat throughout the entire test, he can mount, drink or eat. But he can't be sapped.
  #### 2.2 Source Material
N/A

**Comment by Aggrend** [comment]
Calling this NAB for now as this behavior does match 3.3.5.

**Comment by JamminL** [comment]
Closed, sadly, as NAB
