### ISSUE TITLE
[BUG] [NOMOD] Macros no longer work with modifier keybinds

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#580]
#### 1.1. Description
You curren't cannot use /cast [nomod] spell on a keybind that already has a modifier e.g shift-2. This was changed recently in both classic and DF.
  #### 1.2. How to Reproduce
           1. On a warlock, make the following macro: 
           #showtooltip
           /cast [nomod] Detect Invisibility
           2. Put the macro on a modifier keybind, such as 'shift-2'
           3. Notice how the macro won't work, as it considers the default bind as a modifier already
  #### 1.3  Source Material
N/N
#### 2.1. Description
Before this update, players could use macros like: 
```
#showtooltip summon felhunter
/cast [nomod] summon felhunter
/cast [mod:alt] summon imp
/cast [mod:ctrl] summon voidwalker
```

or

```
#showtooltip devour magic
/dismount
/cast [nomod] devour magic
/cast [nomod] soothing kiss
/cast [mod:alt,@focus] devour magic
/cast [mod:alt,@focus] soothing kiss
```

on keybinds that already have a modifier, now they cannot, as the [nomod] condition will never trigger.
  #### 2.2 Source Material
N/N

**Comment by ManneN1** [comment]
Workaround: If you plan to bind on _shift_-2, just change the [nomod] to [mod:_shift_].
