### ISSUE TITLE
[need research] [BUG] [UI] TargetFrame is getting randomly deselected in PVP combat for no reason

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#581]
#### 1.1. Description

You lose your current target when you tilt your camera/move away from the unit that attacked you if it was targeted via the auto-target mechanism once you're attacked.

  #### 1.2. How to Reproduce

1. Have someone attack you when you have no target selected
2. After it targets the attacker, move slightly out of range and move your camera away
3. Notice how it auto-detargets the enemy

https://streamable.com/i2kcvj

### 2. Expected Behavior

Targets should not drop as this is not user-friendly and unexpected from a user perspective.

**Comment by tuskemx** [comment]
this is happening to me all the time, not sure if someone found a reason already?

**Comment by JamminL** [comment]
https://streamable.com/i2kcvj can confirm. 

Not really sure about what you mean by "some tech that auto-targets the enemy which attacks you." since this is default behavior since vanilla, you always auto-target an enemy if you get attacked and you had no previous target

**Comment by JamminL** [comment]
Edited your main post with info, good find.

**Comment by JamminL** [comment]
Fixed on PTR 3.4.2.49442
