### ISSUE TITLE
[BUG] Resto Druid T8 4 piece effect only procing every other Rejuv

### ISSUE THREAD

**Issue by caccavale** [JamminL/wotlk-classic-bugs#588]
#### 1.1. Description
Resto druid t8 applies a small heal on Rejuv cast.  Currently this only procs every other rejuv cast; it should proc every rejuv cast.
  #### 1.3  Source Material
![image](https://user-images.githubusercontent.com/6198074/213930306-3f059ca6-1530-41e0-b521-e1e55697f4c0.png)

#### 2.1. Description
It should proc every cast.  (note this video is before 3.2.2 nerfed the proc by 50% so the coefficient is larger but at no time was the proc made to be every other cast)
  #### 2.2 Source Material
https://www.youtube.com/watch?v=Gj0l2ugqzrY

**Comment by Loregon** [comment]
Fixed
