### ISSUE TITLE
[#SomeChanges Suggestion] Demonic Pact and "Pet Twisting"

### ISSUE THREAD

**Issue by Zephancode** [JamminL/wotlk-classic-bugs#59]
## 1. Is your feature request related to a problem? Please describe.
One of the core reasons Demonology Warlocks are brought to raids is [Demonic Pact](https://www.wowhead.com/wotlk/spell=48090/demonic-pact). The buff provides the whole raid with 10% of the Warlock's spell power. This buff gets applied whenever the warlock's pet lands a critical hit and stays up for the next 45 seconds. It also incurs a 20-second internal cooldown, as such if the pet crits again during this time Demonic Pact does not get refreshed. After this 20 seconds duration, weaker versions of Demonic Pact (e.g. trigger when the warlock had less spell power) can overwrite an already stronger version that is present (from the same player).

This makes it so that if the Demonology Warlock wants to keep the stronger version (for example when a trinket, blood fury, etc.. is up) active after the initial 20 seconds (after the ICD is up) he is forced to call back his pet and put him on passive until the buff is about to run out and send him back. Leaving the pet to AFK for 25 seconds out of the 45 seconds the buff is up, or in other words over half the time. 

This behavior is observed in the [current beta](https://github.com/Zephancode/wotlk-warlock/issues/26) as can be seen here and was the case back in [retail wotlk as can be seen mentioned in this elitest jerk post](https://web.archive.org/web/20100807225539/http://elitistjerks.com/f80/t100099-demonology_releasing_demon_you/#Demonic_Pact).

What this facilitates is known as "Pet twisting" where a Demonology warlock sacrifices personal DPS by recalling their pet once Demonic Pact is up, in order not to overwrite it with a weaker version. Followed by sending the pet back in when Demonic Pact is about to run out.

When multiple Demonology Warlocks are present stronger versions can overwrite weaker versions of the other warlock, BUT weaker versions can not overwrite stronger ones from the other warlock.

### 1.1 Describe the solution you'd like
In an ideal world the same methodology that applies to having multiple warlocks would be present for a single warlock as well. This would mean that there is no need for "Pet twisting". In other words: Stronger versions take precedent over weaker ones. This would promote actually using your pet to deal damage instead of sidelining your demon for over half the fight.

It should be noted that this could lead to lower uptime of the buff, this could be countered by removing the 20 seconds ICD.
Another potential aid is the weaker version being added at the end of the strong DP, minimizing downtime.

### 1.2 Additional context
A lot of warlocks want to try out the revamped Demonology talent tree but are put off by the idea of having to "Pet Twist".

**Comment by Zephancode** [comment]
Also posted over at the [Warlock Github](https://github.com/Zephancode/wotlk-warlock/issues/28).

**Comment by Aggrend** [comment]
No promises but we'll evaluate this. Brian replied to a tweet about this and seemed amenable to a QoL change here, but our designers need to evaluate it further. Thanks for the write-up!

**Comment by Aggrend** [comment]
We've evaluated this and have a slight tweak in place internally that we are testing now. We'll get this out for testing in next week's beta update (7/20) and post a write up when we get closer to pushing that build with full details. Thanks for the feedback!

**Comment by JamminL** [comment]
Closing as accepted! 🥳
