### ISSUE TITLE
[BUG] Sigil of the Vengeful Heart uses the wrong damage values (uses values from before the ilvl buff)

### ISSUE THREAD

**Issue by dummyaccounter** [JamminL/wotlk-classic-bugs#598]
#### 1.1. Description

Sigil of the Vengeful Heart does not grant the values it says it does. It is operating at pre-buff values instead. Blizzard changed the item's tooltip and item level, but did not actually change what the item actually does.

What it says it does: "Increases the damage done by your Death Coil ability by 437 and by your Frost Strike ability by 136."
What it is supposed to do: "Increases the damage done by your Death Coil ability by 437 and by your Frost Strike ability by 136."
What it is currently doing (bug): "Increases the damage done by your Death Coil ability by 380 and by your Frost Strike ability by 113."

  #### 1.2. How to Reproduce
          1. Without any modifiers or procs, cast Death coil on enemies while using sigil and while not using sigil
          2. Compare damage dealt
          3. Damage difference is ~380 as opposed to ~437
  #### 1.3  Source Material
--
#### 2.1. Description
It should be adding 437 damage to death coil, not 380.

  ### 3. Notes
- the frost strike damage is also likely bugged
- other items may also be bugged to be using pre-buff values, e.g. druid idols, or trinkets

**Comment by CharWS** [comment]
should be fixed as per today's hotfix, if still seeing incorrect scaling can post here and will reopen
