### ISSUE TITLE
[BUG] 5v5 - Last Man Standing Bugged

### ISSUE THREAD

**Issue by Moki182** [JamminL/wotlk-classic-bugs#599]
#### 1.1. Description
Last man Standing Achievement does not work.
  #### 1.2. How to Reproduce
           1. Queue for a 5v5 game
           2. Be the last person alive
           3. Notice you don't gain the achievement
  #### 1.3  Source Material
N/A
#### 2.1. Description
Achievement should be awarded if you're the last person in an arena.
  #### 2.2 Source Material
https://www.wowhead.com/wotlk/achievement=409/last-man-standing

**Comment by Jgrenier91** [comment]
Still bugged!

**Comment by innatez** [comment]
still bugged

**Comment by brandongevat** [comment]
still bugged :)

**Comment by JamminL** [comment]
Seeing people on live classic servers with Arena Master. If there's still problems with it comment and I'll reopen
