### ISSUE TITLE
[BUG] Slow Fall + Jump

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#6]
#### 1.1. Description
Currently, the mage spell Slow Fall affects jumping along the same z-axis (for example, jumping while standing still).
  #### 1.2. How to Reproduce
           1. Cast slowfall on yourself
           2. Jump while not moving
  #### 1.3  Source Material
TBA
#### 2.1. Description
Back in the day, slowfall would only affect you if you are falling down to a lower z-axis - it wouldn't affect normal jumping
  #### 2.2 Source Material
TBA

**Comment by watchyoursixx** [comment]
Adding "Fix not likely" label and noting that this has been brought up to QA multiple times throughout all of classic. It doesn't seem like it's going to ever be changed so I'm going to close this out on our end.
