### ISSUE TITLE
[BUG] Wound poison - multiple debuffs

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#601]
#### 1.1. Description
Wound poison debuffs are not interchangeable
  #### 1.3  Source Material
https://www.youtube.com/watch?v=CJisxZlSW2E&t=60s
#### 2.1. Description
Debuffs from Wound poison should be replaced with a longer effect
  #### 2.2 Source Material
Here you can see how the debuffs from Wounding Poison are replaced with each other:
https://www.warcraftmovies.com/movieview.php?id=156493 @ 3:10
https://www.warcraftmovies.com/movieview.php?id=143993 @ 4:38

**Comment by Miyur1** [comment]
This is not a minor bug. Rogues currently apply 2 wound poisons to weapons, making them almost impossible to dispel.
https://i.imgur.com/EHlufxE.png

**Comment by Miyur1** [comment]
Wound poison does not replace other mortal effects either, so there is a 99% chance that using different poison ranks is also a bug. Poisons just forgot to add to the list of replaceable debuffs

https://www.mmo-champion.com/threads/612981-Patch-3-0-2-On-Debuffs-Buffs-and-Raid-Stacking
Healing Debuff: Wound Poison, Aimed Shot, Mortal Strike, Furious Attacks

**Comment by perpabc** [comment]
The MS effect doesn't stack though
