### ISSUE TITLE
[TEST-REQUEST] Unstable Affliction dispel damage is not increased by Curse of the Elements

### ISSUE THREAD

**Issue by Jgrenier91** [JamminL/wotlk-classic-bugs#607]
#### 1.1. Description
Dispelling a target of Unstable Affliction deals damage to the dispeller. This damage is the same whether or not the dispeller is under the effect of Curse of the Elements/
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
          1. Dispel unstable affliction and monitor the damage you take as dispeller.
          2. Have Curse of the Elements applied to your character and dispel Unstable Affliction once more.
          3. Note that the damage is the same instead of being increased by 13% as noted on the CoE tool-tip.
  #### 1.3  Source Material
https://gfycat.com/AntiqueVibrantFalcon
#### 2.1. Description
![image](https://user-images.githubusercontent.com/14340125/216791688-dffbb22e-c764-4e65-81fc-c10f2548c51d.png)

Curse of the Elements increases the magic damage a player takes by 13%. The damage taken by a player who dispels Unstable Affliction should therefore be increased by 13% if under the effect of CoE.
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by JamminL** [comment]
https://www.wowhead.com/wotlk/spell=65813/unstable-affliction has flag **Ignore Caster Damage Modifier**

It will ignore all increases or decreases. It'll go through spells like Pain Suppresion for example
