### ISSUE TITLE
[BUG] War stomp cast bar not visible

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#612]
#### 1.1. Description
War Stomp, tauren racial cast bar is not visible to others. Some reports say this only started since last patch but I can't confirm.
  #### 1.2. How to Reproduce
           1. Target a male tauren
           2. Have him cast War Stomp
           3. Notice how no castbar is shown on target frame
  #### 1.3  Source Material
https://streamable.com/3cd2kv
#### 2.1. Description
Cast bar should be shown.
  #### 2.2 Source Material
-

**Comment by Miyur1** [comment]
in the original, cast bar was also hidden

https://www.wowhead.com/wotlk/spell=20549/war-stomp
Flags: No cast log

https://www.warcraftmovies.com/movieview.php?id=155093 @ 6:53
https://www.youtube.com/watch?v=Bum1TXAUSH8&t=153s
https://www.youtube.com/watch?v=zvx6WD084Jk&t=214s
https://www.youtube.com/watch?v=njivTDoltrs&t=1367s
