### ISSUE TITLE
[BUG] Attack Power reduction debuffs stack

### ISSUE THREAD

**Issue by raethkcj** [JamminL/wotlk-classic-bugs#615]
#### 1.1. Description
Combinations of Demoralizing Shout, Vindication, and Curse of Weakness can be stacked on enemies to reduce their attack power by significant amounts.
  #### 1.2. How to Reproduce
          1. Apply unimproved Curse of Weakness and then 5/5 Improved Demoralizing Shout
          
          OR
          
          2. Apply unimproved Demoralizing Shout and then 2/2 Vindication
          
Note: these are just the combinations tested here; not all combinations work, but many others likely do
          
  #### 1.3  Source Material
  Base, unimproved Curse of Weakness, 5/5 Demoralizing Shout
![pala_full](https://user-images.githubusercontent.com/7716908/219425889-9cf7b95c-23c8-444e-8226-5606b7981880.jpg)
 Base, unimproved Demoralizing Shout, 2/2 Vindication
![vw_full](https://user-images.githubusercontent.com/7716908/219425901-a2b2d5d9-d20a-4768-8d1b-446771a7d54d.jpg)

#### 2.1. Description
None of these combinations of debuffs should stack with each  other.
  #### 2.2 Source Material
> Vindication: Redesigned. Now lowers target attack power, is consistent and does not stack with Demoralizing Shout.

https://web.archive.org/web/20090807205046/http://www.worldofwarcraft.com/patchnotes/
> Curse of Weakness no longer stacks with Demoralizing Shout or Demoralizing Roar.

https://www.bluetracker.gg/wow/topic/eu-en/8246768669-recent-in-game-fixes-3-6-09/

**Comment by Aggrend** [comment]
We've got a hotfix going out very soon for this.

**Comment by TheDunds** [comment]
I have been getting reports on the hunter discord about Screech stacking with demo/vindication 
On ptr 3.4.3 (51943) i loaded up 3 toons and tested in gurubashi arena 
I found that both sources stack on the target 
I believe this to be a bug as all other sources don't stack like this 
Please see attached images 

![Ap stack 1](https://github.com/JamminL/wotlk-classic-bugs/assets/110584436/edcec6c4-8063-4dea-8a60-e6eded853f18)
![Ap stack 2](https://github.com/JamminL/wotlk-classic-bugs/assets/110584436/f20f3803-b99c-4372-bf6b-0e460eeac6b6)
![Ap stack 3](https://github.com/JamminL/wotlk-classic-bugs/assets/110584436/6a3e7bc6-d570-4a5a-bd06-3fae70f61274)

**Comment by JamminL** [comment]
The screech specifically does stack and matches reference 3.3.5a
