### ISSUE TITLE
[BUG] Hodir ice cirlces

### ISSUE THREAD

**Issue by hvownij** [JamminL/wotlk-classic-bugs#622]
#### 1.1. Description
During Hodir the ice circles spawn on the ground and there is no further animation.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Run the hodir boss
           2. watch the circles
           3.  see NO animation of icicles falling.
  #### 1.3  Source Material
[{Video, Posts, etc..}https://www.youtube.com/watch?v=yTAxvpV-Ggs](https://www.youtube.com/watch?v=yTAxvpV-Ggs) see the circle spawn nothing.
#### 2.1. Description
When the circles are on the ground they should summon a icicle animation.
  #### 2.2 Source Material
[{Video, Posts, etc..}](https://www.reddit.com/r/classicwow/comments/11gcqdr/does_hodir_icicle_damage_seem_frustratingly/) See video posted here. https://www.reddit.com/r/classicwow/comments/11gcqdr/does_hodir_icicle_damage_seem_frustratingly/

**Comment by Speaker1264** [comment]
Is this ever going to get fixed? I can't believe this was never fixed before release, and it still isn't fixed

**Comment by Miyur1** [comment]
Fixed
https://clips.twitch.tv/EnthusiasticAgreeableCaribouSquadGoals-COwEde19eQpvi_fH
