### ISSUE TITLE
[BUG] Wandering Plague - ICD

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#628]
#### 1.1. Description
Wandering Plague has an internal cooldown of 0.5 seconds
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Do this
           2. Do that
           3. Do this again and voilá}
  #### 1.3  Source Material
https://www.wowhead.com/wotlk/spell=49655/wandering-plague - 500ms cooldown

> 3/14 01:02:51.091  SPELL_PERIODIC_DAMAGE,Player-4904-007027C3,"Фывфыаф-ClassicPTRRealm1",0x511,0x0,Creature-0-4908-0-62-32666-00008157F5,"Expert's Training Dummy",0x10a28,0x0,55095,"Frost Fever",0x10,0000000000000000,0000000000000000,0,0,0,0,0,-1,0,0,0,0.00,0.00,1453,0.0000,0,357,243,356,16,0,0,0,nil,nil,nil
> 3/14 01:02:51.091  SPELL_DAMAGE,Player-4904-007027C3,"Фывфыаф-ClassicPTRRealm1",0x511,0x0,Creature-0-4908-0-62-32666-00008157F5,"Expert's Training Dummy",0x10a28,0x0,50526,"Wandering Plague",0x20,0000000000000000,0000000000000000,0,0,0,0,0,-1,0,0,0,0.00,0.00,1453,0.0000,0,1,0,-1,32,0,0,0,nil,nil,nil
> 3/14 01:02:51.685  SPELL_PERIODIC_DAMAGE,Player-4904-007027C3,"Фывфыаф-ClassicPTRRealm1",0x511,0x0,Creature-0-4908-0-62-32666-00008157F5,"Expert's Training Dummy",0x10a28,0x0,55078,"Blood Plague",0x20,0000000000000000,0000000000000000,0,0,0,0,0,-1,0,0,0,0.00,0.00,1453,0.0000,0,367,249,366,32,0,0,0,nil,nil,nil
> 3/14 01:02:51.685  SPELL_DAMAGE,Player-4904-007027C3,"Фывфыаф-ClassicPTRRealm1",0x511,0x0,Creature-0-4908-0-62-32666-00008157F5,"Expert's Training Dummy",0x10a28,0x0,50526,"Wandering Plague",0x20,0000000000000000,0000000000000000,0,0,0,0,0,-1,0,0,0,0.00,0.00,1453,0.0000,0,1,0,-1,32,0,0,0,nil,nil,nil

#### 2.1. Description
ICD should be 1 second
  #### 2.2 Source Material

https://web.archive.org/web/20090305054520/http://elitistjerks.com/f72/t36775-death_knight_simple_questions_simple_answers/p23/
There is an ICD, I believe on beta it was tested around 1s. To prevent massive burst of damage when you have 2 diseases on a lot of mobs at the same time.

http://web.archive.org/web/20100808145734/http://elitistjerks.com/f72/t72364-unholy_dps_3_3_5_only_exception/p135/#post1652223
Wandering Plague indeed has a 1 sec internal cooldown. ~6000 ticks of Blood Plague, ~6000 ticks of Frost Fever, ~6000 WP procs.

Simcraft 3.3.5 (2010):
      cooldown = player -> get_cooldown( "wandering_plague" );
      cooldown -> duration       = 1.0;

**Comment by caccavale** [comment]
https://youtu.be/adJZsb-W-O0?t=160 t159.50, 160.30
https://youtu.be/c1oes504FFw?t=102 t101.79, 102.62 and t148.85, 149.35

Bit of conflicting information here.  The above videos show some multi-procs which seem to be within < 1s but > .5s.  EJ threads without logs and simcraft coeffs/iCDs aren't stellar information either.

**Comment by Miyur1** [comment]
NAB

**Comment by caccavale** [comment]
Appreciate all the tickets you've opened @Miyur1.  They've been consistently well sourced and concise.
