### ISSUE TITLE
[BUG] Hand of Sacrifice disappears

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#630]
#### 1.1. Description
https://www.wowhead.com/wotlk/spell=6940/hand-of-sacrifice
Hand of Sacrifice is sometimes canceled/disappeared
  #### 1.2. How to Reproduce
Can't reproduce, bug has existed since Wotlk started
  #### 1.3  Source Material
Season 5:
https://www.youtube.com/watch?v=XZtbaPY8l7g
https://www.youtube.com/watch?v=Uj60YEflv_E
https://www.youtube.com/watch?v=3pobLjaHZ2k
https://www.youtube.com/watch?v=z296Jz8OylM
https://www.youtube.com/watch?v=2K9lQ4fRhT4
https://www.youtube.com/watch?v=kSZcbi5AAbc
https://www.youtube.com/watch?v=5lhpQzi-r3k
https://www.youtube.com/watch?v=sYptguN7-YY
https://www.youtube.com/watch?v=wMm4kax0WVo
https://www.youtube.com/watch?v=xvAxv_3aFG8
Season 6:
https://clips.twitch.tv/InterestingLachrymoseCoffeeKappaClaus-quu2LVoQyPp5wipa
https://clips.twitch.tv/BrightAmericanLorisM4xHeh-V6Uzx_vrF5altr2Q
https://clips.twitch.tv/GentleCourteousCheetahKevinTurtle-U1elD63mLnrdsX__
https://clips.twitch.tv/OilyCrackyGoatBlargNaut-kYWOEU5tw3S_ThlW
#### 2.1. Description
Should only be canceled if the paladin transfers 100% of his health
  #### 2.2 Source Material
-

**Comment by Skarrow10** [comment]
I did some research on this. Here are my findings:

Hand of Sacrifice can only transfer a total amount of damage equal to the casting Paladin's max HP. Bubble does not bypass this. **If a Hand of Sacrifice expires without transferring the full allowed amount, the amount that was transferred is not reset, and the next Hand of Sacrifice cast will not be able to transfer as much.**

Example with numbers:
Tank has 45k hp, HPal has 25k hp
HPal casts Hand of Sac on Tank. Tank takes 70k damage over the duration, reduced to 49k damage with 21k damage transferred to HPal
Later HPal casts another Hand of Sac on Tank. This cast will only be able to transfer 4k damage before being removed automatically

**Comment by JamminL** [comment]
> I did some research on this. Here are my findings:
> 
> Hand of Sacrifice can only transfer a total amount of damage equal to the casting Paladin's max HP. Bubble does not bypass this. **If a Hand of Sacrifice expires without transferring the full allowed amount, the amount that was transferred is not reset, and the next Hand of Sacrifice cast will not be able to transfer as much.**
> 
> Example with numbers: Tank has 45k hp, HPal has 25k hp HPal casts Hand of Sac on Tank. Tank takes 70k damage over the duration, reduced to 49k damage with 21k damage transferred to HPal Later HPal casts another Hand of Sac on Tank. This cast will only be able to transfer 4k damage before being removed automatically

I'll test this later, if this was it, awesome find! You don't know how many hours I've spent on this one ^^

**Comment by crvarner** [comment]
Had this happen twice last night and my logs are consistent with the reasoning above

https://classic.warcraftlogs.com/reports/a:TkR9QKVnNDpawbfr#type=auras&view=events&ability=6940&boss=757&difficulty=3&wipes=1

Wipe 2: HoSac went the full 12s duration (41.4k transferred)
Wipe 6 (next cast): HoSac disappeared after 4k damage

Wipe 9: HoSac went the full 12s duration (32.9k transferred)
Wipe 10 (next cast): HoSac disappeared after 11.3k damage

Prot Pal had 42.6k health
