### ISSUE TITLE
[BUG] Intervene does not work properly

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#631]
#### 1.1. Description
"Intervene" is not pressed if the warrior has an enemy in the target that is out of sight (behind the pillar). Bug appeared recently.
  #### 1.2. How to Reproduce
           1. Target an enemy that is in out of sight
           2. Use macro on party 1. Example:
              #show Intervene
              /cast Defensive Stance
              /cast [target=party1] Intervene
           3. Try to press Intervene
  #### 1.3  Source Material
https://www.youtube.com/watch?v=BozMN_j6BJE
https://www.twitch.tv/pvelordtv/clip/SpookyRespectfulRaccoonTheRinger-gLM758A-A4hilSxT
https://www.twitch.tv/pvelordtv/clip/AntsySmoothClipsmomBrokeBack-wg6Xlj1HIKt7gH2a
#### 2.1. Description
Intervene should not have such restrictions
  #### 2.2 Source Material
-

**Comment by XyzKangUI** [comment]
All this has to do with the mess of a targeting system since 3.4.1

https://github.com/JamminL/wotlk-classic-bugs/issues/582

**Comment by XyzKangUI** [comment]
The bug is related to all other buffs since the messed up targeting system of 3.4.1. Thanks to the capable devs adding dragonflight changes no one asked for

**Comment by XyzKangUI** [comment]
The bug is related to all other bugs since the messed up targeting system of 3.4.1. Thanks to the capable devs adding dragonflight changes no one asked for

**Comment by XyzKangUI** [comment]
The bug is related to all other bugs since the messed up targeting system of 3.4.1. Thanks to the capable devs adding dragonflight changes.

**Comment by XyzKangUI** [comment]
The bug is related to all other unitid macro bugs since the messed up targeting system of 3.4.1. This issue is brought over from dragonflight, glad they brought over new changes. Hope some retail dev fixes it so the classic ones can bring that over as well.

**Comment by XyzKangUI** [comment]
The bug is related to all other unitid macro bugs since the messed up targeting system of 3.4.1. Probably will be fixed when retail fixes it first.
