### ISSUE TITLE
[BUG] Sun Scope has no effect

### ISSUE THREAD

**Issue by raethkcj** [JamminL/wotlk-classic-bugs#632]
#### 1.1. Description
The [Sun Scope](https://www.wowhead.com/wotlk/item=41146/sun-scope) item crafted by engineers that can be applied to ranged weapons has no effect. 
  #### 1.2. How to Reproduce
           1. On a hunter, note your attack speed in the character sheet and in practice on a ranged weapon with no haste enhancement applied.
           2. Apply a Sun Scope to your ranged weapon
           3. Observe that your attack speed both in character sheet and in practice does not change
  #### 1.3  Source Material
![image](https://user-images.githubusercontent.com/7716908/227644598-ad34bffc-1cb8-470a-b539-535ec927105d.png)
![image](https://user-images.githubusercontent.com/7716908/227644371-69a25c4e-e0db-4ef2-bb0a-c9e0e3317e45.png)

A log with the 2.9 speed Pierce's Pistol with the Sun Scope applied, showing 2.52 seconds between shots:

https://classic.warcraftlogs.com/reports/zjVkfprcZNJYq4BR/#fight=1&view=events

#### 2.1. Description
Sun Scope should add 40 haste rating, equating to roughly 1.22% additional ranged haste. For a 2.9 speed weapon, and accounting for Auto Shot's passive 15% ranged haste, this would be an attack speed of approximately `2.9 / 1.15 / 1.022 = 2.47` seconds.
  #### 2.2 Source Material
Item tooltip

**Comment by TheDunds** [comment]
Still bugged as of ptr 3.4.3(51397) Sep 15

**Comment by TheDunds** [comment]
Fixed on 3.4.3(51831) 
https://media.discordapp.net/attachments/1006662295612563506/1167417895849037894/image.png?ex=654e0da3&is=653b98a3&hm=3712abc21a42c21745b41ec63a48beab86b4e943fdc0c4c6a5b1ad214f9ccdee&=
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/110584436/94f9a8bf-470c-4851-bd6d-11066559b858)
