### ISSUE TITLE
[#SomeChanges Suggestion] Shattering throw glyph

### ISSUE THREAD

**Issue by knasen88** [JamminL/wotlk-classic-bugs#638]
### Glyph of Shattering Throw
**The problem**
To preface, as some of us know, shattering throw armor reduction stacks with all other sources and due to arp mechanics it is the only way to actually get 100% arp. However this clunky spell has three (two for arms) MAJOR drawbacks for the warrior using it resulting in a personal dps loss. Imagine if you will tricks of the trade draining 75 energy, pausing your swingtimer for 3.6 seconds and also taking 1.5 second to cast standing still, that is the equivalent we're talking about here.

**Solution**
_{Minor Glyph}_
**no longer removes invulnerabilities**, probably less damage for sake of pvp balance (or preferably just no damage to players)
**No longer resets swing timer**
**Usable in any stance**
**Instant cast** (this one isn't as important but it's nice regardless)

**Comment by RobFalfa** [comment]
Heroic throw also resets swing timer even if it's instant which many players don't know about. If you dual wield and got same speed weapons they will sync and deep wounds procs will munch. See https://github.com/JamminL/wotlk-classic-bugs/issues/537 for more information.
