### ISSUE TITLE
[BUG] PET AI - Spells and Line of Sight

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#64]
#### 1.1. Description
Currently if you send your pet to cast a spell on an enemy target that's behind LOS, it will just stand still and throw an error message. 

This bug affects pve and pvp but especially for pvp, right now you have to micro your pet so much more - making sure you only press your spells when they are in LOS and in some cases a headache (e.g trying to dispel your teammates with fel hunter, where you can't make use of /petfollow or /petattack)

  #### 1.2. How to Reproduce
           1. Summon Felhunter
           2. Spell lock a target behind Line of Sight
           3. Watch the pet eventually stands still and give up.
  #### 1.3  Source Material
https://gyazo.com/d14674eb2407bb3edaaab0ab26799051
https://gyazo.com/d6441b1848a6358e9fb6041c7233d835
#### 2.1. Description
In 3.3.5a, pets should follow the best available path to the target, and cast the spell as soon as they're in line of sight, without the need of a second command.

1. Press spell lock on a target behind LOS
2. Pet walks over to the target until he's in range and in line of sight
3. Pet automatically casts spell lock once he's in range/Line of sight

If there's ever a case where there's no path, he gives up.

  #### 2.2 Source Material
https://gfycat.com/SphericalUnrealisticHoopoe Lock presses devour, pet goes into range and LOS and then automatically uses it once he meets those criteria.

**Comment by Aggrend** [comment]
This is Not a Bug. This behavior perfectly matches the 3.3.5 reference behavior, right down to the felhunter taking a few steps forward, stopping and returning with an error.
