### ISSUE TITLE
[BUG] Unstable Affliction - resilience

### ISSUE THREAD

**Issue by Miyur1** [JamminL/wotlk-classic-bugs#640]
#### 1.1. Description
Damage dealt when dispelling UA is not reduced by resilience
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Do this
           2. Do that
           3. Do this again and voilá}
  #### 1.3  Source Material
https://imgur.com/a/Mz9tKqf
#### 2.1. Description
UA damage from dispel should be reduced by resilience
  #### 2.2 Source Material

https://web.archive.org/web/20110228080216/http://eu.battle.net/wow/en/game/patch-notes/3-3-3

> Unstable Affliction: The feedback damage from when this spell is dispelled is now affected by resilience as intended.

http://web.archive.org/web/20191025201052/http://www.arenajunkies.com/topic/161461-ua-dispel-silence-debuff/page-5

> About the UA dmg when its dispelled, yesterday I was playing against a Double Healer Warrior as RLD and at one point the priest dispelled all my dots plus fear(including Haunt) with 3 dispels without breaking his shield (PW: S) I checked my recount addon to see how many times It got dispelled and the result was that UA was dispelled 12 times with only 4 times dealing damage. the highest dmg done was 6893 shadow damage, the lowest 2400ish, 2 misses (probably sacred cleansing).
> **And yes Unstable Affliction damage when dispelled IS AFFECTED BY RESILIENCE**

https://www.warcraftmovies.com/movieview.php?id=148991 @ 8:11
Paladin dispels UA, deals 6.8k, too little damage for a warlock in a8, that ignores resilience

**Comment by JamminL** [comment]
Fixed on PTR 3.4.2.49442
