### ISSUE TITLE
[BUG] Corruption sometimes fades for no reason

### ISSUE THREAD

**Issue by powerlol** [JamminL/wotlk-classic-bugs#656]
#### 1.1. Description

Corruption sometimes fades for no reason when there's 1-2 sec left on the dot duration.

  #### 1.2. How to Reproduce

No idea how to reproduce it 100% but sometimes during encounters corruption fades while there's atleast 2 secs left on the dot duration

  #### 1.3  Source Material

https://www.twitch.tv/sajajaja/clip/SullenColdDurianTheThing-4mhAlZhHgc8azpVN?filter=clips&range=7d&sort=time
Happens 2 times in a very short time

#### 2.1. Description

Corruption should last until it's full duration
  
 #### 2.2 Source Material
No need I believe since it's how it works on every dot

**Comment by CharWS** [comment]
looks to be the same issue as https://github.com/JamminL/wotlk-classic-bugs/issues/439
