### ISSUE TITLE
[BUG] Mass Dispel dispeling 2 buffs from target with 100%? dispel resistance

### ISSUE THREAD

**Issue by FatlineDeff** [JamminL/wotlk-classic-bugs#660]
#### 1.1. Description
Today we had arena where I used Pain Suppression on myself and my teammate used Hand of Protection on me aswell to save me
- Pain Suppression adds 65% chance to resist + 5% base chance to resist? + 30% chance silent resolve talent

One cast of Mass Dispel removed both Pain Suppression and Hand of Protection = 2 buffs from 1 target

  #### 1.2. How to Reproduce
I guess spam mass dispells on target with Pain Suppression and HoP? Cannot test
  #### 1.3  Source Material
(my OBS recordings arent the best quality)
![SilentResolve](https://user-images.githubusercontent.com/6503547/232916414-af90d87d-72eb-4726-ba1e-85d5e30042a9.png)
![DuringMDCast](https://user-images.githubusercontent.com/6503547/232916433-1962f735-6fd0-4f5b-9e74-808fac59fbae.png)
![AfterMDCast](https://user-images.githubusercontent.com/6503547/232916445-bfd166dd-48ec-4015-aaa0-15ec0218e992.png)

Combat Log: (trimmed few irrelevant lines)

4/18 22:10:48.147  SPELL_AURA_APPLIED,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,33206,"Pain Suppression",0x2,BUFF
4/18 22:10:48.147  SPELL_CAST_SUCCESS,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,33206,"Pain Suppression",0x2,0000000000000000,0000000000000000,0,0,0,0,0,-1,0,0,0,0.00,0.00,0,0.0000,0
4/18 22:10:48.297  SPELL_CAST_START,Player-4467-029F517E,"Frosthork-Firemaw",0x548,0x0,0000000000000000,nil,0x80000000,0x80000000,32375,"Mass Dispel",0x2
4/18 22:10:48.464  SPELL_CAST_SUCCESS,Player-4467-037B48A1,"Preghiera-Firemaw",0x512,0x0,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,10278,"Hand of Protection",0x2,0000000000000000,0000000000000000,0,0,0,0,0,-1,0,0,0,0.00,0.00,0,0.0000,0
4/18 22:10:48.464  SPELL_AURA_REMOVED,Player-4467-029F0371,"Medinia-Firemaw",0x30548,0x0,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,49800,"Rip",0x1,DEBUFF
4/18 22:10:48.464  SPELL_AURA_REMOVED,Player-4467-029F0371,"Medinia-Firemaw",0x30548,0x0,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,48574,"Rake",0x1,DEBUFF
4/18 22:10:48.464  SPELL_AURA_APPLIED,Player-4467-037B48A1,"Preghiera-Firemaw",0x512,0x0,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,10278,"Hand of Protection",0x2,BUFF
4/18 22:10:48.498  SPELL_AURA_APPLIED,Player-4467-037B48A1,"Preghiera-Firemaw",0x512,0x0,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,25771,"Forbearance",0x2,DEBUFF
4/18 22:10:48.681  SPELL_CAST_SUCCESS,Player-4467-029F517E,"Frosthork-Firemaw",0x548,0x0,0000000000000000,nil,0x80000000,0x80000000,32375,"Mass Dispel",0x2,0000000000000000,0000000000000000,0,0,0,0,0,-1,0,0,0,0.00,0.00,0,0.0000,0
4/18 22:10:48.681  SPELL_AURA_REMOVED,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,33206,"Pain Suppression",0x2,BUFF
4/18 22:10:48.681  SPELL_DISPEL,Player-4467-029F517E,"Frosthork-Firemaw",0x548,0x0,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,32592,"Mass Dispel",0x2,33206,"Pain Suppression",2,BUFF
4/18 22:10:48.681  SPELL_AURA_REMOVED,Player-4467-037B48A1,"Preghiera-Firemaw",0x512,0x0,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,10278,"Hand of Protection",0x2,BUFF
4/18 22:10:48.681  SPELL_DISPEL,Player-4467-029F517E,"Frosthork-Firemaw",0x548,0x0,Player-4467-032BE826,"Fatlinda-Firemaw",0x511,0x0,39897,"Mass Dispel",0x2,10278,"Hand of Protection",2,BUFF
#### 2.1. Description
Silent Resolve 30% + Pain Suppresion 65% + Base resistance 5% should give 100% chance to resist?
Mass Dispel should only attempt to dispel 1 buff per target
  #### 2.2 Source Material
Ingame tooltips

**Comment by JamminL** [comment]
If unresisted, mass dispel will always take the invulnerability + something else.
