### ISSUE TITLE
[BUG] Multiple issues with the Scarab Brooch trinket

### ISSUE THREAD

**Issue by ghost** [JamminL/wotlk-classic-bugs#666]
#### 1.1. Description

There are two issues with the Scarab Brooch trinket, from AQ40, in WotLK classic:
1. The Persistent Shield absorb it places after each heal only absorb 10% of the heal's value, rather than 15% as on the tooltip or as it was in Vanilla/TBC classic.
2. The Persistent Shield absorb appears to be incompatible with the Protection of Ancient Kings absorb from Val'anyr.

  #### 1.2. How to Reproduce
1. While in combat with a mob, use the Scarab Brooch, heal yourself, then take damage. Compare the raw healing of your heal and the total absorb from Persistent Shield, to see it is more or less exactly 10% rather than 15%.
2. With Val'anyr and Scarab Brooch equip, wait for a Val'anyr proc, then activate Scarab Brooch, and start healing. Only one of the buffs Persistent Shield buff and Protection of Ancient Kings will be active at once. Protection of Ancient Kings seems to mostly take precedence.

  #### 1.3  Source Material
A log showing Persistent Shield at clearly 10%, rather than 15%, of the heal value:
https://classic.warcraftlogs.com/reports/N6Y2VRWMgcP8ryFG#type=healing&source=8&fight=last&start=4599149&end=4621708&target=3&view=events

A log showing Persistent Shield and Protection of Ancient Kings as incompatible:
https://classic.warcraftlogs.com/reports/vW3gM21pYA98J7Nb#type=auras&translate=true&fight=52&pins=2%24Off%24%23244F4B%24expression%24ability.name%20%3D%20%22Persistent%20Shield%22%20or%20ability.name%20%3D%20%22Protection%20of%20Ancient%20Kings%22&view=events

#### 2.1. Description
Scarab Brooch was not nerfed until Cataclysm, so we should expect that it absorbs 15% of raw healing. It should also stack with Val'anyr-- it popularly used in retail WotLK together with Val'anyr in the Lich King encounter of ICC. I anticipate many healers are looking forward to similarly using this trinket in ICC, which many people collected in Vanilla and TBC with this express purpose in mind.

  #### 2.2 Source Material
A log from TBC, showing Persistent Shield as 15% of healing then:
https://classic.warcraftlogs.com/reports/fVvybYNxn3AJpXcw#fight=14&type=healing&source=41&start=1934442&end=1943183&view=events&target=13

Comment from Espoire on Wowhead from 3.3.0, stating that Scarab Brooch stacks with Val'anyr:
https://www.wowhead.com/item=21625/scarab-brooch#comments
(this is also attested in many other sources online).

**Comment by Undertoe** [comment]
This is 99% NAB as it is in line with various other mechanics:

1) JOTJ has always caused seal of the righteousness to proc a tick, which means its flagged as a melee attack
2) SOV has been changed as of the glyph of reckoning change to proc off of a variety of different effects and increment stacks off of them (CS / DS / HOW naming a few).
3) Since JOTJ has always counted as a melee attack, it causing SOV to increment is going to be exactly in line with current effects.

**Comment by Restomagus** [comment]
There is a good Weakaura for damage absorbs called Nanshield
I am not home to test (though I do have scarab brooch) and that would also likely be a good way to verify is to run that weakaura and use the brooch. It shows how much absorb you have at any moment.

**Comment by raethkcj** [comment]
nanShield reverse engineers total absorb amounts based on player assumptions. It does not pull any information about total absorb size from the game itself, so it cannot be used to glean new information about untested shields.
