### ISSUE TITLE
[BUG] Hammer of Justice has 13 range

### ISSUE THREAD

**Issue by FatlineDeff** [JamminL/wotlk-classic-bugs#667]
#### 1.1. Description
    Hammer of Justice cast range is 12.5-13 yards
  #### 1.2. How to Reproduce
          Duel with someone in party, let him cast hoj on max range that he can, measure distance
  #### 1.3  Source Material
Measured range after being HoJed in duel with someone in party

	local uiMapID = C_Map.GetBestMapForUnit("player")
	local posXY = nil
	posXY = C_Map.GetPlayerMapPosition(uiMapID, "player") or nil
	local posX, posY = UnitPosition("player") --posXY:GetXY()
	
	local uiMapID = C_Map.GetBestMapForUnit("target")
	local posXY = nil
	posXY = C_Map.GetPlayerMapPosition(uiMapID, "target") or nil
	local tposX, tposY = UnitPosition("target") --posXY:GetXY()
	
	print(posX,posY)
	SendChatMessage(math.sqrt((posX-tposX)*(posX-tposX)+(posY-tposY)*(posY-tposY)),"party")

![HoJ](https://user-images.githubusercontent.com/6503547/235744206-424a0fbf-ce64-40d0-9167-04b2c75168ec.png)

#### 2.1. Description
HoJ should have 10y range
  #### 2.2 Source Material
Ingame tooltip

**Comment by Evolvee** [comment]
2.66 is a hitbox leeway, could be the problem

**Comment by FatlineDeff** [comment]
Well this is more than 2.66 .. think I had some test with even 12.9 range cast... and we werent even moving during some of them so no way leeway does that...

**Comment by caccavale** [comment]
Spells vs melee vs addon api use different distance measuring methods.  Try measuring distance on different hitbox sizes to determine whether HoJ is edge to edge; if so we would expect it to report more than 10 using your method which is center to center.

**Comment by FatlineDeff** [comment]
I cant test hoj vs different hitboxes as im not paladin, but I tested my priest ranged spell and ye turns out all spells count range towards/from edge of player hitbox which is almost 3yards ... so this isnt HoJ thing but general spell thing, only issue becomes that AoE spells calculate distance to center

I have no clue how to find out how was old retail cunting distance :D 

but HoJ 10y vs Psychic Scream 8y sounds like 2 yards difference, but in reality its 5 because aoe abilities count distance to middle..

**Comment by caccavale** [comment]
Yeah this is consistent with testing hunters did in classic but we had the same issue being unable to source how it was in vanilla/original 3.3.5 :/
