### ISSUE TITLE
[BUG] Conflagrate not being affected by spellstone / firestone / pyroclasm

### ISSUE THREAD

**Issue by dreschnuutest** [JamminL/wotlk-classic-bugs#668]
#### 1.1. Description
If you cast immolate under the effect of pyroclasm (+6% dmg) it won't buff the conflagrate even though conflagrate dmg is scaling with the dmg of immolate, also spellstone/firestone don't affect the dmg of conflagrate
  #### 1.2. How to Reproduce
          Apply spellstone or firestone to weapon and get pyroclasm procc
1. Get pyroclasm procc
2. Cast Immolate with pyroclasm procc
3. See the dmg of conflagrate unaffected (also same dmg as if u would not have spellstone or firestone applied
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
As the pyroclasm tooltip states it should increase the damage of spells by 6%, also firestone 1% directdmg or spellstone 1% dotdmg. As of now nothing of those 3 increases conflagrate dmg
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by CharWS** [comment]
Do you have any additional information regarding this, specific damage values, logs, or some information on how the interaction of these worked in retail wotlk 3.3.5?

**Comment by Tharre** [comment]
NAB. Conflagrate does take the snapshotted SP from immolate, but not any %dmg modifiers.

I've also tested this and conflagrate does benefit from firestone and pyroclasm, as long as you have those buffs on you when you're actually casting it, I'm not sure how you came to different results.
