### ISSUE TITLE
[#SomeChanges Suggestion] Prevent gem changes when Arena starts

### ISSUE THREAD

**Issue by Evolvee** [JamminL/wotlk-classic-bugs#671]
### **Suggestions 1:** 

When an arena opens, you should not be able to change any gear outside of weapons. 

Currently you can change your meta gem and all the other gems as well which creates a cancer environment for counter-gearing *(and yes, ppl are actually doing it, what a great minmaxing meta we live in)*

The suggestion is to prevent this behavior by not allowing any gear changes outside of weapon swaps after an arena begins no matter if IC or OOC.

### **Suggestion 2 in case Suggestion 1 gets approved:** 

Prevent any gem changes when you get an arena pop and/or enter inside the arena. This takes the Suggestion 1 even further and aims at higher mmr where you already know whats against you before the arena even starts.

**Comment by JamminL** [comment]
Already the case on PTR, both suggestions

**Comment by Evolvee** [comment]
1) meta gems arent enough
2) only IC (in combat) scenario is on PTR according to this - https://www.wowhead.com/wotlk/news/wotlk-classic-patch-3-4-2-ptr-live-patch-notes-332770?webhook - which is useless and doesnt solve the problem

**Comment by JamminL** [comment]
It's undocumented so far, but if you're in queue you cant change meta gems

**Comment by JamminL** [comment]
Didn't test other gems.

**Comment by Evolvee** [comment]
its not other gems according to this

https://www.wowhead.com/wotlk/news/patch-notes-version-3-4-2-wotlk-classic-333579?webhook

**Comment by JamminL** [comment]
Patch notes are incorrect
