### ISSUE TITLE
[BUG] Turning into a zombie in Titan Rune Culling of Stratholme wipes certain hidden auras

### ISSUE THREAD

**Issue by raethkcj** [JamminL/wotlk-classic-bugs#682]
#### 1.1. Description
When Titan Rune Alpha or Beta are activated in The Culling of Stratholme dungeon, enemies apply the [You're Infected!](https://www.wowhead.com/wotlk/spell=394608/youre-infected) debuff to players. If it is not dispelled, players will turn into a zombie out of their control.

However, the zombie mechanic currently has an additional, unintended side effect, in that it wipes certain hidden auras from the player until they either re-equip affected items, leave the zone, or restart the game completely. 

The full list of auras this affects is unknown. Two auras that I noticed in testing are the stats from Enchant Chest - Powerful Stats, and the spellpower from the item Bands of Mutual Respect. For the latter, note the difference in the spellpower stat between these two items:
https://www.wowhead.com/wotlk/item=40324/bands-of-mutual-respect
https://www.wowhead.com/wotlk/item=46035/aesuga-hand-of-the-ardent-champion
The spellpower from the bracers is applied as a hidden aura on the player, while the spellpower from Aesuga is a regular item stat.

In addition to the missing stats, I have seen vague reports of players saying that talents and abilities were also affected, such as Warrior's Revenge and Enhancement Shaman's Maelstrom Weapon being unusable after this hidden aura wipe. I *believe* this is related to the problem that causes issues during the Prophet Skeram encounter, which has been posted numerous times on the bug report forums: https://us.forums.blizzard.com/en/wow/search?q=skeram%20%23wow-classic%3Awow-classic-bug-report
Since both involve Mind Control effects, I believe its related to the application of certain PvE Mind Control effects in general.

  #### 1.2. How to Reproduce
           1. Enchant and equip a chest item with Powerful Stats (+10 All Stats)
           2. Note your character's stats
           2. Enter The Culling of Stratholme on Heroic difficulty and enable Titan Rune Alpha or Beta
           3. Become infected
           4. Allow the debuff to run its course and be turned into a zombie
           5. Die, and be resurrected without leaving the dungeon
           6. Note the stats of the enchant are missing
  #### 1.3  Source Material
https://www.youtube.com/watch?v=bMTOrUCrxDQ
Note especially my Strength, Agility, and Spell Power before becoming a zombie and after being resurrected. As a caster, my only source of bonus Strength and Agility are the +10 chest enchant. My spellpower decreases by exactly 56. I didn't catch it in this recording, but noticed afterwards that unequipping and re-equipping my bracers restored my spellpower to the intended value.

#### 2.1. Description
Becoming a zombie has no lasting effect on a player's stats.
  #### 2.2 Source Material
N/A

**Comment by LordOfOtakus** [comment]
Prophet Skeram does the same thing at 50% and 25% health in AQ40, but to my knowledge never fixed. They will also clear auras designed to impede the player from spamming certain things (like Trick or Treat) over and over.
