### ISSUE TITLE
Question about Era bugreports [Please delete this if it's not the right place]

### ISSUE THREAD

**Issue by FireReaver** [JamminL/wotlk-classic-bugs#683]
Hi, I'm Turøk and admin from the Vanilla Classic Era discord.

Sorry if I'm asking this here but recently I've been made aware by one of our users about the possibility to report Era bugs in this GitHub as well since the team is maintaining both versions of the game.
Don't get me wrong, seeing all bug reports being for Wotlk Classic always made me skeptical but this has been reported twice so I'd really love to get some type of confirmation at this point.

Is it true? Are we really allowed to share our buglist here too?

Waiting for any input,
Thanks in advance,

Turøk

P.S: I thought there was a more direct way to ask for this but I just realized github removed in the past the option for any direct messages

**Comment by JamminL** [comment]
Feel free to add me on discord @Jamminl

I've added a VANILLA ERA SERVER tag that you can feel free to use when bug reporting vanilla era issues!

I'll close this issue once we've talked so I know you got to see this message!

**Comment by FireReaver** [comment]
> Feel free to add me on discord @JamminL
> 
> I've added a VANILLA ERA SERVER tag that you can feel free to use when bug reporting vanilla era issues!
> 
> I'll close this issue once we've talked so I know you got to see this message!

Definitely, thanks for this!
