### ISSUE TITLE
[BUG] Blue, red, and yellow epic gems are 20k honor

### ISSUE THREAD

**Issue by Lillyton** [JamminL/wotlk-classic-bugs#689]
#### 1.1. Description
Blue, red, and yellow gems are currently 20k honor on the vendor. 
  #### 1.2. How to Reproduce
           1. Check the pvp vendor. 
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
All the epic gem colours should be 10k honor. 
  #### 2.2 Source Material
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/51220367
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/137237050/a715d8e6-567b-4487-9458-e15ea85b9f04)

https://www.wowhead.com/wotlk/item=36919/cardinal-ruby#comments
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/137237050/81324c7e-ebed-4487-994c-e2dc342f8c0a)

https://wowpedia.fandom.com/wiki/Cardinal_Ruby?oldid=1982591
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/137237050/fd34df9e-3922-48ec-a005-6e055509b964)

**Comment by Vishiswaz** [comment]
This is a pretty major bug

**Comment by Vishiswaz** [comment]
No update on this? I really don't want to spend honor on gems if this might be fixed and then I'll have wasted thousands upon thousands of honor.

**Comment by Vishiswaz** [comment]
That's extremely disappointing.
