### ISSUE TITLE
[BUG] Missing PvP vendors in orgrimmar's Hall of Legends

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#69]
#### 1.1. Description
There are no PVP vendors in Hall of Legends

**Comment by yurpcraft** [comment]
up to level 70 pvp vendors are now in the Hall of Legends.  Are we expecting more?
![image](https://user-images.githubusercontent.com/12848366/183667448-786b0f86-aad7-4f58-86d8-78239169f5b7.png)

**Comment by watchyoursixx** [comment]
This may be a separate issue but the last couple times I checked I was unable to interact with any of them. Can anyone confirm?
