### ISSUE TITLE
[BUG] Deep wounds doesn't do damage if warrior is CC'd

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#691]
#### 1.1. Description
Deep wounds stop doing damage if the warrior gets CC'd.
  #### 1.2. How to Reproduce
           1. Gain a deep wounds proc
           2. Get Hand of Justice'd
           3. See deep wounds stops doing damage
  #### 1.3  Source Material
https://streamable.com/nrr5rv
#### 2.1. Description
Deep wounds should persist throught cc
  #### 2.2 Source Material
N/A

EDIT: Fixed for stuns, not working for mindcontrol or vanish

**Comment by TheGroxEmpire** [comment]
Reproducible on player + NPCs also (Argent melee dummy).

https://streamable.com/3yopfw

**Comment by TheGroxEmpire** [comment]
Fixed on 3.4.2.50172.
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/47816228/56ea7926-ad57-4a03-8866-c6e29f98a0cf)

**Comment by Shintaxgg** [comment]
https://clips.twitch.tv/CulturedBoringSquidRlyTho-YypKMD9moOOZa47H
re-open this, still bugged with mindcontrol

**Comment by JamminL** [comment]
And stealth

**Comment by Shintaxgg** [comment]
https://gyazo.com/2ee1d006643083d42f120eb361eab387
https://www.twitch.tv/videos/1875447003?t=01h06m53s
I auto-attack crit on the rogue while he's on stealth, not only deep wounds doesn't do damage, it doesn't apply deep wounds at all
