### ISSUE TITLE
[BUG] Immunities remove the damage buff from Light/Dark Essence on Twin Val'kyrs

### ISSUE THREAD

**Issue by nnyborg** [JamminL/wotlk-classic-bugs#700]
#### 1.1. Description
Light and Dark Essence makes you deal 50% increased damage to one type and 50% decreased damaged to the other.
After using an immunity, like Ice Block or Divine Shield, the damage part of the buff is removed. The absorb part stays.

This is also seen on Wowheads database, where Light/Dark Essence has 2 parts.
The main buff, which is visible ingame, which has the "Unaffected by invulnerability" flag
https://www.wowhead.com/wotlk/spell=65686/light-essence
https://www.wowhead.com/wotlk/spell=65684/dark-essence

And the hidden buff, which has the damage part, missing the invulnerability flag.
https://www.wowhead.com/wotlk/spell=65811/light-essence-effect-2
https://www.wowhead.com/wotlk/spell=65827/dark-essence-effect-2

This seems very unintentional, given both buffs persist through death.

  #### 1.2. How to Reproduce
1. Get either of the two Essence buffs.
2. Use immunity spell
3. Observe damage done is lower than expected
  #### 1.3  Source Material
In this log the mage uses Ice Block at 1:38.508, after which damage done significantly drops.
https://classic.warcraftlogs.com/reports/Rx4hmNWtb9AjZVTf#fight=8&type=damage-done&source=16&view=events&options=2&start=2158555&end=2207688&ability=42833
#### 2.1. Description
No proof that this isn't how the debuff should function, but seems very unintentional given the visible buff stays.
The damage part of the buff is also stated on the buff that isn't removed.

**Comment by simonizeshow** [comment]
This is happening with a rogue's Cloak of Shadows as well. I thought it was good to mention since maybe Cloak wouldn't immediately be thought of when considering "Immunity" effects.

After using Cloak, the damage buff is gone just like described here about Ice Block or Divine Shield.

**Comment by caccavale** [comment]
This seems to be expected behavior.
![image](https://github.com/JamminL/wotlk-classic-bugs/assets/6198074/81afa7a8-a502-434e-97c6-9e957e0419a0)

**Comment by nnyborg** [comment]
Fixed: https://us.forums.blizzard.com/en/wow/t/cloak-of-shadows-removing-damage-bonus-from-essence-on-twin-valkyrs/1625757/10
