### ISSUE TITLE
[BUG] vanish gives slow/root immunity when it shouldn't

### ISSUE THREAD

**Issue by kevinlemage** [JamminL/wotlk-classic-bugs#702]
Current Behavior
#### 1.1. Description
 Rogues are immune to slow and roots for a short window of time after using vanish. When a rogue gets hit by a cone of cold or a nova right after using vanish, they get knocked out of stealth but aren't slowed or rooted like they should.

#### 1.2. How to Reproduce
   Have a rogue vanish, nova him instantly.

#### 1.3  Source Material

https://streamable.com/yoxywj

Expected Behavior#### 2.1. Description
 Rogues shouldn't be immune to roots or slows after using vanish. When a rogue gets knocked out of stealth by a nova or a cone of cold they should be rooted/slowed.#### 2.2 Source Material
  #### 2.1. Description
{Describe how that mechanic/spell/npc should be working, in detail}
  #### 2.2 Source Material
clip from original wotlk
https://youtu.be/LaG35CR_1ps?t=624
https://youtu.be/7FdeDKeHVjg?t=604
https://youtu.be/5cHuRPtnZwU?t=710

**Comment by JamminL** [comment]
NAB, there's a specific spell that vanish gives you that specifically gives you a 1 second slow/snare immunity right after you press it. This is well documented.
