### ISSUE TITLE
[BUG] Magic Dust should have a 1.5s cast time [Era/PTR]

### ISSUE THREAD

**Issue by perpabc** [JamminL/wotlk-classic-bugs#722]
#### 1.1. Description
Magic Dust should have a 1.5s cast time. It's currently instant, but requires you to stand still. Major bug for PVP as this item is very potent when it's bugged.
  #### 1.2. How to Reproduce

           1. .additem 2091
           2. Find a hostile target
           3. Use Magic Dust on it
  #### 1.3  Source Material
https://gyazo.com/9940bad796805db937ad966de04ee3ad
#### 2.1. Description
Magic Dust should have a 1.5 second cast time.
  #### 2.2 Source Material
https://web.archive.org/web/20051226022150/http://thottbot.com/?i=4512 (patch 1.8.4)
https://web.archive.org/web/20060306122351/http://wow.allakhazam.com/db/spell.html?wspell=1090 (March 2006)
https://web.archive.org/web/20060619160717/http://thottbot.com/?sp=1090 (June 2006, this is the spell the item uses, Patch 1.11)

**Comment by JamminL** [comment]
https://youtu.be/qAAERKlq9ZQ?t=37
