### ISSUE TITLE
[#SomeChanges Suggestion] Make Concussive Barrage (MM talent) daze shielded targets even on full absorbs

### ISSUE THREAD

**Issue by Homerjayx** [JamminL/wotlk-classic-bugs#75]
### Description
This is the talent "Concussive Barrage" in the MM Hunter tree.

![image](https://user-images.githubusercontent.com/39262303/176254148-ce328db4-3b77-4a60-aa84-df18f5b90294.png)

The talent Concussive Barrage doesn't work if Chimera or Multi Shot are full absorbed by a shield that protects the target they are hitting. This leads to Concussive Barrage being the only opportunity to spend talent points on where you never know whether they theoretically intentionally help you or not. Every other talent either linearly directly benefits you or it does so by increasing the chance of something benefitial happening to you.

**Comment by caccavale** [comment]
For what its worth, this talent is strong as is and works consistently with shields preventing Aspect of the Cheetah and other dazes.
