### ISSUE TITLE
[#SomeChanges Suggestion] Concussive Barrage not working on absorb.

### ISSUE THREAD

**Issue by Homerjayx** [JamminL/wotlk-classic-bugs#76]
### Description
{Describe your suggestion}

![image](https://user-images.githubusercontent.com/39262303/176267995-1ab9b77a-40d3-49d5-8ff4-ad3af24bfe5e.png)

The talent Concussive Barrage doesn't work if Chimera or Multi Shot are full absorbed by a shield that protects the target they are hitting. This leads to Concussive Barrage being the only opportunity to spend talent points on where you never know whether they theoretically intentionally help you or not. Every other talent either linearly directly benefits you or it does so by increasing the chance of something benefitial happening to you.

**Comment by caccavale** [comment]
You already opened a ticket: https://github.com/JamminL/wotlk-classic-bugs/issues/75
Please avoid opening duplicates.  You can edit that ticket or add comments if you need.
