### ISSUE TITLE
[BUG] Spore Cloud is Stacking w Minor Armor Debuff 

### ISSUE THREAD

**Issue by CharWS** [JamminL/wotlk-classic-bugs#77]
#### 1.2. How to Reproduce
          Describe the steps to reproduce the particular bug, in detail:
           1. find an enemy that's a beast
           2. cast beast lore on them to find armor value
           3. use spore bat spore cloud
           4. use faerie fire and/or other minor/major armor debuffs
           5. note target armor changes
  #### 1.3  Source Material
https://clips.twitch.tv/TemperedFitTrayPRChase-Urdaa1SyDy9QUFYI video of the interaction
#### 2.2 Source Material
Per wowhead comment 2009/01/06 https://www.wowhead.com/wotlk/spell=53598/spore-cloud#comments:id=549652

> The armor debuff is classed as a minor armor reduction, I tested in the nagrand arena with a rogue and druid friend, the rogue and druid both used their armor debuffs on each other and then my pet aoe sporeclouded them both, the druid reported additional armor reduction, while the rogue reported no change.

Images taken from a historical Hunter DPS spreadsheet suggest it changed at some point or was noticed as changing sometime between 22/8/2008 and 13/1/2009
![unknown-2](https://user-images.githubusercontent.com/104176019/176286110-7385f70b-2f12-4939-8a86-97afc20a2162.png)
![unknown-4](https://user-images.githubusercontent.com/104176019/176286124-3373c4b2-abff-4d95-bf06-20088e80cd9b.png)

**Comment by CharWS** [comment]
Moving this over from the DK github, not sure if this is acting as intended or not.

**Comment by watchyoursixx** [comment]
fixed as of build 44930
