### ISSUE TITLE
[BUG] Party wide spells sometimes don't work in LFG dungeons

### ISSUE THREAD

**Issue by RevinderDev** [JamminL/wotlk-classic-bugs#779]
### 1. Current Behavior
Sometimes (not always) whenever I join random group from dungeon, my character seems to not be in party.
  #### 1.1. Description
Neither Gift of the Wild nor Wild Growth nor Tranquility works on any other party member than myself. I suppose this can be extrapolated to other party classes but I have yet to test it. I could not cast my Wild growth on any other target than myself IF I personally was not within 10 yards range (wild growth range) and when I was, the cast was successful but I was the only one affected by it. See source material for example, it's pretty self evident. 
**It's important to mention that this happens regardless if a party member is from mine or different realm.**
  #### 1.2. How to Reproduce
I was not able to consistently reproduce the bug unfortunately so the reproducing steps are not always resulting in bug occuring.
1. Join dungeon through Group finder tool.
2. Attempt to cast party wide spells (e.g. Wild Growth)

  #### 1.3  Source Material
https://www.youtube.com/watch?v=8SMMCE3kpvs   - this is me trying to attempt to cast Wild Growth on a party member - notice `Invalid Target` error message at the top.
#### 2.1. Description
I would have expected to all party spells to hit all party members.
  #### 2.2 Source Material
N/A.

**Comment by JamminL** [comment]
This is due to not having /pvp on flag automatically set. It's known!

**Comment by RevinderDev** [comment]
Oh damn okay, I had no idea. Closed then!
