### ISSUE TITLE
[BUG] Cannot Cast Howling Blast with Freezing Fog proc and no Runes.

### ISSUE THREAD

**Issue by gardinit** [JamminL/wotlk-classic-bugs#78]
#### 1.1. Description
Having a Freezing Frog proc and no runes available will not allow a Howling Blast to be cast.
  #### 1.2. How to Reproduce
           1. Obliterate until you get Freezing Frog aura
           2. Spend all runes (this might just be spend all runes that would allow you to cast Howling Blast)
           3. Cannot cast Howling Blast.

**Comment by CharWS** [comment]
Leaving additional video evidence for this: https://clips.twitch.tv/HotFurryDelicataGivePLZ-WB8Uq7kp8kr4UuSp 
Would additionally note that Rime procs are neither resetting the cooldown of Howling Blast, or allowing it to be cast when Runes are on cooldown, but it is possible to cast a Howling Blast without using Runes when the Runes it would cost are available.

**Comment by caccavale** [comment]
Fixed as of 44729
