### ISSUE TITLE
[TEST-REQUEST] Frostbite and Fingers of Frost same roll

### ISSUE THREAD

**Issue by JamminL** [JamminL/wotlk-classic-bugs#8]
### Description
In 3.3.5a, if fully talented, both frostbite and fingers of frost use the same roll. So if one proc so should the other

**Comment by dawidcxx** [comment]
Using a randomized clips method I've noticed that this does indeed always happen, at least for the clips that I've rolled. 

https://www.youtube.com/watch?v=IRrGbhDnhz0  2:24
https://www.youtube.com/watch?v=-9f6alusBXU 7:22
https://www.youtube.com/watch?v=Hq0nzG2k0T4 13:20 30:40 (good source btw, as it's using the latest wotlk build on a CN server)

**Comment by JamminL** [comment]
Seems to be working properly in wotlk classic beta
