### ISSUE TITLE
[#SomeChanges Suggestion] Growl hunter pet vs Grounding Totem

### ISSUE THREAD

**Issue by Shintaxgg** [JamminL/wotlk-classic-bugs#83]
1. Current Behavior
1.1. Description
Growl from pet shut down the grounding totem

1.2. How to Reproduce
       1. Use Grounding Totem
       2. Press Growl from Pet
       3. Grounding totem disappear
1.3 Source Material
None

2. Expected Behavior
2.1. Description
Growl shouldn't take grounding totem, it was a bug that was fixed later on in patch 6.1 https://wowwiki-archive.fandom.com/wiki/Grounding_Totem, like the spell pen not affecting freezing trap that got fixed in cataclysm patch 4.2

2.2 Source Material
https://wowwiki-archive.fandom.com/wiki/Grounding_Totem

**Comment by Homerjayx** [comment]
I am missing some consistency here. Why make one ability blizzlike and the other not in this context of hunters? What difference lies within these two posts that lead you to making this distinction?

**Comment by Aggrend** [comment]
Calling this NAB for now. This is authentic and a fix 3 expansions later isn't super relevant, unfortunately.
