### ISSUE TITLE
[BUG] Can Cast Multiple Rune Abilities With Only One Death Rune

### ISSUE THREAD

**Issue by CharWS** [JamminL/wotlk-classic-bugs#86]
#### 1.1. With only one Death Rune available it's possible to cast abilities that require multiple runes to cast (for example: Obliterate, Death Strike, Death and Decay, Scourge Strike, Howling Blast)
{Describe how that mechanic/spell/npc is currently working, in detail}
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Convert runes to Death Runes through a talent or rune tap
           2. Spend Runes such that your only available rune is a Death Rune
           3. Try casting an ability which costs multiple runes
  #### 1.3  Source Material
Can see in the screenshot that Death And Decay is castable despite only have one Death Rune available and off cooldown
https://user-images.githubusercontent.com/104176019/176550101-988a75f6-10d6-439d-8c52-70c2854df55e.png
Here's a video that better demonstrates the bug 
https://clips.twitch.tv/ChillyBrightWallabyStrawBeary-YCuLTfz-svB4VxAd

**Comment by Sotomatic** [comment]
Still broken over a month later

**Comment by NuptupTDOW** [comment]
I would like to add that, when you do this to cast a spell that itself creates death runes, such as Death Strike with the Death Rune Mastery talent, it will use a single rune to do the spell as described above, but will also "flash" a second rune that would normally be required, and convert it mid-cooldown into a death rune if it wasn't already one. 

Example: B, B, F, F, U, U are your runes, you have them as B, B, D, F, U, U with all of them being on cooldown except for the Death Rune. If you use that singular Death Rune to cast Death strike with the appropriate talent, one of the Unholy Runes, while on cooldown already, will immediately transform into a Death Rune as if it had been used in that attack.

This should be easy to see during testing of the above glitch, but if you need visual proof, I can make a video and link it when I get home.

**Comment by caccavale** [comment]
Fixed as of 3.4.0.45166
