### ISSUE TITLE
[BUG]dreamstate talent doesn't increase mp5

### ISSUE THREAD

**Issue by Dverikk** [JamminL/wotlk-classic-bugs#88]
#### 1.1. Description
Tooltip doesn't update when you learn the talent druid talent ''dreamstate'', I don't know if the actually mp5 increase.

  #### 1.2. How to Reproduce
          Learn the talent.
  #### 1.3  Source Material

#### 2.1. Description
Increase mp5
  #### 2.2 Source Material

**Comment by ageerik** [comment]
I tested it now, went down to 0 mana and regen to full, took 2min 2sec without the talent and 2min 2sec with the talent. If you calculate the difference it should have been around 30sec difference so it's not working. On tbc the tooltip shows updated mp5 with the talent for me.
