### ISSUE TITLE
typhoon dismounting

### ISSUE THREAD

**Issue by ageerik** [JamminL/wotlk-classic-bugs#92]
When wotlk luached typhoon dismounted https://www.youtube.com/watch?v=pWlBr_fT6bI&ab_channel=wuligan
but was changed later to not dismount https://www.youtube.com/watch?v=utwgumXeiZw&ab_channel=misseryofwow
My suggestion, have it dismount players for first season.

**Comment by JamminL** [comment]
Please follow appropriate format
