### ISSUE TITLE
[BUG] Judgements not proccing Seals correctly

### ISSUE THREAD

**Issue by JayJay-110** [JamminL/wotlk-classic-bugs#93]
#### 1.1. Description
Seal of Righteousness is proccing off of Judgements, while neither Seal of Command or Seal of Vengeance are.  This is a pretty large bug considering they were to memory in wotlk and is a large component of extra damage from seals for both Prot and Ret.
  #### 1.2. How to Reproduce
           1. Put up Seal of Righteousness and Judge. You will see 2 Numbers (Judgement + Seal Damage)
           2. Put up Seal of Command and Judge. You will see 1 Number only (Judgement Damage)
           3. Put up Seal of Vengeance, stack to 5 and Judge. You will see 1 Number only (Judgement Damage)
  #### 1.3  Source Material
[Judgement proccing Seal of Righteousness](https://classic.warcraftlogs.com/reports/R8XZwB6cMWGYdHD7/#fight=1&type=summary&source=4&view=events&start=3267&end=6000)
[Judgement _not_ proccing Seal of Vengeance](https://classic.warcraftlogs.com/reports/R8XZwB6cMWGYdHD7/#fight=1&type=summary&source=4&view=events&start=62200&end=64000)
[Judgement _not_ proccing Seal of Command](https://classic.warcraftlogs.com/reports/R8XZwB6cMWGYdHD7/#fight=1&type=summary&source=4&view=events&start=109000&end=111000)
#### 2.1. Description
It is mentioned in the Elitist Jerks guide from Patch 3.3 that Judgements are considered a Melee Attack which can proc On-Hit effects (like Weapon Procs, Judgements, etc). It is specifically mentioned that Judgements could proc Seal of Vengeance back then.
> 2) A weapon damage based proc [from Seal of Vengeance] will occur if you used a special (CS/DS/judge)
  #### 2.2 Source Material
[Elitist Jerks Guide talking about Judgement and Seal Mechanics](https://web.archive.org/web/20100715221709/http://elitistjerks.com/f76/t68951-retribution_updated_3_3_a/#Judgements)

**Comment by terrynfredrickson-yahoo** [comment]
As a note, seal of light is proccing the Seal Heal as well when a judgement happens: 
https://classic.warcraftlogs.com/reports/9TKjLWtMqY43pNR7/#fight=53&type=summary&view=events&start=11358136&end=11362186 

This is correct to memory and matches many other effects listed.  


We haven't verified if judgements are proccing melee effects IE Trinkets, so thats a thing to verify as well.

**Comment by JayJay-110** [comment]
I recently discovered that picking up the Talent 'Judgements of the Just' in the Protection tree makes Judgement proc Seal effects.
Interestingly enough, this means Seal of Righteousness will trigger 2 times with the Talent.

**Comment by Watcher7** [comment]
It's possible this is intended behavior?
Given it's referenced on old wowwiki pages https://wowwiki-archive.fandom.com/wiki/Seal_of_Righteousness_(old)?oldid=2102671

Not that that's the most credible source of truth, but it does show that "The swing damage is added on Judgments as well, unlike Seal of Command and Seal of Vengeance." was historically noted.

**Comment by Undertoe** [comment]
Also confirming, Seal of Justice is currently proccing off of Judgement.

The only seals that are not are SOC and SOV currently.

**Comment by Aggrend** [comment]
This matches 3.3.5 reference behavior. NAB for now.
