### ISSUE TITLE
[BUG] Avoidance Diminishing Returns

### ISSUE THREAD

**Issue by Itank84** [JamminL/wotlk-classic-bugs#94]
#### 1.1. Description
Currently there is no Diminishing Returns on Avoidance.

The character is a level 70 Blood Elf Paladin, made from the template on the beta.
This Paladin has: 273 Defense Rating, 18 Dodge Rating, 15 Parry Rating, 30 agility from gear and 79 base agility.
If Diminishing Returns wasn't in effect the template Paladin would have 17.74 % dodge and 10.29 % parry.
From the tooltips ingame this Paladin has 17.74 % dodge and 10.29 % parry.
I have tested this on all the races and the result is the same, their tooltip avoidance matches avoidance without Diminishing Returns.

For each point of dodge gained from Defense, agility and Dodge Rating you get back the same amount. Currently on Beta build 44369 at level 70 you gain 1 % dodge from 28.564197129 agility and 1 % dodge from 21.76 Dodge Rating. From each point of Defense you gain 0.04  % chance to dodge.

Same behavior from parry. You gain 1 % parry from 21.76 Parry Rating and 0.04 % chance to parry from each point of Defense.

We cannot easily test Miss chance right now, but there's no reason to believe Miss chance is currently affected by Diminishing Returns either.

  #### 1.2. How to Reproduce
           1. Make a level 70 paladin.
           2. Write down the Base Agility, Agility from gear, Defense Rating from gear, Dodge Rating from gear and Parry Rating from gear.
           3. The formula for calculating Diminishing Returns is: Dodge % = base_dodge + talents + dodge_from_base_agility + diminished_dodge
           4. If your dodge matches this equation then dodge is not being diminished: Dodge % = base_dodge + talents + dodge_from_base_agility + dodge_from_dodge_rating + dodge_from_defense + dodge_from_gear_agility
           5. Base dodge for Paladin is 3.4943, potentially 5 from talents, dodge from base agility is base_agility / 28.564197129, dodge from dodge rating is dodge_rating / 21.76 and dodge from defense is defense_skill_from_gear * 0.04
           6. 3.4943 + 5 + 79/28.564197129 + 18/21.76 + 115 * 0.04 + 30/28.564197129 = 17.74 %
            
          
  #### 1.3  Source Material
[Screenshot of the Character Pane](https://gyazo.com/c5e30fa3225611caa09680e95fc87a4e)
[Screenshot of Defense from Character Pane](https://gyazo.com/88dee754c09952db5591e6bc0282899a)
[Screenshot of Agility from Character Pane](https://gyazo.com/969cd28d9919b05b878a9e53d468a656)
[Screenshot of Dodge from Character Pane](https://gyazo.com/00eaa8aa499bafd10ace90be437cb5fd)
[Screenshot of Parry from Character Pane](https://gyazo.com/94f42cbb7cd6409483115cace17df24b)

#### 2.1. Description
As the amount of dodge, parry and miss increases the return of their value point for point should decrease. With 17.74 % dodge and 10.29 % parry these values should have diminished to 17.55 % and 9.95 % respectively.

           1. The formula for calculating Diminishing Returns should be: Dodge % = base_dodge + talents + dodge_from_base_agility + diminished_dodge
           2. In order to find the Diminished Dodge we have to do some calculations.
           3. First we need to figure out the Undiminished Dodge, which is done by this equation: Undiminished Dodge % = (Agility_gear/Lv70_agi_per_1%_Dodge)+(defense_skill_gear*0.04)+(dodge_rating/dodge_rating_per_1%_dodge)
           7. Then using the Undiminished Dodge we can calculate the Diminished Dodge using this equation. Diminished Dodge % = (undiminished_dodge_%*dodge_cap)/((k*dodge_cap)+undiminished_dodge_%)
           8. You can find the Defense from gear like this: Defense Rating from gear / 2.3653. Round the Defense number down to an integer.
           9. Input the numbers into the equation from step 5.
           10. (30/28.564197129)+(115*0.04)+(18/21.76) = 6.477 %
           11. (6.477*88.129021)/((0.956*88.129021)+6.477) = 6.29 %
           12. Now that we have the Diminished Dodge we can fill in our numbers in the formula from step 3.
           13. base_dodge + talents + dodge_from_base_agility + diminished_dodge = 3.4943 + 5 + 2.7657 + 6.29 = 17.55 %
           
  #### 2.2 Source Material
I have made a [calculator](https://docs.google.com/spreadsheets/d/1hGO_M8_chnVki9bqAm7WAh5SH8TioN_-NOe-hrIgocw/edit?usp=sharing) on google docs if you don't want to manually calculate this every time. 
https://wowwiki-archive.fandom.com/wiki/Melee_diminishing_returns
https://web.archive.org/web/20090508132756/http://elitistjerks.com/f31/t29453-combat_ratings_level_80_a/
https://web.archive.org/web/20090416205150/http://www.tankspot.com/forums/f63/40003-diminishing-returns-avoidance.html

**Comment by watchyoursixx** [comment]
fixed as of build 45189
