### ISSUE TITLE
Corpse Explosion ghoul cast can be pummeled (should be protected cast)

### ISSUE THREAD

**Issue by dariuzsdk** [JamminL/wotlk-classic-bugs#96]
#### 1.2. How to Reproduce
1. Cast ghoul explode
2. Use interrupt ability 
  #### 1.3  Source Material
https://clips.twitch.tv/GeniusCarelessSeahorseGOWSkull-ZYf5WUWLOA7HcxKI
#### 2.2 Source Material
Source footage is unavailable to my knowledge

**Comment by Aggrend** [comment]
This is, rather hilariously, consistent with 3.3.5 reference behavior. :)
