### ISSUE TITLE
[BUG] Shield Block Value

### ISSUE THREAD

**Issue by Itank84** [JamminL/wotlk-classic-bugs#99]
#### 1.1. Description
Shield Block Value, hereby shortened to SBV, is currently being calculated by the TBC formula.

After extensive testing I have come to the conclusion that in TBC SBV is calculated by:

With Eternal Earthstorm Diamond
 `CEILING((strength-20)/20)` + `FLOOR((SBV from gear)*(1+(0.1*Shield Specialization Rank)))` + `FLOOR((SBV from gear)*0.1)`

and 

Without Eternal Earthstorm Diamond
`CEILING((strength-20)/20)` + `FLOOR((SBV from gear)*(1+(0.1*Shield Specialization Rank)))`

In Wrath Beta the SBV is being calculated by the same formula. 

With Eternal Earthstorm Diamond
`CEILING((strength-20)/20)` + `FLOOR((SBV from gear)*(1+(0.1*Redoubt Rank)))` + `FLOOR((SBV from gear)*0.05)`

and

Without Eternal Earthstorm Diamond
`CEILING((strength-20)/20)` + `FLOOR((SBV from gear)*(1+(0.1*Redoubt Rank)))`

  #### 1.2. How to Reproduce
           1. Make a paladin
           2. Input the values from ingame into the equations posted above.
           
  #### 1.3  Source Material
 Without meta gem
[Values](https://gyazo.com/ca181ee82d9411980da994153adb46a8)
[Screenshot of Character Pane](https://gyazo.com/fbe6dc1f4a64089cd031f7f9eb75dae8)

With meta gem
[Values](https://gyazo.com/f59e13263bb310842273402815f68658)
[Screenshot of Character Pane](https://gyazo.com/d429343843d035c1dd24329bfabbee6a)

#### 2.1. Description
In Wrath the SBV calculations were changed to:
`SBV = (SBV from gear + (strength / 2)) * (1+(0.1*Redoubt Rank))`

  #### 2.2 Source Material
https://wowwiki-archive.fandom.com/wiki/Block?oldid=2334873#Damage_reduction

**Comment by watchyoursixx** [comment]
Looking at this again, maybe I'm missing something here but I'm seeing 660 BV on a template pally untalented. ( I made it and put the template tank gear on)
So I have 285 BV from gear, 204 from shield and 81 from ring. STR is 771.
Entering these into either formula above gives incorrect values compared to the tooltip.

Tooltip = 660
SBV on gear = 285
STR = 771
285 + 771 / 2 = 670.5
285 + (771 - 20) / 20 = 322.55

It looks at first glance like it's working, but the 670 doesn't match the 660 tooltip for some reason.
Feel free to chime in if I missed something but this might be fixed at least as of build 45264.

**Comment by JayJay-110** [comment]
Though I do not have any sources for this, I assume block value works just like other Stats like AP, Health or Mana. Some of your **base** attributes don't count towards the conversion.

Some Examples: (Level 80 Paladin without any Gear, Buffs or Talents)
151 Strength increases AP by 282.             = (Strength - 10) * 2
151 Strength increases BV by 65.               = (Strength - 21) / 2
143 Stamina increases Health by 1250.      = (Stamina - 18) * 10
98 Intellect increases Mana by 1190.          = (Intellect - 19) * 15 + 5      Kinda interesting

The above formulas can be applied for a Level 1 Human and Blood Elf Paladin aswell.
